### ISSUE TITLE
The signature help "parentheses" detection needs more work

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1001]
![Screenshot from 2020-04-29 23-05-29](https://user-images.githubusercontent.com/2431823/80647025-12858f80-8a6e-11ea-88b9-8cec2005d75c.png)

We've seen that for e.g. a dockerfile language server the parens detection doesn't work at all.
For gopls, parentheses are used after the function ends. The right decision might be to abandon this parsing. There's nothing in the spec that guarantees us parentheses of any kind.

**Comment by rchl** [comment]
Here are some example signature responses (for my own information mostly).
```json
{
    "signatures": [
        {
            "label": "toggleExpand(memberId: number): void",
            "parameters": [
                {
                    "documentation": "",
                    "label": "memberId: number"
                }
            ]
        }
    ],
    "activeParameter": 0,
    "activeSignature": 0
}
```

```json
{
    "signatures": [
        {
            "documentation": "Copy new files and directories to the image's filesystem.",
            "label": "COPY [flags] source ... dest",
            "parameters": [
                {
                    "documentation": "Optional flags to configure this instruction.",
                    "label": "[flags]"
                },
                {
                    "documentation": "The resource to copy.",
                    "label": "source"
                },
                {
                    "documentation": "The resource to copy.",
                    "label": "..."
                },
                {
                    "documentation": "The name of the destination file or folder.",
                    "label": "dest"
                }
            ]
        }
    ],
    "activeParameter": 1,
    "activeSignature": 0
}
```
I haven't checked what we are parsing them for. Is that to highlight active parameter?

**Comment by AmjadHD** [comment]
there's an issue i noticed before (i don't know if it's still there): when you are inside the parameter section of a function and and click "(" (e.g to create a tuple), signatureHelp is invoked.
```python
f(1, 2, (|))
```

**Comment by rwols** [comment]
> there's an issue i noticed before (i don't know if it's still there): when you are inside the parameter section of a function and and click "(" (e.g to create a tuple), signatureHelp is invoked.

Yes, there's not much we can do about that. The signature help feature works with trigger characters. Trigger characters are blunt and don't know anything about ST scopes.

**Comment by rwols** [comment]
Maybe we can add a customization point in AbstractPlugin for this

**Comment by rchl** [comment]
That sounds fine to me.

What form would the customization have? A regexp (or a series of)?

**Comment by rwols** [comment]
Just another selector in the client config would suffice I think?
