### ISSUE TITLE
Workspace Symbol command should accept an empty query string, since 3.15

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#1008]
The "LSP: Workspace Symbol" command currently requires you enter a query string before receiving any results and thus the command does not function similar to the built-in "Find Symbol in Project" command. 

It is my understanding of the LSP that Workspace Symbol is basically "Goto Symbol in Project" so it should (at least by way of option) allow an empty query string so that it can be implemented in this way.

The spec also allows this according to the comment below:

```
/**
 * The parameters of a Workspace Symbol Request.
 */
interface WorkspaceSymbolParams extends WorkDoneProgressParams, PartialResultParams {
	/**
	 * A query string to filter symbols by. Clients may send an empty
	 * string here to request all symbols.
	 */
	query: string;
}
```

**Comment by rwols** [comment]
Pretty much blocked on https://github.com/sublimehq/sublime_text/issues/3338

**Comment by genericptr** [comment]
It's been so long I forget now, but completion panels now work with partial results so is there anything new that would allow symbols to be recalculated as you type? Workspace Symbols are basically dead in the water until that is possible. Sending empty strings is actually the smaller of the 2 issues.
