### ISSUE TITLE
gopls: go to defnition does not work for packages in $GOROOT

### ISSUE THREAD

**Issue by RafalSkolasinski** [sublimelsp/LSP#1013]
### OS and language server
Ubuntu and gopls

### How you installed LSP (Package Control or from git?)
Package Control

### Minimal reproduction steps
1. Go to Definition that leads out of project directory, e.g. `context.Context` would lead to `/usr/lib/go-1.14/src/context/context.go`
2. Try to "Go to Definition" on any function or struct in this file 

-> Nothing is happening
-> Option seen after clicking RMB is grayed out (inactive)

### Log
What logs?

Please, let me know if there are any more information I could provide.

**Comment by rwols** [comment]
This is a deliberate choice. Your particular linter settings for your project might not apply to other projects.

If you disagree with this policy, share your thoughts in https://github.com/sublimelsp/LSP/issues/997
