### ISSUE TITLE
Restart specific LSP servers vs Restart All LSP servers

### ISSUE THREAD

**Issue by TheSecEng** [sublimelsp/LSP#1021]
### What
**OS and language server:** All

LSP allows for a command `LSP: Restart Servers` which reloads all LSP servers currently in use via "sessions". Useful for debugging, however there is no need to force started all LSP servers, if you only need to restart a single server that is being buggy.

### Solution
 There should be a command that drops into a ListPanel that shows all running LSP servers and allows the user to select the specific server to restart.

**Comment by TheSecEng** [comment]
If possible, assign this to myself.

**Comment by predragnikolic** [comment]
closed with https://github.com/sublimelsp/LSP/pull/1733
