### ISSUE TITLE
Usage with Naomi syntax package

### ISSUE THREAD

**Issue by ryanpcmcquen** [sublimelsp/LSP#1028]
I found a linked issue over at the Naomi package page:
https://github.com/borela/naomi/issues/189

I cannot seem to configure LSP to recognize this syntax as JavaScript, here is my config:

```
{
	"clients": {
		"lsp-tsserver": {
			"enabled": true,
			"command": ["lsp-tsserver"],
			"languageId": "javascript",
			"scopes": ["source.js", "source.jsx"],
			"syntaxes": ["Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax"]
		}
    },
	"complete_all_chars": true
}
```

* OS: Mac OS 10.15.x
* Installed LSP through Package Control.
* To repro: Install Naomi syntax package, enable `lsp-tsserver` globally. Disable Sublime's native JavaScript package. Observe that Naomi JavaScript is not recognized by LSP.

I don't see anything logging in LSPs diagnostic or log panel (or even Sublime's own console).

**Comment by rchl** [comment]
Run `view.settings().get('syntax')` in the ST's console to figure out the syntax. Then number is possibly auto-generated and different for you than for others.

With ST4 it's no longer required to provide syntax, just a scope-based selector.

**Comment by ryanpcmcquen** [comment]
The syntax is source.js, so it should apply. I gave up on Naomi though because of this issue.

**Comment by rchl** [comment]
With ST3 it's necessary to provide the syntax path - it needs to match for the language server to start.
In ST4 that's no longer necessary as it uses different means of matching the document.

**Comment by ryanpcmcquen** [comment]
That'll be nice.
