### ISSUE TITLE
Long log messages should be trimmed

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#1029]
Using the document/workspace symbol commands it's possible send payloads of many megabytes which is viewed in the LSP log panel will halt the program. These long messages should be identified and trimmed down to show only the first portion.

**Comment by rwols** [comment]
Kind of fixed with #1167. However, that PR doesn't "cut off" the string, but rather replaces it with the string "<params with X characters>". But, if you need more serious logging I suggest you look into the remote logger from @rchl.
