### ISSUE TITLE
No auto-completion in julia for sublime text3

### ISSUE THREAD

**Issue by AndyYangjd** [sublimelsp/LSP#1033]
Question: no auto-complete in julia for sublime text3, but the auto-format functon in LSP done well.

* OS: win10
* language server in julia : v2.0.1
* The means of installing LSP: Package Control
* The LSP settings:  
"clients":
	{
		"julials":
		{
			"command":
			[
				"julia",
				"--startup-file=no",
				"--history-file=no",
				"-e",
				"using Pkg; using LanguageServer; using LanguageServer.SymbolServer; env_path=dirname(Pkg.Types.Context().env.project_file); server=LanguageServer.LanguageServerInstance(stdin,stdout,false,env_path,first(Base.DEPOT_PATH)); run(server)"
			],
			"enabled": true,
			"languageId": "julia",
			"scopes":
			[
				"source.julia"
			],
			"settings":
			{
				"julia":
				{
					"format":
					{
						"calls": true,
						"comments": true,
						"curly": true,
						"docs": true,
						"indent": 4,
						"indents": true,
						"iterOps": true,
						"kw": true,
						"lineends": false,
						"ops": true,
						"tuples": true
					},
					"lint":
					{
						"call": false,
						"constif": true,
						"datadecl": false,
						"iter": true,
						"lazy": true,
						"missingrefs": true,
						"modname": true,
						"nothingcomp": false,
						"pirates": true,
						"run": true,
						"typeparam": true,
						"useoffuncargs": true
					}
				}
			},
			"syntaxes":
			[
				"Packages/Julia/Julia.sublime-syntax"
			]
		},
	},
* I also install TabNine and config the auto-complete to false in settings.
* get the output below in LSP' panel when i set the log_payloads & log_stderr to true.
![图片](https://user-images.githubusercontent.com/44262434/81488770-04bae000-92a0-11ea-842a-1d5af33ae4a9.png)
I’m curious about what does the “Info: Received new data from Julia Symbol Server” mean.
At first i guess it means the LSP collect infomation in julia&packages, but the termianal looks still after several minutes. So i’m at a loss.

**Comment by jwortmann** [comment]
In the Julia discourse forum you wrote that LSP doesn't send `textDocument/completion` requests at all to the server while typing. Could you post a full output log (only "log_payloads") for opening a file and typing some letters after the server started, so we can look into why that is the case?

**Comment by rwols** [comment]
It's possible TabNine is doing the same crazy state-machine hacks that we do with respect to completions. Disable it with Package Control to make sure that it's not interfering with LSP's completion logic.

(The crazy state-machine hacks are gone in ST4)

**Comment by AndyYangjd** [comment]
@rwols You're right. The auto-completion in LSP done well after i disable the TabNine and set the auto_complete to true in Preferences.sublime-settings-user.
![a](https://user-images.githubusercontent.com/44262434/81503688-944fa580-9317-11ea-95bd-88fe605e4942.jpg)

@jwortmann Though the auto-complete function work well, i can't see the LSP-panel with  only setting the log_payloads to true. Also it seems that the LSP LSP doesn't send textDocument/completion requests at all to the server while typing, because i can't see the log.
![b](https://user-images.githubusercontent.com/44262434/81503815-556e1f80-9318-11ea-833a-781362ee4ca1.PNG)

**Comment by rwols** [comment]
Run “LSP: Toggle Log Panel” from the command palette.

**Comment by jwortmann** [comment]
OK then I guess we don't need the logs anymore and this issue could be closed. I was just confused because you [previously wrote](https://discourse.julialang.org/t/sublime-text-3-worth-a-look/17142/110) that disabling TabNine had no effect. Perhaps Sublime just needed a restart.

**Comment by AndyYangjd** [comment]
Your're right. Perhaps Sublime also need to set the "auto_complete" to true.
