### ISSUE TITLE
WorkspaceFolders should be in same order as project file

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#1038]
Currently the workspaceFolder paths sent to the server on startup (in the `initialize` message) are not in the same order as they appear in the project file itself.

On MacOS (at least) .sublime-project files contain relative paths so that "." refers to the same folder as the project file. If the order is maintained then the current working directory in the server process will be in sync with the project file so using relative paths in will resolve properly.

This is important for language servers that need to reference files which are kept in the same location as the project file. For example the server below can rely on relative paths because the program file (MyProgram.pas) is in the same location as the sublime text project.

```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"LSP":
		{
			"pascal-language-server":
			{
				"enabled": true,
				"initializationOptions": {
					"program": "./MyProgram.pas",
				}
			}
		}
	}
}
```

**Comment by rchl** [comment]
As longs as the API (`window.folders()`) returns correct order, we should be able to follow that. Not arguing here.

(But here is the off-topic part: You are assuming specific things about where the project file is (which doesn't even exist as a concept in LSP) and you are also assuming that the first folder is what matches the project folder. You probably shouldn't do that but you do you, it's your server that maybe you are not planning to publish anyway. :).)

**Comment by genericptr** [comment]
This is a meta-programming problem it feels like. My brain hurts. ;) Anyways, I don't think the order is the problem although it should be fixed for the sake of logic. 

The problems seems to be "." is the relative location of the project file, that's a fact established by ST by using this symbol in the first place, otherwise I would never have made that assumption.

In my mind I see the "." in the "folders" array and automatically expand it as I'm editing the project file. Every time I see . in the file, I expect it to be expanded to the same location. 

So it's really not about LSP even, it's about expanding paths at the time you read the sublime project file. If "." equals CWD at the top of the file then it should be true at the bottom of the file.

**Comment by rwols** [comment]
You're relying on behavior of a specific editor. In the protocol there's no such thing as a project root folder. Moreover the project file may live in a folder that is not related to the folders specified in the project.

**Comment by genericptr** [comment]
If you're not going to maintain the workspace order as defined by the editor maybe you can consider not changing the working directory at all? I don't know why you decided that folder 0 should be the current working directory instead of leaving it as it was set by Sublime Text. There's nothing in the protocol that says the current working directory should be changed to arbitrary workspace folders so can we at least keep it unchanged?
