### ISSUE TITLE
Support macros in sublime-project files

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#1042]
In the interest of making `initializationOptions` easier to use, allow the use of macros in sublime-project files similar to how VSCode allows `${workspaceFolder}` to mean "current working directory".

**Comment by genericptr** [comment]
I guess this has already been rejected on the grounds of unneeded complexity.

**Comment by rwols** [comment]
Yeah but I disagree with the unneeded complexity argument. It's just not that hard to write. Seems like a one-liner if I can believe the console.

```
>>> sublime.expand_variables({'foo': {'bar': {'baz': {'qux': '${project_path}'}}}}, window.extract_variables())
{'foo': {'bar': {'baz': {'qux': '/home/raoul/.config/sublime-text-3/Packages/LSP'}}}}
```

**Comment by jfcherng** [comment]
Wow. I thought `sublime.expand_variables()` only work on strings.

**Comment by genericptr** [comment]
Servers are going to be using sublime-project as a location to store data files and so we want a way to reference this location. Using absolute paths means if I ever move a project I need to go in and manually change a bunch of paths. A simple macro system is totally worth the trivial work of expanding macros, like you said just a single function or line even.

**Comment by rwols** [comment]
`initializationOptions` are expanded in ST4: https://github.com/sublimelsp/LSP/blob/st4000-exploration/plugin/core/sessions.py#L243

You can use the following template strings:

```
        $file
        $file_base_name
        $file_extension
        $file_name
        $file_path
        $platform
        $project
        $project_base_name
        $project_extension
        $project_name
        $project_path
        $cache_path          sublime.cache_path()
        $temp_dir            tempfile.gettempdir()
        $home                os.path.expanduser('~')
```

**Comment by rchl** [comment]
And also in ST3 with the latest changes (not released at the time of writing but should be soon).
