### ISSUE TITLE
Move to dotted server settings

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1047]
The decision to make server settings be a dict was not optimal in hindsight.

- It's awkward to override a single setting,
- It's kind of hard to read.
- The number of saved characters doesn't matter much.
- Virtually all language servers describe their settings in dotted path notation in their readmes. This confuses users on what to write exactly in LSP.sublime-settings.

I propose we start moving towards dotted notation for server settings for ST4.

**Comment by rchl** [comment]
Sounds good to me.
We could transition softly by having a flag like `supports_dotted_configuration` to make the transition smoother (`Session` needs to know how to read settings when asked through `workspace/configuration`.)

**Comment by jwortmann** [comment]
I think it would also be possible to allow both styles at the same time, with the dotted settings take priority if both styles are present. That wouldn't break compatibility with the current setting style.

Furthermore maybe worth to think about to allow these settings being specified in the general Preferences.sublime-settings file. That is the way how it is stored in VS Code. Again, these could then be overriden by those put in LSP.sublime-settings and project specific settings.

**Comment by rwols** [comment]
Yes, both styles are possible at the same time. I already have something working.

> Furthermore maybe worth to think about to allow these settings being specified in the general Preferences.sublime-settings file. That is the way how it is stored in VS Code. Again, these could then be overriden by those put in LSP.sublime-settings and project specific settings.

Agreed, but that is a story for another time.

**Comment by rwols** [comment]
Fixed by #1049
