### ISSUE TITLE
Core architecture needs a rework

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1052]
The current architecture has a few problems:

- Diagnostic regions of the assoicated sessions are not cleaned up when you disable an LSP-* package
- The `initialize` method of view event listeners can fire too early. This is especially true when a server does dynamic registration.
- Too many fragmented view event listeners. It's hard to make them work together. We should have one view event listener (example: state machine for signature help / doc popup / hover)
- view settings are not cleaned up: `lsp_language` and `lsp_active`.
- `lsp_language` setting on a view is a dict; it should be a string.
- Not a true "multi-session" framework. There are some fixes here and there to get multiple sessions per view working but there's not a good base for it.
- Requests should be able to carry more state for progress reporting and partial results
- It's not possible to get a list of the views associated to a Session (e.g. for set_status)

**Comment by rwols** [comment]
It would also be good to remove the blocking request functionality. It turned out to be too dangerous (for example; any call to the ST API makes ST deadlock). The only place we really use it is in the "do-some-stuff-just-before-saving" functionality (code actions on save, format on save, willSaveWaitUntil). I think it's possible to implement that by listening for the `"save"` command, rewrite it to the `"noop"` command, and then do our stuff async (and then lastly do the `"save"` command again without rewriting it).

**Comment by rwols** [comment]
The issue with `lsp_language` being a dict is annoying. The current settings schema for a server allows users to arbitrarily assign syntaxes/selectors to a language ID. It should instead go through another map. Because most language IDs follow the pattern `languageId <---> source.${languageId}` it's doable to maintain such a map. Something like this?

```js
{
    // languageID -> {document_selector, feature_selector}
    "bat": {"document_selector": "source.dosbatch"},
    "bibtex": {"document_selector": "text.bibtex"},
    "cpp": {"document_selector": "source.c++"},
    "csharp": {"document_selector": "source.cs"},
    "html": {"document_selector": "embedding.php | text.html.basic", "feature_selector": "text.html"},
    "javascript": {"document_selector": "source.js"},
    "javascriptreact": {"document_selector": "source.jsx"}, // 3rdparty
    "jsonc": {"document_selector": "source.json"},
    "latex": {"document_selector": "text.tex"},
    "markdown": {"document_selector": "text.html.markdown"},
    "objective-c": {"document_selector": "source.objc"},
    "objective-cpp": {"document_selector": "source.objective-c++"},
    "php": {"document_selector": "source.php | embedding.php"},
    "ruby": {"document_selector": "text.html.ruby | source.ruby"},
    "shaderlab": {"document_selector": "source.glsl | source.essl"}, // 3rdparty
    "shellscript": {"document_selector": "source.shell.bash"},
    "typescript": {"document_selector": "source.ts"}, // 3rdparty
    "typescriptreact": {"document_selector": "source.tsx"}, // 3rdparty
    "vue": {"document_selector": "tex.html.vue"}, // 3rdparty
    "xml": {"document_selector": "text.xml"},
    "xsl": {"document_selector": "text.xml"}, // 3rdparty
}
```

**Comment by rwols** [comment]
So, with this mapping we can write server configs like this:

```js
{
    "command": ["node", "$cache/LSP-css/out/bin/server.js" "--stdio"],
    "languages": ["css", "scss", "less"]
}
```

```js
{
    "command": ["java", "-jar", "$cache/LSP-lemminx/server.jar"],
    "languages": ["xml"]
}
```
```js
{
    "command": ["clangd"],
    "languages": ["c", "cpp", "objective-c", "objective-cpp", "cuda"]
}
```
```js
{
    "command": ["ccls"],
    // note that you CAN'T have a different document selector for ccls versus clangd
    "languages": ["c", "cpp", "objective-c", "objective-cpp", "cuda"]
}
```

**Comment by predragnikolic** [comment]
This was brought up by @rchl.
https://github.com/sublimelsp/LSP/pull/1022#discussion_r422701061
```
    def do_resolve(self, item: dict) -> None:
        session = session_for_view(self.view, 'completionProvider.resolveProvider')
        if session:
            session.client.send_request(
                Request.resolveCompletionItem(item),
```
> I don't want to say this is wrong because I don't want to open another big exchange here but sending requests to all servers seems wrong ;). Sending it just to the first one also seems wrong. Ideally, we would send it to the one that provided the suggestion.

We need a way to get a session for that fired the completion request, and use the same session for the resolve request. session_for_view returns the "best matching" session for that particular point :) 

One way to solve it is to add an `id` field to a session.
And whenever we make a request, 
we add the `session.id` to associate a the request to a session.
And when we receive a response,
in the response we will also have a `session.id`. By that id we will know what session made the request.

We can have `get_session_by_id(id)` to retrieve the session... This is just an idea

**Comment by rwols** [comment]
The `install_or_update` method for plugins currently runs in ST's worker thread. Because it can take a while to install something, it might be better to run that function in its own thread.

**Comment by rwols** [comment]
> I can save the session.config.name before sending the request. And pass it till the do_resolve function. I just need a function get_session_by_config_name(config_name) to retrieve the session...

Sessions are uniquely identifier by their name *and* set of workspace folders that they operate on. You can have two sessions with the same name working on different workspace folders in the same window (if they are workspace-unaware). But it won't matter if you know the view or uri. In that case sessions are uniquely identifier by their name.

**Comment by rwols** [comment]
Things left to do:

- We have to use `DocumentSelector` for real in the config files. It already works for dynamic registrations, which was the technical challenge. There will now be a communication/deprecation challenge for implementing it in the static config files.
- SessionBuffer should be aware of its in-flight requests. This will allow us to implement things like cancellation when a view closes, workDoneProgress support, and showing the active requests in the status bar.
- Cancellation is a hard topic and I don't think we can do cancellation for old requests unless we switch to asyncio. For example, when a language server takes a long time to compute textDocument/documentSymbol and the user re-requests it because he/she is impatient, we should cancel the old request. Other possible cancellation points are when the buffer has changed, but I've seen clangd reporting a cancellation itself when that happens.
- Handle cancellation notifications when a language server cancels a request, for example due to buffer changes in the meantime.
- partial results for things like textDocument/references and workspace/symbol.
- Prepare for asyncio by removing the requests lock in `Session`.
- Prepare for asyncio by running all request/response/notification handlers on ST's worker thread so we already get used to more serial communication.

**Comment by rwols** [comment]
I'll close this issue and make separate issues for it instead.
