### ISSUE TITLE
How to use with Zig?

### ISSUE THREAD

**Issue by daurnimator** [sublimelsp/LSP#1054]
* OS and language server: Linux
* How you installed LSP (Package Control or from git?): Package Control

I'd like to use your project with the Zig language. However I didn't find the instructions clear. Currently the preferred LSP is [zls](https://github.com/zigtools/zls). The zig sublime package is [here](https://github.com/ziglang/sublime-zig-language) (which I install via package control).

How do I figure out the:
  - languageId
  - scope(s)
  - syntaxes

<details><summary>Further info:</summary><p>

```
$ find ~/.config/sublime-text-3 -iname '*zig*'
/home/daurnimator/.config/sublime-text-3/Packages/User/Zig.sublime-settings
/home/daurnimator/.config/sublime-text-3/Installed Packages/Zig Language.sublime-package
/home/daurnimator/.config/sublime-text-3/Cache/User/Zig
/home/daurnimator/.config/sublime-text-3/Cache/User/Zig/Zig.tmLanguage.cache
/home/daurnimator/.config/sublime-text-3/Cache/Zig Language
/home/daurnimator/.config/sublime-text-3/Cache/Zig Language/Zig.tmLanguage.cache
/home/daurnimator/.config/sublime-text-3/Cache/Zig Language/Zig.tmLanguage.rcache
/home/daurnimator/.config/sublime-text-3/Cache/Zig Language/Syntaxes/Zig.tmLanguage.cache
/home/daurnimator/.config/sublime-text-3/Cache/Zig Language/Syntaxes/Zig.tmLanguage.rcache
```

Random guess for config:
```json
{
  "clients": {
	"zig": {
		"command": ["zls"],
		"enable": true,
		"languageId": "zig",
		"scopes": [
			"source.zig"
		],
		"syntaxes": [
			"Packages/User/Zig.sublime-syntax"
		]
	}
  }
}
```
</p>
</details>

**Comment by rwols** [comment]
It should be:

```
{
    "clients": {
        "zig":{
            "command": ["zls"],
            "enable": true,
            "languageId": "zig",
            "scopes": ["source.zig"],
            "syntaxes": ["Packages/Zig Language/Syntaxes/Zig.tmLanguage"]
        }
    }
}

```
provided that `zls` is in your `$PATH`. Restart ST after you've made changes to LSP.sublime-settings.

**Comment by daurnimator** [comment]
> You can figure out the scope with Tools > Developer > Show Scope Name.
> You can figure out the syntax by opening the ST console and running `view.settings().get("syntax")`.

Thanks! Could you add this info somewhere on https://lsp.readthedocs.io/en/latest/ ?

**Comment by predragnikolic** [comment]
@daurnimator feel free to open a PR :)
the documentation you see on  https://lsp.readthedocs.io/en/latest/  is defined in the LSP repo. (to be precise in `LSP/docs/index.md`)
Also you could also add it in the list of supported languages in the main README (https://github.com/sublimelsp/LSP#available-languages).

**Comment by gxanshu** [comment]
Anyone new looking to install LSP for Zig visit there [official docs](https://github.com/zigtools/zls/wiki/Installation#sublime-text)
