### ISSUE TITLE
Noticeable lag on closing a file

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1057]
* OSX 10.15
* branch: st4000-exploration (8d81a29e54bd7ad148592f0d5c9443b795e32bf2)

There is a noticeable delay on closing a file before the previous file gets activated.

Uploading two videos - one with LSP enabled and one with disabled. You can notice that after closing the tab, the current tab remains in the tab bar for a while.
[demonstration.zip](https://github.com/sublimelsp/LSP/files/4649142/demonstration.zip)

"Profile plugins" doesn't seem to represent that lag in numbers.

**Comment by rchl** [comment]
Note that when using mouse to close the file, the previous file shows up immediately even though the lag is still there.
When closing file with the keyboard (more realistic scenario) the previous file doesn't show up until after the short lag.

**Comment by rchl** [comment]
`master` branch doesn't have this issue and feels much more snappy on closing the file.

**Comment by rwols** [comment]
I'm guessing this is due to a `__del__` in the completion view event listener. It is needed though.

Expect to see more usage of `__del__` as cleaning up resources is important and allows a more dynamic approach.

**Comment by rchl** [comment]
It doesn't seem to be that. I've disabled it and it didn't help. Also tried disabling `on_close` and a couple of other things but nothing made it as snappy as on `master`. Don't have more time to investigate right now.

**Comment by rwols** [comment]
Oh... then I have no idea 😄

**Comment by rchl** [comment]
Git bisect found out the guilty one: 54b9adb31dcff9802ee9b1639a0eb707aa7c5519

It looks like it's `is_supported_syntax` function that is called a lot on de(activating) views and makes things slow.

Not sure if the main offender is `sublime.list_syntaxes` or `sublime.score_selector` but probably one of those.

**Comment by rwols** [comment]
You can try making it a little faster by optimizing `_needed_configs` in WindowManager, perhaps. We're also calling that function twice for reasons I don't quite understand.

**Comment by rwols** [comment]
The `is_supported_syntax` function is also called by every view event listener instance. Yet another reason to move towards one view event listener.

**Comment by rchl** [comment]
#1059 cleans up the code so that we use `is_supported_syntax` only from one place (`LSPViewEventListener`). It will make it easier to implement caching.

Caching needs to be invalidated when configs change though so that makes things a bit more tricky.
