### ISSUE TITLE
cant initialize gopls: invalid response payload to gopls initialize(1)

### ISSUE THREAD

**Issue by alvarolm** [sublimelsp/LSP#1080]
I'm just having a little bit of trouble trying to setup gopls with LSP, any help is appreciated, thanks in advance.

* OS and language server

Ubuntu 18.04.3 LTS
4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

Sublime Text 3.2.2 Build 3211

* How you installed LSP (Package Control or from git?)

Package Control: Install Package, then LSP

* Minimal reproduction steps

"LSP: Enable Language Server Globally" from the Command Palette and chosen gopls.

* Logs:

* Language Servers pane:

:: --> gopls initialize(1): {'rootUri': None, 'initializationOptions': {}, 'clientInfo': {'version': '0.10.1', 'name': 'Sublime Text LSP'}, 'capabilities': {'window': {'workDoneProgress': True}, 'workspace': {'configuration': True, 'workspaceEdit': {'documentChanges': True, 'failureHandling': 'abort'}, 'applyEdit': True, 'executeCommand': {}, 'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceFolders': True, 'symbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}}, 'textDocument': {'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'hover': {'contentFormat': ['markdown', 'plaintext'], 'dynamicRegistration': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'completion': {'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'completionItem': {'snippetSupport': True}, 'dynamicRegistration': True}, 'formatting': {'dynamicRegistration': True}, 'rename': {'dynamicRegistration': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}, 'dynamicRegistration': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'documentHighlight': {'dynamicRegistration': True}, 'synchronization': {'willSave': True, 'willSaveWaitUntil': True, 'didSave': True, 'dynamicRegistration': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}, 'references': {'dynamicRegistration': True}, 'documentSymbol': {'hierarchicalDocumentSymbolSupport': True, 'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'publishDiagnostics': {'relatedInformation': True}, 'colorProvider': {'dynamicRegistration': True}}, 'experimental': {}}, 'rootPath': None, 'processId': 15455, 'workspaceFolders': None}
:: <<< gopls 1: {'code': -32602, 'message': 'invalid response payload'}
:: --> gopls shutdown(2): None
:: <<< gopls 2: None
::  -> gopls exit: None

* Console logs:
...
LSP: global configs ['rust-analyzer=False', 'intelephense-ls=False', 'vscode-css=False', 'rls=False', 'sorbet=False', 'reason=False', 'haskell-ide-engine=False', 'bashls=False', 'golsp=False', 'gopls=True', 'dart=False', 'javascript-typescript-langserver=False', 'sourcekit-lsp=False', 'polymer-ide=False', 'ocaml=False', 'jdtls=False', 'elixir-ls=False', 'erlang-ls=False', 'ruby=False', 'typescript-language-server=False', 'cquery=False', 'lsp-tsserver=False', 'clangd=False', 'rlang=False', 'phpls=False', 'pyls=False', 'flow=False']
LSP: group 0 view None
LSP: group 1 view /home/user/.config/sublime-text-3/Packages/User/LSP.sublime-settings
LSP: window 2 starting 2 initial views
...
LSP: window has override for golsp {'enabled': True}
LSP: window 2 requests gopls for /home/user/dev/assets/go/src/...go
LSP: starting ['gopls']
LSP: window 2 added session gopls
LSP: window 2 requests gopls for /home/user/dev/assets/go/src/...go
...
LSP: LSP stream logger stopped.
LSP: scheduling for delayed open, session gopls not ready: /home/user/dev/assets/go/src/...go
LSP: session gopls ended
LSP: process 15706 stdout ended (still alive)
LSP: process 15706 exited with code 0

* LSP sublime Settings:
{
  "log_debug": true,
  "log_server": true,
  "log_stderr": true,
  "log_payloads": true,
  "clients": {
		"gopls":
		{
			"enabled": true,
		}
  },

**Comment by rwols** [comment]
It looks like you opened a window to a single file (because rootUri is None). Try opening a folder instead?

**Comment by alvarolm** [comment]
thank you !
its working as expected now.

but cant avoid to wonder why not to infer rootUri when opening a window to single file, there are various cases where there is not necessary to open a folder. could you guide where to start digging
?

**Comment by alvarolm** [comment]
https://github.com/golang/go/issues/34160

**Comment by rchl** [comment]
You can check #997 for some relevant information.
