### ISSUE TITLE
Request code actions at the cursor/selection when the selection is modified

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1085]
The [rust-analyzer language server](https://rust-analyzer.github.io/manual.html#assists-code-actions) makes use of VSCode's behavior to request "diagnostic-less" code actions at the cursor whenever it changes. [A user reported this on discord](https://discord.com/channels/280102180189634562/645268178397560865/717091710739546182). We should mirror the behavior. This has already been observed and discussed [here](https://github.com/sublimelsp/LSP/pull/779#issuecomment-557704533).

Because code-actions returned from this type of request do not belong to any diagnostics, we may have to adjust the internal design of the code a little for this feature. For example, we should invalidate those type of code actions whenever the buffer is modified. Most likely we can re-use the logic present in highlights.py or color.py.

Also, the user cannot "see" these code actions unless they turned on the gutter bulb.

**Comment by rchl** [comment]
I can do it after finishing CAOS (soon, I think). I'd want to avoid conflicting changes for now :)

**Comment by rchl** [comment]
I wonder if it's again the cause of custom handling in the extension that makes this server trigger code actions on selection change. It doesn't look like VSCode triggers code actions on selection change for other servers (tried eslint).

Here is some relevant code but it doesn't give me a clear answer: https://github.com/rust-analyzer/rust-analyzer/blob/4029628f15c612182ad9da1c652078f9df62f5cf/editors/code/src/client.ts#L69-L71

If that middleware is called on every selection change then that would explain the behavior but then do we really want to do the same for every server?

And then there is also this comment in that code:
```
// In our case we expect to get code edits only from diagnostics
```
which doesn't really seem to be the case.

**Comment by rchl** [comment]
Also, it builds somewhat custom code actions in that code so, since we don't do that, those code actions wouldn't work for us anyway.

```
action.command = {
                            command: "rust-analyzer.resolveCodeAction",
                            title: item.title,
                            arguments: [resolveParams],
                        };
```

So this behavior might be wanted anyway but rust-analyzer will still not function properly.

And we might want to consider performance impact of triggering code actions on all cursor movements (even when typing).

**Comment by rwols** [comment]
Implemented by https://github.com/sublimelsp/LSP/pull/1109
