### ISSUE TITLE
View synchronization issue when modifying file during LSP initialization

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1096]
1. Install `lsp-eslint` (you might also need proper eslint configuration...)
2. Restart ST with such document open
```js
const a = 1;
const b = 2;
const c = 3;
```
3. While LSP is initializing, join all three lines with `cmd+j` (or equivalent on non-macs).
4. Wait for LSP to initialize fully
5. Undo changes with cmd+z (or equivalent).

The diagnostics will be messed up.
Log:
 - `textDocument/didOpen`:
```const a = 1; const b = 2; const c = 3;\n```
 - `textDocument/didChange`:
```
  "contentChanges": [
    {
      "rangeLength": 1,
      "range": {
        "start": {
          "line": 0,
          "character": 25
        },
        "end": {
          "line": 1,
          "character": 0
        }
      },
      "text": ""
    },
    {
      "rangeLength": 0,
      "range": {
        "start": {
          "line": 0,
          "character": 25
        },
        "end": {
          "line": 0,
          "character": 25
        }
      },
      "text": " "
    }
  ]
```

This is already wrong as replies changes that no longer apply for the view that was sent in `didOpen`.

(Issue found by @predragnikolic )

**Comment by rchl** [comment]
Maybe `on_text_changed` should also include a "document version" (`view.change_count()`) so that we can discard changes that are for past versions of the view.

**Comment by predragnikolic** [comment]
Thanks for the quick fix @rchl 
I can confirm that I no longer experience the issue after #1097
