### ISSUE TITLE
LSP should run CodeAction "edit" before "command" when both exist

### ISSUE THREAD

**Issue by Narretz** [sublimelsp/LSP#1098]
The LSP spec says that when a CodeAction has edit and command, first the edit should be run on the client, then the command should be sent to the server:

```
	/**
	 * The workspace edit this code action performs.
	 */
	edit?: WorkspaceEdit;

	/**
	 * A command this code action executes. If a code action
	 * provides an edit and a command, first the edit is
	 * executed and then the command.
	 */
	command?: Command;
```

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction
(at the bottom of the section)

Currently, LSP kind of tries to implement this, but it's not correct:
https://github.com/sublimelsp/LSP/blob/753f8675452c1a4056c606c92a6ad8d26281e138/plugin/code_actions.py#L167-L179

is_command will return true if command is a string, which means any CodeAction with a command will only execute the command
https://github.com/sublimelsp/LSP/blob/753f8675452c1a4056c606c92a6ad8d26281e138/plugin/code_actions.py#L147-L149

**Comment by rchl** [comment]
But according to the spec `command` can not be a string:
```ts
command?: Command;
```
while `Command` is defined as 
```ts
interface Command {
	/**
	 * Title of the command, like `save`.
	 */
	title: string;
	/**
	 * The identifier of the actual command handler.
	 */
	command: string;
	/**
	 * Arguments that the command handler should be
	 * invoked with.
	 */
	arguments?: any[];
}
```
So I think the code will accidentally do the right thing anyway.

**Comment by rchl** [comment]
Well, as we see in https://github.com/sublimelsp/LSP-vue/issues/4, the `command` is a string sometimes. But that response is non-standard so...

**Comment by Narretz** [comment]
I just tested this with a modified version of Vetur, and LSP only executes the Command.

The response for CodeAction request is this:
`result: (Command | CodeAction)[] | null`

A Command has the following props:

title 
command
arguments

A Code Action has these props:

title
command?
edit?
(and more optionals)

So command_or_code_action is either a Command or a CodeAction, and since both have a string "command" prop, it's not enough to check for it to distinguish them.

**Comment by Narretz** [comment]
You are right, I was so blinded by this whole thing that I didn't grasp that CodeAction.command is a Command instance
