### ISSUE TITLE
LSP4 release should have different (higher) version than LSP3

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1103]
The LSP version for ST4 should have higher version number than the ST3 version.

For once, because it makes sense to differentiate them by version number and more importantly so that PackageControl actually updates to compatible version when upgrading from ST3 to ST4.

If the version is the same then PC will keep existing (old) version.

So for example we could bump LSP4 to 1.x.x version and keep 0.x.x range for LSP3. Or just to 0.20.x and keep <0.20.x range for LSP3, depending on how we feel about stability.

**Comment by rwols** [comment]
Bumped st4 to 1.x.x.
