### ISSUE TITLE
Handle diagnostics with no range

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1104]
I've just spent more time than I wanted on figuring out why eslint doesn't work in typescript file.

It seems like eslint server returned diagnostic that would make the problem clear but I could see it because it had no range. Apparently VSCode still showed it but not us.

```
[Trace - 4:13:03 PM] Sending request 'textDocument/codeAction - (5)'.
Params: {
    "textDocument": {
        "uri": "file://project/types/index.d.ts"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": null,
                        "character": null
                    },
                    "end": {
                        "line": null,
                        "character": null
                    }
                },
                "message": "Parsing error: \"parserOptions.project\" has been set for @typescript-eslint/parser.\nThe file does not match your project config: types/index.d.ts.\nThe file must be included in at least one of the projects provided.",
                "severity": 1,
                "source": "eslint"
            }
        ],
        "only": [
            "quickfix"
        ]
    }
}
```

![Screenshot 2020-06-08 at 16 16 12](https://user-images.githubusercontent.com/153197/84040820-648dcf00-a9a3-11ea-99b4-781132318972.png)

**Comment by rchl** [comment]
It seems to be marking the whole first work or if there is none, it does this:
![Screenshot 2020-06-08 at 16 17 12](https://user-images.githubusercontent.com/153197/84040960-9010b980-a9a3-11ea-9233-e74416ea06d9.png)

**Comment by rwols** [comment]
The type of `line` and `character` is `number`, not `number?`.

**Comment by rchl** [comment]
https://github.com/microsoft/vscode-eslint/issues/987

**Comment by predragnikolic** [comment]
I just followed this [guide](
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md).
I manged to setup eslint with typescript/

![image](https://user-images.githubusercontent.com/22029477/84067899-7766ca80-a9c8-11ea-8fa4-747889adfaa3.png)

Here is an example repo
https://github.com/predragnikolic/eslint-typescript-example

**Comment by rchl** [comment]
Upstream bug fixed.
We'll get diagnostics with 0,0 location so I hope that will show up somehow?

**Comment by rchl** [comment]
First character in the view is highlighted in this case.
![Screenshot 2020-06-12 at 21 57 21](https://user-images.githubusercontent.com/153197/84541460-b746ee00-acf7-11ea-828c-82fda4515386.png)
