### ISSUE TITLE
When there's only a documentRangeFormattingProvider, do "full" formatting via that capability

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1106]
It can be the case that the server advertises only as documentRangeFormattingProvider, but not as documentFormattingProvider.

In that case, still allow the user to format the entire file simply by passing the entire range of the view to the range formatter.

see also https://github.com/microsoft/vscode/issues/99513

**Comment by rwols** [comment]
Fixed by #1111 (why did this not close automatically?)

**Comment by rchl** [comment]
I've noticed that bugs never do. Maybe there is some setting for repo?

**Comment by predragnikolic** [comment]
Maybe because in the PR description you wrote 'close 1106' instead of 'closes 1106'
