### ISSUE TITLE
LSP-eslint partially stops working after "restart servers"

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1114]
LSP 23d5f0888baec58e4763c4258d151c2a5e05bce9

I open vue document that starts those servers:
![Screenshot 2020-06-11 at 12 13 01](https://user-images.githubusercontent.com/153197/84373613-1d8b1e00-abdd-11ea-8066-015e48462b05.png)

After triggering `LSP: Restart servers` all servers are restarted (based on the logs), but `lsp-eslint` doesn't re-appear in the status bar:
![Screenshot 2020-06-11 at 12 13 11](https://user-images.githubusercontent.com/153197/84373675-34317500-abdd-11ea-9b69-ff00808bdf9e.png)

In the logs I can see that some requests are still being made to lsp-eslint (like code actions), but for example, it no longer works for CAOS.

**Comment by rwols** [comment]
Does this still happen with the latest st4000-exploration?

**Comment by rchl** [comment]
Works fine now. :)
