### ISSUE TITLE
Latest release 4070-1.0.1 Phantom Code Action bug

### ISSUE THREAD

**Issue by marcoSven** [sublimelsp/LSP#1126]
Your issue may have been solved already - please search before creating new!

Please see attached screenshot
<img width="961" alt="Screen Shot 2020-06-15" src="https://user-images.githubusercontent.com/3860298/84677636-dace8c00-aee3-11ea-8d05-21372567acb3.png">

Troubleshooting guide: https://lsp.readthedocs.io/en/latest/troubleshooting
Chat: https://discord.gg/RMkk5MR
Miscellaneous notes (anyone can edit!): https://github.com/sublimelsp/LSP/wiki/Notes

Is it a language server problem? The LSP package can do little to prevent slowness or missing content - please check their support materials!

Please include in your report:

* OS and language server
* How you installed LSP (Package Control or from git?)
* Minimal reproduction steps
* Log

OSX ST4 LSP LSP-typescript

Requesting a feature?

Please read https://github.com/sublimelsp/LSP/blob/master/CONTRIBUTING.md. Specifically, LSP avoids building functionality that does not exist in Sublime Text, or that serves only one language.

**Comment by rchl** [comment]
What is the issue? Apart from the screenshot you've just posted default template with no info

**Comment by rwols** [comment]
Most likely this one: https://github.com/sublimehq/sublime_text/issues/3396

**Comment by predragnikolic** [comment]
![20200615_190640](https://user-images.githubusercontent.com/22029477/84685962-61fb1e80-af3b-11ea-9df8-c7b3c0220591.jpg)
Without a DESCRIPTION, there is no HELP. 🙂

**Comment by marcoSven** [comment]
@predragnikolic 😂

@rwols @rchl I apologize, essentially when my cursor is in a region where an action is available I see an annotation with a clickable link to trigger the action options.
Not sure if this is by design, a new feature / config option - it just started to appear today after the last update.

sublimehq/sublime_text#3396 - yes the painting issue also lead me to believe this is a bug

I just glanced at my LSP settings and noticed "show_code_actions_bulb" has disappeared from the default.

My user settings 

```
{
"show_code_actions_bulb": false,
"show_symbol_action_links": false,
}
```
I **believe** "show_symbol_action_links" used to control if the action link is visible in the hover popup, now it shows regardless if true or false

<img width="934" alt="Screen Shot 2020-06-15 at 11 03 24 AM" src="https://user-images.githubusercontent.com/3860298/84691156-871a6d80-aef8-11ea-83b7-8d1b4ba8850d.png">

**Comment by rchl** [comment]
That's a new feature. It's not controllable by any setting (currently at least).

Why do you think it's a bug though? If you click it you should see code actions related to your cursor position. Is that not working correctly?

Yes, `show_code_actions_bulb` was removed since there is no bulb anymore.
As far as `show_symbol_action_links` nothing should have changed and nothing should have changed what appears in the popup by default.

**Comment by marcoSven** [comment]
> That's a new feature. It's not controllable by any setting (currently at least).
That is unfortunate I was about to ask how can to hide it. And no it works as designed, however it is the UI + the painting issue that made me think it's a bug. Personally I think the light bulb in the gutter is a better implementation to point out there is an available code action.  

> As far as show_symbol_action_links
Though I do want action links to show in the hover popup, I did set it to false and I think it's not working see screenshot
<img width="934" alt="Screen Shot 2020-06-15 at 11 03 24 AM" src="https://user-images.githubusercontent.com/3860298/84692938-87683800-aefb-11ea-8e94-ef6568fc05c0.png">

**Comment by rchl** [comment]
>  Personally I think the light bulb in the gutter is a better implementation

See reasoning for current behavior in https://github.com/sublimelsp/LSP/pull/1109#issuecomment-642489969 (you can also read other comments).

> Though I do want action links to show in the hover popup, I did set it to false and I think it's not working see screenshot

`show_symbol_action_links` controls something else ("references", "rename" links and other). I don't think there was ever a setting to disable the Code Actions links.

**Comment by marcoSven** [comment]
> See reasoning for current behavior in #1109 (comment) (you can also read other comments).

Thank you, makes sense - I guess I would like to see show_code_actions_annotations as a replacement for show_code_actions_bulb 😄 

> show_symbol_action_links controls something else

You are right - thanks!

**Comment by rchl** [comment]
> Thank you, makes sense - I guess I would like to see show_code_actions_annotations as a replacement for show_code_actions_bulb 😄

You wouldn't be able to trigger those code actions then though as hover popup only shows annotations related to diagnostics while annotations should both those and ones that don't have any linked diagnostic.

**Comment by predragnikolic** [comment]
FWIW, I still prefer the bulb. For me the only minor disadvantage was not being able to click it, but I could not care less about the click. I just wanted to know it there are any code actions 🙂 (but let's experiment with the anotations)

**Comment by marcoSven** [comment]
@predragnikolic @rchl 
Is it not possible to use the light bulb in the gutter and trigger a popup on hover with the available code actions that are clickable?
