### ISSUE TITLE
Feature request - config option to hide code actions annotations

### ISSUE THREAD

**Issue by marcoSven** [sublimelsp/LSP#1127]
> See reasoning for current behavior in #1109 (comment) (you can also read other comments).

Thank you, makes sense - I guess I would like to see show_code_actions_annotations as a replacement for show_code_actions_bulb 😄 

_Originally posted by @marcoSven in https://github.com/sublimelsp/LSP/issues/1126#issuecomment-644312321_

**Comment by rchl** [comment]
Annotations show code actions for current selection (which always includes empty selection - a plain cursor position) while hover popup only shows code actions related to issues marked with diagnostic. So those are not 100% equivalent even if there is some overlap.

**Comment by predragnikolic** [comment]
Would it be ok to add a setting to chose weather to:
- show the code actions in the annotations,
- or in the gutter with a bulb
- or don't show anything

Something like:
```
// "annotations"
// "bulb"
// "none"
"show_code_actions": "annotation" 
```

I would like to work on this, I just want other people feedback on this :)

**Comment by rchl** [comment]
I really don't think gutter provides good enough UX to use it right now but I won't have strong enough opinion to be against it.

What is the issue with annotation really, compared to the bulb in the gutter? One is on the left and one is on the right (and as a bonus, clickable). It's not that much of a difference IMO.

Maybe bulb image in the annotation is something that would be worth considering instead?

**Comment by marcoSven** [comment]
> What is the issue with annotation really, compared to the bulb in the gutter?

Depending on the Sublime window width, the travel distance from the working area to the annotation on the right can be quite far. Even on a 13 inch I prefer hovering over a gutter icon to trigger a popup ( e.g. Sublime Linter). The popup ideally contains all code actions. Currently you need to move all the way to the right to click on the  annotation followed by moving back to the left and click again on the action links in the popup.


> bulb image in the annotation 

yes that would be great considering the current painting issues - I guess I could live with that and not feel the need to disable it ;)

**Comment by rwols** [comment]
There's a new setting in 4070-1.0.6 called "show_code_actions". If you set it to "bulb" it will show a lightbulb in the gutter instead. (but it's not clickable due to ST API limitations).
