### ISSUE TITLE
Different amount of code actions available for same cursor/pointer position

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1128]
Depending on if we use the mouse pointer or caret, the number of available code actions can differ (annotations will show a different amount than hover popup).

One example where this can happen with LSP-typescript:
```js
const a = require('./types')
```

![Screenshot 2020-06-15 at 22 03 29](https://user-images.githubusercontent.com/153197/84701061-916a5500-af54-11ea-91ee-cd3e0416dc3f.png)

Since `require('./types')` has a diagnostic, hovering within that region will include the region of the diagnostic in `textDocument/codeAction` request while putting a caret within that region will only include the range of the caret and server will not include some code actions then.

When making a code action request for the caret (selection) we should probably extend the range if there is a diagnostic intersecting the selection.

**Comment by rwols** [comment]
Fixed by #1129
