### ISSUE TITLE
Rename Symbol occasionally causes a completely different command to run

### ISSUE THREAD

**Issue by keithrussell42** [sublimelsp/LSP#1131]
Please include in your report:

Windows 10 (I _think_ it was also happening on my Linux machine but I haven't used it for a few months so I can't be sure).
Sublime Text 3.2.2 (build 3211)
Language servers: gopls and jdtls.
Installed LSP v0.11.1 from Package Control 

Unfortunately I don't have a reproducible test case nor can I get logs. The issue is very random.

Occasionally when I run LSP Rename Symbol a completely different command is executed. I've had at least:
  - Package Control remove channel
  - Syntax change to some other type
There were a couple of others I can't remember. There seems to be no consistency. It does not matter which language server I'm using (it's happened for both Go and Java) nor does it matter how I invoke the rename. I've tried the command palette, my keybinding and the context menu all with the same results. Initially I thought my keybinding was interfering with a default which is why I tried it using the other methods.

It's very disconcerting when you're going along only to be presented with a "Are you sure you want to remove the only channel" message from Package Control after pressing LSP Rename Symbol. 

I was actually quite surprised to find no one else had reported it.

**Comment by rwols** [comment]
Perhaps another package is rewriting the command? Can you post your list of packages installed?

**Comment by predragnikolic** [comment]
I experienced this issue a lot on linux while I was using ST3.
In the past on random occasions when I tried to trigger the rename command, 
it either changed the syntax to a different one
or it triggered a random command(can't remember which one)...

If I had to guess this was more likely a Sublime Text 3 bug, but on the bright side I haven't experience it with the latest ST<4000 builds :)

**Comment by willrowe** [comment]
This sounds similar to: https://github.com/sublimehq/sublime_text/issues/3010

**Comment by keithrussell42** [comment]
Ahh ok. Thanks. I'll wait (im)patiently for ST4.
