### ISSUE TITLE
Triggers completion command on the wrong session

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1139]
When having both LSP-css and LSP-stylelint running for open file (*.css), the completions are requested from LSP-css but the `command` that the completion item triggers runs on `LSP-stylelint` triggering an error dialog.

An example completion item looks like this:
```
    {
      "command": {
        "command": "editor.action.triggerSuggest",
        "title": "Suggest"
      },
      "documentation": {
        "kind": "plaintext",
        "value": "Specifies the width of the content area, padding area or border area (depending on 'box-sizing') of certain boxes.\n\nSyntax: <viewport-length>{1,2}\n\nMDN Reference: https://developer.mozilla.org/docs/Web/CSS/width"
      },
      "insertTextFormat": 2,
      "kind": 10,
      "label": "width",
      "sortText": "d_0000",
      "tags": [],
      "textEdit": {
        "newText": "width: $0;",
        "range": {
          "end": {
            "character": 5,
            "line": 4
          },
          "start": {
            "character": 4,
            "line": 4
          }
        }
      }
    },
```

It has a `command` that runs after inserting completion.

**Comment by rchl** [comment]
Even if this is fixed and command runs on the correct session, the `executCommand` will probably still fail as it seems like the intention here is for the editor (VSCode specifically) to intercept that command and trigger completions.

**Comment by rchl** [comment]
So a related question is: do we want to special case `editor.action.triggerSuggest` command in LSP to trigger completion popup (not sure if we are even able to do that)?

**Comment by rwols** [comment]
Maybe we need a mapping from command names that start with `editor.` to ST commands? And then run the ST command instead of a server command.

**Comment by rchl** [comment]
Sure.

I guess LSP could trigger any [VSCode editor action](https://github.com/microsoft/vscode/search?q=extends+EditorAction&unscoped_q=extends+EditorAction) like that but hopefully, it's not that many we have to care about.

**Comment by rchl** [comment]
@rwols let's just keep it simple and just handle that single one for now, as their suggestController does. There is not necessarily gonna be any other to care about.
