### ISSUE TITLE
gopls: Format on save is disabled globally for the duration of the session after syntax error

### ISSUE THREAD

**Issue by uhthomas** [sublimelsp/LSP#1145]
# System information
macOS Catalina 10.15.5 (19F101)
Sublime Text Dev Channel, Build 4074

# Install
Package Control

# Reproduction
Assuming the LSP configuration
```json
{
    "lsp_format_on_save": true,
    "lsp_code_actions_on_save": {
        "source.fixAll": true,
        "source.organizeImports": true
    },
    "show_symbol_action_links": true,
    "only_show_lsp_completions": true,
    "clients": {
        "gopls": {
            "enabled": true,
            "settings": {
                "gopls.usePlaceholders": true,
                "gopls.analyses": {
                  "fillreturns": true,
                  "nonewvars": true,
                  "undeclaredname": true,
                  "unusedparams": true
                },
                "gopls.completeUnimported": true,
                "gopls.staticcheck": true
            }
        }
    }
}
```

Then, given the snippet (note the superfluous indentation, and missing `.`)
```go
package main

import "fmt"

func main() {



                fmt Println("Hello, world!")
}
```

Save the snippet as `main.go`, open `main.go` in `subl` and save (to run the format on save).

Then replace
```go
fmt Println("Hello, world!")
```
with
```go
fmt.Println("Hello, world!")
```

From this point, saving the file does not do any formatting. However, it does still do imports, if
```go
import "fmt"
```
is removed.

# Logs
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 795, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 622, in run_view_callbacks
    callback(*args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 167, in exception_handler
    return event_handler(*args)
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/documents.py", line 52, in on_activated_async
    self.manager.activate_view(self.view)
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 419, in activate_view
    self._initialize_on_open(view)
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 461, in _initialize_on_open
    startable_configs = needed_configs(self._configs.match_view(view))  # type: ignore
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 441, in needed_configs
    for c in configs:
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 47, in match_view
    configs = self.match_document(view2scope(view))
  File "/Users/thomas/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 115, in view2scope
    return view.scope_name(0).split()[0]
IndexError: list index out of range
```

**Comment by rchl** [comment]
I think the log is unrelated as it shows an error that triggered on file activation, not at saving.

Can you try reproducing again and check when does that line appear exactly?

**Comment by uhthomas** [comment]
I had a feeling that might be the case - it's the only output I get, and it's doesn't always show up. Otherwise it's quiet, even with all the lsp log options enabled.

```sh
$ gopls version
version master, built in $GOPATH mode

➜  tools git:(master) git rev-parse HEAD
20370b0cb4b25d20a35ee592d915c5e0640a0258
```

**Comment by rwols** [comment]
>  Otherwise it's quiet, even with all the lsp log options enabled.

You can run "LSP: Toggle Log Panel" from the command palette to see the barrage of RPC messages.

**Comment by rchl** [comment]
Could you try latest released version to make sure we are on the same page?

**Comment by uhthomas** [comment]
Thanks for the tip @rwols! When I save with invalid code the panel closes (crashes?). Here's some logs you might find interesting
```
--> gopls textDocument/codeAction(61): {'context': {'diagnostics': [], 'only': ['source.fixAll', 'source.organizeImports']}, 'textDocument': {'uri': 'file:///Users/thomas/a/main.go'}, 'range': {'end': {'character': 0, 'line': 282}, 'start': {'character': 0, 'line': 0}}}
:: <~~ gopls 61: {'message': 'invalid response payload', 'code': -32602}
:: ==> gopls textDocument/formatting(62): {'options': {'insertFinalNewline': True, 'insertSpaces': False, 'trimTrailingWhitespace': True, 'trimFinalNewlines': True, 'tabSize': 8}, 'textDocument': {'uri': 'file:///Users/thomas/a/main.go'}}
::  -> gopls textDocument/didSave: {'textDocument': {'uri': 'file:///Users/thomas/a/main.go'}}
```

```
<<< gopls 84: None
```

I'll go ahead and try with 0.4.1   @rchl

**Comment by uhthomas** [comment]
@rchl Same behaviour with 0.4.1

Given this snippet
```go
package main

type    b    bo ol

func main() {



}
```

Like before, create a new file `main.go`, and open in `subl`. Save it, and then fix it by replacing `bo ol` with `bool`. Once saved again, it should not fix formatting.

Let me know if this helps!

**Comment by rwols** [comment]
That "invalid response payload" is our own created error response. It's created here: https://github.com/sublimelsp/LSP/blob/85ea2570993526794bb3fd05a1662364d0974980/plugin/core/rpc.py#L310-L311

This means the payload from gopls either has both `"result"` and `"error"` keys, or neither. Unfortunately it's not printed to the console at the moment, we should probably do that.

The JSON-RPC spec states that `"result"` XOR `"error"` is present in the JSON payload https://www.jsonrpc.org/specification

We should verify whether this is really the case.

**Comment by uhthomas** [comment]
Great! It's still a little suspect that all consequent formatting then fails. As before, it's not like it's _completely_ broken. Imports still work, and it can be manually formatted, but format on save is permanently broken globally.

**Comment by rchl** [comment]
I'd say it's a bug in gopls. It seems like it has some internal state that breaks after you try to format invalid code.

**Comment by rchl** [comment]
> and it can be manually formatted, but format on save is permanently broken globally.

I've missed that part. That sounds like an LSP bug then.

**Comment by rwols** [comment]
Someone should still verify my claims before pointing to gopls :)

**Comment by rchl** [comment]
Well, regardless what gopls sends, it shouldn't break subsequent formatting attempts after the syntax was made valid. :)

**Comment by rchl** [comment]
I found an issue with subsequent sync requests failing after one failed.

**Comment by rchl** [comment]
For the record, gopls sends this response when there is a syntax error in the document.
```json
{
  "jsonrpc": "2.0",
  "error": {
    "data": null,
    "code": 0,
    "message": "computing fix edits: /Users/me/main.go:9:21: expected ';', found Println (and 2 more errors)"
  },
  "id": 3,
  "result": null
}
```
Which is invalid per spec as, as @rwols said, the `result` property is not allowed on error responses.

**Comment by rwols** [comment]
So there are two issues here:

1) gopls sends both "error" and "result" in the payload which violates JSON-RPC.
2) We didn't reset our blocking request state properly. Fixed by #1148.

@uhthomas You should probably open an issue on the gopls repo about this.

**Comment by uhthomas** [comment]
Amazing, thank you both. Is this change available via Package Control now? Is the first point required to get this to work correctly?

Thanks again for the analysis on this, I've found the part of the [JSON-RPC spec](https://www.jsonrpc.org/specification#response_object:~:text=This%20member%20MUST%20NOT%20exist%20if%20there%20was%20an%20error%20invoking%20the%20method.) which indicates this is a violation. I'll go ahead an open a gopls issue, but in reality I think it's a [Go issue](https://golang.org/src/net/rpc/jsonrpc/client.go?s=1712:1751#L64) (note the lack of `,omitempty`).

**Comment by rchl** [comment]
My fix fixes the actual problem so I think we could resolve it.
The issue with invalid response doesn't really change anything here once the fix is in.
Fixing the gopls issue will just make it return valid error response but it will fail the same way in that it won't be able to format document with syntax error.

> Is this change available via Package Control now?

Not yet. Look out for new releases (you can subscribe on github) or checkout the package manually.

**Comment by rwols** [comment]
The fix will be in the next ST4 release.
