### ISSUE TITLE
"View not found for ..." after closing file

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1155]
After we send `textDocument/didClose`, servers like to send back `textDocument/publishDiagnostics` with empty diagnostics which causes a debug log to trigger - `view not found for ...` from `DiagnosticsPresenter.update`. I haven't investigated best way to fix it. The easy way could be to just remove the log but maybe we should rather unregister something on `didClose`.

**Comment by rwols** [comment]
Fixed by #1170
