### ISSUE TITLE
Hovering diagnostic hides code actions annotation

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1156]
Code actions annotation disappears when hovering diagnostic:
![Screen_Recording_2020-06-18_at_21 15 24](https://user-images.githubusercontent.com/153197/85276454-1fc56600-b482-11ea-975a-e8d18f8f1311.gif)

We've determined that it's because `show_popup` is called twice without having an extra (50ms) timeout in between (like we had before).

**Comment by rwols** [comment]
Fixed by #1158
