### ISSUE TITLE
Feature request: allowing passthrough of sublime snippets in "only_show_lsp_completions" mode

### ISSUE THREAD

**Issue by nehbit** [sublimelsp/LSP#1166]
* OS and language server
- Mac OS X Mojave
- Any language server (general LSP package feature request)

Hi there, this is a feature request as mentioned on Discord chat, being moved here. My set-up is Sublime Text 4, however I think this applies to all versions of ST and ST-LSP.

ST-LSP has the feature `only_show_lsp_completions`, which, when enabled, show only LSP completions. This drastically improves the ST autocomplete, which has never been worth much on its own.

However, there is one feature that lots of people use via autocomplete as the main interface — the sublime snippets. Enabling `only_show_lsp_completions` disables snippet completion.

The feature request is to make sublime snippets either by default passed through LSP in the case `only_show_lsp_completions` is enabled, or make this snippet passthrough a flag in the settings. My vote would be towards passing snippets through by default, since it is unlikely for a person to attempt disabling sublime snippets by enabling `only_show_lsp_completions` in LSP. 

Thanks for making this package — this is quite possibly the best ST package in existence in terms of usefulness.

**Comment by predragnikolic** [comment]
maybe deprecate `only_show_lsp_completions`
in favor of a more dynamic setting?

```
// smart_completions - show lsp completions 
// explicit_completions - show completions based on .sublime-completions files
// word_completions - show completions based on the contents of the view 
"auto_complete_includes": ["smart_completions", "explicit_completions", "word_completions"]
```

**Comment by nehbit** [comment]
Yes, that would be better. But any extra code written is a maintenance burden to the maintainers, especially if not many people use it, so I was going for the minimum workable configuration.

It also makes me think that would be much better served as a Sublime Text core feature rather than LSP, your kind of 'list of subscriptions' for autocomplete providers sound quite useful outside of LSP as well.

**Comment by rwols** [comment]
Just exposing `sublime.INHIBIT_WORD_COMPLETIONS` and `sublime.INHIBIT_EXPLICIT_COMPLETIONS` as `"inhibit_word_completions"` and `"inhibit_snippet_completions"` would work. The translation would be straightforward.

**Comment by nehbit** [comment]
Thanks! If you need QA on this, happy to help out — already have LSP `git clone`'d. in place.
