### ISSUE TITLE
Blank area in popups

### ISSUE THREAD

**Issue by guest73** [sublimelsp/LSP#1171]
* OS and language server
Ubuntu Mate, typescript-language-server and css-languageserver
* How you installed LSP (Package Control or from git?)
Package control
* Minimal reproduction steps
In .ts files: Hover over some function or class a blank square is shown where the function signature should be shown.
In .ts files: press Ctrl+Alt+Space - a blank square with some odd line is shown, no signature.
In .scss file: Hover over :last-child selector, a blank square is shown with a link to selector specification beneath.

![blank_area](https://user-images.githubusercontent.com/4907799/85957961-7b1fb880-b99a-11ea-8bf2-48c65cdeeb16.gif)

**Comment by rchl** [comment]
Does anything show up in Sublime console?

I'd guess it has something to do with either color scheme or mdpopups (maybe local overrides?).

It's hard to help without asking 100 of questions so it would be best if you just [try a clean install](http://www.sublimetext.com/docs/3/revert.html) and see if you can reproduce.

**Comment by predragnikolic** [comment]
What is your ST UI theme and color scheme?

**Comment by guest73** [comment]
Well, tried with clean install. Unfortunately it did not help. Among installed plugins I had only 3
![Screenshot at 2020-06-29 17-15-13](https://user-images.githubusercontent.com/4907799/86016975-27f64600-ba2c-11ea-90ab-296bae25461f.png)
Everything was installed from package control. And, of course, I ran "Satisfy dependencies" to install mdpopups.

Here is a piece of LSP config I used

![Screenshot at 2020-06-29 17-18-21](https://user-images.githubusercontent.com/4907799/86017335-9935f900-ba2c-11ea-8327-b3de2b6964d7.png)


Also tried with different pre-installed ST themes and color schemas, did not help either, still having this blank area ;(

**Comment by rchl** [comment]
I can see the issue in ST3 actually.
(We here are on the bleeding edge ST4 builds normally so tend to miss issues with ST3. :)

**Comment by guest73** [comment]
Also, forgot to mention, nothing special in the console. No errors, or warnings.
And, I can see some blocks in some of the popups.

![blocks](https://user-images.githubusercontent.com/4907799/86018761-74db1c00-ba2e-11ea-8afb-3e72750b451f.gif)

So far, thanks for the response guys.

**Comment by rchl** [comment]
Actually I can only reproduce similar thing when not having Typescript syntax installed so I've probably seen something else.

Back to your issue... What theme, color syntax are you using. It's clearly not the default. And the screenshot you posted from supposedly clean build has had light theme. Can you make sure that you are really testing a clean profile?

**Comment by predragnikolic** [comment]
Related issue:
https://github.com/sublimelsp/LSP/issues/383

**Comment by predragnikolic** [comment]
The cause of #383 was a wrong mapping in mdpopups. Check https://github.com/facelessuser/sublime-markdown-popups/issues/57 for more info

**Comment by jwortmann** [comment]
I think the color scheme is the built-in Celeste.

That related issue @predragnikolic metioned would only explain code blocks losing their highlighting colors, but the font color should still be the default `foreground` color from the color scheme in that case (you can see this for example by temporarily disabling the HTML syntax and look at the popups for the CSS language server then).

@guest73 can you add `"mdpopups.debug": 3,` to your `Packages/User/Preferences.sublime-settings` file, and then look at the console when you have a hover popup with a code block? That will show the HTML code for the minihtml popups generated by mdpopups. I guess all the used font colors there will be set to the same color as the schemes background color. I cannot explain why that would happen, but that might give more clues.

<hr>

By the way (unrelated to this issue), but why is there `var(--whitish)` used for the diagnostics boxes in popups.css, e.g. [here](https://github.com/sublimelsp/LSP/blob/69769ae1487e2f923bb581f7578d8b4be48064eb/popups.css#L22)? `--whitish` is none of the pregenerated colors for minihtml, so that color is just ignored and the actual font color falls back to the `foreground` color, I guess.

**Comment by guest73** [comment]
The light theme is actually the default. There are 2 preinstalled themes, 
![Screenshot at 2020-06-29 19-05-39](https://user-images.githubusercontent.com/4907799/86029378-c0e08d80-ba3b-11ea-98e2-f9bd81020f97.png)
adaptive and default (white or gray for me) I haven't installed any. I tried on both.
Also I did not install any color schema except preinstalled. There are 5 preinstalled schemes
![Screenshot at 2020-06-29 19-10-18](https://user-images.githubusercontent.com/4907799/86029874-6b58b080-ba3c-11ea-96d1-452327089ffd.png)
Tried with all of them 
![more](https://user-images.githubusercontent.com/4907799/86029976-8aefd900-ba3c-11ea-8828-a0a5ebb983ac.gif)
The same result.

**Comment by guest73** [comment]
`
mdpopups: =====CSS=====
mdpopups: 
html {
  --mdpopups-font-mono: "sf mono", Consolas, "Liberation Mono", Menlo, Courier, monospace;
  --mdpopups-admon-fg: var(--foreground);
  --mdpopups-admon-info-fg: var(--foreground);
  --mdpopups-admon-error-fg: var(--foreground);
  --mdpopups-admon-warning-fg: var(--foreground);
  --mdpopups-admon-success-fg: var(--foreground);
  --mdpopups-admon-bg: var(--background);
  --mdpopups-admon-info-bg: var(--background);
  --mdpopups-admon-error-bg: var(--background);
  --mdpopups-admon-warning-bg: var(--background);
  --mdpopups-admon-success-bg: var(--background);
  --mdpopups-admon-accent: color(var(--background) blend(var(--foreground) 50%));
  --mdpopups-admon-title-fg:  var(--foreground);
  --mdpopups-admon-info-title-fg:  var(--foreground);
  --mdpopups-admon-error-title-fg:  var(--foreground);
  --mdpopups-admon-warning-title-fg:  var(--foreground);
  --mdpopups-admon-success-title-fg:  var(--foreground);
  --mdpopups-admon-info-accent: color(var(--background) blend(var(--bluish) 50%));
  --mdpopups-admon-error-accent: color(var(--background) blend(var(--redish) 50%));
  --mdpopups-admon-warning-accent: color(var(--background) blend(var(--orangish) 50%));
  --mdpopups-admon-success-accent: color(var(--background) blend(var(--greenish) 50%));
  --mdpopups-kbd-fg: var(--background);
  --mdpopups-kbd-bg: var(--foreground);
}
html.light {
  --mdpopups-hr: color(var(--foreground) blend(white 80%));
  --mdpopups-kbd-border: color(var(--foreground) blend(white 80%));
  --mdpopups-hl-border: color(var(--background) blend(black 90%));
  --mdpopups-hl-bg: color(var(--background) blend(black 98%));
}
html.dark {
  --mdpopups-hr: color(var(--foreground) blend(black 80%));
  --mdpopups-kbd-border: color(var(--foreground) blend(black 80%));
  --mdpopups-hl-border: color(var(--background) blend(white 90%));
  --mdpopups-hl-bg: color(var(--background) blend(white 98%));
}
html, body { padding: 0; margin: 0; }
div.mdpopups {
  display: block;
  margin: 0;
  padding: 0;
  font-size: 1rem;
  line-height: 1.1rem;
}
.mdpopups .highlight,
.mdpopups code,
.mdpopups var,
.mdpopups tt {
  font-family: var(--mdpopups-font-mono);
}
.mdpopups div { display: block; }

.mdpopups h1 { font-size: 1.5rem; }
.mdpopups h2 { font-size: 1.4rem; }
.mdpopups h3 { font-size: 1.3rem; }
.mdpopups h4 { font-size: 1.2rem; }
.mdpopups h5 { font-size: 1.1rem; }
.mdpopups h6 { font-size: 1rem; }
.mdpopups h1, .mdpopups h2, .mdpopups h3, .mdpopups h4, .mdpopups h5, .mdpopups h6 {
  margin-top: 0.2rem;
  margin-bottom: 0.2rem;
}

.mdpopups blockquote { display: block; font-style: italic; }

.mdpopups hr {
  display: block;
  border-color: var(--mdpopups-hr);
  border-style: solid;
  border-width: 0 0 1px 0;
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.mdpopups dl { display: block; }
.mdpopups dt {
  display: block;
  font-style: italic;
  font-weight: bold;
  margin-bottom: 0.5rem;
}
.mdpopups dd {
  display: block;
  margin-left: 1.5rem;
  margin-bottom: 0.5rem;
}

.mdpopups pre { display: block; }

.mdpopups blockquote, .mdpopups ol, .mdpopups ul, .mdpopups dl, .mdpopups p {
  padding: 0;
  margin-top: 0;
  margin-bottom: 0.5rem;
  margin-left: 0;
  margin-right: 0;
}
.mdpopups ul, .mdpopups ol { padding-left: 2rem; }

.mdpopups kbd {
  display: inline;
  font-size: 0.9rem;
  padding: 0.05rem 0.25rem;
  border-radius: 0.25rem;
  background-color: var(--mdpopups-kbd-bg);
  color: var(--mdpopups-kbd-fg);
  border: 1px solid var(--mdpopups-kbd-border);
}

.mdpopups .admonition {
  display: block;
  padding: 0 0.5rem 0.5rem 0.5rem;
  border-radius: 0.25rem;
  margin-bottom: 0.5rem;
  background-color: var(--mdpopups-admon-bg);
  color: var(--mdpopups-admon-fg);
  border: 1px solid var(--mdpopups-admon-accent);
}
.mdpopups .admonition-title {
  font-weight: 600;
  font-size: 1.1rem;
  margin: 0 -0.5rem 0.5rem -0.5rem;
  padding: 0.1rem 0.5rem 0.1rem 0.5rem;
  border-top-left-radius: 0.25rem;
  border-top-right-radius: 0.25rem;
  color:  var(--mdpopups-admon-title-fg);
  background-color: var(--mdpopups-admon-accent);
}

.mdpopups .admonition.panel-success .admonition-title {
  color: var(--mdpopups-admon-success-title-fg);
  background-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-success {
  color:  var(--mdpopups-admon-success-fg);
  background-color: var(--mdpopups-admon-success-bg);
  border-color: var(--mdpopups-admon-success-accent);
}
.mdpopups .admonition.panel-warning .admonition-title {
  color: var(--mdpopups-admon-warning-title-fg);
  background-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-warning {
  color:  var(--mdpopups-admon-warning-fg);
  background-color: var(--mdpopups-admon-warning-bg);
  border-color: var(--mdpopups-admon-warning-accent);
}
.mdpopups .admonition.panel-error .admonition-title {
  color: var(--mdpopups-admon-error-title-fg);
  background-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-error {
  color:  var(--mdpopups-admon-error-fg);
  background-color: var(--mdpopups-admon-error-bg);
  border-color: var(--mdpopups-admon-error-accent);
}
.mdpopups .admonition.panel-info .admonition-title {
  color: var(--mdpopups-admon-info-title-fg);
  background-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .admonition.panel-info {
  color:  var(--mdpopups-admon-info-fg);
  background-color: var(--mdpopups-admon-info-bg);
  border-color: var(--mdpopups-admon-info-accent);
}
.mdpopups .highlight {
  border: 1px solid var(--mdpopups-hl-border);
  border-radius: 0.25rem;
  font-size: 0.9rem;
  background-color: var(--mdpopups-hl-bg);
}
.mdpopups div.highlight,
.mdpopups pre.highlight {
  padding: 0.5rem;
  margin-bottom: 0.5rem;
  font-size: 1rem;
}
.mdpopups code.highlight{
  padding: 0.05rem 0.25rem;
}

.lsp_popup {
    margin: 0.5rem 0.5rem 0 0.5rem;
}
.lsp_popup .highlight {
    border-width: 0;
    border-radius: 0;
}
.lsp_popup p {
    margin-bottom: 0.5rem;
    padding: 0 0.5rem;
    font-family: system;
}
.lsp_popup li {
    font-family: system;
}
.lsp_popup .diagnostics {
    margin-bottom: 0.5rem;
}
.lsp_popup .errors {
    border-width: 0;
    background-color: color(var(--redish) alpha(0.25));
    color: var(--whitish);
    padding: 0.5rem;
}
.lsp_popup .warnings {
    border-width: 0;
    background-color: color(var(--yellowish) alpha(0.25));
    color: var(--whitish);
    padding: 0.5rem;
}
.lsp_popup .info {
    border-width: 0;
    background-color: color(var(--bluish) alpha(0.25));
    color: var(--whitish);
    padding: 0.5rem;
}
.lsp_popup .hints {
    border-width: 0;
    background-color: color(var(--bluish) alpha(0.25));
    color: var(--whitish);
    padding: 0.5rem;
}
.lsp_popup .actions {
    border-width: 0;
    background-color: color(var(--foreground) alpha(0.1));
    color: var(--whitish);
    padding: 0.5rem;
}
.lsp_popup .actions a {
    text-decoration: none;
    color: var(--foreground);
}
pre.related_info {
    border-top: 1px solid color(var(--background) alpha(0.25));
    margin-top: 0.7rem;
    padding-top: 0.7rem;
}
mdpopups: =====HTML OUTPUT=====
mdpopups: 
<div class="highlight"><pre><span style="color: #d8dee9;">(</span><span style="color: #d8dee9;">alias</span><span style="color: #d8dee9;">)</span><span style="color: #d8dee9;"> </span><span style="color: #c695c6; font-style: italic;">class</span><span style="color: #d8dee9;"> </span><span style="color: #f9ae58;">FormBuilder</span><br><span style="color: #d8dee9;"></span><span style="color: #f9ae58;">import</span><span style="color: #d8dee9;"> </span><span style="color: #f9ae58;">FormBuilder</span><br></pre></div><p><em>@description</em> — Creates an <code class="highlight"><span style="color: #d8dee9;">AbstractControl</span></code> from a user-specified configuration.</p><p>The <code class="highlight"><span style="color: #d8dee9;">FormBuilder</span></code> provides syntactic sugar that shortens creating instances of a <code class="highlight"><span style="color: #d8dee9;">FormControl</span></code>,<br /><code class="highlight"><span style="color: #d8dee9;">FormGroup</span></code>, or <code class="highlight"><span style="color: #d8dee9;">FormArray</span></code>. It reduces the amount of boilerplate needed to build complex<br />forms.  </p><p><em>@see</em> — <a href="/guide/reactive-forms">Reactive Forms Guide</a>  </p><p><em>@publicApi</em></p><p class='actions'><a href='definition'>Definition</a> | <a href='typeDefinition'>Type&nbsp;Definition</a> | <a href='implementation'>Implementation</a> | <a href='references'>References</a> | <a href='rename'>Rename</a></p>
`

**Comment by guest73** [comment]
![Screenshot at 2020-06-29 19-26-02](https://user-images.githubusercontent.com/4907799/86031377-698fec80-ba3e-11ea-855e-896d28d0f611.png)

mdpopups' output as a picture

**Comment by jwortmann** [comment]
The color values from the console screenshot are the correct highlighting font colors from the color scheme, e.g. `#d8dee9` or `#f9ae58`. I have no idea why they are not rendered in the popup itself.
Maybe try the following, open the console and type
```python
import sublime
sublime.active_window().active_view().show_popup('<span style="color: #f9ae58;">Hello world</span>')
```
If the shown popup has a orange font color, I would say the issue must be somewhere at mdpopups, and otherwise it looks like it is at Sublime itself for your OS.

**Comment by guest73** [comment]
Seems, like I can see the text.

![Screenshot at 2020-06-29 21-01-47](https://user-images.githubusercontent.com/4907799/86039940-dc539480-ba4b-11ea-8456-03170907a9dc.png)

Couldn't it be the problem with the background, then with the text itself?

**Comment by guest73** [comment]
That's what I mean
![some text is visible](https://user-images.githubusercontent.com/4907799/86040641-12dddf00-ba4d-11ea-9962-3b8fefba402a.gif)

**Comment by rchl** [comment]
Maybe one more try. How does this look (it's the content that you've logged from mdpopups):

`
view.show_popup('<div class="highlight"><pre><span style="color: #d8dee9;">(</span><span style="color: #d8dee9;">alias</span><span style="color: #d8dee9;">)</span><span style="color: #d8dee9;"> </span><span style="color: #c695c6; font-style: italic;">class</span><span style="color: #d8dee9;"> </span><span style="color: #f9ae58;">FormBuilder</span><br><span style="color: #d8dee9;"></span><span style="color: #f9ae58;">import</span><span style="color: #d8dee9;"> </span><span style="color: #f9ae58;">FormBuilder</span><br></pre></div><p><em>@description</em> — Creates an <code class="highlight"><span style="color: #d8dee9;">AbstractControl</span></code> from a user-specified configuration.</p><p>The <code class="highlight"><span style="color: #d8dee9;">FormBuilder</span></code> provides syntactic sugar that shortens creating instances of a <code class="highlight"><span style="color: #d8dee9;">FormControl</span></code>,<br /><code class="highlight"><span style="color: #d8dee9;">FormGroup</span></code>, or <code class="highlight"><span style="color: #d8dee9;">FormArray</span></code>. It reduces the amount of boilerplate needed to build complex<br />forms.  </p><p><em>@see</em> — <a href="/guide/reactive-forms">Reactive Forms Guide</a>  </p><p><em>@publicApi</em></p><p class="actions"><a href="definition">Definition</a> | <a href="typeDefinition">Type&nbsp;Definition</a> | <a href="implementation">Implementation</a> | <a href="references">References</a> | <a href="rename">Rename</a></p>')
`

Should look something like that:
![Screenshot 2020-06-29 at 20 15 20](https://user-images.githubusercontent.com/153197/86041006-49176080-ba45-11ea-9b78-8147df1bfb74.png)

**Comment by guest73** [comment]
@rchl , When I post it in the console it looks exactly the way you posted.

**Comment by rwols** [comment]
If you put the caret at FormBuilder, can you open the console and run the following:
```
view.run_command("lsp_hover", {"point": view.sel()[0].b})
```
Does the popup render correctly in this case?

<hr>
@jwortmann I guess we should remove var(--whitish) from the CSS. Pull requests are welcome!

**Comment by guest73** [comment]
Hi, @rwols.
When I did as you asked it did not look normal.

**Comment by jwortmann** [comment]
I have another guess what could be the reason for this issue. The parts affected in your popups are the `<div class="highlight">` and `<code>` tags. In mdpopups the font face for code blocks and preformatted text is set to
```css
.mdpopups .highlight,
.mdpopups code,
.mdpopups var,
.mdpopups tt {
  font-family: var(--mdpopups-font-mono);
}
```
with `--mdpopups-font-mono: "sf mono", Consolas, "Liberation Mono", Menlo, Courier, monospace;`.

Maybe for whatever reason none of these fonts can be found on your system. Actually that shouldn't happen because `monospace` should at least result in some available font, but it might be worth to try whether that was the cause. You can overwrite that rule by creating a file `mdpopups.css` in your User folder with e.g.
```css
.mdpopups .highlight,
.mdpopups code,
.mdpopups var,
.mdpopups tt {
  font-family: "put a font here that you know exists on your system";
}
```

**Comment by rchl** [comment]
That sounds like a good guess. Maybe @wbond can chime in. I guess it's possible that ST doesn't even support generic font values like `monospace`.

**Comment by guest73** [comment]
@jwortmann, thanks! That did the trick!
Actually I had some fonts installed but apparently they are named differently or something.

![Screenshot at 2020-06-30 16-32-31](https://user-images.githubusercontent.com/4907799/86132737-ff378480-baef-11ea-8085-64ed7e634051.png)

![Screenshot at 2020-06-30 16-32-59](https://user-images.githubusercontent.com/4907799/86132760-08c0ec80-baf0-11ea-950d-b628fd058a63.png)

![Screenshot at 2020-06-30 16-33-13](https://user-images.githubusercontent.com/4907799/86132783-0fe7fa80-baf0-11ea-9570-7c07ddf038fd.png)

I specified "Ubuntu Mono Regular" in the `mdpopups.css` file as you suggested but it actually works if I put anything as a font.

![Screenshot at 2020-06-30 16-37-07](https://user-images.githubusercontent.com/4907799/86132901-3d34a880-baf0-11ea-9f9b-f3e3070ad4c8.png)

So, any string in the font-family property fixes my problem.

I guess, I am happy now :). Thank you guys very much for your help!

**Comment by wbond** [comment]
I believe the only "special" font name we support is `system`, which defaults the sans serif, non-monospace font the OS Sublime Text is running on users for the interface.

My hunch is that it is possible some platforms will support `monospace` themselves - I would hazard a guess Linux will. My Mac appears to:

```python
view.show_popup('<div style="font-family: monospace">Testing monospace</div>', 0, view.sel()[0].a)
```

Typically if we don't find a font we fallback to something. This appears to fall back to something like Times on my Mac.

```python
view.show_popup('<div style="font-family: foobar">Testing monospace</div>', 0, view.sel()[0].a)
```

I don't have my Windows machine in front of me for testing at the moment.

**Comment by wbond** [comment]
Based on the screenshot from @guest73, I would hazard a guess that it was finding "Liberation Mono", but the font was broken/corrupt somehow?

**Comment by guest73** [comment]
@wbond, you might be right. In my package manager I have 2 versions of Liberation fonts. And only the first one was installed, the one with version 1. After I installed a second version everything started to work even without mdpopups.css.

![Screenshot at 2020-06-30 16-49-04](https://user-images.githubusercontent.com/4907799/86134173-f9db3980-baf1-11ea-9ab8-3b5311d3e5a1.png)

**Comment by guest73** [comment]
So, I guess the problem is solved and issue could be closed.
Thanks everybody for help.
