### ISSUE TITLE
The user needs a way to know the name of the diagnostic being shown

### ISSUE THREAD

**Issue by frou** [sublimelsp/LSP#1173]
Take a diagnostic like this for example:

```text
 ◌ src/main.c:
      159:30  	clang-tidy  	warning   	Narrowing conversion from 'double' to 'int'
```

Many linters/static-analyzers provide a way to suppress a specific issue on a specific line by having the user write a special comment, e.g. [in clang-tidy's case](https://clang.llvm.org/extra/clang-tidy/#suppressing-undesired-diagnostics):

`// NOLINT(???)`

But what should the LSP user write where `???` is? We're out of luck, because the diagnostic as shown doesn't tell us the name of the specific issue.

That name **is** already present inside the `textDocument/publishDiagnostics` message from the language server though, it's [`Diagnostic.code`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic). In this example, that has the value `"bugprone-narrowing-conversions"`.

---

So if the diagnostic was instead shown including something like this:

`Narrowing conversion from 'double' to 'int' [bugprone-narrowing-conversions]`

...then the user would have the information they need to be able to write the comment:

`// NOLINT(bugprone-narrowing-conversions)`

---

I think some language servers duplicate the value of `Diagnostic.code` inside the `Diagnostic.message` string. That could be checked for to avoid showing the same information twice.

(These diagnostic names used by clangd+clang-tidy are quite wordy. The equivalent in the pyls+flake8 world are diagnostic names like `E731` and comments like `# noqa: E731`)

**Comment by rchl** [comment]
The code in the response is a new thing in the proposed version of the spec so hopefully, we should be able to implement it soon.

See also https://github.com/microsoft/vscode-eslint/issues/992

**Comment by rchl** [comment]
Or are we not showing the `code` from the current version of the spec either? I guess it might be so...

**Comment by frou** [comment]
> Or are we not showing the `code` from the current version of the spec either? I guess it might be so...

That's right. Just a string is what servers are sending. I just checked and that has been in the spec for 3+ years, possibly forever.

**Comment by frou** [comment]
This omission has probably been masked somewhat by the fact that some servers, in some configurations, duplicate the "code" inside the prose of the message itself.

With that in mind, the logic in this plugin should probably be something along the lines of:


```python
if str(diagnostic.code) not in diagnostic.message:
    diagnostic.message += " [{}]".format(str(diagnostic.code))
```

**Comment by rwols** [comment]
This will be fixed in the ST4 version

**Comment by frou** [comment]
Thanks @rwols . I noticed that recently pyls has [started](https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/flake8_lint.py#L148) to do the duplication I mentioned in my previous comment. Did you decide one way or the other about trying to detect that?

**Comment by rwols** [comment]
I consider putting the code in the message prose a "bug" of the language server. Servers shouldn't do that. It should be fixed in the server. We shouldn't make workarounds in this code base.

pyls has more problems. Look into [pyright](https://github.com/sublimelsp/LSP-pyright) for a smoother experience.
