### ISSUE TITLE
Document formatting inserts <0x0d> (\r)

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#1179]
## Problem

LSP's document formatting inserts `<0x0d>` (i.e., `\r`), which should be removed from the server response before inserting.

![GIF 2020-7-8 下午 06-27-22](https://user-images.githubusercontent.com/6594915/86908575-51f4ea00-c149-11ea-9279-2642b8edd460.gif)

## Environments

- LSP client: `st4000-exploration` (97548138dbfbf30dec792ebc1f403c378da4f3d8)
- LSP server: https://github.com/jfcherng-sublime/LSP-latex (uses https://github.com/latex-lsp/texlab)
- Sublime Text: 4074

## Server Log

```
:: --> lsp-latex textDocument/formatting(3): {'textDocument': {'uri': 'file:///C:/Users/Clover/AppData/Roaming/Sublime%20Text/Packages/LSP-latex/test.tex'}, 'options': {'trimTrailingWhitespace': True, 'insertFinalNewline': True, 'insertSpaces': True, 'tabSize': 4, 'trimFinalNewlines': True}}
:: <<< lsp-latex 3: [{'newText': "\\documentclass[12pt]{article}\r\n\\usepackage{lingmacros}\r\n\\usepackage{tree-dvips}\r\n\\begin{document}\r\n\r\n\\section*{Notes for My Paper}\r\n\r\nDon't forget to include examples of topicalization.\r\nThey look like this:\r\n\r\n{\\small\r\n\\enumsentence{Topicalization from sentential subject:\\\\\r\n\\shortex{7}{a John$_i$ [a & kltukl & [el &\r\n\t\t\t\t{\\bf l-}oltoir & er & ngii$_i$ & a Mary]]}\r\n{ & {\\bf R-}clear & {\\sc comp} &\r\n{\\bf IR}.{\\sc 3s}-love   & P & him & }\r\n{John, (it's) clear that Mary loves (him).}}\r\n}\r\n\r\n\\subsection*{How to handle topicalization}\r\n\r\nI'll just assume a tree structure like (\\ex{1}).\r\n\r\n{\\small\r\n\\enumsentence{Structure of A$'$ Projections:\\\\ [2ex]\r\n\\begin{tabular}[t]{cccc}\r\n\t                & \\node{i}{CP}                                      \\\\ [2ex]\r\n\t\\node{ii}{Spec} &              & \\node{iii}{C$'$}                   \\\\ [2ex]\r\n\t                & \\node{iv}{C} &                  & \\node{v}{SAgrP}\r\n\\end{tabular}\r\n\\nodeconnect{i}{ii}\r\n\\nodeconnect{i}{iii}\r\n\\nodeconnect{iii}{iv}\r\n\\nodeconnect{iii}{v}\r\n}\r\n}\r\n\r\n\\subsection*{Mood}\r\n\r\nMood changes when there is a topic, as well as when\r\nthere is WH-movement.  \\emph{Irrealis} is the mood when\r\nthere is a non-subject topic or WH-phrase in Comp.\r\n\\emph{Realis} is the mood when there is a subject topic\r\nor WH-phrase.\r\n\r\n\\end{document}\r\n", 'range': {'start': {'line': 0, 'character': 0}, 'end': {'line': 46, 'character': 0}}}]
```

**Comment by rwols** [comment]
Interesting. Can you check if https://github.com/sublimelsp/LSP/commit/a5d878d007551a486ae826b35eb95cfa935d6f57 introduced this or did this happen before?

**Comment by jfcherng** [comment]
> Interesting. Can you check if [a5d878d](https://github.com/sublimelsp/LSP/commit/a5d878d007551a486ae826b35eb95cfa935d6f57) introduced this or did this happen before?

I tried 479661519e853daa8cfe4eb9f1c60a04a68948b6 (which is the parent of a5d878d007551a486ae826b35eb95cfa935d6f57) and this still happens.

**Comment by rwols** [comment]
Perhaps something can be said for actually respecting the `\r`. Would there be any scenario where we do not want to strip the `\r`? Hmm, thinking about this some more I don't think there's any such scenario, because ST will translate the buffer line-endings to `\r\n` when saving the buffer I think.

**Comment by jfcherng** [comment]
I think people always use `\n` in plugins. ST will deal with it when saving. Inserting `\r` with plugin API just causes visual annoyance without actual benefits.

**Comment by rwols** [comment]
Are there any pitfalls in simply doing `replacement = replacement.replace("\r", "")` ?

**Comment by jfcherng** [comment]
I can't find one. Maybe `replacement = replacement.replace("\r\n", "\n")` is safer.

**Comment by jfcherng** [comment]
Thanks. Confirm working for https://github.com/sublimelsp/LSP-TexLab :)
