### ISSUE TITLE
Create an overraide in Python/Completion Rules.tmPreferences to allow triggering AC after def

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1182]
I opened sublime in safe mode
and created a python file with the following content:

```
def hello():
    pass

|
```

if I type:
```
def hello():
    pass

def |
```
if I trigger the AC:
I will get hello in the AC.

but if I type:
```
def hello():
    pass

def he|
```
and trigger the AC.
The AC wont be shown.

@FichteFoll gave an [anwser](https://discord.com/channels/280102180189634562/280157067396775936/725841310472339556).
> AC is blocked by Python/Completion Rules.tmPreferences
so to disable that you'd want to create an override

Issue was originally reported on [discord](https://discord.com/channels/280102180189634562/645268178397560865/725780986377535619).

This change will allow us to get completions items like `__init__` and other magic method or inherited methods after the keyword `def`.

**Comment by rchl** [comment]
Maybe Python package should reconsider what it's doing? Not sure what's the reasoning for it...

It's probably not a great idea for this package to create any overrides since those would apply globally, even when not using python server.

**Comment by predragnikolic** [comment]
Yes adding the override to the LSP plugin doesn't seem like the right place. But LSP-pyls looks like the right place... Or should we open an issue to at the Default packages repo to reconsider the python AC scope restriction?

**Comment by rwols** [comment]
It has been this way since forever. Since the TextMate days https://github.com/sublimehq/Packages/blame/42e4c1dcf8baca808ea25d6e108bcb0dbb74be32/Python/Completion%20Rules.tmPreferences

It would be intrusive and unexpected to have this package make an override for that file. Best to discuss it in https://github.com/sublimehq/Packages/issues

Or tell users in the docs/readmes that they can change that file by themselves.

**Comment by rchl** [comment]
Created https://github.com/sublimehq/Packages/issues/2404

**Comment by FichteFoll** [comment]
I also disagree with overriding this file from a package. Let's discuss it in the packages issue.

**Comment by rwols** [comment]
Let's continue the discussion in the link above at sublimehq/Packages.
