### ISSUE TITLE
packagecontrol LSP release docs inconsistency

### ISSUE THREAD

**Issue by craigmac** [sublimelsp/LSP#1189]
Running 3211 stable, installed LSP package from package control, and in the Preferences there are several references to a command "LSP: Toggle Panel: Language Servers" which seems to have been renamed to "LSP: Toggle Log Panel" (or is there a difference)? Related, probably: #837 

Updated docs on package control release should clear up the confusion.

**Comment by rwols** [comment]
Fixed in 1f8da08
