### ISSUE TITLE
Wired completion list when using gopls

### ISSUE THREAD

**Issue by wsw0108** [sublimelsp/LSP#1220]
Your issue may have been solved already - please search before creating new!

Troubleshooting guide: https://lsp.readthedocs.io/en/latest/troubleshooting
Chat: https://discord.gg/RMkk5MR
Miscellaneous notes (anyone can edit!): https://github.com/sublimelsp/LSP/wiki/Notes

Is it a language server problem? The LSP package can do little to prevent slowness or missing content - please check their support materials!

Please include in your report:

* OS and language server
- Windows 10
- gopls, 0.4.3
* How you installed LSP (Package Control or from git?)
Package Control
* Minimal reproduction steps
- input `filepath.E` in main.go
* Log
![image](https://user-images.githubusercontent.com/4977975/88540878-63ddf480-d046-11ea-8e69-b632e372786d.png)

Requesting a feature?

Please read https://github.com/sublimelsp/LSP/blob/master/CONTRIBUTING.md. Specifically, LSP avoids building functionality that does not exist in Sublime Text, or that serves only one language.

**Comment by rwols** [comment]
You must install gopls from its master branch because 0.4.3 is bugged. Instructions to install gopls from the master branch are here: https://github.com/golang/tools/pull/225

**Comment by wsw0108** [comment]
Thanks for so quick response.

I'm closing this.
