### ISSUE TITLE
Server is being shutdown on server sending empty stderr line

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1237]
When server triggers stderr output that is an empty string (or becomes an empty string after `rstrip` then LSP closes the transports and thus the server.

Issue found when analyzing https://github.com/sublimelsp/LSP-angular/issues/1

**Comment by rwols** [comment]
Fixed by #1241 :)

**Comment by rchl** [comment]
Another follow-up merged (see linked PRs), but I've also noticed that it's still possible to reproduce freeze by force-killing the server. So when transport shutdown is not initiated by us.
