### ISSUE TITLE
Discuss removal of the Settings class 

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1244]
There is this `Settings` class in LSP/plugin/core/types.py
```
class Settings:
    def __init__(self) -> None:
        self.show_view_status = True
        self.auto_show_diagnostics_panel = 'always'
        self.auto_show_diagnostics_panel_level = 2
        self.diagnostics_panel_include_severity_level = 4
        self.show_diagnostics_count_in_view_status = False
        self.show_diagnostics_in_view_status = True
        self.show_diagnostics_severity_level = 2
        self.only_show_lsp_completions = False
        self.diagnostics_highlight_style = "underline"
        self.document_highlight_style = "stippled"
        self.document_highlight_scopes = {
            "unknown": "text",
            "text": "text",
            "read": "markup.inserted",
            "write": "markup.changed"
        }
        self.diagnostics_gutter_marker = "dot"
        self.diagnostics_delay_ms = 0
        self.diagnostics_additional_delay_auto_complete_ms = 0
        self.show_symbol_action_links = False
        self.show_references_in_quick_panel = False
        self.disabled_capabilities = []  # type: List[str]
        self.log_debug = False
        self.log_server = []  # type: List[str]
        self.log_stderr = False
        self.log_max_size = 8 * 1024
        self.lsp_format_on_save = False
        self.show_code_actions = "annotation"
        self.lsp_code_actions_on_save = {}  # type: Dict[str, bool]
        self.code_action_on_save_timeout_ms = 2000
```

instead just use sublime default settings object.

`settings = sublime.load_settings('LSP.sublime-settings')`

That way we don't have to refresh sublime to see the changes made to settings. :)

**Comment by predragnikolic** [comment]
`load_settings(base_name) -> Settings` - Loads the named settings. The name should include a  file name and extension, but not a path. The packages will be searched  for files matching the base_name, and the results will be collated into the settings object. **Subsequent calls to load_settings() with the base_name will return the same object**, and not load the settings from disk again.

**Comment by rchl** [comment]
I kinda feel uneasy about calling `load_settings` every time a little setting is needed. It might not trigger any expensive operation but it's still a function call that potentially crosses the cross-process boundary.

Always calling `load_settings` doesn't even magically fix all the cases where old settings are used since sometimes we need to "re-initialize" things using new settings and that requires custom handling on settings change.

Since there is a change listener API for settings, we can have the best of both
 - have a global that allows avoiding calling `load_settings` every time
 - always get the latest values

**Comment by predragnikolic** [comment]
I imagined something like this:
```
import sublime
settings = None

def plugin_loaded():
    settings = sublime.load_settings('LSP.sublime-settings')
    ...

def some_method()
    settings.get('code_actions')
    ...

def some_other_method()
    settings.get('disabled_capabilities')
    ...
```

Currently we have our own Settings class, and we need to add new settings to it each time we want to add a new setting.
which feels like a redundant step for me.

```
_settings_obj = None  # type: Optional[sublime.Settings]
settings = Settings()  
client_configs = ClientConfigs()


def load_settings() -> None:
    global _settings_obj
    loaded_settings_obj = sublime.load_settings("LSP.sublime-settings")
    _settings_obj = loaded_settings_obj
    update_settings(settings, loaded_settings_obj)
    client_configs.update(loaded_settings_obj, also_update_configs=False)
    loaded_settings_obj.add_on_change("_on_new_settings", lambda: update_settings(settings, loaded_settings_obj))
    loaded_settings_obj.add_on_change(
        "_on_new_client_settings",
        lambda: client_configs.update(loaded_settings_obj, also_update_configs=True))


def unload_settings() -> None:
    if _settings_obj:
        _settings_obj.clear_on_change("_on_new_settings")
        _settings_obj.clear_on_change("_on_new_client_settings")

```
and the update_settings function looks like this:
```

def update_settings(settings: Settings, settings_obj: sublime.Settings) -> None:
    settings.show_view_status = read_bool_setting(settings_obj, "show_view_status", True)
    settings.auto_show_diagnostics_panel = read_auto_show_diagnostics_panel_setting(settings_obj,
                                                                                    "auto_show_diagnostics_panel",
                                                                                    'always')
    settings.auto_show_diagnostics_panel_level = read_int_setting(settings_obj, "auto_show_diagnostics_panel_level", 2)
    settings.diagnostics_panel_include_severity_level = read_int_setting(settings_obj,
                                                                         "diagnostics_panel_include_severity_level",
                                                                         4)
    settings.show_diagnostics_count_in_view_status = read_bool_setting(settings_obj,
                                                                       "show_diagnostics_count_in_view_status", False)
    settings.show_diagnostics_in_view_status = read_bool_setting(settings_obj, "show_diagnostics_in_view_status", True)
    settings.show_diagnostics_severity_level = read_int_setting(settings_obj, "show_diagnostics_severity_level", 2)
    settings.diagnostics_delay_ms = read_int_setting(settings_obj, "diagnostics_delay_ms", 0)
    settings.diagnostics_additional_delay_auto_complete_ms = read_int_setting(
        settings_obj, "diagnostics_additional_delay_auto_complete_ms", 0)
    settings.diagnostics_highlight_style = read_str_setting(settings_obj, "diagnostics_highlight_style", "underline")
    settings.document_highlight_style = read_str_setting(settings_obj, "document_highlight_style", "stippled")
    settings.document_highlight_scopes = read_dict_setting(settings_obj, "document_highlight_scopes",
                                                           settings.document_highlight_scopes)
    settings.diagnostics_gutter_marker = read_str_setting(settings_obj, "diagnostics_gutter_marker", "dot")
    settings.show_symbol_action_links = read_bool_setting(settings_obj, "show_symbol_action_links", False)
    settings.only_show_lsp_completions = read_bool_setting(settings_obj, "only_show_lsp_completions", False)
    settings.show_references_in_quick_panel = read_bool_setting(settings_obj, "show_references_in_quick_panel", False)
    settings.disabled_capabilities = read_array_setting(settings_obj, "disabled_capabilities", [])
    settings.log_debug = read_bool_setting(settings_obj, "log_debug", False)
    log_server_default = ["panel"] if read_bool_setting(settings_obj, "log_server", False) else []
    settings.log_server = read_array_setting(settings_obj, "log_server", log_server_default)
    settings.log_stderr = read_bool_setting(settings_obj, "log_stderr", False)
    settings.log_max_size = read_int_setting(settings_obj, "log_max_size", 8 * 1024)
    settings.lsp_format_on_save = read_bool_setting(settings_obj, "lsp_format_on_save", False)
    settings.show_code_actions = read_str_setting(settings_obj, "show_code_actions", "annotation")
    settings.lsp_code_actions_on_save = read_dict_setting(settings_obj, "lsp_code_actions_on_save", {})
    settings.code_action_on_save_timeout_ms = read_int_setting(settings_obj, "code_action_on_save_timeout_ms", 2000)
```

I think that we can live without our Settings class and delete a lot of code :)

**Comment by predragnikolic** [comment]
@rchl I am not sure what you meant by:

> fix all the cases where old settings are used since sometimes we need to "re-initialize" things using new settings and that requires custom handling on settings change.

Can you give an example for this "requires custom handling on settings change"? Maybe I missed something.

**Comment by rchl** [comment]
I don't know off-hand if there is any specific place that needs such handling. I was just saying hypothetically.

A hypothetical example: we have settings that control how diagnostics look. On changing such settings we would ideally re-create all diagnostics so that the changes are applied immediately and not the next time diagnostics are created.

**Comment by rchl** [comment]
> Currently we have our own Settings class, and we need to add new settings to it each time we want to add a new setting.

Yes but that's orthogonal to the issue of whether we call `load_settings` on every setting query or not, IMO.

That code is more as a fail-safe in case there is something wrong with default settings probably. But that's quite a corner case and I wouldn't personally argue for keeping it.

**Comment by rwols** [comment]
From what I remember, the idea was to have this indirection with a Settings class so that one could handle backwards-compatible changes to settings, and indeed also guard against users putting a `str` where an `int` should be. Removing the Settings class would entail:

1) Accounting for backwards-compatibility ad hoc,
2) Accounting for runtime type-safety ad hoc.

**Comment by predragnikolic** [comment]
After some trial and error of refactoring of trying to delete the Setting class, 
I concluded that the Settings class will probably stay. 

I thought that if I delete the class the code after that would be smaller, 
but the price for that is that I always need to call sublime.load_settings('LSP.sublime-settings') each time I want to get a setting (and that seems tedious)
```python
def plugin_loaded():
    settings = sublime.load_settings('LSP.sublime-settings')
    if settings.get('disabled_capabilities'):
    ...
```
I thought I could go with this solution(but this doesn't work as I expected):
```python
import sublime
settings = None

def plugin_loaded():
    global settings
    settings = sublime.load_settings('LSP.sublime-settings')

# OtherFile.py
from .settings import settings

def underline():
    if settings.get('disabled_capabilities'):
    ...
```
I got errors when starting ST, that I cannot read `.get` from `None`. 

-----

As far as the runtime validations of the settings keys like `read_str_setting`.
I do think that can prevent errors, but I also do believe that that cannot prevent user mistakes. 
For sure it will use an default value if the user passed a number to read_str_setting, 
but in reality, the user is more likely to make a typo, so instated of `annotation`, the user typed `annotations`, the `read_str_setting` will return the what the user typed "annotations" which is the wrong value.
So I am not if we should even have these runtime check. 

Ideally I imagine that we have LSP json schema, that will draw error underlines if we provide the wrong values to keys..
But even without the schema, I belive that it is the responsibility of the user to type the right value. 

I will close this issue :)
if you think differently feel free to reopen it.
