### ISSUE TITLE
[ST4] gopls: after PR #1257, LSP doesn't start gopls

### ISSUE THREAD

**Issue by arsham** [sublimelsp/LSP#1258]
## OS and language server

Arch Linux
gopls: `@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=`
ST4: `4.4081-1`

## How you installed LSP (Package Control or from git?)

Git clone, `st4000-exploration` branch at any of d19a3ef6 , cc8d42e9 , 5705aee2.

## Details

LSP doesn't produce any logs on `ST4` console or `LSP` log panel. There are no `gopls` processes running on the system. 

3c49f5f5 works fine and it seems that #1257 introduced this issue.

## Logs

<details><summary>Troubleshoot Server Output</summary>
<p>

# Troubleshooting: gopls
## Version
 - LSP: 1.0.8
 - Sublime Text: 4081
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "gopls"
]
```
 - shell command
```sh
gopls
```
 - languages
```json
[
  {
    "document_selector": "source.go", 
    "feature_selector": "source.go", 
    "language_id": "go"
  }
]
```
 - init_options
```json
{}
```
 - settings
```json
{
  "gopls": {
    "workspaceFolders": true
  }
}
```
 - env
```json
{
  "CGO_ENABLED": "0", 
  "GO111MODULE": "on", 
  "GOFLAGS": "-tags=integration", 
  "GOPATH": "/home/arsham/go:/usr/lib/go", 
  "PATH": "/home/arsham/go/bin:$PATH:/usr/lib/go/bin:/usr/bin"
}
```

## Active view
 - File name
```
/home/arsham/Projects/Go/github.com/xxx/yyyy/zzzz
```
 - Settings
```json
{
  "auto_complete_selector": "source, text", 
  "lsp_active": true, 
  "syntax": "Packages/sublime-mate/Go.sublime-syntax"
}
```

## Project / Workspace
 - folders
```json
[
  "/home/arsham/Projects/Go/github.com/xxx/yyyy", 
  "/usr/lib/go/src", 
  "/home/arsham/go/pkg/mod"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "file_exclude_patterns": [
        "*.test", 
        "*.coverprofile", 
        "*.out", 
        "*.zip"
      ], 
      "folder_exclude_patterns": [
        "tmp/notes", 
        "bin"
      ], 
      "path": "/home/arsham/Projects/Go/github.com/xxx/yyyy"
    }, 
    {
      "file_exclude_patterns": [
        "*"
      ], 
      "folder_exclude_patterns": [
        "*"
      ], 
      "name": "Standard Library", 
      "path": "/usr/lib/go/src/"
    }, 
    {
      "file_exclude_patterns": [
        "*"
      ], 
      "folder_exclude_patterns": [
        "*", 
        "cache"
      ], 
      "name": "Mod", 
      "path": "/home/arsham/go/pkg/mod/"
    }
  ]
}
```

## LSP configuration

```json
{
  "auto_show_diagnostics_panel": false, 
  "clients": {
    "gopls": {
      "command": [
        "gopls"
      ], 
      "enabled": true, 
      "env": {
        "CGO_ENABLED": "0", 
        "GO111MODULE": "on", 
        "GOFLAGS": "-tags=integration", 
        "GOPATH": "/home/arsham/go:/usr/lib/go", 
        "PATH": "/home/arsham/go/bin:$PATH:/usr/lib/go/bin:/usr/bin"
      }, 
      "languageId": "go", 
      "scopes": [
        "source.go"
      ], 
      "settings": {
        "gopls.workspaceFolders": true
      }, 
      "syntaxes": [
        "Packages/Go/Go.sublime-syntax", 
        "Packages/sublime-mate/Go.sublime-syntax"
      ]
    }
  }, 
  "disabled_capabilities": [
    "completion"
  ], 
  "log_debug": false, 
  "log_payloads": false, 
  "log_stderr": true
}
```
## System PATH
 - /home/arsham/.local/bin
 - /usr/lib/ccache/bin/
 - /home/arsham/go/bin
 - /usr/local/sbin
 - /usr/local/bin
 - /usr/bin
 - /home/arsham/dotfiles/plugins/git
 - /home/arsham/dotfiles/plugins/kubectl
 - /opt/cuda/bin
 - /usr/lib/jvm/default/bin
 - /usr/bin/site_perl
 - /usr/bin/vendor_perl
 - /usr/bin/core_perl
 - /var/lib/snapd/snap/bin

</p>
</details>

Thank you.

**Comment by jfcherng** [comment]
Maybe you want to try the 1.0.9 release, which is still not on Package Control but it will be there soon.

**Comment by rwols** [comment]
You are on ST version 4081. Release 1.0.9, which includes 5705aee211a0c5eedfa5cd542351f2194ab0c562, will require ST version 4082 and later.

**Comment by rchl** [comment]
Yes, please update to ST4082+ or downgrade LSP release.

**Comment by arsham** [comment]
Upgraded ST4 to `4083` resolved the issue. Thank you.
