### ISSUE TITLE
After the input is complete, the selection is hidden

### ISSUE THREAD

**Issue by rzxe** [sublimelsp/LSP#1269]
Is my configuration wrong?
![image](https://user-images.githubusercontent.com/66535032/90983004-96bfcd80-e59d-11ea-86db-37b1f548a7d9.png)
When I finish "t", I can't find "fmt.Print" this one.
![image](https://user-images.githubusercontent.com/66535032/90983053-e900ee80-e59d-11ea-9c5a-d25fa0dedcb7.png)

**Comment by predragnikolic** [comment]
1.Can you tell what exact ST build you are using?
2.Have you installed LSP through package control, or you cloned the repo(provide the version, or the branch)
3. I see you configured go. Are you using gopls or golsp, please paste you go lsp configuration?

So after you pressed "t" you no longer see the `Print` completion item in the autocomplete?

**Comment by rzxe** [comment]
1 ST4(4083)
2 From package control
3 gopls
`
{
    "auto_show_diagnostics_panel_level": 1,
    "show_diagnostics_severity_level": 1,

    "lsp_format_on_save": true,
    "only_show_lsp_completions": true,

    "document_highlight_style": "box",

    "clients":
    {
        "gopls":
        {
            "command": ["gopls"],
            "enabled": true,
            "settings":
            {
                "gopls.completeUnimported": true,
            },
        }
    }
}
`
Yes, after that the `Print` completion item is not in the autocomplete

**Comment by rchl** [comment]
In this case the trigger is (I believe since there is no server log) `print` so ST hides completion when it's fully typed.

I believe there is an issue for that in ST issue tracker.
