### ISSUE TITLE
Syntax highlighting issue in server output panel

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP#1278]
some times syntax highlighting in the server output panel is broken, I don't know why
![image](https://user-images.githubusercontent.com/33235928/91507470-3a2e1c80-e8d5-11ea-90f9-91b744bb7fd6.png)

* Windows 10
* How you installed LSP: git master
* Minimal reproduction steps
  * run the LSP-json in a supported document

**Comment by rchl** [comment]
ST disables highlighting on the line of it's over certain number of characters.
