### ISSUE TITLE
Possibility to click on the comment links

### ISSUE THREAD

**Issue by andremacola** [sublimelsp/LSP#1280]
Some documentation blocks has links to more complete documentation. It would be interesting to be able to click on these links directly from the popup.

## ACTUAL BEHAVIOR

![lsp](https://user-images.githubusercontent.com/3408809/91644805-04448180-ea16-11ea-9e6c-e834a47a2e5b.png)

## PROPOSED

![lsp-proposal](https://user-images.githubusercontent.com/3408809/91644887-bda35700-ea16-11ea-9ea3-bb7f86c1b3f8.png)

**Comment by rwols** [comment]
Seems to be a language server issue https://github.com/bmewburn/vscode-intelephense/issues/1316

**Comment by andremacola** [comment]
Well, the image on second example is from VSCode using `vscode-intelephense`. I thought this would have to be identified by the LSP package

**Comment by andremacola** [comment]
I just saw on Discord, you said It only happens for plaintext and for markdown LSP trust the langserver to do it.

What is the possibility of this being handled by the LSP?

**Comment by rwols** [comment]
There are complications with markdown that would make it fragile to try to parse links. For example, we should not make links clickable inside backticks or inside `<a>` tags. We could kindly ask @facelessuser, the author of [mdpopups](https://facelessuser.github.io/sublime-markdown-popups/), to implement automatic link parsing of some sorts for markdown, possibly enabled with frontmatter.

**Comment by facelessuser** [comment]
Just use the MagicLink extension.

**Comment by facelessuser** [comment]
I was on my phone when I posted that, but here is the link: https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/. It is already included in Sublime Text if you are using mdpopups, but you probably just need to enable it.

**Comment by rwols** [comment]
Should be fixed in release 4070-1.0.11 (coming soon to package control)
