### ISSUE TITLE
[LSP-elm] Documentation popup is no logner visible when "More" link is clicked

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1309]
* OS and language server - Ubunutu 20.04, LSP-elm, ST 4085 
* How you installed LSP - git, latest st-4000-exploration

When clicking the `More` link in the AC popup,
I expect to see a documentation popup.
But I see nothing. 

This commit introduced this behavior 19df9e19afeb0f32064a8b7e3a11ebaa4254f63c
If I checkout the commit before 19df9e19afeb0f32064a8b7e3a11ebaa4254f63c, everything works as expected.

**Comment by rchl** [comment]
I have a fix. It's due to the server not supporting the resolve provider.

**Comment by predragnikolic** [comment]
Confirmed as fixed
