### ISSUE TITLE
LSP Document Symbols downside compared to native one

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1323]
**Describe the bug**
I've been running with `cmd+r` overridden to use Document Symbols from LSP. The functionality is better than native but it has one downside compared to native behavior. Namely, with native, I can trigger the shortcut and start typing immediately. The quick panel appears immediately (synchronously or at least with almost no latency). When using LSP's document symbol, the quick panel only opens after we receive server response so, being used to just start typing my query right away, my query ends up being inserted into the active view instead.

Ideally, the quick panel would open right away, even before the response comes, but I guess the API might not let us do that.

Alternatively, we could potentially work around that somehow by capturing user input when the command is triggered and before the quick panel is shown.

**Comment by willrowe** [comment]
I have noticed this as well. It would be very helpful to capture the input so that it is not accidental entered into the active view. Would it be possible to open a panel with nothing in it, keep track of the input, and then close it and open the actual panel with that same input?

**Comment by rchl** [comment]
Capturing the input could probably be done by having a key binding assigning to `<char>` that does nothing when certain view setting is set. Then we can set that setting on triggering `Document Symbols` and remove it once we get a reply (success or error).

**Comment by rwols** [comment]
Related: https://github.com/sublimehq/sublime_text/issues/3338

**Comment by rchl** [comment]
> Would it be possible to open a panel with nothing in it, keep track of the input, and then close it and open the actual panel with that same input?

That's not possible because the Quick Panel API doesn't allow setting the initial query value.

**Comment by willrowe** [comment]
It's technically possible in a round-about way since the Quick Panel is a View. You can call a TextCommand on the View associated with the Quick Panel like so:

```python
class QuickPanelSetContent(sublime_plugin.TextCommand):
    def run(self, edit, query_content):
        self.view.replace(edit, sublime.Region(0, self.view.size()), query_content)
```

It may not be something that you want to do, but it is technically possible.

**Comment by rchl** [comment]
But how would I get ahold of the view? `window.show_quick_panel` doesn't return it.

**Comment by willrowe** [comment]
That's the tricky part. You would use an EventListener with `on_activated` set to listen right after creating the quick panel. If the next View to trigger `on_activated` has the `is_widget` setting set to `True` then that is the view. Again, probably not something that you want to do, it is just how I have worked around some shortcomings of the Quick Panel API in the past.

**Comment by rchl** [comment]
That sounds like too much of a hack but thanks for an idea.
