### ISSUE TITLE
Setting to specify PATH env variable like in SublimeLinter

### ISSUE THREAD

**Issue by tobiastimm** [sublimelsp/LSP#1349]
I always need to start sublime via the terminal to get the `PATH` variable right for some plugins like LSP. 

It would be cool if we could specify the `PATH` variable via the settings.

For example, in SublimeLinter, you can do:

```
// SublimeLinter Settings - User
{
  "linters": {
    "eslint": {
        "env": {
          "PATH": "/Users/tobias.timm/.volta/bin"
        }
    },
}
```

This would help me a lot and solves my struggles :D

**Comment by rchl** [comment]
You can just save yourself a lot of trouble but fixing the issue with ST not having correct `PATH` set.

You just need to extend the path in your `~/.profile` or `~/.zprofile` (if using `zsh` shell), restart your system (or re-login) and it should work.

**Comment by tobiastimm** [comment]
@rchl Thank you very much for that help :D you solved all of my problems!
