### ISSUE TITLE
Document state can get out of sync when server supports incremental sync

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1365]
**Describe the bug**
In some situations, the document state can get out of sync with the server. One case where I can reproduce is when activating a view that doesn't have server started yet and immediately changing something.

**To Reproduce**
1. Activate a view that doesn't have the server started yet.
2. Immediately type something that would cause an error

**Expected behavior**
The server having a correct state of the document.

**Environment (please complete the following information):**
- Sublime Text version: 4087
- LSP version: 1.0.17
- Language servers used: LSP-json

**Additional context**
I believe what happening is:
1. the file is opened and immediately some text is inserted:
   - the `change_count()` (revision) is now 1
   - server receives the text content of the document as seen in revision 1
2. The `on_text_changed_async` is triggered
   - the reported change is the insert done in point 1.
   - the revision is still 1
3. Server receives a didChange notification with insert done in point 1
   - now the server has an out-of-sync state since it has applied the change to the initial state which already included that change.

Here are logs from when a couple of `,` are inserted quickly after activating the view. The logs are for when `didOpen` and then `didChange` notifications are sent:
```
DID_OPEN 1
ON_TEXT_CHANGED 1 [(5, 5, ',')]
ON_TEXT_CHANGED 1 [(6, 6, ',')]
ON_TEXT_CHANGED 2 [(7, 7, ',')]
```

**Comment by rwols** [comment]
Yeah, we need a check to see if the change_count is actually larger than what is already sent in didOpen. It'd be nice if on_text_changed_async would pass along the change_count from the point in time that the on_text_changed was recorded. I think we can solve it in the plugin, but the most tidy solution would probably be to have the ST api changed a bit.

**Comment by rchl** [comment]
Thanks for fixing.
