### ISSUE TITLE
Implement codeDescriptionSupport

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1367]
**Is your feature request related to a problem? Please describe.**
Version 3.16 adds a codeDescription to the Diagnostic structure. The codeDescription contains a url to "more information".

**Describe the solution you'd like**
Advertise codeDescriptionSupport, and handle the codeDescription by allowing the user to click on the url.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/microsoft/language-server-protocol/commit/1de6e8e8d4f69ab7079f2626637de7c583c0822a

**Comment by rchl** [comment]
At the same time make sure we show the `code` (both in the popup and diagnostics panel).
