### ISSUE TITLE
Official way for deferring specifying the client "command" from plugin

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1373]
As mentioned in https://github.com/sublimelsp/LSP/issues/899#issuecomment-706703808, it's possible to not specify the path for `command` from `AbstractPlugin.plugin_configuration()` and then manually update it later from `AbstractPlugin.can_start()`.

It works but it's neither clean nor obvious to users of the API that don't study the LSP code. It's not specified anywhere that the user is allowed to modify the `ClientConfig` like that (maybe the config was propagated to some other parts of the code already? Maybe `command` is not really considered public property?).

It basically looks like a hack to do it as LSP-Dart and LSP-flow are doing it and I think that we should have a clearer and more explicit API for that. I'm not sure how it should look like though.

**Comment by rwols** [comment]
I don't have a strong opinion about this (I think the way the dart and flow packages are doing it now is fine). Yes, those packages modify the client config per-window just-in-time. I would also be fine with it if someone delineated more strict API boundaries. (isn't the plugin the owner of that ClientConfig that it is modifying in-place?)
