### ISSUE TITLE
The "path" argument must be one of type string, Buffer, or URL. Received type object

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1374]
Is it a language server problem? No
Please include in your report:

* OS and language server? MacOS/Linux, LSP-typescript
* How you installed LSP (Package Control or from git?) git
* Minimal reproduction steps.
1. Open a typescript repo in sublime merge. 
2. Open command palette and choose `Open Repository in sublime text`.
3. Open a `.js`, `.ts` file in ST.

Expected behaviour:
Start the server in the file.

Actual behaviour:
I get an  error popup:
```
Request initialize failed with message: The "path" argument must be one of type string, Buffer, or URL. Received type object
```

<img width="445" alt="Screenshot 2020-10-12 at 13 46 42" src="https://user-images.githubusercontent.com/22029477/95743087-7654eb00-0c91-11eb-89fc-455c3a0a76ee.png">

And I have  to quit ST and open it to make the error go away.

Additional info,
I suspect to it is due to not having a way to detect when we open ST like that. (similar that we don't have a callback to  detect when set_project_data was called, or maybe we do have a way, but I am not aware of it).

**Comment by rwols** [comment]
There are a couple parties here:

- Shouldn't Merge open the repo as a folder? Is it opening that one file?
- Should LSP-typescript implement `can_start` and refuse to start when there's no folder?
- Should the typescript language server gracefully handle an initialize request without workspaceFolders and without a rootUri? These keys are allowed to be null values.
- Should this LSP package somehow cook up a rootUri and workspaceFolder even if there isn't one?

**Comment by rchl** [comment]
> * Open a typescript repo in sublime merge.
> * Open command palette and choose `Open Repository in sublime text`.

I've seen this error before but those steps actually don't reproduce for me. SM opens a folder so LSP-Typescript gets a property rootPath and all.

**Comment by ivansvlv** [comment]
Hi 👋🏻 I was just about to ask this in Discord, when decided to go through GitHub issues. I have the very same error, but steps to reproduce are different.

1. Open clean ST (Build 4090) on macOS Catalina (Version 10.15.7)
2. File -> Open, and choose the project folder.
3. The first .js, .ts (i think it's only, when i open the first file of that extension) file I open I receive the error below.

![image](https://user-images.githubusercontent.com/16175855/97171424-1896c780-1796-11eb-9f35-9b9d41a3755d.png)

Restart button doesn't help, I have to Cancel and reload editor, then it's fine.

To be honest I have no clue how to debug ST, so if you have some directions which will help you and that I can follow, I would  gladly perform them.

**Comment by rchl** [comment]
I can reproduce using those steps.

Looks like an LSP bug. I don't think ST has a way of notifying us when workspace folders change but we could probably work around it somehow.

**Comment by rwols** [comment]
The "bug" is that we still don't have an event for when `window.project_data()` changes. The only thing that File > Open does when you select a folder is that it is added to `window.project_data()["folders"]`. While the situation is improved now that we have `on_project_loaded` etc, really we only need a new `on_project_data_changed`.

**Comment by rchl** [comment]
I was thinking that we could re-evaluate the workspace folders before starting the server.
It's not gonna be pretty or proper but sometimes you gotta do what you gotta do. :)

**Comment by ivansvlv** [comment]
@rchl @rwols Thank you guys, you are doing a fantastic job with LSP 🤘🏻
