### ISSUE TITLE
Support for TailwindCSS

### ISSUE THREAD

**Issue by rrrrando** [sublimelsp/LSP#1377]
**Is your feature request related to a problem? Please describe.**
This is a feature request to implement a new language server.

**Describe the solution you'd like**
They have an official vscode language server here -> https://github.com/tailwindlabs/tailwindcss-intellisense maybe this could be added to packagecontrol with the rest of the language servers.

**Describe alternatives you've considered**
I have tried to add it myself but with no luck

**Comment by jfcherng** [comment]
Disclaimer: I have no experience in using TailwindCSS framework at all.

---

https://github.com/jfcherng-sublime/LSP-tailwindcss

Screenshot tested in ST 4088:
![Snipaste_2020-10-17_09-29-52](https://user-images.githubusercontent.com/6594915/96325740-e8944980-105c-11eb-8416-e87ebe2e0e01.png)

**Comment by rrrrando** [comment]
Works just fine. Even with lsp-vue nad lsp-eslint enabled.

Thank you very much!

I can maintain it. It's just going to take a week or so, since i then need to fully understand how all this works.

**Comment by rwols** [comment]
When I read this page: https://tailwindcss.com/docs/installation

I feel like the best way for this tailwind organization ([tailwindlabs](http://tailwindlabs.com)?) is to have the server be installed along with the other files when you install it in your project with `npm install tailwind`

It should have a binary placed in

```
node_modules/.bin/tailwind-lsp
```

flow employs the same strategy and it works well. It's independent of an editor this way.

**Comment by rwols** [comment]
Thinking about this a little more, why can't the standard HTML language server (i.e. [this one](https://github.com/sublimelsp/lsp-html)) not deduce what the possible css classes are?

**Comment by predragnikolic** [comment]
> Thinking about this a little more, why can't the standard HTML language server (i.e. this one) not deduce what the possible CSS classes are?

CSS can be included in via the link tag, or via JavaScript, or via some other way. Some JS frameworks have scoped css... 
Some people use sass, less, stylus, which can use for loops to create classes dynamicly...

I would say that it is not easy to get perfect CSS class/id completions in the html ls :)
