### ISSUE TITLE
Allow edit the TCP connection timeout value on the Settings

### ISSUE THREAD

**Issue by danillos** [sublimelsp/LSP#1378]
**Is your feature request related to a problem? Please describe.**

Using `solargraph` in a project with many files, `solargraph` sometimes takes more than 5 seconds to start the server and Sublime shows a timeout error.

**Describe the solution you'd like**

Allow users to edit the timeout value on the Settings.

**Describe alternatives you've considered**

I attempted to limit the files that `solargraph` index using the `.solargraph` config file but it wasn't enough.

**Additional context**

The test were done using the `solargraph v0.39.17` and `ST3`

**Comment by rwols** [comment]
I'm of the opinion that this is a fundamental problem of solargraph. It starts parsing files, only responding to the `initialize` request once all files are parsed. It should instead use an asynchronous design where it responds to the `initialize` request _immediately_, and parses files _asynchronously_, reporting its _progress_ via a standard LSP mechanism to report progress, which this client supports.

While computing its internal data structures, solargraph should provide basic or no features.

Given this fundamental design problem of solargraph I am not keen to provide yet another setting for servers that should ideally use progress reporting. You should also open an issue on the solargraph repository explaining your situation.

**Comment by rwols** [comment]
cc @castwide

**Comment by castwide** [comment]
@rwols Thanks for the heads up. I agree with your suggested implementation and expect to move in that direction in an upcoming release.

**Comment by castwide** [comment]
I've begun work on improving Solargraph's initialization process: https://github.com/castwide/solargraph/issues/415

**Comment by castwide** [comment]
The castwide/solargraph master branch includes near-immediate server initialization, background mapping, and progress reports for clients that support `window/workDoneProgress`. Barring unforeseen problems, it should be published in the next release within a day or so. More info: castwide/solargraph#415

**Comment by castwide** [comment]
The update's been published in solargraph gem v0.41.0.

**Comment by danillos** [comment]
Thank you, @castwide, it is working pretty well on SublimeText 4.
