### ISSUE TITLE
AttributeError: run_code_action

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1398]
**Describe the bug**
Selecting a code action throws a:

```
Traceback (most recent call last):
  File "/home/predrag/.config/sublime-text/Packages/LSP/plugin/code_actions.py", line 313, in handle_select
    session.run_code_action(selected[2])
  File "/home/predrag/.config/sublime-text/Packages/LSP/plugin/core/sessions.py", line 683, in __getattr__
    raise AttributeError(name)
AttributeError: run_code_action
```

**To Reproduce**
1. Use any LS that has code actions.
2. Trigger code actions via keybinding or click the code actions from the annotation on the right.
3. Select a code action
4. See error in ST console.

**Expected behavior**
Execute the code action. 

**Actual behavior**
Code action is command is not executed and an error is logged in the ST console.

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Sublime Text version: 4090
- LSP version: lates st4000-exploration branch(3507a84ea18aa5413f5ca28265f1d02dca326ee4)
- Language servers used: LSP-typescript, LSP-elm

**Additional context**

This is the commit that introduced this behavior 4d5bb06d2b3aad4755b852ae19096c42835a919a

**Comment by rwols** [comment]
Thanks for the bug report. Committed directly to the default branch.

**Comment by predragnikolic** [comment]
Thanks for the quick fix
