### ISSUE TITLE
sublime.pyi: Cool type hints, how do I use them?

### ISSUE THREAD

**Issue by ratijas** [sublimelsp/LSP#1400]
**Is your feature request related to a problem? Please describe.**

I'm interested in using sublime API to develop plugins. I also used to work in PyCharm. There are python type hints for ST built-in modules in this repository, and I'm wondering how can I import them into PyCharm, so it can make sense out of them?

Hereby, I request instructions, ideally a README in their folder, and a separate PyPI package with stubs.

**Describe the solution you'd like**

1. Instructions in README explaining how to install Sublime Text API stubs.
2. Independent package on PyPI, which could be easily installed with one `pip` command.

**Describe alternatives you've considered**

I suppose, I could just manually download them, and copy to my `~/.local/lib/python3.x/site-packages/`.

https://www.jetbrains.com/help/pycharm/stubs.html#install-stub

**Comment by rwols** [comment]
Perhaps try adding the directory ~/.local/sublime-text-3/Packages/LSP/stubs to your `PYTHON_PATH` environment variable.

**Comment by ratijas** [comment]
Can confirm that manually downloading into `~/.local/lib/python3.x/site-packages/` does the thing for PyCharm. Method suggested by @rwols works too, but is a bit troublesome because requires altering global env and thus restarting stuff.

**Comment by ratijas** [comment]
That said, I'd be even happier if I could just `pip install` them.

**Comment by rwols** [comment]
I don't think that will happen. `pip` works with your system python executable, whereas sublime.py only works with the bundled plugin_host executable from Sublime Text.

**Comment by rwols** [comment]
So it makes little sense to have pyi files on pip for a py file that a random python interpreter can never run anyway.

**Comment by ratijas** [comment]
Sorry, I just can't agree. Even if you don't run it, it's still extremely useful for the development. For example, take a look at [`@types`](http://definitelytyped.org/) namespace on npm: all they do is provide stubs with type hints — and that became a huge project out of thin air.

**Comment by jfcherng** [comment]
But isn't https://github.com/sublimelsp/LSP/issues/1400#issuecomment-718783914 working?

**Comment by ratijas** [comment]
@jfcherng Yep, it's working. But I'm kindly asking (feature requesting) for explicit instructions in README, and ideally a package on PyPI. :slightly_smiling_face: 

> Also if you use LSP-pyright, you can add that directory into python.analysis.extraPaths.

I have no idea what's that. Actually, I'm working on a plugin which is not related to LSP in any way.

**Comment by rchl** [comment]
> Sorry, I just can't agree. Even if you don't run it, it's still extremely useful for the development. For example, take a look at [`@types`](http://definitelytyped.org/) namespace on npm: all they do is provide stubs with type hints — and that became a huge project out of thin air.

The difference being that `@types/*` are created to match respective `*` packages that are available on npm.

The ST types would be for something (not a library) that doesn't exist on pip. I don't know pip ecosystem and I can't judge whether that would make sense in that ecosystem.

**Comment by ratijas** [comment]
> The ST types would be for something (not a library) that doesn't exist on pypi. I don't know the pypi ecosystem and I can't judge whether that would make sense in that ecosystem.

PyPI is just like any other community-based package manager: it is flooded with tons of low quality trash and all sort of stuff. So I don't think ST stubs would impose any political problems there.

Actually, if you follow the link in my first post, there is a reference to [PEP 561](https://www.python.org/dev/peps/pep-0561/) -- Distributing and Packaging Type Information. That essentially dictates the rules how to make distributable stubs packages. So, it's worth checking out. (Honestly, didn't know about that PEP myself until today).

**Comment by rwols** [comment]
I won't be spending time on getting the type stubs on PyPI. But you are of course free to do it yourself. This code base has an MIT license after all.

**Comment by rchl** [comment]
FYI: sublime_lib also includes its own stubs: https://github.com/SublimeText/sublime_lib/blob/master/stubs/sublime.pyi

**Comment by jfcherng** [comment]
Would like to advertise mine too https://github.com/jfcherng-sublime/ST-API-stubs
