### ISSUE TITLE
Wrong placeholder in the rename quick panel

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#1410]
**Describe the bug**

For LSP-intelephense, it seems that the placeholder in the quick panel is the one under the caret rather than the actual symbol which triggers that. The actual renaming operation is done right though.

Unfortunately `Rename` is a premium feature in intelephense... and I can't reproduce this with LSP-pyright... weird.

**To Reproduce**

```php
<?php

class Foo
{
    public static function getInstance()
    {
        return new static();
    }

    public function abcd()
    {
        echo 'haha';
    }
}

Foo::getInstance()->abcd();
```

1. Place caret on `haha`
2. Hover on `bar`
3. Click `Rename` on the popup
4. `haha` will be in the shown quick panel

**Expected behavior**

It should be `bar` in the shown panel.

**Screenshots**

Video recording: https://streamable.com/bw762h

**Environment (please complete the following information):**
- OS: Win7 x64
- Sublime Text version: 4090
- LSP version: the latest commit on `st4000-exploration` 653fd3c4e25c2ed5294f76b0b8b5db79f56f18c2 
- Language servers used: intelephense

**Additional context**

I see the server communication log but I didn't see any "line 11" in it but they are all correct "line 15".

LSP log:

```
:: --> LSP-intelephense textDocument/hover(87): {'position': {'character': 23, 'line': 15}, 'textDocument': {'uri': 'file:///E:/_Test/php/src/test.php'}}
:: <<< LSP-intelephense 87: {'range': {'start': {'character': 20, 'line': 15}, 'end': {'character': 24, 'line': 15}}, 'contents': {'kind': 'markdown', 'value': '__Foo::abcd__\n\n```php\n<?php\npublic function abcd() { }\n```\n\n_@return_ `void`'}}
:: --> LSP-intelephense textDocument/prepareRename(88): {'position': {'character': 23, 'line': 15}, 'textDocument': {'uri': 'file:///E:/_Test/php/src/test.php'}}
:: <<< LSP-intelephense 88: {'start': {'character': 20, 'line': 15}, 'end': {'character': 24, 'line': 15}}
```

**Comment by rwols** [comment]
The difference is that intelephense is a prepareRenameProvider, while pyright is not.
