### ISSUE TITLE
Request for animated GIFs of features

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1450]
I want to show off the features of this package on the readme page with animated GIFs, ideally with various language servers. If you can find the time to record a feature, please post the GIF here.

- Duration should be short
- Show off one feature, not multiple (e.g. show off textDocument/completion or textDocument/rename)
- Use as few keystrokes as possible
- Type slowly
- Click and move slowly if using the mouse

Thanks!

**Comment by ayoub-benali** [comment]
Here is an example of workspace symbol query: 

![gif](https://i.imgur.com/8X0XNi2.gif)

**Comment by Serega124** [comment]
completion
![completion](https://user-images.githubusercontent.com/5006548/119979746-06973480-bfc4-11eb-87c1-cc9caf72a6d7.gif)

signature help
![signature help](https://user-images.githubusercontent.com/5006548/119979818-1c0c5e80-bfc4-11eb-9056-3cc0cae2e38b.gif)

format
![format](https://user-images.githubusercontent.com/5006548/119979865-26c6f380-bfc4-11eb-9273-93b848cc8e87.gif)

code actions
![code actions](https://user-images.githubusercontent.com/5006548/119979896-321a1f00-bfc4-11eb-96f4-47fb1db48728.gif)

definitions
![definitions](https://user-images.githubusercontent.com/5006548/119979953-478f4900-bfc4-11eb-9274-9dda442dfa3f.gif)

references
![references](https://user-images.githubusercontent.com/5006548/119979971-5118b100-bfc4-11eb-9b6a-c0e109b1843c.gif)

symbol rename
![symbol rename](https://user-images.githubusercontent.com/5006548/119979993-5aa21900-bfc4-11eb-9169-37e2a9ee66ac.gif)

project-wide symbol rename
![project-wide symbol rename](https://user-images.githubusercontent.com/5006548/119980137-891ff400-bfc4-11eb-830e-509a5dd181bb.gif)

color provider
![color provider](https://user-images.githubusercontent.com/5006548/119980160-9341f280-bfc4-11eb-92e0-d85f125e0913.gif)

**Comment by predragnikolic** [comment]
Can we close this?
