### ISSUE TITLE
Frequent ST freezes, LSP waits indefinitely for clangd 

### ISSUE THREAD

**Issue by haferburg** [sublimelsp/LSP#1475]
Killing the clangd processes unfreezes ST.

I'm also seeing frequent crashes of clangd.

    clangd: I[10:31:06.458] <-- textDocument/hover(2)
    clangd: I[10:31:06.465] --> reply:textDocument/hover(2) 6 ms
    clangd: E[10:31:06.519] Transport error: io error
    clangd: I[10:31:06.519] LSP finished, exiting with status 1

What can I do to debug this? I don't even know where to start. I turned on verbose logging.

On https://clangd.llvm.org/troubleshooting.html#dealing-with-crashes it says 

> clangd is likely writing a “stack trace” to the logs which helps explain why it crashed

Where can I find those logs? Is that referring to a file? I didn't see a stack trace in the output window or console.

It also seems to freeze out of nowhere. I just tried to paste text (log messages) into a new buffer, and it freezes. I didn't see any log messages after killing clangd.

I'm on Windows, ST 3210, clangd 11.0.0 prebuilt.

**Comment by rwols** [comment]
Sorry to hear you're experiencing freezes. The "logs" should be printed to the log panel.

> It also seems to freeze out of nowhere.

This seems to suggest the crash occurs in the background indexer. Try adding `-background-index=0` to the `"command"` and see if the crash still occurs.

**Comment by haferburg** [comment]
@rwols It just 'crashed' again when I saved a document.

    clangd: E[14:15:19.739] Transport error: io error
    clangd: I[14:15:19.739] LSP finished, exiting with status 1

I'll add the flag to the command, thank you for the suggestion.

**Comment by haferburg** [comment]
Enabled `log_debug`:

    ::  -> clangd textDocument/didChange
    clangd: V[20:21:49.380] <<< {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///src/main.cpp"}}}
    ::  -> clangd textDocument/didSave
    clangd: 
    clangd: I[20:21:49.380] <-- textDocument/didSave
    clangd: V[20:21:49.380] ASTWorker skipping Update (1303) for src\main.cpp
    clangd: V[20:21:49.392] <<< {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///src/main.cpp"}}}
    clangd: 
    clangd: I[20:21:49.392] <-- textDocument/didSave
    clangd: V[20:21:49.393] ASTWorker skipping Update (1303) for src\main.cpp
    ::  -> clangd textDocument/didSave
    clangd: E[20:21:49.500] Transport error: io error
    clangd: I[20:21:49.500] LSP finished, exiting with status 1

Is it possible that LSP accidentally sends `textDocument/didSave` twice, causing some sort of race condition in clangd?

**Comment by haferburg** [comment]
I just had a freeze after a hover.

    :: --> clangd textDocument/hover(7)
    clangd: V[20:36:45.182] <<< {"id":7,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":29,"line":4469},"textDocument":{"uri":"file:///src/main.cpp"}}}
    clangd: 
    clangd: I[20:36:45.182] <-- textDocument/hover(7)
    clangd: V[20:36:45.185] ASTWorker running Hover on version 1308 of src\main.cpp
    clangd: I[20:36:45.188] --> reply:textDocument/hover(7) 6 ms
    clangd: V[20:36:45.188] >>> {"id":7,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### field `AttackProcessed`  \n\n---\nType: `bool`  \n\n---\n```cpp\n// In mob\npublic: bool AttackProcessed = false\n```"},"range":{"end":{"character":36,"line":4469},"start":{"character":21,"line":4469}}}}
    clangd: 
    :: <<< clangd 7

I had to kill clangd for ST to unfreeze.

**Comment by haferburg** [comment]
Crash when ST lost focus

    clangd: 
    clangd: E[20:43:14.381] Transport error: io error
    clangd: I[20:43:14.381] LSP finished, exiting with status 1

**Comment by rwols** [comment]
Do you have a virus scanner or some other daemon process that inspects the clangd binary, perhaps?

**Comment by rwols** [comment]
Do you have any non-ASCII characters in your source code?

**Comment by haferburg** [comment]
Some of the source files are in my Dropbox folder, but I disable syncing while I'm working. I don't think Dropbox touches the .cache folder. No virus scanner.

ASCII: I had ∙ and ° in comments. Will try if removing them helps.

**Comment by rwols** [comment]
Do you have a package installed that also runs the "save" command somehow? Can you list your installed packages?

**Comment by rwols** [comment]
Did you notice any freezes in the meantime?

**Comment by haferburg** [comment]
I stopped using LSP, unfortunately. It frustrated and got me sidetracked too often. I might give it another try once ST4 is out. Or I'll switch to VS code. I really like ST, it's just moving way too slow. Sublime Merge is fantastic, but it didn't exactly help ST's velocity.

Thank you for checking in, though. Feel free to close.

**Comment by rwols** [comment]
Understandable. Do try the ST4 version.
