### ISSUE TITLE
LspTextCommand should honor both session_name and capability if defined

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#1485]
If `capability` in [LspTextCommand](https://github.com/sublimelsp/LSP/blob/81a6e6aeb2c3a6aebad59fbd6eb0361301243bd1/plugin/core/registry.py#L52-L70) is defined, `session_name` is ignored. You might say that LSP-* plugins exactly know the capabilities of their server and thus never need to specify `capability` in a derived class, but in particular it's impossible for plugins to derive from LspExecuteCommand (which is derived from LspTextCommand), because that class already comes with a predefined `capability`. It can be convenient for a plugin to declare a derived class from LspExecuteCommand, so that their commands are only shown/enabled for corresponding filetypes:
```python
class FooExecuteCommand(LspExecuteCommand):
    session_name = "foo"
```

**Describe the solution you'd like**
```python
    def is_enabled(self, event: Optional[dict] = None, point: Optional[int] = None) -> bool:
        if self.capability:
            # At least one active session with the given capability must exist.
            if not bool(self.best_session(self.capability, get_position(self.view, event, point))):
                return False
        if self.session_name:
            # There must exist an active session with the given (config) name.
            if not bool(self.session_by_name(self.session_name)):
                return False
        if not self.capability and not self.session_name:
            # Any session will do.
            return any(self.sessions())
        return True
```

**Describe alternatives you've considered**
Make `session_name` win against `capability`

**Additional context**
Notice that the implementation suggested above doesn't guarantee that the sessions with the specified name and capability are the same (in case of multiple attached sessions for a view).

**Comment by rwols** [comment]
Sounds good to me. Would you be willing to make a pull request?
