### ISSUE TITLE
The latest (2020-11-23) Rust-Analyzer version causes crash

### ISSUE THREAD

**Issue by Jcskz** [sublimelsp/LSP#1487]
**Describe the bug**
The latest(2020-11-23) rust-analyzer causes crash and restart

**To Reproduce**
1. update the latest (2020-11-23) version rust-analyzer
2. open a rust project
3. open a main.rs
4. enter `primary+s` to save

**Expected behavior**
The file is save normally

**Actual behavior**
the lsp server crashed.

**Environment :**
- OS:macOS 11.0.1
- Sublime Text version: 4093
- LSP version: 1.1.0
- Language servers used: the latest rust-analyzer version

**Additional context**
The possible cause of this crash is that the latest rust-analyzer is updated to 3.16. 
Refer rust-analyzer [changelog](https://github.com/rust-analyzer/rust-analyzer/pull/6566)
[ServerLog.log](https://github.com/sublimelsp/LSP/files/5587013/ServerLog.log)

**Comment by rwols** [comment]
Looks like https://github.com/microsoft/language-server-protocol/issues/1147

**Comment by rwols** [comment]
Does the latest version fix this? https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-11-30

**Comment by Jcskz** [comment]
Yes,the latest version has fixed it. 
You can close this issue. 
@rwols

**Comment by rchl** [comment]
You can do it yourself too. :)
