### ISSUE TITLE
Proposal: rename `selector` to `scopes`?

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1489]
**Is your feature request related to a problem? Please describe.**

When a user upgrades from the ST3 to ST4 they would have to update their client configuration for their servers to work.
Ideally the user should not do anything.

I would want the Client Configuration for ST4 to be backwards compatible with ST3.

**Describe the solution you'd like**
Rename the `selector` to `scopes`.
In ST3 the `scopes` is an array of strings like `["source.js", "source.jsx"]`.
In ST4 the `selector` is just a string `"source.js | source.jsx"`.

To make this backwords compatible in ST4 we can check if the `scopes` is an array or a string. 
If it is a string `"source.js | source.jsx"` than everthing is ok.
If it is an array  `["source.js", "source.jsx"]`, join the strings with a `" | "` an the result `scopes` will be `"source.js | source.jsx"`

**Comment by rwols** [comment]
This already works. In fact, parsing `scopes` for `selector` is not correct. The `syntaxes` correspond to `selector`, and `scopes` corresponds to `priority_selector`. https://github.com/sublimelsp/LSP/blob/520cb76059f516ace691752ae1d0a0b40ea503f2/plugin/core/types.py#L726-L771
