### ISSUE TITLE
Rename `auto_show_diagnostics_panel_level` to `show_diagnostics_panel_on_save`

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1528]
`auto_show_diagnostics_panel_level` might not be a clear and simple setting name as it could be.

**Describe the solution you'd like**
`show_diagnostics_panel_on_save` gives more context that `auto_show_diagnostics_panel_level`.

**Describe alternatives you've considered**
I considered even suggesting the removed `auto_show_diagnostics_panel` instead of `auto_show_diagnostics_panel_level`, but I still think that `show_diagnostics_panel_on_save` is more descriptive.

**Comment by rwols** [comment]
Sounds good to me.
