### ISSUE TITLE
streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by JeremyBois** [sublimelsp/LSP#1530]
> Using a `stack` project I get the following error:
> 
> `streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)'`

I check online and it seems [`nix` have the same issue with `stack`](https://github.com/commercialhaskell/stack/issues/2282). 
> ```For future reference (me): streamingProcess: runInteractiveProcess: exec: does not exist usually means it called an executable that failed to run since dynamic libraries weren't there, meaning you ran nix-collect-garbage.```

Related to commercialhaskell/stack#2282

_Originally posted by @JeremyBois in https://github.com/sublimelsp/LSP/issues/1529#issuecomment-749432945_

**Comment by JeremyBois** [comment]
The solution is to update the **PATH** to include missing binaries or libraries.

One solution is to update the `~/.profile` with needed path:
```bash
### Home
export PATH=$PATH:~/.local/bin:~/bin

### ghcup-hs
export PATH=$PATH:~/.ghcup/bin

### Cabal
export PATH=$PATH:~/.cabal/bin
```

 Another solution is to update the `env` variable in the server configuration (replace `<Home_path>` by your Home path):
```json
"haskell-language-server":
{
    "command":
    [
        "haskell-language-server-wrapper",
        "--lsp"
    ],
    
    // ...

    "env":
    {
        "PATH": "/usr/local/bin:/usr/bin:<Home_path>/.local/bin:<Home_path>/bin:<Home_path>/.ghcup/bin:<Home_path>/.cabal/bin"
    }
}
```

**Comment by rwols** [comment]
Awesome! @moodmosaic perhaps you can expand on this in the docs? Could be a blocker for more users.

**Comment by JeremyBois** [comment]
> Awesome! @moodmosaic perhaps you can expand on this in the docs? Could be a blocker for more users.

Yeah sure I will.

Thanks again !

**Comment by moodmosaic** [comment]
I'd be more than happy to do so, but first I must follow the thread. Perhaps the best person to do this is @JeremyBois. If not, I can look into it over the next few days.

**Comment by JeremyBois** [comment]
Oh I misread @rwols comment ...

@moodmosaic, I will try to update the docs today if possible if it's ok. I just first want to finish to setup and test everything is working on my side in different project configurations.

If I have issues with the process I will ask for help.

**Comment by moodmosaic** [comment]
@JeremyBois :+1: :rocket:
