### ISSUE TITLE
Frozen popup windows with Typescript LSP

### ISSUE THREAD

**Issue by agam** [sublimelsp/LSP#1544]
**Describe the bug**
When editing Typescript a popup will remain in place on the screen. An arbitrary number of these popups can be created on the screen, as shown in the screenshot below.

**To Reproduce**
1. Open a typescript file, after enabling TS LSP.
2. Type `console.log`
3. Type `(`, watch the popup window showing the definition of `log` show up
4. Type something else, watch a a new popup window with suggestions come up, pushing the previous popup window to the side.
5. Delete the line
4. See the previous popup window frozen in place.
5. Repeat as many times as needed.

**Expected behavior**

**Screenshots**
<img width="797" alt="Screen Shot 2021-01-12 at 1 58 25 PM" src="https://user-images.githubusercontent.com/315427/104379830-e49e8900-54de-11eb-9659-d62daede1a9d.png">

**Environment (please complete the following information):**
- OS: _macOS Big Sur (11.1)_
- Sublime Text version: _Dev Channel, Build 4094_
- LSP version: `LSP-Typescript v1.1.4`, `Typescript v3.9.2`
- Language servers used: typescript (separately also using `gopls` for a different project)

**Additional context**
No other config or manual changes needed to repro.

**Comment by predragnikolic** [comment]
The issue you are experiencing is the `Typescript` plugin. It is not a popup provided by LSP or LSP-typescript. 

I would suggest removing the `Typescript` plugin.
Feel free to reopen this issue, if you still need some help.

**Comment by agam** [comment]
You're right, this _did_ turn out to be a problem with the `Typescript` plugin.
