### ISSUE TITLE
Hide inline diagnostics if they span multiple lines

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#1547]
LemMinX tends to mark huge portions of a document (see https://github.com/eclipse/lemminx/issues/963). It marks everything from the opening to the expected position of a closing tag in case it is missing.

An author therefore sees only red when writing XML which is not valid most of the time.

**Describe the solution you'd like**
I'd like to only see underlined issues which don't exceed one single line. Larger diagnostics regions should be represented by a gutter icon and the panel diagnostics only in order to reduce the noise within the editor control.

**Describe alternatives you've considered**
A possibility to quickly enable/disable dynamic linting while writing. It's useful in general though.

**Additional context**

These kinds of markups don't help much.

![grafik](https://user-images.githubusercontent.com/16542113/104943178-a3621980-59b5-11eb-8f05-6f079cd5cdeb.png)

**Comment by rwols** [comment]
Yeah, we should probably think of solving this somehow.

In the meantime, you can set `"diagnostics_highlight_style": "box"` in Preferences/User/LSP.sublime-settings.

**Comment by predragnikolic** [comment]
I do not think that the client should (or can) handle this. 

There is no way for a client to know on what it should not underline. 

The only way right now to avoid underlines in the client is to not use underlines for errors, but rather "box"-es  as @rwols mentioned earlier.

**Comment by rchl** [comment]
Just an idea: switch automatically to box if diagnostic spans more than one line.

No idea if it would work nicely in practice...

**Comment by deathaxe** [comment]
Had such an idea, too, because dozens of boxes around each word is very distracting and reduces readability heavily. I start hating live linting in general as a file in progress is most likely always broken.

Another idea is to just keep the gutter icon and remove markers in file then. That's what I've done for now in general, just `"diagnostics_highlight_style": ""`

**Comment by rwols** [comment]
What about this:

If the region spans multiple lines, then:
1) if it's a hint/note, don't show anything
2) if it's a warning/error, use the box style

If the region doesn't span multiple lines, then:
1) if it's a hint/note, use dotted style
2) if it's a warning/error, use squiggly style

consequently we can remove the style setting altogether, or replace it with a boolean to either show it or not show it?

**Comment by deathaxe** [comment]
Sounds like a good overall approach.

With multiline regions using box style boolean settings to show/hide are sufficient.

Not sure if it may be intentional to still provide style settings for single line regions though, just in case someone wants to tweak the appeareance.

**Comment by predragnikolic** [comment]
This has been fixed on the server. 

Currently I don't know any other server that can return diagnostics that span multiple lines, so there is maybe no need for us to add any additional logic to handle cases like this.

Should we close the issue?

**Comment by deathaxe** [comment]
![grafik](https://user-images.githubusercontent.com/16542113/116759148-f5352980-aa11-11eb-827d-575cf2841a93.png)

LSP-css

**Comment by rwols** [comment]
We shouldn’t assume every language server does the appropriate thing by restricting diagnostics to a single line. The client (us) is in a good position to present this to end-users in an optimally pleasing way, regardless of what the particular server does.
