### ISSUE TITLE
Option to change where type hinting is displayed in the suggestion window

### ISSUE THREAD

**Issue by dvcrn** [sublimelsp/LSP#1549]
Similar to how vscode and other editors are inlining the type hints:

<img width="594" alt="Screen_Shot_2021-01-14_at_16 29 08" src="https://user-images.githubusercontent.com/688326/105137423-9b7db300-5b36-11eb-9b37-0f6f71312a2f.png">

While LSP does it this way:
<img width="380" alt="Screen_Shot_2021-01-14_at_16 28 26" src="https://user-images.githubusercontent.com/688326/105137474-b3553700-5b36-11eb-9cb2-5555ea55dec7.png">

Other plugins that integrate with sublimes autocomplete, for example sublime-go and snippet related extensions render it on the right as well, so when these results are combined with LSP results, it gets very confusing on where to look because LSP puts it at the bottom:
<img width="661" alt="Screen_Shot_2021-01-14_at_16 32 28" src="https://user-images.githubusercontent.com/688326/105137531-ca942480-5b36-11eb-907d-2ba0d306085f.png">

Because it's all a bit over the place, the results from LSP feel like they aren't actually relevant and just some random word completions, because on first glance they lack type information if you don't know where to look. 

It would be nice if the location where this is displayed is settable from withing sublime-LSP settings. 

I'm happy to help with adding support of this if it can get considered if you have any pointers which parts to touch :)

**Comment by rchl** [comment]
We should even consider changing the default.

We'd just need to check various servers to see if this gives any unexpected results.

**Comment by rwols** [comment]
All you would have to do is play around with the st_details and st_annotation variables here:

https://github.com/sublimelsp/LSP/blob/6c2521ba17c2ae57d3dc84233b2cfeed0a42f71e/plugin/core/views.py#L667-L679

**Comment by dvcrn** [comment]
Thanks for the pointer. I put `lsp_detail` into the annotation and it's working perfectly for what I wanted:

<img width="801" alt="Screen Shot 2021-01-22 at 15 32 11" src="https://user-images.githubusercontent.com/688326/105455545-04943080-5cc7-11eb-818e-8897410c576a.png">

**Comment by rwols** [comment]
So will you make a pull request?

**Comment by dvcrn** [comment]
I can do that! I thought it was still under consideration if this project wants to change the default

**Comment by rwols** [comment]
> I thought it was still under consideration if this project wants to change the default

Let's just see what you got in a pull request so we can all discuss it :)

**Comment by dvcrn** [comment]
Created a PR over at https://github.com/sublimelsp/LSP/pull/1569. It's literally just a one-line change though 😅
