### ISSUE TITLE
Option to disable code actions

### ISSUE THREAD

**Issue by mitranim** [sublimelsp/LSP#1554]
Currently code actions can be shown as bulbs or annotations, but there doesn't seem to be a way to completely disable them. Would be nice to get such an option.

I wrote a very simple patch that prevents them from rendering when `"show_code_actions"` is not set to a known value (currently it falls back on `'annotation'` instead). But ended up not submitting it because ideally we shouldn't even calculate the code actions when they should be disabled. Unfortunately, tracking down every code path that invokes code actions has proven too much. Requesting support. 🙂

**Comment by predragnikolic** [comment]
@mitranim you can now dissable code actions with `"disabled_capabilities": ["codeActionProvider"]`  - https://sublimelsp.github.io/LSP/features/#package-settings-lsp

**Comment by rwols** [comment]
We could differentiate more between disabling explicitly requested code actions (lsp_code_actions), or implicit code actions (via selection changes) and code-actions-on-save, but I think for now this should be sufficient.

**Comment by mitranim** [comment]
Very nice, thanks!
