### ISSUE TITLE
[regression] lsp_execute does nothing due to empty session

### ISSUE THREAD

**Issue by ayoub-benali** [sublimelsp/LSP#1556]
Since this [commit](https://github.com/sublimelsp/LSP/commit/7d05794fa3cc4ecd3931d09a90e801addc70d9fa) the `capability` variable got deleted which means that `self.best_session(self.capability)` is unable to find session.

The consequence is that [LSP-metals.sublime-commands](https://github.com/scalameta/metals-sublime/blob/master/LSP-metals.sublime-commands) aren't executed.

**Comment by rwols** [comment]
The `capability` was removed because there are servers that are not an `executeCommandProvider`, yet still send commands for their code actions/lenses (such as rust-analyzer). I think we should instead go the route of explicitly stating which language server we want.

**Comment by ayoub-benali** [comment]
> I think we should instead go the route of explicitly stating which language server we want.

You mean that LSP-metals package should set the `session_name` argument ?

**Comment by rwols** [comment]
Yeah. Except then it won't work with ST3 :) fun stuff. But I think I have something for that.

**Comment by rwols** [comment]
This should be fully resolved by https://github.com/scalameta/metals-sublime/pull/35
