### ISSUE TITLE
The code action is not displayed properly

### ISSUE THREAD

**Issue by husanjun** [sublimelsp/LSP#1562]
**Describe the bug**
`code action` on the right is not displayed properly

**Screenshots**
![image](https://user-images.githubusercontent.com/49985266/106103227-909cd100-617b-11eb-80c3-807f4e79a234.png)
![image](https://user-images.githubusercontent.com/49985266/106103271-a4e0ce00-617b-11eb-8c6e-3f39aeecaab9.png)

**Environment (please complete the following information):**
- OS: win7
- Sublime Text version: 4095
- LSP version: 1.2.8
- Language servers used: intelephense

**Comment by rchl** [comment]
This looks like a bug that belongs to ST bug tracker rather.
You should report it at https://github.com/sublimehq/sublime_text with extra information like the ST settings that you have overridden (font, line-height and stuff that might be related).

**Comment by husanjun** [comment]
Hi @rchl ,
I'm not sure if it is `sublime` problem, but I submitted a PR that can solve this problem
#1663

**Comment by husanjun** [comment]
It's a theme problem, Thanks @rchl @rwols @jwortmann
