### ISSUE TITLE
Getting error "list index out of range" when no command is defined

### ISSUE THREAD

**Issue by azizk** [sublimelsp/LSP#1564]
**Describe the bug**
LSP shows a cryptic error message when you want to use elixir-ls but the package settings don't define a default command similar to other clients. When you install ElixirLS on Manjaro the executable is named `elixir-ls`.

**To Reproduce**
1. In the User LSP.sublime-settings file choose a client you have installed.
2. Set command to an empty array e.g.:
```json
{
  "clients": {
    "elixir-ls": {
      "command": [],
      "enabled": true
    }
  }
}
```

**Expected behavior**
I would expect a hint that the command is empty/missing and needs to be configured before LSP tries to call it.

**Screenshots**
A dialog window pops up with the following error message:
```
Could not start elixir-ls
list index out of range
Server will be disabled for this window
```

**Environment (please complete the following information):**
- OS: Linux Manjaro
- Sublime Text version: 4096
- LSP version: 1.2.9
- Language servers used: only elixir-ls

**Additional context**
The error originally stems from `subprocess.Popen()` which expects args to be a non-empty array. The `Popen` function is called from `def _start_subprocess` in `"transports.py:260"`.

The error message comes from `"/plugin/core/windows.py:344"`.

**Comment by ayoub-benali** [comment]
I get the same error by just editing and saving `LSP-metals` settings
