### ISSUE TITLE
Could not start javascript-typescript-langserver

### ISSUE THREAD

**Issue by huyhoang8398** [sublimelsp/LSP#1565]
**Describe the bug**

**To Reproduce**
- Enable javascript-typescript global in LSP sublime text
- Install theia from npm  

**Environment (please complete the following information):**
- OS: Archlinux 
- Sublime Text version: Sublime Text Build 3211
- Language servers used: typescript-language-server

**Comment by predragnikolic** [comment]
I would suggest you to undo what you did by running `LSP disable language server globally` and select `"javascript-typescript".

Than just install the LSP-typescript plugin from Package Control, see the [readme](https://packagecontrol.io/packages/LSP-typescript) for the installation instructions.

I will close this, 
but if you have any problems, feel free to reopen it.

**Comment by huyhoang8398** [comment]
thank @predragnikolic , it works for me
