### ISSUE TITLE
Make header font-size same as text in popups

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1566]
I do not find it very useful for the header text to be this big in popups. Just being bold makes them stand out just enough.

![image](https://user-images.githubusercontent.com/22029477/106670369-3ea9e000-65ad-11eb-926c-e788ebe63272.png)

**Describe the solution you'd like**
Reduce the font size of h1, h2, h3, h4, h5, h6 elements to be the same as the rest of the text.

**Comment by rchl** [comment]
I would think that uses the same size for all of them could make the content harder to read in case it's structured with multiple different heading levels.
