### ISSUE TITLE
Look into detailedLabelSupport

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1570]
**Is your feature request related to a problem? Please describe.**
The upcoming 3.17 spec allows servers to provide a more detailed completion label:

```typescript
export interface CompletionItemLabel {
	/**
	 * The name of a function or variable.
	 */
	name: string;

	/**
	 * The parameters without the return type.
	 */
	parameters?: string;

	/**
	 * The fully qualified name, like package name or file path.
	 */
	qualifier?: string;

	/**
	 * The return-type of a function or type of a property/variable.
	 */
	type?: string;
}
```

**Describe the solution you'd like**
Because ST4 allows us to use a limited form of minihtml in the `details` slot, it should be possible to render this additional information with some coloring.

**Describe alternatives you've considered**
N/A

**Additional context**
See the upcoming 3.17 spec: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/

**Comment by predragnikolic** [comment]
related https://github.com/microsoft/language-server-protocol/issues/1236#issue-848567478

**Comment by ryuukk** [comment]
it doesn't work as expected, i feel like the implementation is not respecting the goal of the LSP proposal

actual:

![image](https://user-images.githubusercontent.com/44361234/147585153-984f9902-b626-4cf8-a34f-44ae08a48919.png)


expected: (vscode)

![image](https://user-images.githubusercontent.com/44361234/147585217-62356cd6-53b1-4964-afaf-1c25bbad6a4e.png)

**Comment by jfcherng** [comment]
The core problem is that ST has no way to do it. ST simply doesn't have the "middle" part in the following screenshot.
![image](https://user-images.githubusercontent.com/6594915/147589390-9058e127-c8ac-437e-8668-fbd941a2a88c.png)
