### ISSUE TITLE
"Rename…" code action is broken

### ISSUE THREAD

**Issue by NiavlysB** [sublimelsp/LSP#1572]
(v1.1.6) The _Rename_ code action doesn’t work correctly. I wasn’t able to use it in VSCode so I can’t tell whether it comes from the language server of the Sublime extension.

Here is a minimal example:

```elm
module Test exposing (..)

import Html exposing (Html)


view : Html msg
view =
    Html.text body


body : String
body =
    "..."
```

When renaming `body` for instance:

* if the new name has the same length, it seems to work fine
* if the new name is longer (`bodyxyz` in the example below), the last few characters are duplicated:
```elm

view : Html msg
view =
    Html.text bodyxyzxyz


bodyxyzxyz : String
bodyxyzxyz =
    "..."
```
* if the new name is shorter (`a` in this example), well…
```elm
view : Html msg
view =
    Html.text aaString
a    "..."
```

**Comment by rwols** [comment]
This fix will show up in a new release (for ST4).

**Comment by NiavlysB** [comment]
Nice, thank you!
