### ISSUE TITLE
mdpopup popups are rendered tiny

### ISSUE THREAD

**Issue by dmilith** [sublimelsp/LSP#1578]
**Describe the bug**
I use `lsp_hover` function very often with my Rust development. It shows a popup window which has super small max_width and max_height properties. By default (an example "Dispatch" type) it looks like this: http://s.verknowsys.com/80a79f0d3b423fd7a7fdd335e15b9a4a.png

I altered User/mdpopups.css to decrease default font sizes, but I can't alter the width or height of the popup window.

Workaround:

edit `Packages/mdpopups/st3/mdpopups/__init__.py` file on line 610, and change "max_width=320, max_height=240," to some bigger numbers. I did "max_width=2160, max_height=2160,", but after ST4 restart I still have the width limited. Looks like this: http://s.verknowsys.com/4de808d955af370e9da630125f7c1295.png
It's better, but still width is not 2160 max.

**To Reproduce**
1. Latest ST4 build (b4098)
2. Use Rust Enhanced with rust-analyzer
3. Hover mouse on fern Dispatch type (or any well documented type?)
4. See small popup

**Expected behavior**
Popup should get as large as screen or at least as large as ST4 workspace/ canvas.

**Screenshots**
Yes, above.

**Environment (please complete the following information):**
- OS: macOS 11.2.1
- Sublime Text version: [build 4098]
- LSP version: 1.2.10 (latest)
- Language servers used: rust-analyzer (last non-nightly build available)

**Additional context**
None

**Comment by rchl** [comment]
In screenshot pixels, the popup width is 800px which is what we've set but I'm assuming that on your actual screen everything looks half that size in which case the width would look like 400px basically.

Not sure if there is any smart way to handle that. Either in LSP or ST itself...

**Comment by rchl** [comment]
Of course, we can just make max-width unlimited and it will extend to the whole window size but that could a little weird on really big screens.

**Comment by rchl** [comment]
Looked that those screenshots again and it looks like 800px is 800px. It just looks small due to the overall high resolution of your screen and the code blocks using a really big font size. So since it's related to user settings, I guess the only option here is to allow very wide popups by default or provide an option to be able to customize it.

**Comment by rchl** [comment]
> I did "max_width=2160, max_height=2160,", but after ST4 restart I still have the width limited.

It looks like your override is not really working. Changing the default value of the argument won't help if the value is passed from the called (like LSP does). You'd need to override it in the function body instead.

**Comment by dmilith** [comment]
@rchl Yes, I know that override isn't working. 2160px is ~half of my screen while 1/3 of the screen is ST4 window.
