### ISSUE TITLE
A python exception raised when enable LSP.

### ISSUE THREAD

**Issue by cmsxbc** [sublimelsp/LSP#1599]
**Describe the bug**

**To Reproduce**
Just enable LSP in Project.

**Expected behavior**
No exception.

**Screenshots**

```
Traceback (most recent call last):
  File "/home/<myname>/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/configuration.py", line 47, in _on_done
  File "/home/<myname>/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 369, in enable_config
  File "/home/<myname>/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 365, in update_configs
  File "/home/<myname>/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 109, in update
  File "/home/<myname>/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 127, in _create_window_configs
AttributeError: 'str' object has no attribute 'get'
```

**Environment (please complete the following information):**
- OS:  Arch Linux (kernel 5.10.13)
- Sublime Text version: 3.2.2 (Build 3211)
- LSP version: 0.14.3
- Language servers used: rust-analyzer

**Additional context**
Add any other context about the problem here. For example, whether you're using a helper
package or your manual server configuration in LSP.sublime-settings. When using
a manual server configuration please include it here if you believe it's applicable.

**Comment by rwols** [comment]
> When using
a manual server configuration please include it here if you believe it's applicable.

What does your Packages/User/LSP.sublime-settings look like?

**Comment by cmsxbc** [comment]
> > When using a manual server configuration please include it here if you believe it's applicable.
> 
> What does your Packages/User/LSP.sublime-settings look like?

It seems be a long time ago configuration....

```
// Settings in here override those in "LSP/LSP.sublime-settings"
{
    "clients": {
        "haskell-ide-engine": {
            "command": ["hie-8.8.3", "--lsp"],
            "scopes": ["source.haskell"],
            "syntaxes": ["Packages/Haskell/Haskell.sublime-syntax"],
            "languageId": "haskell",
        },
    },
    "log_debug": false,
    "log_stderr": true,
}
```

**Comment by rwols** [comment]
Please click on View > Show Console. What is the output of:

```
window.project_data()
```

Alternatively, if you're backed by a .sublime-project file, what does that look like?

**Comment by cmsxbc** [comment]
> Please click on View > Show Console. What is the output of:
> 
> ```
> window.project_data()
> ```
> 
> Alternatively, if you're backed by a .sublime-project file, what does that look like?


```
>>> window.project_data()
{'folders': [{'path': '/home/lane/Code/rust'}], 'settings': {'LSP': {'rust-analyzer': {'enabled': True}}}}
```

**Comment by cmsxbc** [comment]
> Please click on View > Show Console. What is the output of:
> 
> ```
> window.project_data()
> ```
> 
> Alternatively, if you're backed by a .sublime-project file, what does that look like?

And I'm bot backed by a .sublime-project file. 
A try of enable globally just works fine.

**Comment by rwols** [comment]
Something in the statement

```
(self._window.project_data() or {}).get("settings", {}).get("LSP", {})
```

seems to be a string for some reason. I'm not sure how that can happen.

You can try running it yourself in the console:

```
(window.project_data() or {}).get("settings", {}).get("LSP", {})
```

**Comment by cmsxbc** [comment]
I have a try to debug it, just print the type and value of `self._window.project_data()`

It's my modification
```Python
# plugin/core/configurations.py, Line 126:
    def _create_window_configs(self) -> List[ClientConfig]: 
        data = self._window.project_data()
        print(type(data))
        print(data)
        try:
            project_clients_dict = (data or {}).get("settings", {}).get("LSP", {})
        except AttributeError:
            print('exp:', data)
            raise
        return [self._apply_project_overrides(c, project_clients_dict) for c in self._global_configs]
```
 And this is the output.
```
<class 'dict'>
{'folders': [{'path': '/home/<myname>/Code/rust'}]}
<class 'str'>
Packages/Rust Enhanced/RustEnhanced.sublime-syntax
exp: Packages/Rust Enhanced/RustEnhanced.sublime-syntax
Traceback (most recent call last):
  File "/home/<myname>/.config/sublime-text-3/Packages/LSP/plugin/configuration.py", line 47, in _on_done
    wm.enable_config(config_name)
  File "/home/<myname>/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 369, in enable_config
    self.update_configs()
  File "/home/<myname>/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 365, in update_configs
    self._configs.update()
  File "/home/<myname>/.config/sublime-text-3/Packages/LSP/plugin/core/configurations.py", line 109, in update
    self.all = self._create_window_configs()
  File "/home/<myname>/.config/sublime-text-3/Packages/LSP/plugin/core/configurations.py", line 131, in _create_window_configs
    project_clients_dict = (data or {}).get("settings", {}).get("LSP", {})
AttributeError: 'str' object has no attribute 'get'
```

**Comment by rwols** [comment]
```
<class 'str'>
Packages/Rust Enhanced/RustEnhanced.sublime-syntax
```

It's a mystery for me at this point  ¯\\\_(ツ)\_/¯

**Comment by cmsxbc** [comment]
Maybe just a bug of sublime_api itself. (I had a try of uninstalling "Rust Enhanced"  and the problem live still)

**Comment by rwols** [comment]
As it turns out, this is a bug in ST, and is still present in ST4: https://github.com/sublimelsp/LSP/issues/1632
