### ISSUE TITLE
Goto Definition support for ES modules that use a HTTP URI scheme

### ISSUE THREAD

**Issue by stexxart** [sublimelsp/LSP#1605]
**Is your feature request related to a problem? Please describe.**
At the moment, _Goto Definition_ does not work for remote ES modules that use the HTTP URI scheme. Deno projects import libraries directly from URLs and browser JavaScript projects have supported this for a long while. The current behaviour of _Goto Definition_ shows an empty file.

**Describe the solution you'd like**
When wanting to go to the definition of a module I'd like to be able to view it's source directly in Sublime. It was suggested the file contents could be fetched and stored in a scratch buffer. It should also continue to work if import maps are being used.

**Describe alternatives you've considered**
VSCode can already do this. Specifically, the VSCode Deno extension supports this out of the box.

**Additional context**
Note, importing modules via HTTP isn't new but is being reborn with the advent of specialised globally-distributed high-performance CDNs like https://www.skypack.dev. With the improved support for ES modules in browsers, the rise of faster front-end build tools-Snowpack, and the need for predictable dependency management, developers will continue to investigate and use this approach to dependency management.

**Comment by rwols** [comment]
> It should also continue to work if import maps are being used.

Does this mean the reported uri to the language server when opening the document should also have an http scheme? If we open it as a scratch buffer then we can't rely on `view.file_name()` anymore as being the "canonical" uri. Moreover currently we don't attach to views without a file name. Lots of challenges here.

**Comment by rwols** [comment]
I'm trying this out locally now and what you claim isn't actually true. The scheme is not `http://` but `deno:/`.

```
:: --> Deno textDocument/implementation(4): {'position': {'character': 12, 'line': 0}, 'textDocument': {'uri': 'file:///Users/raoulwols/dev/denoserver/server.ts'}, 'workDoneToken': 'wd4'}
:: <<< Deno 4: [{'targetUri': 'deno:/https/deno.land/std/http/server.ts', 'targetRange': {'end': {'character': 1, 'line': 305}, 'start': {'character': 0, 'line': 298}}, 'targetSelectionRange': {'end': {'character': 21, 'line': 298}, 'start': {'character': 16, 'line': 298}}}]
```

So both server and client have IMO bugs.

1. Server should report proper `http://` or `https://` uris
2. Client should be able to open those uris

I'll be focussing on just http(s) schemes, not `deno:/` schemes.

**Comment by rwols** [comment]
I'm looking into this a bit more and it's a custom protocol extension to show these kinds of documents. So vscode-specific client glue.

https://github.com/denoland/vscode_deno/blob/34b7130f3b810a635f88dd88e5927f3faaa1bffa/client/src/lsp_extensions.ts

I guess the idea is to ask a plugin for the content of `deno:/https/deno.land/std/http/server.ts`. Such a plugin would then have to request `deno/virtualTextDocument`.

So you need an LSP-Deno helper package.

**Comment by rwols** [comment]
I have something working here :)

https://user-images.githubusercontent.com/2431823/110857246-e7d4ac00-82b8-11eb-9af7-8dfc90b64322.mov

**Comment by hronro** [comment]
@rwols Great. Can I expect we will have `deno lsp` integration in `sublimelsp` soon?

**Comment by rwols** [comment]
It’s done when it’s done.

**Comment by rwols** [comment]
A helper package called LSP-Deno will appear on packagecontrol.io soon. This will allow you to goto-def on remote files and find-references on remote files (only when using the quick panel variant presentation).

However LSP will not attach the language server to such remote files. I will close this issue and create new ones to make us focus more on the remaining issues.

**Comment by rwols** [comment]
#1739
