### ISSUE TITLE
Minimize popups jumping above and below the line while typing every letter

### ISSUE THREAD

**Issue by ernestoalejo** [sublimelsp/LSP#1608]
**Describe the bug**
While I'm writing code LSP popups jump around with every keystroke making it difficult to focus on their contents.

**To Reproduce**
Write things while having enough symbols on the project for the popups to jump around. I was typing letter after letter and the screenshots below will demonstrate the jumps after typing a single "C" letter for example (02 -> 03)

**Expected behavior**
Take a side below or above the line and keep it until the user is done to avoid jumps. Reproducing the default sublime autocomplete behaviour would be fine in this scenario.

**Screenshots**

With LSP:
| 01 | 02 | 03 |
| -- | -- | -- |
| ![01](https://user-images.githubusercontent.com/961966/110226266-1edc4380-7eee-11eb-9fd0-7b495773787f.png) | ![02](https://user-images.githubusercontent.com/961966/110226267-1f74da00-7eee-11eb-837a-ad88ac5e59a8.png) | ![03](https://user-images.githubusercontent.com/961966/110226268-1f74da00-7eee-11eb-8f42-e5117ab86d9d.png) |

After disabling the LSP server:
| 01 | 02 | 03 |
| -- | -- | -- |
| ![01](https://user-images.githubusercontent.com/961966/110226286-31ef1380-7eee-11eb-88d0-dffe10d5b28b.png) | ![02](https://user-images.githubusercontent.com/961966/110226287-3287aa00-7eee-11eb-8669-a3e6fda1d1a9.png) | ![03](https://user-images.githubusercontent.com/961966/110226288-3287aa00-7eee-11eb-9e75-a35cc5e50f2f.png) |

**Environment (please complete the following information):**
- OS: Ubuntu 20.10
- Sublime Text version: 4098 (latest right now)
- LSP version: v1.2.12
- Language servers used: gopls is the only one configured

**Additional context**
<details><summary>My full configuration for reference:</summary>
<p>

```json
{
	"clients":
	{
		"gopls":
		{
			"enabled": false,
			"env":
			{
				"GOPATH": "/home/ernesto/go",
				"PATH": "/home/ernesto/go/bin:/usr/local/go/bin",
			},
			"settings":
			{
				"completeUnimported": true,
				"fuzzyMatching": false,
			},
		},
	},
  "show_diagnostics_count_in_view_status": true,
  "auto_show_diagnostics_panel": "never",
  "inhibit_snippet_completions": true,
  "document_highlight_style": "",
}
```

</p>
</details>

**Comment by rchl** [comment]
LSP doesn't have control over that.

I believe the reason why this problem triggers with this language server is that due to this server returning completions with `isIncomplete` flag set to true which then makes LSP use the `sublime.DYNAMIC_COMPLETIONS` flag which results in ST basically re-requesting completions on each character.

Many servers (and also built-in completions) don't trigger the `sublime.DYNAMIC_COMPLETIONS` flag.

I think this should be reported in https://github.com/sublimehq/sublime_text/issues instead.
But ideally, a simple test case would be added to the report as otherwise devs might not be bothered to set up everything just right to analyze the issue.

**Comment by rchl** [comment]
For example:

```py
import random
import sublime
import sublime_plugin


class CompletionListener(sublime_plugin.ViewEventListener):
    def on_query_completions(self, prefix, locations):
        print('on_query_completions')
        completion_list = sublime.CompletionList()

        completions = []
        for i in range(1, random.randint(1, 10)):
            completions.append(sublime.CompletionItem(trigger='a' * (i + 10), kind=(sublime.KIND_ID_FUNCTION, "m", "Method")))

        flags = 0
        flags |= sublime.INHIBIT_WORD_COMPLETIONS
        flags |= sublime.INHIBIT_EXPLICIT_COMPLETIONS
        flags |= sublime.INHIBIT_REORDER
        flags |= sublime.DYNAMIC_COMPLETIONS

        completion_list.set_completions(completions, flags=flags)
        return completion_list
```

https://user-images.githubusercontent.com/153197/110252405-80032600-7f85-11eb-8f2f-cbf6758dae5c.mov

**Comment by rwols** [comment]
I have created an issue for it on the ST issue tracker. Please continue the discussion there @ernestoalejo.
