### ISSUE TITLE
Sublime doesn't appear to work with Bicep language server

### ISSUE THREAD

**Issue by MikeChristensen** [sublimelsp/LSP#1621]
**Describe the bug**
Would be great to see support for Bicep, Microsoft's new language for describing Azure infrastructure.  Bicep can be installed [here](https://github.com/Azure/bicep/blob/main/docs/installing.md) and it comes with an LSP implementation.

**To Reproduce**

1. Configure Bicep LSP:

```
{
	"clients":
	{
		"bicep-lsp":
		{
			"command":
			[
				"C:\\Users\\Michael.Christensen\\bicepLanguageServer\\Bicep.LanguageServer.exe"
			],
			"enabled": true,
			"languageId": "bicep",
			"scopes":
			[
				"source.bicep"
			],
			"syntaxes":
			[
				"Packages/JavaScript/JavaScript.sublime-package"
			]
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_stderr": true
}
```

2. Open .bicep file

**Expected behavior**
It should launch the `Bicep.LanguageServer.exe` process and connect.
Result: No process is launched.  Nothing in debug console or logs.

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows 10
- Sublime Text version: 3.2.2 Build 3211
- LSP version: 0.14.3
- Language servers used: Bicep.LanguageServer.exe (Part of VSCode Bicep extension)

**Additional context**
Add any other context about the problem here. For example, whether you're using a helper
package or your manual server configuration in LSP.sublime-settings. When using
a manual server configuration please include it here if you believe it's applicable.

**Comment by jfcherng** [comment]
At my first glance,
```
				"Packages/JavaScript/JavaScript.sublime-package"
```
should be
```
				"Packages/JavaScript/JavaScript.sublime-syntax"
```

**Comment by MikeChristensen** [comment]
Made the first change.  I'm curious, do I need to create a syntax for this language first before I can use the LSP server?  I'm hoping I can just get it working first, then define the syntax (there might already be a .tmLanguage file for it somewhere)..

**Comment by MikeChristensen** [comment]
[bicepLanguageServer.zip](https://github.com/sublimelsp/LSP/files/6186745/bicepLanguageServer.zip)

Attaching the LSP server in case anyone wants to try to get it working.  It's a .NET 5 app..

**Comment by jfcherng** [comment]
> Made the first change. I'm curious, do I need to create a syntax for this language first before I can use the LSP server?

No.

---

"syntaxes": The syntax file which wants to use this server
"scopes": Basically the top scope of the syntax(es) above

When both conditions meet, the server will be activate. (but you use two contradictory conditions so it won't start anyway)

I would suggest 
```
			"scopes":
			[
				"source.js"
			],
			"syntaxes":
			[
				"Packages/JavaScript/JavaScript.sublime-package"
			]
```

**Comment by MikeChristensen** [comment]
Tried that and no go as well.  Is there a way to see errors or anything?  I'm guessing I should be able to see the `Bicep.LanguageServer.exe` process running on the machine as well.

Also, note this LSP communicates via stdin and stdout (rather than TCP or anything).  Is that supported?

**Comment by jfcherng** [comment]
> Tried that and no go as well. Is there a way to see errors or anything?

Haven't used ST3 for a long time. In ST4, right click on the bottom-left button and there will be a `Output: ...` for LSP.
![image](https://user-images.githubusercontent.com/6594915/112091177-dc925200-8bcf-11eb-8489-e0474d6a981e.png)



> Also, note this LSP communicates via stdin and stdout (rather than TCP or anything). Is that supported?

It's the default behavior.

**Comment by MikeChristensen** [comment]
I'm not really aware of the difference between ST3 and ST4.  I was just reading from the documentation, but maybe I was looking at old stuff.  I'd be fine trying another approach using ST4.

I got the "Output: Language services" panel to show up, but it's empty..

**Comment by MikeChristensen** [comment]
Oh, if ST4 means "Sublime Text 4", I wasn't able to figure out where to get it.  According to all docs I could find (including Wikipedia), v3 is the latest version.

**Comment by jfcherng** [comment]
> Oh, if ST4 means "Sublime Text 4", I wasn't able to figure out where to get it. According to all docs I could find (including Wikipedia), v3 is the latest version.

If you have a valid ST3 license, ST4 is currently private alpha in the official Discord chat server: https://discord.gg/HcmwdVK
But ST4 wouldn't be necessary to use that language server.

---

Hmm... I actually can start that language server (don't know what it can do though).
```
:: --> lsp-bicep initialize(1): {'clientInfo': {'version': 'xxx', 'name': 'yyy'}, 'rootPath': 'E:\\_Data\\_Test', 'capabilities': {'textDocument': {'codeAction': {'dataSupport': True, 'dynamicRegistration': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': ['quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source.organizeImports']}}, 'resolveSupport': {'properties': ['edit']}}, 'signatureHelp': {'dynamicRegistration': True, 'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'rename': {'prepareSupport': True, 'dynamicRegistration': True}, 'synchronization': {'willSaveWaitUntil': True, 'dynamicRegistration': True, 'willSave': True, 'didSave': True}, 'formatting': {'dynamicRegistration': True}, 'hover': {'dynamicRegistration': True, 'contentFormat': ['markdown', 'plaintext']}, 'documentHighlight': {'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'codeLens': {'dynamicRegistration': True}, 'completion': {'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'dynamicRegistration': True, 'completionItem': {'snippetSupport': True, 'deprecatedSupport': True, 'documentationFormat': ['markdown', 'plaintext'], 'tagSupport': {'valueSet': [1]}}}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'dynamicRegistration': True, 'hierarchicalDocumentSymbolSupport': True, 'tagSupport': {'valueSet': [1]}}, 'selectionRange': {'dynamicRegistration': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'publishDiagnostics': {'relatedInformation': True, 'dataSupport': True, 'codeDescriptionSupport': True, 'tagSupport': {'valueSet': [1, 2]}, 'versionSupport': True}, 'colorProvider': {'dynamicRegistration': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}}, 'workspace': {'executeCommand': {}, 'applyEdit': True, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'dynamicRegistration': True, 'tagSupport': {'valueSet': [1]}}, 'configuration': True, 'workspaceEdit': {'documentChanges': True, 'failureHandling': 'abort'}, 'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceFolders': True}, 'window': {'workDoneProgress': True, 'showDocument': {'support': True}, 'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}}, 'general': {'regularExpressions': {'engine': 'ECMAScript'}, 'markdown': {'parser': 'Python-Markdown', 'version': '3.2.2'}}}, 'initializationOptions': {}, 'rootUri': 'file:///E:/_Data/_Test', 'workspaceFolders': [{'uri': 'file:///E:/_Data/_Test', 'name': '_Test'}], 'processId': 13240}
:: <<< lsp-bicep 1: {'capabilities': {'experimental': {}, 'workspace': {'workspaceFolders': {'changeNotifications': 'a64a4e3d-c0a6-4448-ad54-7dad4a854de2', 'supported': True}}, 'textDocumentSync': {'change': {'syncKind': 0}, 'didOpen': {}, 'save': {}, 'didClose': {}}, 'semanticTokensProvider': {'workDoneProgress': False, 'id': None, 'legend': {'tokenTypes': ['comment', 'keyword', 'string', 'number', 'regexp', 'operator', 'namespace', 'type', 'struct', 'class', 'interface', 'enum', 'typeParameter', 'function', 'member', 'property', 'macro', 'variable', 'parameter', 'label', 'modifier', 'event', 'enumMember'], 'tokenModifiers': ['documentation', 'declaration', 'definition', 'static', 'async', 'abstract', 'deprecated', 'readonly', 'modification', 'defaultLibrary']}, 'full': {'delta': True}, 'range': True}}, 'serverInfo': {'version': '0.3.126+a5e4c2e567', 'name': 'Bicep.LangServer'}}
::  -> lsp-bicep initialized: {}
::  -> lsp-bicep textDocument/didOpen: {'textDocument': {'uri': 'file:///E:/_Data/_Test/a.js', 'version': 0, 'text': '// myVar evaluates to "hello!"\nvar myVar = \'hello!\'\n\n// myVar evaluates to "what\'s up?"\nvar myVar2 = \'what\\\'s up?\'\n\n// myVar evaluates to "hello steve!"\nvar name = \'steve\'\nvar myVar3 = \'hello ${name}!\'\n', 'languageId': 'javascript'}}
:: <-- lsp-bicep client/registerCapability(1): {'registrations': [{'id': '5416a3e8-0496-4888-aa39-0f10721880ec', 'registerOptions': {'documentSelector': [{'language': 'bicep'}], 'includeText': True}, 'method': 'textDocument/didSave'}, {'id': 'e53711f0-4096-4524-904c-7e07a1f6fda3', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/documentHighlight'}, {'id': '226e29b2-a192-4ca0-860b-76919fc5e34f', 'registerOptions': {'syncKind': 1, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/didChange'}, {'id': 'bf301e5b-ebc9-43a8-93d7-60c0fb7d33fe', 'registerOptions': {'workDoneProgress': True, 'triggerCharacters': ['(', ',', ')'], 'documentSelector': [{'language': 'bicep'}], 'retriggerCharacters': []}, 'method': 'textDocument/signatureHelp'}, {'id': 'feb4e553-003e-4389-b0dc-3cace16c995b', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/hover'}, {'id': 'b2acb6bc-bdfb-4a58-bd69-bb0b36cbdf11', 'registerOptions': {'resolveProvider': True, 'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}], 'codeActionKinds': ['quickfix']}, 'method': 'textDocument/codeAction'}, {'id': '8e8a15b7-bed9-4e95-ace6-1b66df2e3e19', 'registerOptions': {'resolveProvider': True, 'triggerCharacters': [':', ' ', '.', '/', "'", '@'], 'documentSelector': [{'language': 'bicep'}], 'workDoneProgress': True, 'allCommitCharacters': []}, 'method': 'textDocument/completion'}, {'id': 'f3b163e9-0d09-4a18-99c6-004107a1d463', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/formatting'}, {'id': 'f96ca298-0c3c-4817-8624-a1eafc169765', 'registerOptions': {'documentSelector': [{'language': 'bicep'}], 'includeText': True}, 'method': 'textDocument/didClose'}, {'id': 'a3f92887-bdfc-488d-b066-aaebced2ba49', 'method': 'workspace/didChangeConfiguration'}, {'id': '152c10cd-8907-4496-a871-4a089795b024', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}], 'prepareProvider': False}, 'method': 'textDocument/rename'}, {'id': '947d54f2-d58f-4c7e-907c-5011e6968db5', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/definition'}, {'id': '50fcb185-396b-4610-9d1e-311d8ee7533c', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/references'}, {'id': 'b1158032-1d73-4548-a81d-a0df53a1da3b', 'registerOptions': {'workDoneProgress': True, 'documentSelector': [{'language': 'bicep'}]}, 'method': 'textDocument/documentSymbol'}, {'id': '85282d37-2bbe-40be-95fa-9aabfc0f2e7e', 'registerOptions': {'documentSelector': [{'language': 'bicep'}], 'includeText': True}, 'method': 'textDocument/didOpen'}]}
:: >>> lsp-bicep 1: None
:: <-  lsp-bicep textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///e:/_Data/_Test/a.js', 'version': 0}
```

**Comment by MikeChristensen** [comment]
Trying on ST4.  Here's the results of the server test:

```
# Troubleshooting: bicep
## Version
 - LSP: 1.2.12
 - Sublime Text: 4099
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "c:\\Users\\Michael.Christensen\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-dotnettools.vscode-dotnet-runtime\\.dotnet\\5.0.4\\dotnet.exe", 
  "c:\\Users\\Michael.Christensen\\.vscode\\extensions\\ms-azuretools.vscode-bicep-0.3.126\\bicepLanguageServer\\Bicep.LangServer.dll"
]
```
 - shell command
```sh
c:\Users\Michael.Christensen\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\5.0.4\dotnet.exe c:\Users\Michael.Christensen\.vscode\extensions\ms-azuretools.vscode-bicep-0.3.126\bicepLanguageServer\Bicep.LangServer.dll
```
 - selector
```
source.js
```
 - priority_selector
```
(source.js)
```
 - init_options
```json
{}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
C:\Users\Michael.Christensen\OneDrive - Limeade, Inc\Desktop\Test.bicep
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Text/Plain text.tmLanguage"
}
```
 - base scope
```
text.plain
```

## Project / Workspace
 - folders
```json
[]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "bicep": {
      "command": [
        "c:\\Users\\Michael.Christensen\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-dotnettools.vscode-dotnet-runtime\\.dotnet\\5.0.4\\dotnet.exe", 
        "c:\\Users\\Michael.Christensen\\.vscode\\extensions\\ms-azuretools.vscode-bicep-0.3.126\\bicepLanguageServer\\Bicep.LangServer.dll"
      ], 
      "enabled": true, 
      "languageId": "bicep", 
      "scopes": [
        "source.js"
      ], 
      "syntaxes": [
        "Packages/JavaScript/JavaScript.sublime-syntax"
      ]
    }
  }, 
  "log_debug": true, 
  "log_stderr": true, 
  "show_diagnostics_count_in_view_status": true
}
```
## System PATH
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\System32\OpenSSH\
 - C:\Program Files\WindowsPowerShell\Scripts
 - C:\ProgramData\chocolatey\bin
 - C:\Program Files\Git\cmd
 - C:\Program Files\dotnet\
 - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
 - C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
 - C:\ProgramData\chocolatey\lib\gsudo\bin\
 - C:\Program Files\Docker\Docker\resources\bin
 - C:\ProgramData\DockerDesktop\version-bin
 - C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
 - C:\Program Files\Azure Data Studio\bin
 - C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin
 - C:\Program Files\nodejs\
 - C:\Program Files\Microsoft\Web Platform Installer\
 - C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code
 - C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
 - C:\Users\Michael.Christensen\AppData\Local\Microsoft\WindowsApps
 - C:\Users\Michael.Christensen\.dotnet\tools
 - C:\Program Files\JetBrains\JetBrains Rider 2020.3.4\bin
 - 
 - C:\Program Files\Azure Data Studio\bin
 - C:\Users\Michael.Christensen\AppData\Roaming\npm
 - C:\Users\Michael.Christensen\AppData\Local\Programs\Microsoft VS Code\bin
```

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/112095257-2599d480-8bd7-11eb-934d-6ea147f8a95a.png)

So you are not using Javascript to highlight a bicep file.

**Comment by MikeChristensen** [comment]
Yea, I noticed that too...  No idea how to change it though..  Maybe there's some syntax that's different in ST4.

Basically, the goal is to get .bicep files to use the configured LSP server, but use the Javascript syntax (until I can create a syntax for it later on)..  Or, if there's no syntax (just plain text) for now, that's fine too - I just want to see the errors and perhaps get auto-complete.

**Comment by jfcherng** [comment]
In ST4, you can create syntax by inheriting an existing language like

### Bicep.sublime-syntax

```yaml
%YAML 1.2
---
version: 2
file_extensions:
  - bicep
scope: source.bicep
extends: Packages/JavaScript/JavaScript.sublime-syntax
```

So it would identical to javascript except the base `scope` (and `file_extensions`).

---

With the following lsp config, it seems working.

```js
        "bicep-ls": {
            "enabled": true,
            "command": [
                "D:\\_Download\\bicepLanguageServer\\Bicep.LangServer.exe",
            ],
            "languegeId": "bicep",
            "selector": "source.bicep",
        },
```

**Comment by MikeChristensen** [comment]
Cool!  I got it working!  Here's my final settings:

```
{
	"show_diagnostics_count_in_view_status": true,
	"log_debug": true,
	"log_stderr": true,
	"clients":
	{
		"bicep":
		{
			"command":
			[
				"C:\\Users\\Michael.Christensen\\bicepLanguageServer\\Bicep.LangServer.exe"
			],
			"enabled": true,
			"languegeId": "bicep",
			"selector":	"source.bicep"
		},
	},
}
```

I'll see if I can back port it to ST3 as well.  I guess the next step is to create a syntax for it.  Luckily it's a fairly simple language.

**Comment by rwols** [comment]
It sounds like the first order of business would be to establish a Bicep language syntax in the .sublime-syntax format. After this has been done, you can easily start this Bicep language server for this .sublime-syntax.

**Comment by MikeChristensen** [comment]
Yea, there's already someone [working on a TextMate version](https://github.com/Azure/bicep/pull/2069/files) so might be easier to start with that.  I was only able to get the language server working with Sublime 4, not with 3.  I don't know if it's an issue with Sublime or the language server, and I wasn't able to find any more time to look at it further.

**Comment by rwols** [comment]
The current .tmLanguage file doesn't seem to be parseable by ST4: https://raw.githubusercontent.com/Azure/bicep/main/src/textmate/bicep.tmlanguage

I made an effort to create a simple ST4 syntax: https://github.com/rwols/sublime-bicep

Because it uses version 2 of .sublime-syntax it's not compatible with ST3.

Does the string interpolation and has basic goto symbol functionality.
