### ISSUE TITLE
LSP sometimes confuses autocompletion even in unrelated syntaxes

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#1622]
**Describe the bug**

Every here and then I find me surprised by ST's mini_auto_completion to commit different content than it previews. See how it shows `true` and commits `terminator` in the following code snippet.

![Animation](https://user-images.githubusercontent.com/16542113/112184936-ffd4f580-8bff-11eb-80d6-c3cb7fac9242.png)

Why do I report it here? Well, in fact disabling the LSP package fixes the issue.

The strange thing is, the syntax in use not being supported by any language-server on earth. So there's none active.

The question is, how can or does LSP interact with ST's auto-completion in syntaxes which do not use LSP?

The only thing I saw on console was the `commit_completion` command being executed when hitting tab.

**Expected behavior**

The previewe'd completion should be committed.

This is what it looks like with LSP disabled:

![Animation](https://user-images.githubusercontent.com/16542113/112187961-dc5f7a00-8c02-11eb-846b-dbd6fc47ff6d.png)

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows 10 x64 2004
- Sublime Text version: 4099
- LSP version: ST4000-exploration (commit 1bc9cff7f4385637cafdb0ae43ec843367cee19f)
- Language servers used: all disabled for debugging

**Comment by rwols** [comment]
If there's no langserver attached to the view then this is essentially what happens:

```python
from typing import Any, List
import sublime_plugin
import sublime


class Foo(sublime_plugin.ViewEventListener):
    def on_query_completions(self, prefix: str, locations: List[int]) -> Any:
        promise = sublime.CompletionList()
        sublime.set_timeout_async(
            lambda: sublime.set_timeout(
                lambda: promise.set_completions([], 0)
            )
        )
        return promise
```

https://github.com/sublimelsp/LSP/blob/1bc9cff7f4385637cafdb0ae43ec843367cee19f/plugin/documents.py#L388-L396

https://github.com/sublimelsp/LSP/blob/1bc9cff7f4385637cafdb0ae43ec843367cee19f/plugin/documents.py#L641-L645

**Comment by deathaxe** [comment]
Thanks to for pointing to the entry for debugging, but your minimal example is not very correct. The promise is reloved by `promise.set_completions([], INHIBIT_WORD_COMPLETIONS)`, which seems to be the root cause here. replacing `flags` by `0` in line 392 solves the issue.

**Comment by deathaxe** [comment]
`self.sessions` in line 642 returns a generator. So the `if` statement in `643` is never true.

**Comment by rchl** [comment]
I wonder if mini_auto_complete should handle that case better... If completion was removed from the list due to `INHIBIT_WORD_COMPLETIONS` then shouldn't the visible suggestion be updated?

**Comment by rwols** [comment]
> If completion was removed from the list due to INHIBIT_WORD_COMPLETIONS then shouldn't the visible suggestion be updated?

I agree, but we should still fix things in this package

**Comment by deathaxe** [comment]
The strange thing is just that both candidates are word completions.

**Comment by rchl** [comment]
Could be that the list of completions is mutated internally due to some completions "disappearing" which then causes some index point to the wrong item. I'd still report this to ST tracker.

**Comment by predragnikolic** [comment]
This is a ST core issue(I have LSP disabled):
![output](https://user-images.githubusercontent.com/22029477/112729410-3d9d8b00-8f2c-11eb-8e60-d53770376445.gif)
