### ISSUE TITLE
Debug output blocks UI

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP#1626]
**Describe the bug**
When there is a lot of communication the UI may freeze up to a few seconds. This does happen if the output panel is closed too.

**To Reproduce**
1. Enable debugging  options
2. Generate a lot of communication (eg. LaTex build with LSP-TexLab)

**Expected behavior**
UI does not freeze (especially if the debug panel is closed).

**Environment (please complete the following information):**
- OS: Windows 10
- Sublime Text version: 4099
- LSP version: Commit 218c87d

**Additional context**
I am running a really powerful machine, I can image that the situation may be worse on a weaker machine.

**Comment by rchl** [comment]
Would be nice to not update the panel in the background as indeed it's not a very "cheap" thing to do.

And having it not updating automatically would allow us to make the panel always available, without needing to enable the relevant option.

The only difficulty would be to enable the panel updates only when it's open. Not sure what would be the best way to detect that. Maybe `on_window_command` listener checking for `show_panel` command.

**Comment by LDAP** [comment]
The issues when the panel is closed is fixed, but instead I observed that when I am opening the panel after a lot of communication happened the ST process pins one core to 100% for 30 seconds and blocks and then the panel opens.

**Comment by rchl** [comment]
The https://github.com/sublimelsp/LSP/pull/1637 should help with that.
