### ISSUE TITLE
Remove some sections from the README

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1627]
**Is your feature request related to a problem? Please describe.**
I believe that the README has some information that are not that important to the user. 

**Describe the solution you'd like**
1. [Customisation of the popups](https://github.com/sublimelsp/LSP#customisation-of-the-popups), is not the most important feature about LSP, so I would move it to the docs in the guides section. 

![image](https://user-images.githubusercontent.com/22029477/112727682-f3b0a700-8f23-11eb-9540-ee853ef6b689.png)

2. [LSP specification implementation status](https://github.com/sublimelsp/LSP#lsp-specification-implementation-status) is also not that important to a regular user. Would consider moving it either to:
* the wiki page [here](https://github.com/sublimelsp/LSP/wiki#protocol-compatibility) (there is already a section for it), 
* or the docs site (but I don't know where I would put it)

**Comment by rwols** [comment]
> LSP specification implementation status is also not that important to a regular user.

There should be a section in the docs for language server maintainers explaining the peculiarities of this client. For instance, we use Python-Markdown, "document outline" is quite different from VSCode, ST doesn't really understand Language IDs, etc. The overall protocol implementation status can go in there as well.

**Comment by predragnikolic** [comment]
Closed with https://github.com/sublimelsp/LSP/pull/1629

Thanks @jwortmann!
