### ISSUE TITLE
Popup window takes too long to show..

### ISSUE THREAD

**Issue by qazip** [sublimelsp/LSP#1639]
**Describe the bug**
Not sure if this is a bug, but I find LSP to be extremelly slow. I think it used to be faster a few weeks/days? ago, but now it takes forever for the popup to show. I disabled LSP and ST's native popup works extremely fast, so it is not ST's fault, it seems.

Say I have a variable, "abc123" and another one "abc999". If I type "abc", it takes forever to get the popup showing "abc123" and "abc999". By forever I mean like 4 seconds. Is there anything you changed? Is there some variable in the settings I can change to decrease the popup window delay?

Was it always like this?

**Environment (please complete the following information):**
- OS: Arch
- Sublime Text version: 4102
- LSP version: Latest
- Language servers used: pyls

**Comment by rchl** [comment]
It shows the popup as soon as the language server responds (in your case pyls, I guess).

It looks like pyls is just being slow for you. Likely due to a specific setup in your project.
You can log server communication to make sure but it's likely that pyls is just slow to respond to `textDocument/hover` request.

LSP-pyright is generally much faster.

**Comment by qazip** [comment]
Indeed, I installed LSP-pyright and it seems to work as intended.. Weird that pyls is slow. It used to be fast. Anyway, I will close this for now! Thank you rchl!

**Comment by qazip** [comment]
@rchl, sorry to bother again but:

pyright seems to ignore snippets. Could you point in the right direction? If I type "for + tab" very fast (really really fast), the snippet is triggered. If, however, I don't do it fast enough and let pyright "take-over"; I have no snippets showing in the popup. Any idea?

**Comment by rchl** [comment]
For reference, you've created #1640 for that which appears to be a ST issue.
