### ISSUE TITLE
Support for disabling capability at language server level

### ISSUE THREAD

**Issue by kanadkanhere** [sublimelsp/LSP#1649]
From what I can tell, Sublime LSP supports disabling capabilities using the "disabled_capabilities" setting of LSP. But this sets it globally for all language servers. It would be nicer to have a language server specific control for this. I tried adding this setting under "clients": { "mylanguageserver": { "disabled_capabilities": ["hover"] } } and that doesn't work.

Sublime version: 3.2.2

**Comment by rwols** [comment]
This is implemented in the ST4 version.

**Comment by rwols** [comment]
Thank you for thinking about possible enhancements by the way 🙂. But this one is implemented.
