### ISSUE TITLE
Add option to disable `show_code_actions`

### ISSUE THREAD

**Issue by Zapeth** [sublimelsp/LSP#1654]
**Is your feature request related to a problem? Please describe.**
I don't see myself using this feature, and I prefer to keep the amount of information in the interface to a minimum.

**Describe the solution you'd like**
Don't display possible code actions when setting `show_code_actions` to `""` or `false`.

I don't know the internal workings, but it would be even better if the the entire logic to check for code actions would be disabled in this case (to reduce performance cost).

**Comment by rwols** [comment]
What's your environment?

**Comment by rwols** [comment]
In case you're using ST4 and you have a client configuration set up manually in LSP.sublime-settings, this is the way to disable code actions entirely, including requesting them:

```jsonc
// Settings in here override those in "LSP/LSP.sublime-settings"
{
    "clients": {
        "your-language-server-identifier": {
            "disabled_capabilities": {
                // disable code actions for this language server
                "codeActionProvider": true
            },
            "command": [
                "..."
            ],
            "enabled": true,
        }
    },
}
```

**Comment by Zapeth** [comment]
Yes I'm using ST4 with latest LSP and rust-analyzer. Applying the setting to the config worked too, the suggested code actions don't show up anymore in the interface.

Thanks for the quick help

**Comment by rwols** [comment]
Note that an upcoming update will allow you to set `"show_code_actions"` to the empty string, `""`, and this way no automatic code actions will be performed, while you can still request them manually.

**Comment by Zapeth** [comment]
I just updated to the most recent versions of ST4 and LSP (as well as installing LSP-rust-analyzer package), and it seems the original workaround isn't applicable anymore (actions are still being suggested in the interface).

Maybe LSP-rust-analyzer overwrites these settings now? But it doesn't look like the plugin features a `disabled_capabilities` setting, so I would assume this should still be managed by the LSP plugin?

The above mentioned solution with `show_code_actions` works, however it would also be nice to get `disabled_capabilites` working again.

**Comment by rchl** [comment]
You might be talking about code lenses. Can you screenshot the thing that you are seeing?

**Comment by Zapeth** [comment]
![image](https://user-images.githubusercontent.com/11491561/140417453-f26182e6-2418-4aed-84a4-5dbba5e8cf5b.png)

My lsp config in this case is
```json
{
    "log_debug": false,
    "show_diagnostics_panel_on_save": 0,
    "show_diagnostics_severity_level": 4,
    "inhibit_snippet_completions": true,
    "clients": {
        "rust-analyzer": {
            "disabled_capabilities": {
                "codeActionProvider": true
            },
        }
    }
}
```
and lsp-rust-analyzer:
```json
{
    "settings": {
        "rust-analyzer.terminusUsePanel": true,
        "rust-analyzer.checkOnSave.enable": false,
        "rust-analyzer.debug.openDebugPane": true,
    }
}
```

As I said, if I set `"show_code_actions ": ""` they disappear again, so I'm pretty sure they are code action elements. But for some reason the they seemingly can't be disabled anymore with `disabled_capabilities`.

**Comment by rwols** [comment]
If you have LSP-rust-analyzer (the package), then you don't need a manual client configuration in Packages/User/LSP.sublime-settings. So you can remove the `"clients"` object.

To disable capabilities for a client configuration provided through a helper package like LSP-rust-analyzer, you can add it to the settings in Packages/User/LSP-rust-analyzer.sublime-settings

```js
{
    "disabled_capabilities": {
        "codeActionProvider": true
    },
    "settings": {
        "rust-analyzer.terminusUsePanel": true,
        "rust-analyzer.checkOnSave.enable": false,
        "rust-analyzer.debug.openDebugPane": true,
    }
}
```

LSP-rust-analyzer also manages the rust-analyzer binary so you can delete your self-managed rust-analyzer binary.

**Comment by Zapeth** [comment]
Thanks, now it works again.

I was unsure earlier because `disabled_capabilties` isn't listed in the default settings of LSP-rust-analyzer, so I didn't know where it had to be placed in the structure.
