### ISSUE TITLE
Can't unbind LSP keymappings

### ISSUE THREAD

**Issue by Zapeth** [sublimelsp/LSP#1655]
**Describe the bug**
Specifying an already bound lsp command in the keymappings to a different mapping works, but doesn't disable the original binding.

**To Reproduce**
1. Apply a key mapping for an lsp command that is different from the default one, for example `lsp_show_diagnostics_panel`: 
```json
    {
        "command": "lsp_show_diagnostics_panel",
        "keys": [ "primary+shift+m" ],
        "context": [ { "key": "setting.lsp_active" } ]
    },
```
2. Save mapping
3. New mapping (`primary+shift+m`) opens the lsp diagnostics panel
4. Default mapping (`primary+alt+m`) also still opens the lsp diagnostics panel

**Expected behavior**
The original/default mapping shouldn't work anymore when binding the command to different keys (or it should fall back to the original mapping if the lsp command was already overriding a key mapping, like `lsp_save`)

**Environment (please complete the following information):**
- OS: Windows 7 x64
- Sublime Text version: 4102
- LSP version: 1.3.0
- Language servers used: rust-analyzer

**Additional context**
I'd like to restore Sublime's original save command and map `lsp_save` to different keys, so I can choose whether the LSP client should run its analysis on save or not.

In case of rust-analyzer it always runs `cargo --check` on each save, and since I tend to save quite often I'd prefer to only run it selectively. I know I could disable it with the client setting `rust-analyzer.checkOnSave.enable`, but then I'd loose the checking functionality entirely (unless I'm missing something, I welcome any suggestions)

**Comment by rchl** [comment]
If the rust analyzer runs that code on `textDocument/didSave` notification then it won't help anything to disable the `lsp_save` command.

`lsp_save` is there to trigger handling of "code actions on save", `textDocument/formatting` and `textDocument/willSaveWaitUntil` requests and it seems like rust analyzer doesn't use those for its functionality.

**Comment by predragnikolic** [comment]
I think that this is the expected behaviour because Sublime Text functions this way.

I have a custom keybinding for toggling the sidebar:
```
    { "keys": ["super+\\"], "command": "toggle_side_bar" }
```
But the default keybinding is:
```
	{ "keys": ["super+k", "super+b"], "command": "toggle_side_bar" },
```

I can use both keybindings to toggle the sidebar.

**Comment by Zapeth** [comment]
Oh ok, to be honest I haven't actually tried to do the same with standard sublime key bindings and just assumed it would work that way.

I guess this is a sublime issue/feature request then, so feel free to close this (though I don't know if there is an official/public tracking system for that, I guess I'll post it in the forum at some point).

@rchl Would you say this is something that needs to be supported by the language server (i.e. provide an option to run the check command in other scenarios), or could this handled in the LSP plugin?

**Comment by rchl** [comment]
> @rchl Would you say this is something that needs to be supported by the language server (i.e. provide an option to run the check command in other scenarios), or could this handled in the LSP plugin?

I'm not familiar with that server. I think you should discuss possible options on the server's repo instead. They could easily expose a [command](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand) for triggering that functionality or tie it to the "code actions on save" feature which would allow more flexibility.

BTW. Saving the file from the File menu (File -> Save) doesn't trigger the `lsp_save` command so you can use it for your testing to see what would happen when `lsp_save` is not triggered.

**Comment by jwortmann** [comment]
As usual, all the user-defined key mappings take precedence over the mappings from packages. So to unbound the default key binding for `lsp_show_diagnostics_panel`, you could use
```json
{
    "command": "noop",
    "keys": ["primary+alt+m"],
    "context": [{"key": "setting.lsp_active"}]
},
```
(noop = "no operation")

Or to restore the original save function, it should work if you just copy the binding for `lsp_save` into your user bindings and adjust the `lsp_save` command to `save`:
```json
{
        "command": "save",
        "keys": [
            "primary+s"
        ],
        "context": [
            {
                "key": "lsp.session_with_capability",
                "operator": "equal",
                "operand": "textDocumentSync.willSave | textDocumentSync.willSaveWaitUntil | codeActionProvider.codeActionKinds | documentFormattingProvider | documentRangeFormattingProvider"
            }
        ]
    },
```

**Comment by Zapeth** [comment]
Thanks, that indeed works, albeit its a little counter-intuitive having to explicitly disable the original binding instead of it being bound to the specified command only (but I guess thats a design decision).

@rchl You were correct that rust-analyzer still executes the checking command on save, even if the default save command is being executed in Sublime. I'll ask around on their end if there is a way to resolve this, or if they'd be willing to implement one.
