### ISSUE TITLE
add settings for pyflakes

### ISSUE THREAD

**Issue by arcturus140** [sublimelsp/LSP#1662]
I would like to use Pyflakes without rule W191. I receive a lots of warnings about it and i don't want to change my indentations. 

Please provide an option to the settings for a list of rules to be excluded by Pyflakes.

**Comment by rwols** [comment]
It seems pyflakes doesn't have a config file?

**Comment by arcturus140** [comment]
@rwols yes, it seems so. Sorry i was simply assuming that rules can be disabled.

**Comment by rwols** [comment]
If you can use flake8, settings should be automatically picked up from its various config sources
