### ISSUE TITLE
Add newly published LSP-* to docs

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#1673]
There are 6 new LSP-* plugins worth documenting :)

4 - (ST 4 only)
M - Only Mac

LSP-Source​Kit 4 M
LSP-lua 4
LSP-ltex-ls 4
LSP-jdtls 4
LSP-flow 4
LSP-Power​Shell​Editor​Services 4 

Because these plugins support only ST 4.
We should document them similar/consistent like the [latex](https://lsp.sublimetext.io/language_servers/#latex) docs. For the ST4 the we will link to the plugin, but for ST3 we will leave the client configuration.

For LSP-Source​Kit we should specify that is Mac only (somewhere).

**Comment by predragnikolic** [comment]
Also LSP-OmniSharp (ST 4 only) was also added 2 min ago.

And a [PR](https://github.com/sublimelsp/LSP/pull/1672) that addresses this issue was made 35 minutes ago :)

**Comment by rwols** [comment]
Fixed in #1672
