### ISSUE TITLE
options that were available in ST'3 cannot be used in ST'4

### ISSUE THREAD

**Issue by yuki1318** [sublimelsp/LSP#1675]
**Describe the bug**
"Diagnostics Panel" is not automatically displayed during editing (not save)
 &
The display of "diagnosis panel" is better of ST3 for me.
Is there a way to return to the ST3 format display?

**Screenshots**

https://user-images.githubusercontent.com/29481798/119262250-7cdb1600-bc15-11eb-8bb5-e9d210ffa37d.mp4

https://user-images.githubusercontent.com/29481798/119262276-98deb780-bc15-11eb-8a6a-a68b176c9588.mp4

**Environment (please complete the following information):**
- OS: [windows10 21H1]
- Sublime Text version: [4107]
- LSP version: [tag 4070-1.3.1]
- Language servers used: [clangd, pyls]

**Comment by rwols** [comment]
> Is there a way to return to the ST3 format display?

No. I just don't think showing panels at random without deliberate user action is good UX. There are a few other options:

- Put the caret on the squiggly lines and look at the error message in the status bar.
- Press F4 or shift+F4 to navigate errors.
- Hover with your mouse over the error to read the popup.
- Bind the command `lsp_hover` to a key (e.g. ctrl+h) and press that to show the popup with error information.
- Keep the diagnostics panel open at all times.
- Bind the command `lsp_show_diagnostics_panel` to a key and toggle it manually.

**Comment by yuki1318** [comment]
I understand the intention, but I'm not convinced.
I would like the user to leave a choice...
