### ISSUE TITLE
LSP cannot be automatically enabled in ST4

### ISSUE THREAD

**Issue by asam46** [sublimelsp/LSP#1676]
**Describe the bug**

`LSP` is installed for ST4, but cannot be automatically enabled when editing files. Here is the example for R file:

```
// Settings in here override those in "LSP/LSP.sublime-settings"
{
	"clients":
	{		
		"rlang":
		{
			"command":
			[
				"R",
				"--slave",
				"-e",
				"languageserver::run()"
			],
			"enabled": true
		}
	},
}
```

However, when opening the new R file the left bottom corner cannot indicate `rlang` is loaded. A stranger stuff is that when I click `LSP: Enable Language Server Globally`, and then the left bottom corner says: `No config available to enable`. Another stranger stuff is that if I edit the LSP settings a little bit (e.g. add the comma and then remove it) and save, then I can find the left bottom conner in the R file indicates that `rlang initialize` and work. Such situation also applies for `pylsp`, so that LSP cannot be enabled globally unless I re-open the settings of LSP and modify it a little bit and save.

**Expected behavior**
LSP should be automatically loaded like in ST3.

**Screenshots**
![Screen Shot 2021-05-24 at 1 32 36 PM](https://user-images.githubusercontent.com/52985706/119301097-82c40c00-bc94-11eb-96ca-1dff3c17e378.png)
![Screen Shot 2021-05-24 at 1 33 26 PM](https://user-images.githubusercontent.com/52985706/119301163-a0917100-bc94-11eb-9693-dd54308d055c.png)
![Screen Shot 2021-05-24 at 1 33 46 PM](https://user-images.githubusercontent.com/52985706/119301197-abe49c80-bc94-11eb-8aa9-45f1a77e9653.png)

Then everything works well.
![Screen Shot 2021-05-24 at 1 34 16 PM](https://user-images.githubusercontent.com/52985706/119301258-bdc63f80-bc94-11eb-88da-1a01aad4ffe0.png)

**Environment (please complete the following information):**
- OS: Running under: macOS Big Sur 11.3.1
- Sublime Text version: 4107
- LSP version: 1.3.1

**Comment by asam46** [comment]
Maybe the records of packages I am using now can help

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"BracketHighlighter",
		"GitSavvy",
		"LSP",
		"NeoVintageous",
		"OrgExtended",
		"Origami",
		"Package Control",
		"PowerShell",
		"R-IDE",
		"SendCode",
		"Table Editor",
		"Terminus"
	]
}
```

**Comment by jfcherng** [comment]
Probably unrelated but what if you also copy the `      "selector": "source.r | text.html.markdown.rmarkdown",` line to your config?

**Comment by rchl** [comment]
The only idea that comes to mind is that on opening the *.R file, the syntax would not be set correctly yet and so LSP would not be able to tell that it's an R file yet. But I don't see how that could happen.

On related note, ignoring this issue for a while, all you should need is a configuration like this:

```
    "rlang": {
      "enabled": true,
    },
```

because all other settings are already included in the bundled config:

![Screenshot 2021-05-24 at 12 25 50](https://user-images.githubusercontent.com/153197/119334256-2f00f500-bc8b-11eb-81f9-5ae18347b3a4.png)

**Comment by asam46** [comment]
Well, I figure out the problem. Actually, `R-IDE` is the problematic plugin to make `LSP` not work. I just remove it and everything goes well:

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"BracketHighlighter",
		"GitSavvy",
		"LSP",
		"NeoVintageous",
		"OrgExtended",
		"Origami",
		"Package Control",
		"PowerShell",
		"SendCode",
		"Table Editor",
		"Terminus",
	],
}
```


Now `LSP` can load automatically and it is not the problem about `LSP` so I think we can just close the discussion here.

Thanks so much for your thoughts.

**Comment by rchl** [comment]
@randy3k is the author of the R package so he might be interested in whatever the issue is

**Comment by intheravine** [comment]
I ran into the same issue and appreciate the solution @asam46  found - thanks.

**Comment by randy3k** [comment]
Originally, R-IDE tried to do something smart to detect R binary (especially for windows). However, it turns out that it is very difficult to do it correct. So I have removed the "smart" thing for the new version of R-IDE.

**Comment by randy3k** [comment]
Oh, it seems that LSP has decided to deprecate the rlang config. For that reason, I will bring back the lsp thing to R-IDE.

**Comment by rwols** [comment]
@randy3k yeah, there's a helper package for it (R-IDE) so we can remove the default config. All default configs should disappear in the future. They can be explained in docs (lsp.sublimetext.io) or be part of a helper package.

**Comment by randy3k** [comment]
Would it be actually better to create a separate  LSP-R package than baking it in R-IDE?

**Comment by rwols** [comment]
> Would it be actually better to create a separate LSP-R package than baking it in R-IDE?

sounds good to me.

**Comment by randy3k** [comment]
@rwols Would you mind creating the repo `LSP-r` at sublimelsp and add me as a collaborator?

**Comment by rwols** [comment]
@randy3k done. BTW, apologies if this might have brought you sudden extra work. I was under the impression the R-IDE package took care of providing a client configuration. In any case, I'm not in a hurry to release a new LSP version soon :)

**Comment by randy3k** [comment]
Yes, R-IDE did provide a client configuration implicitly. But it seems that it’s making users confused because it is not visible to users. So I decided to remove it. And now it is a great opportunity to make it right and more transparent to users.

**Comment by rwols** [comment]
OK. I got extra confused because R-IDE is even mentioned in the readme of the language server: https://github.com/REditorSupport/languageserver/

**Comment by randy3k** [comment]
By the way, which of the settings has higher precedence? `LSP.sublime-settings`'s `client` config or `LSP-xxx.sublime-settings`? I thought it is easier to just ask than peeking into the internals.

**Comment by rwols** [comment]
LSP-xxx.sublime-settings always wins https://github.com/sublimelsp/LSP/blob/9e748e380d0878093933e59808b5a50c8ab81078/plugin/core/settings.py#L78-L80

**Comment by randy3k** [comment]
> OK. I got extra confused because R-IDE is even mentioned in the readme of the language server: [REditorSupport/languageserver](https://github.com/REditorSupport/languageserver/)

It was because I put it there (I am the developer of the R language server) and I should probably point it to the new LSP.R.
