### ISSUE TITLE
Diagnostics panel user setting ignored

### ISSUE THREAD

**Issue by lapega** [sublimelsp/LSP#1695]
Ubuntu 20.04 - ST4

I have this setting in LSP.sublime-settings

```
{
	"show_diagnostics_panel_on_save": 1,
}
```
But the panel also opens on warnings, so now I have to set to 0
to keep it closed, but would be nice to have this setting working.

Thanks!

**Comment by rwols** [comment]
I cannot reproduce this.

https://user-images.githubusercontent.com/2431823/120047614-505c3b00-c015-11eb-89be-e577537f3b31.mov

In the video above you can see me saving a file as can be seen from the status bar. I then open the diagnostics panel to reveal one warning present. I have `show_diagnostics_panel_on_save` set to 1 in my settings.

What langserver are you using?

**Comment by lapega** [comment]
I'm using php, the problem doesn't happens all the time, I can't reproduce the behaviour, but seems to be randomly.
(the panel opens when are hints to show)

![imagen](https://user-images.githubusercontent.com/572502/120192336-70485600-c1f1-11eb-9a62-a571d213cf0b.png)

**Comment by husanjun** [comment]
I think the error triggered the diagnostic panel, but in a flash the error disappeared and the panel didn't close automatically. I've had that happen

**Comment by rchl** [comment]
> I think the error triggered the diagnostic panel, but in a flash the error disappeared and the panel didn't close automatically. I've had that happen

There is no auto-close functionality so that would be expected (and not related to this issue, I believe).

**Comment by husanjun** [comment]
> There is no auto-close functionality so that would be expected (and not related to this issue, I believe).

Thanks, Let me explain that when there is an error in the view (which may be caused by some reason), we save the view before the diagnostic response arrives, which will trigger the panel, and then the response arrives it is good

**Comment by rwols** [comment]
> Thanks, Let me explain that when there is an error in the view (which may be caused by some reason), we save the view before the diagnostic response arrives, which will trigger the panel, and then the response arrives it is good

I think you're correct @husanjun. There's not much we can do about that.

**Comment by predragnikolic** [comment]
Hopefully this is addressed with https://github.com/sublimelsp/LSP/pull/2063
I tried to reproduce it, but could not.

**Comment by rchl** [comment]
It should be addressed, yes.
