### ISSUE TITLE
Filter errors in the diagnostics panel to files in view

### ISSUE THREAD

**Issue by Rapptz** [sublimelsp/LSP#1696]
**Is your feature request related to a problem? Please describe.**
Some projects have a lot of lints that cause the diagnostic panel to be spammed with warnings/hints/errors. 

**Describe the solution you'd like**
For focusing on the problem I think it'd be desirable to only have the currently open file's diagnostics displayed.

**Describe alternatives you've considered**
Disabling the panel.

**Additional context**
N/A

**Comment by rwols** [comment]
You could also:

- Right-click on the Tab and select Close Other Tabs
- Disable various linter settings in the server settings, if your langserver has those settings

**Comment by rwols** [comment]
Fixed by #1884
