### ISSUE TITLE
Solargraph does not work on sublime text 4

### ISSUE THREAD

**Issue by danglduy** [sublimelsp/LSP#1708]
**Describe the bug**
-

**To Reproduce**
I have the this configuration for solargraph but it does not work after upgrading to ST4:
```
"ruby":
{
  "command":
  [
    "~/.rbenv/shims/solargraph",
    "stdio"
  ],
  "enabled": true,
  "languageId": "ruby",
  "scopes":
  [
    "source.ruby",
    "source.ruby.rails"
  ],
  "syntaxes":
  [
    "Packages/Ruby/Ruby.sublime-syntax",
    "Packages/Rails/Ruby on Rails.sublime-syntax",
    "Packages/Rails/HTML (Rails).sublime-syntax"
  ],
  "tcp_port": false
}
```

**Expected behavior**
LSP should work with Solargraph
**Screenshots**
![image](https://user-images.githubusercontent.com/38782010/120150020-b95dd180-c214-11eb-8352-92ebd44d2a06.png)

**Environment (please complete the following information):**
- OS: macOS 10.15
- Sublime Text version: 4107
- LSP version: 1.4.0
- Language servers used: ruby solargraph

**Additional context**

**Comment by rwols** [comment]
Thanks for the report. Removing the “tcp_port” should make it start.

**Comment by predragnikolic** [comment]
also see https://lsp.sublimetext.io/language_servers/#solargraph

**Comment by danglduy** [comment]
Thank you so much. I removed the line and it works now.

**Comment by rwols** [comment]
Good to hear you got it working.
