### ISSUE TITLE
The "name" method in AbstractPlugin API is "broken"

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1713]
- If you create an `LSP-foo` package and implement the `name` method that returns `foo` then in the project overrides you have to use the `foo` key instead of `LSP-foo`.
 - If you implement the `name` method that returns `LSP-foo` then the default `configuration()` implementation will fail so the only option is then to override it. In this case the project overrides will use the `LSP-foo` key as expected.

Should there be a way to override the name displayed in the UI to `foo` while still using the `LSP-foo` key for configuration?
Or would that be confusing since then there will be a disconnect between the package name and what's displayed in the UI? I feel that would be a non-issue if the name is close enough.

**Comment by rwols** [comment]
This is intentional? the name of the client config is what you override... the client config is the name in the status bar.

With regards to LSP-TexLab: if you return `TexLab` in `name()`, then you don't need to override `configuration()`

**Comment by jfcherng** [comment]
> With regards to LSP-TexLab: if you return `TexLab` in `name()`, then you don't need to override `configuration()`

But I intended to make it show `LSP-TexLab` at the status bar, rather then just `TexLab`.

**Comment by rchl** [comment]
Ok, it's not really broken but what's not good is the lack of consistency. If all LSP packages would do the same then it would be ok but otherwise you end up with a confusing mess where sometimes you need to use the package name as a key and sometimes just the server name.

Also the fact that the settings for always have the prefix, even if the key doesn't.

I'm not sure if there is anything we can do here apart from consolidating to use the LSP- prefix always. That would be a breaking change though

**Comment by rwols** [comment]
> I'm not sure if there is anything we can do here apart from consolidating to use the LSP- prefix always. That would be a breaking change though

I was hoping to not use the LSP- prefix eventually. For instance jdtls, OmniSharp, PowerShellEditorServices, flow all have no LSP- prefixes for their client configurations.

**Comment by rchl** [comment]
Yes, but what specifically is purpose of that? Just to not include `LSP-` in the status bar? In that case we should probably add API just to override that.

> For instance jdtls, OmniSharp, PowerShellEditorServices, flow all have no LSP- prefixes for their client configurations.

And it's not explained anywhere what the project key should be and even schema is wrong (https://github.com/sublimelsp/LSP-jdtls/blob/46e9d992badab6cda4f3b13584819a6799cbc90f/sublime-package.json#L617).

**Comment by rwols** [comment]
> even schema is wrong 

An honest mistake :) I used the command palette to parse the settings.
