### ISSUE TITLE
Error highlighting to like the warning level

### ISSUE THREAD

**Issue by dwhenson** [sublimelsp/LSP#1718]
Mentioned on Discord, but just adding it here to so that it might make it onto a list....

The warning level seems to work fine and display nicely, but with errors I just see a red vertical line.  This is a bit confusing and makes it harder to invoke the 'hover' with a key binding as the cursor has to be in the exact same place. 

Please let me know if you'd like any other information to help with this. 
Thanks.
<img width="535" alt="warning" src="https://user-images.githubusercontent.com/50716370/120622933-ed7d0080-c467-11eb-83a4-0dd1758f695c.png">
<img width="535" alt="error" src="https://user-images.githubusercontent.com/50716370/120622956-f4a40e80-c467-11eb-9394-558c9d9fb851.png">

**Comment by rchl** [comment]
Transferred to LSP repo since we can't do anything in the LSP-eslint repo.

**Comment by dwhenson** [comment]
Ah OK thanks! Should I close this here?

**Comment by rchl** [comment]
No. The issue was transferred.

**Comment by rwols** [comment]
New LSP release will display them as small horizontal lines, instead of vertical lines.
