### ISSUE TITLE
Setting to increase timeout

### ISSUE THREAD

**Issue by njalerikson** [sublimelsp/LSP#1719]
**Is your feature request related to a problem? Please describe.**
I have `"lsp_format_on_save"` enabled for **LSP-pylsp** where I use `black`. This works great in most cases but from time to time I'm working on larger/more complex codes that take a little longer to format and so the formatting hits the 1000ms default timeout here:

https://github.com/sublimelsp/LSP/blob/5611169a5b4e004b9b1722758ca856ca98d1927f/plugin/save_command.py#L33-L37

And as seen here in the status bar:
<img width="542" alt="Screen Shot 2021-06-03 at 6 25 47 PM" src="https://user-images.githubusercontent.com/4546435/120725445-94c75b00-c49b-11eb-8866-2c66ff8166eb.png">

**Describe the solution you'd like**
Add a setting allowing us to customize the timeout value.

**Describe alternatives you've considered**
A working alternative is to force the formatting via context menu > LSP > Format File but for obvious reasons this can become annoying.

**Additional context**
N/A

**Comment by njalerikson** [comment]
I see that there is a `"code_action_on_save_timeout_ms"` setting but this does not appear to apply to formatting on save? I would assume a similar implementation is needed?

**Comment by rchl** [comment]
True, the other save tasks have hard-coded 1s limit.

Maybe best would be to rename the setting to `on_save_task_timeout_ms`
