### ISSUE TITLE
The `next_result`/`prev_result` hooks don't jump to the next/prev diagnostic if there are build results

### ISSUE THREAD

**Issue by timfjord** [sublimelsp/LSP#1721]
**Describe the bug**
The `next_result`/`prev_result` hooks don't jump to the next/prev diagnostic if there are build results

**To Reproduce**
Steps to reproduce the behaviour:
1. Initiate a build
2. Introduce an LSP error in some file
3. Press `f4`(the default `next_result` shortcut)
4. Observe nothing happens

**Expected behaviour**
The error should be highlighted

**Environment (please complete the following information):**
- OS: macOs 0.15.7 
- Sublime Text version: 4107
- LSP version: 1.4.0
- Language servers used: ruby(solargraph, sorbet)

**Comment by mikewilkerson-solas** [comment]
It appears that this also happens when generating search results (the `next_result`/`previous_result` functionality applies to searches, not LSP diagnostics). The only way I know to get back to navigating LSP results is to quit and restart Sublime Text.

(I'm also on build 4107)

**Comment by wilkystyle** [comment]
It appears that this also happens when generating search results (the `next_result`/`previous_result` functionality applies to searches, not LSP diagnostics). The only way I know to get back to navigating LSP results is to quit and restart Sublime Text.

(I'm also on build 4107)

**Comment by timfjord** [comment]
I think closing the search result page(or the search panel) should fix the problem. But there is no such thing for builds, there is no way to reset the build without restarting Sublime

**Comment by wilkystyle** [comment]
> I think closing the search result page(or the search panel) should fix the problem. But there is no such thing for builds, there is no way to reset the build without restarting Sublime

At least for me, closing the search page doesn't restore my ability to navigate between LSP diagnostics with `next_result` or `previous_result`—it simply disables navigating between search results, with `next_result`/`previous_result` no longer performing any action.

**Comment by rwols** [comment]
Fixed by #1884

**Comment by timfjord** [comment]
@rwols I think the issue is only partly fixed, because in the References search the `next_result/prev_result` hooks are still used.

It might make sense to introduce the same `Goto` thing but for references

**Comment by rwols** [comment]
You can use a quick panel for references, see LSP.sublime-settings.

**Comment by timfjord** [comment]
Indeed, thanks for the tip @rwols

**Comment by frou** [comment]
I have been able to get the behaviour I personally want by adding a small userland plugin that automatically gives brief focus to certain output panels whenever they are shown. This causes them to subsequently have the attention of the `next_result` / `prev_result` keybindings.

```python
import re

import sublime
import sublime_plugin


class TouchShownOutputPanel(sublime_plugin.EventListener):
    OUTPUT_PANEL_NAME_ALLOWLIST = {"references", "diagnostics"}

    def on_post_window_command(self, window, command_name, command_args):
        if (
            command_name == "show_panel"
            and (panel_arg := command_args.get("panel", None))
            and (match := re.match(r"output\.(.+)", panel_arg))
            and (output_panel_name := match.group(1))
            and output_panel_name in self.OUTPUT_PANEL_NAME_ALLOWLIST
            and (output_panel := window.find_output_panel(output_panel_name))
        ):
            original_focus = window.active_sheet()

            window.focus_view(output_panel)

            if original_focus:
                window.focus_sheet(original_focus)
```

cc @jwortmann who posted a helpful writeup here: https://github.com/sublimelsp/LSP/pull/2054#issuecomment-1249023979

**Comment by jwortmann** [comment]
Note that as a performance optimization, the LSP diagnostics panel updates lazily now, i.e. it only will be updated if it is visible, or when it gets opened. This means that `next_result` / `prev_result` won't work reliably anymore, unless the panel is open. But you can/should add key bindings for `lsp_next_diagnostic` / `lsp_prev_diagnostic` instead, which will only jump to diagnostics in the current tab (the other commands would open other files if the server reports diagnostics for those too), and they wrap around when the last/first diagnostic is reached.

**Comment by frou** [comment]
Good information. The way I personally use ST, I only navigate things like this when a panel is open anyway, and really value being able to use the exact same bindings to navigate them all (LSP References, LSP Diagnostics, Build Results, Find Results, ...).

**Comment by jwortmann** [comment]
You could still use the same key binding if you add a [context](https://www.sublimetext.com/docs/key_bindings.html#context-key), for example
```jsonc
[
    { "keys": ["f4"], "command": "lsp_next_diagnostic", "context": [{"key": "panel_visible", "operand": false}] },
    { "keys": ["shift+f4"], "command": "lsp_prev_diagnostic", "context": [{"key": "panel_visible", "operand": false}] },
]
```
would allow to navigate LSP diagnostics whenever no panel is open.
