### ISSUE TITLE
Window status messages from plugins should be cleared if plugin gets unloaded

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#1730]
If plugins set status messages via `Session.set_window_status_async`, they should automatically be erased when the plugin gets unloaded (by *Package Control: Disable Package*), just like it happens for the plugin name in the status bar.

I tried to add something like
```python
for status_key in session._status_messages.keys():
    view.erase_status(status_key)
```
(with the right references/substitutions for `session` and `view`) in `SessionView.__del__` or in `Session.unregister_session_view_async`, but neither of these places worked for me.

I would create a PR, but it would be great if someone could help me where exactly to put that code.

**Comment by rwols** [comment]
It should probably go in `Session.__del__`, no?

**Comment by rchl** [comment]
I think the SessionViews might already be deleted at the point of `Session.__del__` if the session was force-shutdown.
Have you tried doing it from `Session.end_async()`?

**Comment by jwortmann** [comment]
> Have you tried doing it from Session.end_async()?

Thanks, this works! 👍
