### ISSUE TITLE
Unable to start any servers: --- Error: --- global name 'path' is not defined

### ISSUE THREAD

**Issue by thewchan** [sublimelsp/LSP#1754]
**Describe the bug**
When ever any server I use tries to starts, it wan't able to, displaying this error message with a pop up window. 
`--- Error: --- global name 'path' is not defined`

I generally use lsp-pyright, although other servers exhibited the same behavior, lsp-html, lsp-json, lsp-metals...

I've never had this problem until today and it isn't clear to me what triggered it.

**Expected behavior**
Server should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/49702524/122507901-13111a80-cfcf-11eb-89a5-518c567288e3.png)

**Environment (please complete the following information):**
- OS: Windows 10
- Sublime Text version: 4107
- LSP version: 1.6.0
- Language servers used: Pyright, JSON, YAML, Metals, HTML

**Comment by jfcherng** [comment]
https://github.com/sublimelsp/lsp_utils/pull/68/files

**Comment by thewchan** [comment]
@jfcherng so does this mean this can be fixed once that PR is merged in? Is there a timeline for that?

**Comment by jfcherng** [comment]
> @jfcherng so does this mean this can be fixed once that PR is merged in? Is there a timeline for that?

As the latest release of `lsp_utils` breaks many LSP-*, I expect it will be merged and there will be a new release ASAP. Before that, you can override that file by yourself as a emergency temporary solution.

**Comment by husanjun** [comment]
Manual rollback to the previous version

**Comment by predragnikolic** [comment]
I released a new version on package control (but it should take ~2h for Package Control to pick up)  
https://github.com/sublimelsp/lsp_utils/releases/tag/1.13.3

:)

**Comment by jhonoryza** [comment]
manual edit in ~/.config folder hahahah

**Comment by rchl** [comment]
Version 1.13.3 is now available. Run `Package Control: Satisfy Dependencies` from the Command Palette to get the fix quicker.
