### ISSUE TITLE
Error installing the server: 'ResourcePath' object has no attribute 'copytree'

### ISSUE THREAD

**Issue by jeffersonchen-tw** [sublimelsp/LSP#1790]
**Describe the bug**
Error installing the server:
'ResourcePath' object has no attribute 'copytree'.

**To Reproduce**
1. Just simply open any file

**Screenshots**
<img width="273" alt="截圖 2021-07-13 下午2 46 12" src="https://user-images.githubusercontent.com/67701545/125404702-7f721480-e3e9-11eb-8cea-790a2186555e.png">

**Environment (please complete the following information):**
- OS: [macOS 11]
- Sublime Text version: [4007]
- LSP version: [v1.7.0]
- Language servers used: [ clangd, goplst, pyright, lsp-json, lsp-sourceKit]

**Comment by jfcherng** [comment]
What if you run `Package Control: Satisfy Dependencies`?

**Comment by jeffersonchen-tw** [comment]
> What if you run `Package Control: Satisfy Dependencies`?

I still got the same issue

**Comment by jfcherng** [comment]
Could you try `Preferences` => `Browse Packages...` => delete `sublime_lib` directory => re-run `Package Control: Satisfy Dependencies` => restart ST?

**Comment by jeffersonchen-tw** [comment]
Oh! Everything is fine now. Thanks a lot. 謝謝你

**Comment by rwols** [comment]
Glad to hear things worked out.
