### ISSUE TITLE
ST4 autocomplete issue 

### ISSUE THREAD

**Issue by glubbfreund** [sublimelsp/LSP#1795]
**Describe the bug**
With ST4 it should be possible to autocomplete the following function with brackets (and jump inside the brackets)
def foo(text: str):
print(text)

foo();
fo -> completes to foo only and doesnt jump inside the brackets

**To Reproduce**
1. Install ST4, LSP and eiter LSP-pyright or LSP-pylsp 
2. Create a function, for example 
```
    Foo(text:str): 
        print(text)   
```
3. Try to autocomplete it with the new ST4 features (for example it determinates that it is a function, add parentheses and jump in to these that you are able to insert your parameters
4. It works as soon as you disable LSP

**Expected behavior**
New ST4 autocomplete should work without any issue

**Screenshots**
no screenshot atm

**Environment (please complete the following information):**
- OS: Windows 10
- Sublime Text version: 4113
- LSP version: 1.7.0
- Language servers used: lsp-pyright

**Additional context**
see: https://forum.sublimetext.com/t/autocomplete-trailing-symbols/59677/7
I opened an Issue on pyright github, but it seems to be general: https://github.com/sublimelsp/LSP-pyright/issues/80

**Comment by glubbfreund** [comment]
https://github.com/sublimelsp/LSP-pyright/issues/80

**Comment by glubbfreund** [comment]
sorry, I closed it by accident =)

**Comment by jwortmann** [comment]
The completion flags from LSP seem to be set correctly (note that you need `"inhibit_word_completions": false` in the LSP settings to allow built-in completions).

But this looks like a bug (or intended behavior?) in Sublime Text to me. I can reproduce the issue even in safe mode with this simple plugin:
```python
import sublime
import sublime_plugin


class CompletionListener(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        return [
            ["foo", "foo"]
        ]

```

The built-in completion for `foo()` also doesn't show up with this.

**Comment by rwols** [comment]
This is just how pylsp presents its completions. By default LSP supresses the default word completions as they can turn into a word salad for larger projects. You can opt to enable them by setting "inhibit_word_completions" to false in Packages/User/LSP.sublime-settings, reachable via Preferences: LSP Settings in the Command Palette.

The issue mentioned by @jwortmann might need more attention. Or maybe that's just how ST works as well. We can only guess with closed-source software.
