### ISSUE TITLE
Add ability to hide diagnostics on hover

### ISSUE THREAD

**Issue by felixcatto** [sublimelsp/LSP#1797]
There is a quite big diagnostic window appears on hover. 
![Screenshot from 2021-07-20 05-54-15](https://user-images.githubusercontent.com/6022888/126251450-c75cd5fb-c13e-4452-8ae3-4e8b8a9f5075.png)

But there is no setting to disable/hide it. Could you kindly add it? Something like "show_hover_diagnostics_severity_level". Or can you point me to line of code where it called, so i can override it?

**Comment by rchl** [comment]
But the `show_diagnostics_severity_level` setting should be affecting the popup too. If you set it to 3 so that `hint` severity is not reported then the diagnostic should not show up in the popup either.

(From the color of the diagnostic I'm assuming it's a "hint" diagnostic)

**Comment by felixcatto** [comment]
Yes it is hint, but  `show_diagnostics_severity_level` doesn't affect it. It only removes circles near line numbers and underlines near variables. I already set it to 3, and as you see circles and underlinse are disappears, but on hover we still see hints.

**Comment by rchl** [comment]
That's not how it's supposed to work and not how it works here. Did you try restarting ST? And also, are you on ST4?

**Comment by felixcatto** [comment]
Yes, i am on ST4. And i restarted ST several times.

**Comment by rchl** [comment]
You are right. I didn't wait long enough before checking.
Then it looks like a bug to me./
