### ISSUE TITLE
Diagnostics across files within a project

### ISSUE THREAD

**Issue by agreco** [sublimelsp/LSP#1803]
**Is your feature request related to a problem? Please describe.**
Cannot find a way to run diagnostics across files within a project. 

**Describe the solution you'd like**
An option to run diagnostics across files within a project, esp that can be bound to a shortcut keybinding

**Describe alternatives you've considered**
Running a build from outside the project to ascertain any project errors/warnings

Hopefully the above items I've answered against are enough to describe the request. If not I'd be happy to elaborate.

Cheers

**Comment by rchl** [comment]
It's not in LSP's control to do that. It is something that only server can choose to do or not. Many just report diagnostics for files that were opened since providing all diagnostics for the whole project would often be too time consuming (in a C++ project, for example, it would have to basically "compile" the whole project).

All diagnostics that the server reports are visible in the LSP diagnostics panel (`LSP: Toggle Diagnostics Panel` command from the Command Palette).

**Comment by agreco** [comment]
> It's not in LSP's control to do that. It is something that only server can choose to do or not. 

OK I see, so the server that I'm using (lsp-typescript with ts-server) would be responsible for implementing a feature such as this. 

> (in a C++ project, for example, it would have to basically "compile" the whole project).

Yes, this is exactly what I'm looking for, where the diagnostics panel would display the files that have errors/warnings

> BTW. Not sure what you mean by "run diagnostics". Diagnostics can't be run as they just report an issue of some kind. It's just an information state.

Ah ok, I meant, open the diagnostics panel, a compilation occurs and the errors/warnings appear for that project. Just  a turn of phrase.

**Comment by rchl** [comment]
Since it's up to the server, I'm closing this issue.

**Comment by agreco** [comment]
Sure, will raise a feature request on the lsp-typescript repo.

**Comment by rchl** [comment]
I think the https://github.com/theia-ide/typescript-language-server repo would be more appropriate since the LSP helper packages likely can't do nothing about it either.

**Comment by agreco** [comment]
> I think the https://github.com/theia-ide/typescript-language-server repo would be more appropriate since the LSP helper package likely can't do nothing about it either.

Ah thanks, will take a look at this. Unfortunately I've already raised an feature request on the lsp-typescript repo :S
