### ISSUE TITLE
Inhibit is a confusing english word

### ISSUE THREAD

**Issue by RUSshy** [sublimelsp/LSP#1804]
I don't have a clue what that word mean

Can it be changed to something else, i guess it means disable, so use disable, it's a pretty comon word in programming

Why make things complex?

The world is not english first

https://github.com/sublimelsp/LSP/blob/9d6b1fa73a117dc46e7b3ed3ded47988a8c86f6c/LSP.sublime-settings#L116-L117

you said it in the comment, why make the option a completly different word, this is bad

**Comment by willrowe** [comment]
I think inhibit is used for consistency, since Sublime itself also uses it.

**Comment by RUSshy** [comment]
If that is for consistency then it make sense, my bad
