### ISSUE TITLE
Not working at all after update, no errors and no functionality

### ISSUE THREAD

**Issue by ViggoV** [sublimelsp/LSP#1806]
**Describe the bug**
Sublime LSP completely stopped working, possibly in relation to both Sublime and SublimeLSP receiving updates during my vacation. LSP either doesn't show in the status bar at all or, more commonly, shows `LSP-[server] installing...` infinitely and there is no autocompletion or other indication of LSP working when editing a file. I have added `log_debug: true` and `log_server: ["panel"]` as described in the [troubleshooting guide](https://lsp.sublimetext.io/troubleshooting/), but no errors are shown in the console.

Opening a `.ts` file with `LSP-typescript` and `LSP-eslint` enabled yields the following related output.
```
LSP: starting ['/usr/local/bin/node', '/Users/vef/Library/Caches/Sublime Text 3/Package Storage/LSP-eslint/14.7.0/language-server/out/eslintServer.js', '--stdio'] in /Users/vef/Documents/projects/notes/ejendomme
LSP: LSP-eslint: Supported execute commands: ['eslint.applySingleFix', 'eslint.applySuggestion', 'eslint.applySameFixes', 'eslint.applyAllFixes', 'eslint.applyDisableLine', 'eslint.applyDisableFile', 'eslint.openRuleDoc']
LSP: LSP-eslint: supported code action kinds: ['quickfix', 'source.fixAll.eslint']
```

The statusbar shows the following
<img width="349" alt="Screen Shot 2021-07-23 at 13 24 55" src="https://user-images.githubusercontent.com/3153568/126775414-dd329406-db67-49fb-bd0c-a7bd7934419d.png">

I have also tried GraphQL files, which similarly show `LSP-graphql installing...`

To clarify, everything was working perfectly when I left for holiday three weeks ago.

**To Reproduce**
- Let Sublime autoupdate LSP to version `4070-1.7.0`
- Let Sublime update itself to build `4113`

**Expected behavior**
LSP should work just as before the update

**Environment (please complete the following information):**
- OS: macOS 10.15
- Sublime Text version: 4113
- LSP version: 1.7.0
- Language servers used: `LSP: enabled configs: LSP-angular, LSP-eslint, LSP-graphql, LSP-typescript`

**Additional context**
- The path for `node` as seen in the console output is wrong, since I am using NVM. I expected it to source `.zshrc` when launcing via terminal but that doesn't seem to happen.
- SublimeLinter seems to suffer from the same issue
- I have been using FixMacPath, which is supposed to source the shell config, but it's 7 years old and doesn't seem to work as expected
- I use `PackageResourceViewer` to extract packages when needed. The problem persists whether or not LSP and the servers are extracted

**Comment by rchl** [comment]
ST sources your default shell environment (You should see a line like `environment variables loaded using: /bin/zsh -l` in the console on starting ST) but not the `.zshrc` file specifically. Read more here on what it actually sources: https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

And since ST does it itself now, as long as you have extended the PATH in the proper file, you shouldn't need packages like `FixMacPath`.

**Comment by ViggoV** [comment]
Weird. It really seems like ST loads the correct PATH but running `import os; out = os.popen("which node").read(); print(out)` still yields the wrong path and `import os; out = os.popen("nvm current").read(); print(out)`  shows nothing at all.

In any case I am not sure this issue is entirely related since it's not limited to JS/TS files.

**Comment by ViggoV** [comment]
In addition, running "LSP: Troubleshoot Server" just shows "Running Server Test..." infinitely and nothing else happens in the UI, console or log..

**Comment by rchl** [comment]
In the ST console, you can switch to the 3.3 runtime by right clicking the input field. Most of the packages, including LSP, run in 3.3 environment so you might get different results there.

Generally the PATH is (almost) the same in both but if you are running package like `FixMacPath` then it can affect only one of those.

> Weird. It really seems like ST loads the correct PATH but running `import os; out = os.popen("which node").read(); print(out)` still yields the wrong path and `import os; out = os.popen("nvm current").read(); print(out)` shows nothing at all.

What about `import shutil; shutil.which('node')` (or `nvm`)?

**Comment by rwols** [comment]
> I use PackageResourceViewer to extract packages when needed. The problem persists whether or not LSP and the servers are extracted

Are  you sure nothing is extracted now? I suggest to remove PackageResourceViewer as it screws up package updates. An alternative is the built-in View Package File command.

**Comment by rwols** [comment]
what other packages do you have installed?

**Comment by ViggoV** [comment]
> what other packages do you have installed?

`
['A File Icon', 'ApplySyntax', 'Auto Close HTML Tags', 'ayu', 'Boron Color Scheme', 'C++11', 'Case Conversion', 'ChangeQuotes', 'DiffView', 'Dockerfile Syntax Highlighting', 'DotENV', 'ESLint-Formatter', 'Fix Mac Path', 'GenerateUUID', 'Git blame', 'Gofmt', 'GraphQL', 'Hasher', 'Indent XML', 'JSONLint', 'LoremIpsum', 'LSP-angular', 'LSP-eslint', 'LSP-graphql', 'LSP-typescript', 'LSP', 'Makefile Plus', 'Markdown Extended', 'MarkdownPreview', 'Monokai - Spacegray', 'Monokai Extended', 'nginx', 'Ngx HTML', 'Oceanic Next Color Scheme', 'Origami', 'Package Control', 'PackageResourceViewer', 'Pretty JSON', 'Protobuf Syntax Hightlighting', 'Python 3', 'Restart', 'RustFmt', 'Sass', 'SideBarEnhancements', 'Slugify', 'SublimeLinter-eslint', 'SublimeLinter-golangcilint', 'SublimeLinter-gotype', 'SublimeLinter-json', 'SublimeLinter-rubocop', 'SublimeLinter', 'TerminalView', 'Theme - Afterglow', 'Theme - Alpenglow', 'Theme - Gravity', 'Theme - Spacegray', 'TOML', 'TrailingSpaces', 'Whitespace', 'Wrap Plus', 'Zeus', 'HTML-CSS-JS Prettify', 'LiveReload', 'Naomi', 'Pretty YAML', 'rainbow_csv', 'Random Everything', 'ZSH']`

I will try removing `PackageResourceViewer` as suggested, but I am sure that LSP and the servers where not extracted when the problem began.

**Comment by ViggoV** [comment]
I managed to fix my $PATH, turns out I had a Homebrew installation of Node , but the issue remains. I also removed FixMacPath as it obviously didn't work as intended, as well as PackageResourceViewer. It seems almost random whether or not a given LSP server shows up in the status bar. E.g. when opening a `.ts` file, sometimes it shows `LSP-eslint, LSP-typescript: installing...` (indefinitely), sometimes just `LSP-typescript: installing...` and sometimes nothing except line and column numbers. The only output I get related to LSP is the following:
```
LSP: enabled configs: LSP-typescript
LSP: disabled configs: clangd, erlang-ls, gopls, ocaml, polymer-ide, ruby, rust-analyzer, sorbet
```

**Comment by rchl** [comment]
Feels like the `npm` process is getting stuck while installing dependencies. There doesn't seem to be great way of debugging that from ST.

You can try this:
 - go to the caches directory:
![Screenshot 2021-07-26 at 12 45 09](https://user-images.githubusercontent.com/153197/126976828-c9c6c44e-6046-429b-bba0-e7774be25086.png)
 - (you might have just one version listed here)
 - navigate inside the directories to the one that contains `package.json`
 - run `npm ci --scripts-prepend-node-path=true --verbose --production` in that directory within the terminal

This should print all the output and hopefully tell you where it's deadlocking.

**Comment by rchl** [comment]
Also, if one server is stuck installing then that will make all other servers not work since they all run on the same thread (because @rwols has thread aversion ;))

**Comment by rchl** [comment]
Also you can try deleting the `LSP-typescript` directory and see if that helps to get it installed correctly. But the issue might be in your node's caches so it might not help.

**Comment by ViggoV** [comment]
I don't have an LSP-typescript folder in Package Storage at all, even after remove/reinstall 🤔 Nothing in my NPM cache folder either..

**Comment by rchl** [comment]
You can try disabling the `LSP-eslint` package. Maybe that one is blocking something. Or disabled all 3 LSP-packages and then start enabling one by one (and restarting ST).

**Comment by ViggoV** [comment]
@rchl Sorry, I was a little to quick.. I was in the wrong `Package Storage` folder before. I did find the LSP-typescript folder in `~/Library/Caches/...`. I've tried both running your oneliner and deleting everything in the folder, with no luck. I already removed all other enabled LSP packages and un-/re-installed LSP-typescript several times

**Comment by rchl** [comment]
What happens when you run the one-liner. Does npm get stuck?

The code that handles the installation is simple and there is really no other place it could block on besides npm-install step - https://github.com/sublimelsp/lsp_utils/blob/908bb6c4524b643fd62f1023555a7476a0ca9d60/st3/lsp_utils/server_npm_resource.py#L86-L100

**Comment by ViggoV** [comment]
Initially it completed without error:

```
vef@mbp:typescript-language-server$ npm ci --scripts-prepend-node-path=true --verbose --production
npm verb cli [
npm verb cli   '/Users/vef/.nvm/versions/node/v14.16.0/bin/node',
npm verb cli   '/Users/vef/.nvm/versions/node/v14.16.0/bin/npm',
npm verb cli   'ci',
npm verb cli   '--scripts-prepend-node-path=true',
npm verb cli   '--verbose',
npm verb cli   '--production'
npm verb cli ]
npm info using npm@7.17.0
npm info using node@v14.16.0
npm timing npm:load:whichnode Completed in 2ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/vef/.nvm/versions/node/v14.16.0/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 2ms
npm verb config production Use `--omit=dev` instead.
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/vef/Library/Caches/Sublime Text 3/Package Storage/LSP-typescript/14.16.0/typescript-language-server/.npmrc Completed in 2ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/Users/vef/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/vef/.nvm/versions/node/v14.16.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 19ms
npm timing config:load:flatten Completed in 2ms
npm timing arborist:ctor Completed in 1ms
npm timing npm-ci:rm Completed in 99ms
npm timing idealTree:init Completed in 1ms
npm timing idealTree:userRequests Completed in 1ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 3ms
npm timing reify:loadTrees Completed in 7ms
npm timing reify:diffTrees Completed in 1ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 3ms
npm timing reify:trashOmits Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/universalify Completed in 304ms
npm timing reifyNode:node_modules/tempy Completed in 303ms
npm timing reifyNode:node_modules/temp-dir Completed in 304ms
npm timing reifyNode:node_modules/unique-string Completed in 305ms
npm timing reifyNode:node_modules/p-debounce Completed in 305ms
npm timing reifyNode:node_modules/crypto-random-string Completed in 305ms
npm timing reifyNode:node_modules/jsonfile Completed in 307ms
npm timing reifyNode:node_modules/graceful-fs Completed in 308ms
npm timing reifyNode:node_modules/commander Completed in 314ms
npm timing reifyNode:node_modules/command-exists Completed in 315ms
npm timing reifyNode:node_modules/vscode-uri Completed in 319ms
npm timing reifyNode:node_modules/vscode-languageserver-types Completed in 329ms
npm timing reifyNode:node_modules/vscode-languageserver Completed in 330ms
npm timing reifyNode:node_modules/vscode-textbuffer Completed in 346ms
npm timing reifyNode:node_modules/vscode-jsonrpc Completed in 347ms
npm timing reifyNode:node_modules/fs-extra Completed in 348ms
npm timing reifyNode:node_modules/vscode-languageserver-protocol Completed in 354ms
npm timing reifyNode:node_modules/typescript-language-server Completed in 362ms
npm timing reifyNode:node_modules/typescript Completed in 563ms
npm timing reify:unpack Completed in 563ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/typescript Completed in 3ms
npm timing build:link:node_modules/typescript-language-server Completed in 2ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 584ms
npm timing auditReport:getReport Completed in 585ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 585ms
npm timing build:link:node_modules/vscode-languageserver Completed in 17ms
npm timing build:link Completed in 18ms
npm timing build:deps Completed in 20ms
npm timing build Completed in 20ms
npm timing reify:build Completed in 21ms
npm timing reify:trash Completed in 0ms
npm timing reify Completed in 607ms

added 19 packages, and audited 20 packages in 1s

found 0 vulnerabilities
npm timing command:ci Completed in 711ms
npm verb exit 0
npm timing npm Completed in 1192ms
npm info ok 
```

However, after deleting the contents and restarting sublime it has reinstalled in the same folder. Now the oneliner fails:

```
vef@mbp:typescript-language-server$ npm ci --scripts-prepend-node-path=true --verbose --production
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/Users/vef/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/Users/vef/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/Users/vef/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/npm.js:58:19)
    at Object.<anonymous> (/Users/vef/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/npm.js:48:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
´´´

**Comment by ViggoV** [comment]
Oh wait. NPM failed, then I cd'd out and back in and then it worked

**Comment by rchl** [comment]
Maybe jump on Discord (https://github.com/sublimelsp/LSP#getting-help) if you can since it's not the most practical place to troubleshoot this issue.

**Comment by ViggoV** [comment]
Thank you for your time and help in any case 👍

**Comment by ViggoV** [comment]
YES! Found the root of the problem. I had fixed the `node` path but I still had a dangling `npm` binary in `/usr/local/bin/`. I'm not sure why it differs from the system PATH or why the problem coincided with an ST update, but perhaps the aging FixMacPath broke or something. Thanks for the help!
