### ISSUE TITLE
env handling in client settings not portable

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1811]
There is no way to alter the env paths in a way that would work across all systems.

For example `LSP-pylsp` defines some env variables (https://github.com/sublimelsp/LSP-pylsp/blob/75a07c497fcca88cb2780230e559ae0e7402c361/LSP-pylsp.sublime-settings#L37-L37) that are PATH-like and are using path separator `:` but that is obviously not correct on Windows.

The only way to handle that comes to my mind right now is to have a template variable for the separator. The only small downside would be that it would not be easily discoverable.

**Comment by jfcherng** [comment]
Since you cannot have `:` in the filename on Windows, I guess you can replace all `:`s with `;`s if the OS is Windows? And always use `:` as the separator.

**Comment by rwols** [comment]
So we end up with paths like C;/Users/jfcherng?

**Comment by jfcherng** [comment]
> So we end up with paths like C;/Users/jfcherng?

What if the reverse way? Convert `;`s into `:` if on non-Windows?

**Comment by rchl** [comment]
> What if the reverse way? Convert `;`s into `:`s if on non-Windows.

Error prone. We don't know in which variables we have to do the replacement and if we do that in all, we might break something.

> Or allowing using a list in `env` values and merged it into a str since all env values are str, actually.

That is an option.

**Comment by rchl** [comment]
So we have two options right now:

```
"env": {
  "LIKEPATH": "/usr/lib/bin${pathsep}/usr/var/foo"
}
```

or

```
"env": {
  "LIKEPATH": ["/usr/lib/bin", "/usr/var/foo"]
}
```

**Comment by rwols** [comment]
I like the list approach best :)

**Comment by rchl** [comment]
Don't mind the list handling being implemented but I'll add `pathsep` template variable in `lsp_utils` for the time being since I want this to work in ST3 also.

https://github.com/sublimelsp/lsp_utils/pull/75
