### ISSUE TITLE
[Clangd] How do I configure a include directory in a plugin settings file?

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP#1818]
example:
in the Sublime-Linters plugins,the Clang extenstion configure include directory only need setting like this:
```json
"clang":{
            "I":[
                "${folder}/src",
                "${folder}/include",
                "${folder}/inc/",
                "${folder}/"
            ]
        }
```

**Comment by jingyuexing** [comment]
[sublime-linters clang](https://github.com/SublimeLinter/SublimeLinter-clang)

**Comment by rwols** [comment]
- When using cmake, configure with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` (requires only a configure step)
- When using make, build with `bear make` (requires complete build before obtaining compile_commands.json)
- When using visual studio solution files, write a compile_flags.txt by hand

Does this answer your question?

**Comment by jingyuexing** [comment]
> 
> 
>     * When using cmake, configure with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` (requires only a configure step)
> 
>     * When using make, build with `bear make` (requires complete build before obtaining compile_commands.json)
> 
>     * When using visual studio solution files, write a compile_flags.txt by hand
> 
> 
> Does this answer your question?

thanks

**Comment by predragnikolic** [comment]
This seems to be resolved, so I will close the issue.
