### ISSUE TITLE
Cannot install due to dependency backrefs not being available.

### ISSUE THREAD

**Issue by johanrosenson** [sublimelsp/LSP#1819]
I am trying to install the plugin on ST build 4113.

I get the following error in the console and the installation fails.

```
Package Control: The dependency 'backrefs' is not currently installed; installing...
Package Control: The dependency 'backrefs' is not available
Package Control: The dependency 'backrefs' could not be installed or updated
```

**Environment (please complete the following information):**
- OS: MacOS 10.15.7 (19H2)
- Sublime Text version: 4113
- LSP version: N/A
- Language servers used: N/A

**Comment by rwols** [comment]
This is a Package Control issue: https://github.com/wbond/package_control/issues

**Comment by johanrosenson** [comment]
thanks @rwols
