### ISSUE TITLE
LSP unavailable on Package Control

### ISSUE THREAD

**Issue by tleb** [sublimelsp/LSP#1821]
**Describe the bug**
Every package published by the user [sublimelsp](https://packagecontrol.io/browse/authors/sublimelsp) on Package control are marked as *REMOVED* on each individual package page and *NEEDS REVIEW* on the user's package listing. They are therefore unavailable to install using Package Control (inside Sublime Text).

*REMOVED* is described by its title attribute as "Package was removed and is no longer available" and *NEEDS REVIEW* as "Package was previously missing and needs manual review to re-enable".

I deleted the sections *to reproduce*, *expected behavior*, *screenshots*, *environment* and *additional context* as not applicable to this issue.

Anything that can be done to help resolve this issue? Thanks for the project!

**Comment by rwols** [comment]
Thanks for the report.

This is a package control issue. See: https://github.com/wbond/package_control/issues/1581
