### ISSUE TITLE
LSP package requires backrefs but backrefs isn't available

### ISSUE THREAD

**Issue by rerorengine** [sublimelsp/LSP#1822]
I'm trying to install LSP for all languages that I use (Lua, Python, HTML-CSS-JS/TS, etc) and as per the guidelines, it seems that I have to install "LSP" package as the starting point.

When I press enter to install it I opened my Console.
The installation didn't success and saw that it need a dependency that's unavailable right now

Here take a look at the output:
``` shell
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'backrefs' is not currently installed; installing...
Package Control: The dependency 'backrefs' is not available
Package Control: The dependency 'backrefs' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Please help me on how to succeed on the installation.

Thank You
Rero

**Comment by rwols** [comment]
Thanks for the report. This is a package control issue. See: https://github.com/wbond/package_control/issues/1581

**Comment by rerorengine** [comment]
Yeah I referred the issue you have mentioned and helped me a Lot. Thank You
