### ISSUE TITLE
Configuring LPS-R

### ISSUE THREAD

**Issue by fabeit** [sublimelsp/LSP#1857]
I have installed languageserver in R, LPS, LPS-R, and R-IDE on Windows.

But I can't seem to run the LPS-R server. I get this message

"FileNotFoundError: [WinError 2] The system cannot find the file specified"

I tried to follow the available guides including this one https://lsp.readthedocs.io/en/latest/ but they are confusing as they don't explain which files or paths should go in my environmental variables. What command should I be able to run in CMD?

I hope someone can help.

**Comment by jfcherng** [comment]
do you have the languageserve install as stated in https://packagecontrol.io/packages/LSP-R

**Comment by jfcherng** [comment]
> What command should I be able to run in CMD?
 https://github.com/sublimelsp/LSP-R/blob/f5c717f39edce3bfd67bd433dfc5ba28f88e4a08/LSP-R.sublime-settings#L3

it runs R

**Comment by fabeit** [comment]
> 
> 
> > What command should I be able to run in CMD?
> 
> https://github.com/sublimelsp/LSP-R/blob/f5c717f39edce3bfd67bd433dfc5ba28f88e4a08/LSP-R.sublime-settings#L3
> 
> it runs R

Thank you. That's what I have but I get that error message. Should I be able to R.exe in Windows command prompt for LSP-R to run?

**Comment by jfcherng** [comment]
hmm.... this reminds me that it should be R.exe on Windows.

**Comment by rwols** [comment]
No it doesn’t. LSP should try .exe automatically

**Comment by rwols** [comment]
It’s apparently not even needed to append .exe https://github.com/sublimelsp/LSP/blob/237437041d0a7344169f4add240bafd2d5bdb582/plugin/core/transports.py#L286

**Comment by jfcherng** [comment]
then maybe you can try to run `R.exe --slave -e languageserver::run()` in cmd.

**Comment by rwols** [comment]
> I tried to follow the available guides including this one https://lsp.readthedocs.io/en/latest/

That's the legacy docs for ST3. The ST4 docs are at https://lsp.sublimetext.io.

**Comment by fabeit** [comment]
Ok I solved the issue by adding the R bin directory path to the Windows PATH environmental variables. It works without the ".exe". Thanks!
