### ISSUE TITLE
Unwanted splitting on dot of the setting keys

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#1858]
**Describe the bug**

In LSP-yaml, the user can specify schema mapping like so:

```
yaml.schemas: {
    "https://json.schemastore.org/composer": "/*"
}
```

This doesn't work in ST because LSP splits the URL key on every dot, creating an object that the server doesn't understand.

**Expected behavior**

Should send the value of the `yaml.schemas` object without altering it

**Additional context**

I'm not sure how VSCode manages to handle it but I would guess it is somewhat taking into consideration the schema itself. We could try to check that first.

**Comment by kapitanluffy** [comment]
Tried looking for the part where they split the settings. Maybe this will help. 

https://github.com/microsoft/vscode-languageserver-node/blob/f5b306a318246ae71a8275406e0c5211c5c67de9/client/src/common/client.ts#L2541-L2573

**Comment by rchl** [comment]
That code is used by language servers and works the same regardless of the editor used. The relevant code would be somewhere in the vscode repo, I would think.

Basically, the issue already happens at the point of parsing the setting and storing it in the model. We split every key on a dot and that is not reversible later. So we would need to avoid that at the time of parsing.

**Comment by rwols** [comment]
I think we can just check for the presence of a `:` or `/` character. Nobody uses those characters for their key (part), no?

**Comment by kapitanluffy** [comment]
So I was trying to figure out how they parse the settings and I get stuck around this. They don't seem to do anything special with the settings. I guess we need someone who can read typescript better 😅

https://github.com/microsoft/vscode/blob/main/src/vs/platform/configuration/common/configuration.ts#L303-L322

**Comment by EmilySeville7cfg** [comment]
I am not sure but maybe due to this issue my YAML lsp [doesn't work](https://www.reddit.com/r/SublimeText/comments/v0c6jc/setting_up_json_language_server/):

```json
{
    "settings": {
        "LSP": {
            "LSP-yaml": {
                "settings": {
                    "yaml.schemas": {
                        "https://json.schemastore.org/hugo.json": "config.yml",
                        "static/schemas/about/environment/configs.json": "data/about/environment/configs/*.yml",
                        "static/schemas/about/environment/extensions.json": "data/about/environment/extensions/*.yml",
                        "static/schemas/about/skills/editors.json": "data/about/skills/editors/*.yml",
                        "static/schemas/about/skills/languages.json": "data/about/skills/languages/*.yml",
                        "static/schemas/about/skills/vcs.json": "data/about/skills/vcs/*.yml",
                        "static/schemas/about/achievements.json": "data/about/achievements.yml",
                        "static/schemas/about/organizations.json": "data/about/organizations.yml",
                        "static/schemas/about/presentations.json": "data/about/presentations.yml"
                    }
                }
            }
        }
    }
}

```

**Comment by rchl** [comment]
Yes, it's the same issue as in the initial comment.

**Comment by EmilySeville7cfg** [comment]
@rchl, what about allow user manually specify whether to split json keys on dots or not via some comment:

```
// split-dots
// ...
```

or top-level json key

```json
{
  "split-dots": false,
  // ...
}
```

?
