### ISSUE TITLE
Suggestion for callback: on_post_initialize

### ISSUE THREAD

**Issue by bostick** [sublimelsp/LSP#1860]
I know there is a `on_post_start` callback that is invoked when the subprocess was just started, but I am interested in a callback for when the `initialize` is sent back to the client.

Motivation:
It is common for something to go wrong with starting the server that I am developing, and it may hang. So the subprocess starts with no problem, but then nothing else happens.

So I'd like to implement a timeout that a new `on_post_initialize` callback would cancel.

**Comment by rwols** [comment]
Can’t you debug this at the server level catching the `initialized` notification from the client?

**Comment by bostick** [comment]
Server may be unreliable. It is common for something to go wrong with starting the server that I am developing, and it may hang.


Basically, in `on_pre_start`, I want to start a thread that will give an error dialog after 10 seconds if the server did not start properly.

Then, after client receives `initialize` response from server, then I know I can cancel the timer.

I just need a callback for when the client receives `initialize` response from server.

**Comment by jwortmann** [comment]
Doesn't this already exist as `AbstractPlugin.__init__()`?
https://github.com/sublimelsp/LSP/blob/2100cd0fe003a44456e4f4c018ab775fdddddde1/plugin/core/sessions.py#L593-L600

I use it in LSP-julia to show a permanent message in the status bar, but only after the server is ready:
https://github.com/sublimelsp/LSP-julia/blob/ad7415e040464afac39796fe07fd58c73b7f9120/plugin.py#L94-L100

I agree that a separate `on_post_initialize` would probably have been a better name than `__init__` for this method. Note that `on_pre_start` is a classmethod, so I think you can't really communicate with a thread from that method unless you add global variables, which on the other hand would probably break in case someone starts multiple instances of the server at the same time. But it might work for debugging.

**Comment by rwols** [comment]
> I want to start a thread that will give an error dialog after 10 seconds if the server did not start properly.

You should leave that up to this package though. There's also no need to start a thread. You can use something like `sublime.set_timeout(f, 10000)` to run `f` after 10 seconds.

**Comment by bostick** [comment]
Thanks all.

I had not thought to use `AbstractPlugin.__init__()`! That does allow me hook into when the server is ready.

So, I think I withdraw this suggestion.

I also switched to using `sublime.set_timeout(f, 10000)`, thank you for the suggestion!
