### ISSUE TITLE
[clangd] when I import assert.h file, the clangd is broken

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP#1871]
**Describe the bug**
when I write into some code, for example, inline assembly or import assert.h , then clangd is broken

**To Reproduce**
1. open a .c file
2. write content as `#include <assert.h>`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19589872/137187855-9a47a8a4-d269-4dcc-a53d-db8ee87e5094.png)

**Environment (please complete the following information):**
- OS: Windows
- Sublime Text version: 4100
- LSP version: v1.12.1
- Language servers used: clangd 13.0.0

**Additional context**
```c
#include <stdint.h>
#include <stdlib.h>
int32_t *somefunc( hash){
}
```
```c
__asm{

}
```
You can try to copy that code to your editor

**Comment by rchl** [comment]
Sounds like a server issue but can you provide full server log? (https://lsp.sublimetext.io/troubleshooting/#self-help-instructions)

**Comment by jingyuexing** [comment]
> Sounds like a server issue but can you provide a full server log? (https://lsp.sublimetext.io/troubleshooting/#self-help-instructions)

[SourceLocation.h#L327](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/SourceLocation.h#L327)

**Comment by rchl** [comment]
I'm sure you can report a bug to clang. https://llvm.org/docs/HowToSubmitABug.html

I doubt that any of us will have time and/or expertise to analyze this clang crash.

**Comment by rwols** [comment]
There is a GitHub issue tracker here: https://github.com/clangd/clangd/issues/

cc @HighCommander4, @kadircet

**Comment by rwols** [comment]
It doesn't crash here by the way

https://user-images.githubusercontent.com/2431823/137602924-98da2601-c690-4803-8139-884d26c9b4f5.mov

```
~/d/clangd-test-crash $ xcrun clangd --version
Apple clangd version 13.0.0 (clang-1300.0.29.3)
```

**Comment by jingyuexing** [comment]
> It doesn't crash here by the way
> 
>  Schermopname.2021-10-16.om.23.49.19.mov 
> ```
> ~/d/clangd-test-crash $ xcrun clangd --version
> Apple clangd version 13.0.0 (clang-1300.0.29.3)
> ```

```c
#include <assert.h> // when I include assert.h ,then clangd is crash 
// any code in here
```

**Comment by rwols** [comment]
I see you've tried to submit a bug (https://github.com/clangd/clangd/issues/892) but it needed more information. I hope you can find the time to obtain that additional information for the clangd developers.
