### ISSUE TITLE
Allow manually killing the server process

### ISSUE THREAD

**Issue by bostick** [sublimelsp/LSP#1872]
I am developing an LSP server implementation.

But let's say that I had a typo in my command.

The command is now some command that hangs when given the usual traffic from an LSP client.

I am already showing an error message after 10 seconds if this happens.

I am interested in also manually killing the server process that was started.

I could not see if there was already an API for doing that, so I am creating this issue.

This is not anything to do with the actual protocol, because I am talking about a process that does not even understand the protocol.

This is low-level error handling and cleanup.

The real-world case that I am trying to solve is running a command that may not have the proper packages installed yet, and so hangs on startup.

**Comment by rchl** [comment]
If the`command` is not correct then the server process should not even start correctly (cause crash on start). So what specific case are you talking about that would not be handled by using the restart command?

**Comment by bostick** [comment]
There is no "server's code" yet. That is the problem I'm trying to solve. The package for providing this LSP functionality may not yet be installed for the server process.

re: `needs_update_or_installation` and `install_or_update`:
The server processes that are started (WolframKernel) are considered expensive to start (time taken and licenses taken), and the installation process may be complicated and really does need to be done manually by a user with supervision.

It looks like `needs_update_or_installation` cannot prevent the server from starting.

If there was a way for to say "This binary does exist but it needs manual updating. The user must manually update first before proceeding." and then refuse to start the server, then that would fit my needs.

I agree that a command in the command palette might be confusing for users, but that's not what I'm asking for.

I'm asking for a way to kill the server process inside of an implementation of `AbstractProcess`.

I am already calling `on_pre_start` and setting up a timeout with `sublime.set_timeout`.

Inside the timeout function after 10 seconds (if server did not initialize yet), I show an error message with `sublime.message_dialog`.

But the server process is still hanging at this point and it needs to be killed.

**Comment by bostick** [comment]
I had not noticed `AbstractPlugin.can_start`. That does seem to fit my need.

I will try to fit in and see if it works for my purpose.
