### ISSUE TITLE
Disable LSP-intelephense globally doesn't work, in projects it does

### ISSUE THREAD

**Issue by braver** [sublimelsp/LSP#1880]
**Describe the bug**
When I use the command to disable the LSP server I'm using (Intelephense) globally, it makes the required entry in the settings file, but Intelephense still runs and will continue to run and initialise for any new window I open. Even after restarting ST, etc. It appears this setting does not work at all. There is a note in the example settings that other settings are required as well (command, selector), but adding those makes no difference. The debug log has no error messages, it does clearly log the initialisations that still happen.

If I use "disable language server in project" it creates the same settings, now in the project file. This immediately stops the server for that project and effectively stops it from running in future instances, e.g. after restarting ST. The debug logs indicate that the project override is applied. This seems to work exactly as it says on the tin.

**To Reproduce**
1. Open a project with some PHP in it, and have LSP-intelephense set up.
1. Note that it runs and appears in the status bar.
2. Run the command "disable language server globally".
3. Note that it is however still running and displayed on the status bar.
4. Run the command "disable language server in project".
4. Note that it stops running and doesn't come back.

**Expected behavior**
LSP-intelephense should stop running when disabled globally.

**Environment (please complete the following information):**
- OS: macOS Big Sur 11.6
- Sublime Text version: 4113
- LSP version: 1.12.1
- Language servers used: LSP-intelephense

**Comment by rwols** [comment]
Was this fixed by #1907?

**Comment by predragnikolic** [comment]
Yes.
