### ISSUE TITLE
prefs.inhibit_word_completions as false does not work on Sublime Text 4

### ISSUE THREAD

**Issue by evandrocoan** [sublimelsp/LSP#1887]
**Describe the bug**
Already posted on core https://github.com/sublimehq/sublime_text/issues/4999 (Returning a CompletionList() on on_query_completions always do INHIBIT_WORD_COMPLETIONS).

This problem shows up better when no completions are received from the language server and no calls to `clist.set_completions([], flags)` are performed.

The "fix" for now would be to calculate the `prefs.inhibit_word_completions` before returning from `on_query_completions`, i.e.:
```diff
--- a/plugin/documents.py
+++ b/plugin/documents.py
@@ -431,6 +431,12 @@ class DocumentSyncListener(sublime_plugin.ViewEventListener, AbstractViewListene
 
         clist = sublime.CompletionList()
         sublime.set_timeout_async(lambda: self._on_query_completions_async(partial(resolve, clist), locations[0]))
+        prefs = userprefs()
+        if prefs.inhibit_snippet_completions:
+            flags |= sublime.INHIBIT_EXPLICIT_COMPLETIONS
+        if prefs.inhibit_word_completions:
+            flags |= sublime.INHIBIT_WORD_COMPLETIONS
+        sublime.set_timeout(lambda: clist.set_completions([], flags))
         return clist
 
     # --- textDocument/signatureHelp -----------------------------------------------------------------------------------
```

**Comment by rchl** [comment]
I've commented on the core issue.

**Comment by rwols** [comment]
I also commented on the linked issue and I don't see the problem as word completions show up for me.
