### ISSUE TITLE
Access to clangd logs

### ISSUE THREAD

**Issue by cqc-alec** [sublimelsp/LSP#1891]
**Is your feature request related to a problem? Please describe.**

Yes. When editing a moderately complex C++ project, I frequently find that clangd (v13) exits with status code -9, whatever that means. I have been trying to obtain logs for a clue as to the reason. My LSP settings are:
```
{
	"clients":
	{
		"clangd":
		{
			"enabled": true,
			"command": ["clangd", "--log=verbose"]
		}
	},
	"log_debug": true,
	"log_stderr": true,
	"log_server": ["panel"]
}
```
But all I see in the panel immediately after a crash is:
```
reloading settings Packages/User/LSP.sublime-settings
LSP: enabled configs: clangd
LSP: disabled configs: erlang-ls, gopls, ocaml, polymer-ide, ruby, rust-analyzer, sorbet
LSP: starting ['clangd', '--log=verbose'] in /opt/sublime_text
LSP: starting ['clangd', '--log=verbose'] in /opt/sublime_text
LSP: starting ['clangd', '--log=verbose'] in /opt/sublime_text
LSP: starting ['clangd', '--log=verbose'] in /opt/sublime_text
LSP: starting ['clangd', '--log=verbose'] in /opt/sublime_text
LSP: clangd: Supported execute commands: ['clangd.applyFix', 'clangd.applyTweak']
LSP: clangd: supported code action kinds: ['quickfix', 'refactor', 'info']
LSP: clangd: Supported execute commands: ['clangd.applyFix', 'clangd.applyTweak']
LSP: clangd: supported code action kinds: ['quickfix', 'refactor', 'info']
LSP: clangd: Supported execute commands: ['clangd.applyFix', 'clangd.applyTweak']
LSP: clangd: supported code action kinds: ['quickfix', 'refactor', 'info']
LSP: clangd: Supported execute commands: ['clangd.applyFix', 'clangd.applyTweak']
LSP: clangd: supported code action kinds: ['quickfix', 'refactor', 'info']
LSP: clangd: Supported execute commands: ['clangd.applyFix', 'clangd.applyTweak']
LSP: clangd: supported code action kinds: ['quickfix', 'refactor', 'info']
```

**Describe the solution you'd like**

I would like a way to get at the clangd logs so that I have something to go on and perhaps file an issue with clangd.

Apologies if this documented somewhere and I have missed it.

**Describe alternatives you've considered**

It's happening so often that TBH I may have to consider switching to another editor :-(

**Additional context**

This a CMake-based project with a number of third-party dependencies, e.g. boost.

**Comment by rwols** [comment]
There is another output panel that prints the stderr messages. Run "LSP: Toggle Log Panel" from the command palette.

**Comment by cqc-alec** [comment]
Thank you, that did it! I will close this issue now and see what I can glean from those logs.
