### ISSUE TITLE
Close the diagnostics panel automatically on save

### ISSUE THREAD

**Issue by sylbru** [sublimelsp/LSP#1904]
**Is your feature request related to a problem? Please describe.**
When I save a file containing an error, the diagnostics panel opens automatically (in accordance to the `show_diagnostics_panel_on_save` setting). Then I fix the error and save, and the diagnostics panel now contains no errors in it (or no diagnostics equal to or less than the `show_diagnostics_panel_on_save` value). But the panel stays open and I have to type Esc to close it. 

**Describe the solution you'd like**
One of these two solutions would be great:

* Make the panel automatically close on save, under the same conditions it automatically opens (`show_diagnostics_panel_on_save` setting, even the current name would still fit, I think)
* Add a new `close_diagnostics_panel_on_save` setting, mirroring the behaviour of the existing one, but for closing the panel.

**Describe alternatives you've considered**
Typing Esc everytime I fix an error :)

**Comment by aerobounce** [comment]
Agreed.
It was distracting so ultimately I left it disabled and instead showing E | W count in status bar now.

Good example plugin that handles this nice is [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter).
SublimeLinter doesn't even have something like `auto_close_panel_on_save`, but it just closes it when it doesn't have any warning or errors.

**Comment by rchl** [comment]
This needs some more work as it can behave incorrectly when editing the document and immediately saving. Then the panel will sometimes just flash and stay hidden, even if there are relevant diagnostics present.

**Comment by predragnikolic** [comment]
closed again with https://github.com/sublimelsp/LSP/pull/2063
