### ISSUE TITLE
Trigger hover / open hover popup programatically

### ISSUE THREAD

**Issue by Narretz** [sublimelsp/LSP#1910]
**Is your feature request related to a problem? Please describe.**
The hover popup is my main utility. It works great, but when you move the mouse away or move  via keyboard, there seems to be no other way than to hover again to show the popover.

**Describe the solution you'd like**
A LSP command that triggers hover / the LSP command to get the info at the point of the selection.

**Describe alternatives you've considered**

-

**Additional context**
There is already lsp_signature_help_show, which works when you are inside a function's arguments, but not when
you are on the function name itself, or any other type.

**Comment by jwortmann** [comment]
See "Preferences: LSP Key Bindings" from the command palette.

It's already listed in the default keybindings (but commented out, so you need to add it to your user keybindings yourself):
```jsonc
    // Hover Popup
    // {
    //     "command": "lsp_hover",
    //     "keys": [
    //         "UNBOUND"
    //     ],
    //     "context": [
    //         {
    //             "key": "lsp.session_with_capability",
    //             "operator": "equal",
    //             "operand": "hoverProvider"
    //         }
    //     ]
    // },
```

**Comment by Narretz** [comment]
Oh dear, totally missed that. Thanks!
