### ISSUE TITLE
 How should I set up clangd to slove c header file cannot be found?

### ISSUE THREAD

**Issue by krisfans** [sublimelsp/LSP#1911]
**Is your feature request related to a problem? Please describe.**
My Platform:
- Windows 10
- mingw64
- clang 12

I use `clangd` as the lsp of the c language on `Windows`, but you know, clang uses msvc as the default backend on windows, while I am using gcc, so clangd will prompt that the c language header file cannot be found, as shown in the picture .

![Snipaste_2021-12-03_21-56-16](https://user-images.githubusercontent.com/57793534/144616305-b00b86ab-5a88-4f35-8f4c-8a6e99b774e1.png)

**Describe the solution you'd like**
I know in vs code I can add this in settings.json file to solve this problem .
```json
{
    "clangd.fallbackFlags": [
        "--target=x86_64-w64-mingw"
    ],
}
```
Can a similar method be used in sublime lsp? I tried the following, but it didn't work。
```json
{
	"clients":
	{
		"clangd":
		{
			"enabled": true,
			"command": [
        		"clangd",
        	],
        "settings":{
        	"clangd.fallbackFlags": ["--target=x86_64-w64-mingw"]
        },
      	"selector": "source.c | source.c++ | source.objc | source.objc++",
      	"auto_complete_selector": "punctuation.accessor | (meta.preprocessor.include string - punctuation.definition.string.end)",
		}
	}
}

```
Maybe there is a way to solve this problem by setting the `compile_flags.txt` file, but I don’t know how to do it

**Comment by satyampathak223** [comment]
Your Lsp settings file should look like this 
```
{
	"clients":
	{
		"clangd":
		{
			"enabled": true,
			"command": [
        		"clangd",
                        "-compile-commands-dir=C:\\Users\\Your Username here\\"
        	],
        },
      	"selector": "source.c | source.c++ | source.objc | source.objc++",
      	"auto_complete_selector": "punctuation.accessor | (meta.preprocessor.include string - punctuation.definition.string.end)",
		}
	}
}
```
 Now create a `compile_flags.txt` in your user home directory `Replace Your Username here with your username in settings.json`
And put the following lines in `compile_flags.txt`

`--target=x86_64-pc-windows-gnu`  
Now save the file close and open Sublime or Restart clangd server and it should work for you.

**Comment by rwols** [comment]
`fallbackFlags` is an initialization option: https://github.com/clangd/vscode-clangd/blob/b768b01cdf2c3a315abeab53f25a23d519028df4/src/clangd-context.ts#L87

So you can put it in the `initializationOptions` object. You also don't need to override the `selector`, nor the `auto_complete_selector`. Overriding the `command` is also not necessary. So this should be all that's needed:

```json
{
    "clients":
    {
        "clangd":
        {
            "enabled": true,
            "initializationOptions":
            {
                "fallbackFlags": ["--target=x86_64-w64-mingw"]
            }
        }
    }
}
```
