### ISSUE TITLE
Infinite error message loop

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#1913]
**Describe the bug**

When LemMinX failed to start, the according error dialog appears again and again after hitting ok button.

I needed to kill ST to escape this infinite loop.

**To Reproduce**

Not sure. It happened after updating LSP-LemMinX to use language server version 0.18.1 

**Expected behavior**

After dismissing the dialog (see: screenshot), ST should be usable normally.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/144715150-0bc3fee4-4bc2-405f-9a4b-a015f067089b.png)

**Environment (please complete the following information):**
- OS: Windows 11
- Sublime Text version: 4122
- LSP version: f6ab314382fa634dd0d8a2fc18ba1787a6412e5e
- Language servers used: LSP-LemMinX

**Additional context**
Add any other context about the problem here. For example, whether you're using a helper
package or your manual server configuration in LSP.sublime-settings. When using
a manual server configuration please include it here if you believe it's applicable.

**Comment by rchl** [comment]
Most likely fixed by https://github.com/sublimelsp/LSP/pull/1906

**Comment by rchl** [comment]
Let me know if you have a chance to test with that fix. I've merged it now.

**Comment by deathaxe** [comment]
Seems to work. I was able to dismiss the dialog once it appeared. Thanks!
