### ISSUE TITLE
Errors in the console from the Troubleshoot Server window

### ISSUE THREAD

**Issue by ghyatzo** [sublimelsp/LSP#1919]
**Describe the bug**
Upon running the command from the command palette `LSP: Troubleshoot Server` a new tab opens. Upon entering the mouse cursor inside the editor space (and leaving with the cursor such space) in the ST console appear these 4 lines
```
no such prop deleted_line_texture when matching text_area_control against text_area_control sheet_contents
no such prop deleted_line_texture when matching text_area_control against text_area_control sheet_contents
no such prop deleted_line_texture when matching text_area_control against text_area_control sheet_contents
no such prop deleted_line_texture when matching text_area_control against text_area_control sheet_contents
```
once when entering and once when exiting.

**To Reproduce**
1. Open command plette
2. Select `LSP: Troubleshoot Server` command
3. Open ST console
4. Move cursor in and out of the Troubleshoot Server view

**Expected behavior**
no spam in the console.

**Environment **
- OS: macOS 12.0.1
- Sublime Text version: 4121
- LSP version: 1.14
- Language servers used: clangd, erlang-ls, gopls, julia, ocaml, polymer-ide, ruby, rust-analyzer, sorbet

**Comment by rwols** [comment]
What theme are you using? Does this also occur with the Default or Adaptive theme?

**Comment by rchl** [comment]
This was fixed very recently (in dev build 4123).

**Comment by rwols** [comment]
OK well, it’s fixed in a dev build, and so should eventually show up in a new stable build.
