### ISSUE TITLE
Option to not run lsp client in unsaved buffers

### ISSUE THREAD

**Issue by aawilson** [sublimelsp/LSP#1921]
**Is your feature request related to a problem? Please describe.**
When the LSP client runs, it will evaluate a bunch of unsaved buffers I have open with the language selector. Since I use those as scratchpads, they'll very commonly evaluate errors based on the fact that they're not meant to be actually running code, but they still clutter the window with diagnostics that I have no intention of resolving.

**Describe the solution you'd like**
I'd like an option to set, preferably per-project, that will let me just skip unsaved buffers whenever they would normally be run through LSP.

**Additional context**
The diagnostics are the ones generated for `buffer://sublime/<some number>`, e.g.
![image](https://user-images.githubusercontent.com/57950/147171824-f3ed7fdf-d30b-429c-8c75-66f573debc70.png)

**Comment by jwortmann** [comment]
I think you can configure it per language server via the "schemes" setting. For example if you use LSP-pyright, then you would need to adjust the following entry in LSP-pyright.sublime-settings: https://github.com/sublimelsp/LSP-pyright/blob/6b2d860f26472628940dc7147b4d6ce212f7d915/LSP-pyright.sublime-settings#L5

Description: https://github.com/sublimelsp/LSP/blob/88076898a6dc79749314298c3cb9b3b68a3981f8/LSP.sublime-settings#L200-L211

**Comment by aawilson** [comment]
Thanks for tracking that down, that does what I need for this.
