### ISSUE TITLE
detailedLabelSupport not correctly implemented

### ISSUE THREAD

**Issue by ryuukk** [sublimelsp/LSP#1924]
**Describe the bug**

A screenshot worth more than words:

actual:

![image](https://user-images.githubusercontent.com/44361234/147585153-984f9902-b626-4cf8-a34f-44ae08a48919.png)

expected: (vscode)

![image](https://user-images.githubusercontent.com/44361234/147585217-62356cd6-53b1-4964-afaf-1c25bbad6a4e.png)

**To Reproduce**

Use D's LSP according to the documentation

https://github.com/Pure-D/serve-d/

https://lsp.sublimetext.io/language_servers/#d

**Expected behavior**

with detailedLabelSupport, i expect each completion item to properly strip the funciton parameters, so it doesn't show the item label twice.. 

**Screenshots**

please refer to the 1st block above

**Environment (please complete the following information):**
- OS: arch linux
- Sublime Text version: 4126
- LSP version: 1.14
- Language servers used: D

**Comment by jfcherng** [comment]
There is no feasible solution.

![image](https://user-images.githubusercontent.com/6594915/147589889-f5369237-ab8b-4538-8929-4b03272e5360.png)

related discuss:
- https://discord.com/channels/280102180189634562/645268178397560865/893676807616884789

**Comment by ryuukk** [comment]
Oh i see, is it being looked at by the sublime text developpers?

**Comment by predragnikolic** [comment]
I am looking at the image for the expect behavior 
and IMO displaying that much info in the autocomplete panel is distracting.

For me the LSP signature popup is used to show the parameters for a given function. 

Is it helpful to see a pretty wide autocomplete popup with a bunch of information?
And if so please emphasize what information is really important.

**Comment by ryuukk** [comment]
@predragnikolic 

showing all the line isn't the point of the feature, let's ignore it for the moment

it's the fact that no information is duplicated anymore

# before:

``create_texture --------------------------- create_texture(uint....)``

why is ``create_texture`` displayed twice?

# after:

``create_texture (uint...) --------------------------- Texture2D``


There is less confusing, and the duplication of information is no more, less distraction

--

Then for showing all the lines at once, it could be an option ``"show_details_for_all_items":  "true|false"``

**Comment by jwortmann** [comment]
1. Are you sure that the D server has the `completionProvider.completionItem.labelDetailsSupport` capability?
  I think this capability was renamed from `detailedLabelSupport`, so if the server still expects the old name, it may not send the `CompletionItemLabelDetails` at all to this client. An excerpt from the log panel with the payload when triggering autocompletions would reveal if that is the case.

    If you look at the code https://github.com/sublimelsp/LSP/blob/f1e96dcc67b1351c409e145dcb338c458977db02/plugin/core/views.py#L884 you can see that the only thing this client puts into the "annotation" field is `CompletionItem.detail`, but not `CompletionItem.labelDetails.detail`. It seems to be the case that the D server just puts everything into `CompletionItem.detail` here when it communicates with this client.
    The information from `CompletionItemLabelDetails` is only used for the "details" area at the bottom of the autocomplete popup: https://github.com/sublimelsp/LSP/blob/f1e96dcc67b1351c409e145dcb338c458977db02/plugin/core/views.py#L889-L905

2. As it was already pointed out above, your suggestion

    > `create_texture (uint...) --------------------------- Texture2D`

    is currently not possible with the ST API. If the additional details text is put into "trigger", then it would also be used for filtering of the items while typing, which probably would make the autocompletion behavior really bad.

3. Note that even VSCode does it a bit wrong; according to the [LSP specs](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItemLabelDetails), `CompletionItemLabelDetails.detail` should be

    > rendered less prominently directly after label, without any spacing.

    So it ideally should be `create_texture(uint...)`, not `create_texture (uint...)`

**Comment by ryuukk** [comment]
1. i guess so, otherwise it wouldn't work on vscode?
2.  vscode have 2 thing, label, so it show the text, and insertText, that's what get put instead of the label https://github.com/Pure-D/serve-d/blob/84094fade433f3d52e43c5296d20af53b102ffdd/source/served/commands/complete.d#L1197-L1219
3. i think the spacing was done intentionally by the D server https://github.com/Pure-D/serve-d/blob/84094fade433f3d52e43c5296d20af53b102ffdd/source/served/commands/complete.d#L1073

**Comment by jwortmann** [comment]
> 1. i guess so, otherwise it wouldn't work on vscode?

Yes, but I meant that maybe the D server expects `detailedLabelSupport` instead of `labelDetailsSupport` as a client capability, and perhaps VSCode also uses the old capability name for backwards compatibility or so. Anyway, you can test it if you set `"log_server": ["panel"]` in the LSP settings, then use "LSP: Toggle Log Panel" from the command palette and look for the server response after `textDocument/completion`. Then you can see if it contains "labelDetails" or not (I assume it doesn't).

> 2. vscode have 2 thing, label, so it show the text, and insertText, that's what get put instead of the label https://github.com/Pure-D/serve-d/blob/84094fade433f3d52e43c5296d20af53b102ffdd/source/served/commands/complete.d#L1197-L1219

Sublime LSP also supports and uses insertText. The point is that the "trigger" field is used for *filtering*. For example if you type `foo`, then do you want to see a completion item for the following?
![foo](https://user-images.githubusercontent.com/6579999/147650039-70fd35df-b088-4705-8f1f-9e991f201b82.png)


> 3. i think the spacing was done intentionally by the D server https://github.com/Pure-D/serve-d/blob/84094fade433f3d52e43c5296d20af53b102ffdd/source/served/commands/complete.d#L1073

OK, then the screenshot from VSCode makes sense.

**Comment by ryuukk** [comment]
@jwortmann 

```
{
	'kind': 3,
	'data': None,
	'label': 'create_texture',
	'labelDetails': {
		'description': 'Texture2D',
		'detail': ' (uint width, uint height, ubyte* ptr, PixelFormat format = PixelFormat.Rgba)'
	},
	'sortText': '2_4_Texture2D create_texture(uint width, uint height, ubyte* ptr, PixelFormat format = PixelFormat.Rgba)',
	'detail': 'Texture2D create_texture(uint width, uint height, ubyte* ptr, PixelFormat format = PixelFormat.Rgba)'
}
```

**Comment by jwortmann** [comment]
Maybe LSP should favor `labelDetails.description`, if it exists, over `detail` for the "annotation" field, and don't show it in the "details" area at the bottom then? I think the descriptions of the fields in the LSP specs are written in a way that doesn't consider having an additional panel area at the bottom.
```diff
     if isinstance(lsp_label_description, str): 
         # `description` should be rendered less prominent than `detail`. 
         # Additional separation is added. 
-        st_details += " - {}".format(_wrap_in_tags("i", lsp_label_description))
+        st_annotation = lsp_label_description.replace('\n', ' ')
     st_details += "</p>" 
```

This would be sililar to what VSCode uses on the right side for the items.

But it would be useful to know if other language servers use the fields in the same way.

**Comment by ryuukk** [comment]
Any news on this?

This is annoying because the current popup is unreadable, most of the info is hidden because too mutch duplicate informations

![image](https://user-images.githubusercontent.com/44361234/156785783-8fa4a898-3c5f-4ec5-b26d-92223b1397fc.png)

**Comment by rchl** [comment]
From the servers I'm using regularly (LSP-typescript, LSP-pyright, LSP-vue, LSP-dockerfile, LSP-json, LSP-terraform, LSP-yaml), none of them supports `labelDetails` it seems (or at least not for the completions I've tried) so the impact of such change would probably be pretty low but ideally someone who uses server that supports it should make such change and run with it for a while to see the upside and downside clearly.

**Comment by rwols** [comment]
What do you mean by “sublime text”? We’re all unpaid volunteers here. Please also research clangd on how it renders the labelDetails.

**Comment by rchl** [comment]
LSP is open source and it's possible to experiment with it per @jwortmann's comment. But if you'd expect a more complete solution from Sublime Text itself then it would need to be requested in its bug tracker (if it isn't already).

**Comment by rchl** [comment]
The typescript server now implements support for `labelDetails` (behind a flag) and it looks far from ideal in ST:

![Screenshot 2022-07-24 at 00 28 43](https://user-images.githubusercontent.com/153197/180624973-28ec6870-177e-4086-830a-0d70db6ba036.png)

It provides two completions, one `bar` and one `bar(x) {}` snippet but label is the same for both.

**Comment by rchl** [comment]
I guess best ST can do is something like below which looks rather weird.:

![Screenshot 2022-07-24 at 00 47 41](https://user-images.githubusercontent.com/153197/180625321-618d6556-4d88-4ab1-8851-69bbf3439d5d.png)

**Comment by rchl** [comment]
Or we could in fact try to put this into the `trigger`. The claim that it would make filtering worse would have to be tested.

![Screenshot 2022-07-24 at 16 36 36](https://user-images.githubusercontent.com/153197/180652093-b098b7e8-5634-4c5b-bb56-851e848885c5.png)

**Comment by rchl** [comment]
Did a quick change for testing: https://github.com/sublimelsp/LSP/pull/2002

**Comment by rchl** [comment]
No, the left-aligned part of the completion is a plain text and can't have styling applied.

**Comment by rwols** [comment]
> As expected, the result looks a little bit hard to differentiate, wich ends up being the hack that was used prior to that LSP suggestion
> 
> ![image](https://user-images.githubusercontent.com/44361234/180654338-a4390618-e85b-4c89-bfce-4ec02405f25e.png)

This influences the matching algorithm, which is not acceptable for me.

![image](https://user-images.githubusercontent.com/2431823/180853132-3d27cba5-cfd6-4ac0-a51e-d8d112773e13.png)

> Something like that would be better
> 
> ![image](https://user-images.githubusercontent.com/44361234/180654567-c4a26bc5-e3d2-4630-98ec-722a0d2c4f24.png)
> 
> Can theming be applied to that string so a contrast/brightness filter could be applied?

The effect you want to achieve cannot be done as there are only three slots in the completion widget which can be filled in; one is left-aligned and determines the matching, one is right-aligned and dimmed, and the last is a "detail" field (which _can_ have styling).

If you want to have this "trigger detail" in ST, you need to open a feature request here: https://github.com/sublimehq/sublime_text/issues

**Comment by predragnikolic** [comment]
This was addressed with https://github.com/sublimelsp/LSP/pull/2010

NOTE: there is still [something](https://github.com/sublimelsp/LSP/pull/2010#issuecomment-1205473391) that needs to be addressed on the server side

**Comment by rwols** [comment]
Summarizing, detailed label support is something that must also be supported from ST core. We can only do so much with the slots currently given. I hope the changes suite your workflow better. Overall I hope you get work done with your 3D engine regardless of the particular completion widget details.
