### ISSUE TITLE
No diagnostics published

### ISSUE THREAD

**Issue by nugovit** [sublimelsp/LSP#1930]
Recently I installed LSP package in Sublime Text. However, the diagnostics are not being published, and the diagnostics gutter marks are not showing (for all language servers).

Python: when I type `print(` and open the Output: Diagnostics panel, there's always the same message " No diagnostics. Well done!".

But looking in Output: Language Servers it seems to have diagnostics:
`:: <-  LSP-pyright textDocument/publishDiagnostics: {'version': 19, 'diagnostics': [{'range': {'start': {'line': 0, 'character': 5}, 'end': {'line': 0, 'character': 6}}, 'message': '"(" was not closed', 'severity': 1, 'source': 'Pyright'}], 'uri': 'file:///home/rafael/teste.py'}`

The same thing happen with other language servers.

![diagnostics1](https://user-images.githubusercontent.com/90799484/148945165-1acb13be-c3f1-434c-aa09-75184b09311d.png)
![diagnostics2](https://user-images.githubusercontent.com/90799484/148945179-e08c3b26-d993-4142-ba76-c2931ec951f4.png)

- OS: Arch Linux x86_64
- Sublime Text version: Build 4126
- LSP version: 1.15.0
- Language servers used: LSP-pyright (1.1.28), clangd (13.0.0)

**Comment by rchl** [comment]
Can you post result of `LSP: Troubleshoot Server`?

I suspect your custom settings are the reason.

**Comment by nugovit** [comment]
> Can you post result of `LSP: Troubleshoot Server`?
> 
> I suspect your custom settings are the reason.

Sure.

There it is:

# Troubleshooting: LSP-pyright
## Version
 - LSP: 1.15.0
 - Sublime Text: 4126
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/usr/bin/node "/home/rafael/.cache/sublime-text/Package Storage/LSP-pyright/17.3.0/language-server/node_modules/pyright/langserver.index.js" --stdio
```
 - selector
```
source.python
```
 - priority_selector
```
(source.python)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "pyright": {
    "dev_environment": "", 
    "disableLanguageServices": false, 
    "disableOrganizeImports": false
  }, 
  "python": {
    "analysis": {
      "autoImportCompletions": true, 
      "autoSearchPaths": true, 
      "diagnosticMode": "openFilesOnly", 
      "diagnosticSeverityOverrides": {
        "reportDuplicateImport ": "warning", 
        "reportImplicitStringConcatenation": "warning", 
        "reportMissingParameterType": "none", 
        "reportUnboundVariable": "warning", 
        "reportUninitializedInstanceVariable": "none", 
        "reportUnusedClass": "information", 
        "reportUnusedFunction": "information", 
        "reportUnusedImport": "information", 
        "reportUnusedVariable": "information"
      }, 
      "extraPaths": [], 
      "logLevel": "information", 
      "stubPath": "./typings", 
      "typeCheckingMode": "basic", 
      "typeshedPaths": [], 
      "useLibraryCodeForTypes": true
    }, 
    "pythonPath": "python", 
    "venvPath": ""
  }
}
```
 - env
```json
{
  "PATH": "/usr/bin:/usr/bin:"
}
```

## Active view
 - File name
```
/home/rafael/teste.py
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/Python/Python.sublime-syntax"
}
```
 - base scope
```
source.python
```

## Project / Workspace
 - folders
```json
[
  "/home/rafael/.config/sublime-text/Packages/User"
]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "LSP-pyright": {
      "enabled": true
    }, 
    "clangd": {
      "enabled": true
    }, 
    "ruby": {
      "enabled": true, 
      "env": {
        "PATH": "/home/rafael/.local/share/gem/ruby/3.0.0/bin/"
      }, 
      "initializationOptions": {
        "diagnostics": true
      }
    }
  }, 
  "log_debug": true, 
  "log_server": [
    "panel"
  ], 
  "show_diagnostics_panel_on_save": 1, 
  "show_diagnostics_severity_level": 1
}
```
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /var/lib/snapd/snap/bin
 - /usr/local/sbin
 - /usr/bin/site_perl
 - /usr/bin/vendor_perl
 - /usr/bin/core_perl

**Comment by rchl** [comment]
LSP currently filters out diagnostics for files that are not part of the project folders. Your project folder is `/home/rafael/.config/sublime-text/Packages/User` and the file is at `/home/rafael/teste.py` so it's not part of the folder.

You can open the file in its own window, without adding a folder to the project and then it will work.

It's not recommended to add your whole home directory as a folder as that could take a lot of memory and CPU resources.

**Comment by rchl** [comment]
Semi-related issue: #1835

**Comment by nugovit** [comment]
Now the diagnostics are showing up. Thank you.
