### ISSUE TITLE
Support for Astro

### ISSUE THREAD

**Issue by joshstobbs** [sublimelsp/LSP#1940]
**Is your feature request related to a problem? Please describe.**
This is a request to add a new language server, specifically for [Astro](https://astro.build)

**Describe the solution you'd like**
I've recently discovered that the Astro team publishes their language server [here](https://github.com/withastro/language-tools/tree/main/packages/language-server), additionally they publish all their language tools [here](https://github.com/withastro/language-tools) (VS Code extension, and a Typescript plugin).  In my brief reasoning I had hoped that maybe the language server could help in creating an lsp extension that could go to package control.

**Describe alternatives you've considered**
Honestly this is my first stop, I could try to put something together but I have essentially no experience working with language server and my Python is rough at best.  I was hoping that with what is available to someone versed in this could make short work of it.

**Additional context**
Have a great day, and thanks for reading!  If you have any questions I can of course try to help.

**Comment by TheSecEng** [comment]
@joshstobbs I would create this package but I don't want to get stuck with the bill of maintaining it :D

But I encourage you to look at LSP-deno as an example. Since this is a node package. LSP has an amazing NpmClient which handles almost all of the work.

That would get you up and running initially

**Comment by deathaxe** [comment]
I've created https://github.com/deathaxe/LSP-astro

If someone coud add a public repo in this organization, ... .

**Comment by rchl** [comment]
> I've created [deathaxe/LSP-astro](https://github.com/deathaxe/LSP-astro)
> 
> If someone coud add a public repo in this organization, ... .

Done.
Could you create a PR against it (just for the initial visibility)?

**Comment by rchl** [comment]
https://github.com/sublimelsp/LSP-astro
