### ISSUE TITLE
Side by side option for symbol action links in hover popup doesn't work if location is in same file

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#1946]
**Describe the bug**
The side by side icon link for "Definition" / "Type Definition" / "Declaration" from the hover popup doesn't work if the location of the definition/declaration is in the same file.

**To Reproduce**
1. Have `"show_symbol_action_links": true` in the settings (this is the default value)
2. Hover over symbol (e.g. function call) which has a definition in the same file
3. Click on ◨ next to "Definition", or use <kbd>Ctrl</kbd> + click on the text link
4. See that the view scrolls to the location, instead of opening the location in a new tab to the right

**Expected behavior**
LSP should open the definition in a new new to the right, similar to how the built-in definitions popup from ST does

**Environment (please complete the following information):**
- OS: Win 10
- LSP version: main

**Additional context**

Seems like the `flags` argument which includes the "side_by_side" information is lost/ignored here:
https://github.com/sublimelsp/LSP/blob/1bcd518102c1516c9d808c974b7d2a5eba7d0b80/plugin/core/open.py#L30-L31

**Comment by rchl** [comment]
Thanks for the exact pointer. :)

I've made something quickly, not sure if the logic is fully robust though. https://github.com/sublimelsp/LSP/pull/1950
