### ISSUE TITLE
Syntax highlighting not working in hover popup

### ISSUE THREAD

**Issue by prime31** [sublimelsp/LSP#1953]
**Describe the bug**
When hovering over a type/method the popup that is shown does not have syntax highlighting enabled. See attached image. It is very possible I haven't properly set something up correctly with regard to syntax highlighting in popups. Note that syntax highlighting does work fine for the regular code editor views.

**To Reproduce**
Steps to reproduce the behavior: (tested using Zig language and Zig Language Server)
1. Hover any type/method
2. See that popup doesn't have syntax highlighting

**Expected behavior**
It is expected that the popup would have syntax highlighting enabled.

**Screenshots**
<img width="939" alt="Screen Shot 2022-03-26 at 11 02 03 PM" src="https://user-images.githubusercontent.com/60377/160268943-58fdbf21-e42d-491f-af1d-440be28311a7.png">

**Environment (please complete the following information):**
- OS: macOS 12.3 (21E230)
- Sublime Text version: 4126
- LSP version: Zig Language Server master branch
- Language servers used: Zig

**Additional context**
Manual server config:
```
	"clients": {
		"zls": {
			// enable this configuration
			"enabled": true,
			// the startup command -- what you would type in a terminal
			"command": ["~/zig/zls/zig-out/bin/zls"],
			// the selector that selects which type of buffers this language server attaches to
			"selector": "source.zig"
		}
	}
```

**Comment by rwols** [comment]
The code block highlighting depends on three factors:

- The hover response that zls returns may or may not highlight the code block. To see if that is the case, enable debug output and open the log panel.

- If zls does indicate to highlight the code block, then mdpopups (a dependency that LSP uses to transform Markdown into minihtml) needs a way to map a Markdown language ID to a Sublime syntax file.

- Finally, the Sublime syntax used must be able to understand/parse the constructs in the code block.

**Comment by rwols** [comment]
I see that mdpopups supports zig: https://github.com/facelessuser/sublime-markdown-popups/blob/aeb7586da26fe46b7764cf1e2832336bc306195d/st3/mdpopups/st_mapping.py#L61

so we need to know

1) the payload of zls to the hover request to make sure that zls sends back a code block with a `zls` Markdown Language ID (see https://lsp.sublimetext.io/troubleshooting/#self-help-instructions)
2) Did you install the package "Zig Language" from PC and is its location `$DATA/Installed Packages/Zig Language.sublime-pacakge`?

**Comment by prime31** [comment]
Genius! That was it. I use my own custom Zig plugin so i just had to move it to `Packages/Zig Language` and it worked like a champ. Thanks for the crazy fast responses and solution!

**Comment by prime31** [comment]
I should also thank you for the LSP package. It is utterly fantastic. I switched over from VS Code and have found your LSP package to be far more stable. Many thanks!
