### ISSUE TITLE
There is no `MarkdownLangMap` for ST 3

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#1956]
LSP-pyright uses [MarkdownLangMap](https://github.com/sublimelsp/LSP-pyright/blob/ecb4d04586f52c21b8783af9afcc8a5b2f38917d/plugin.py#L1) for its custom syntax in the hovered popup.

Wondering will `MarkdownLangMap` be ported to the st3 branch?

Related issue: https://github.com/sublimelsp/LSP-pyright/issues/146

**Comment by jfcherng** [comment]
No longer interest.

**Comment by rwols** [comment]
Yeah I don’t think I’ll ever port this.
