### ISSUE TITLE
Emmet preview not working with LSP-html

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP#1958]
**Describe the bug**
Emmet normally shows a preview of complex abbreviations. When LSP-html is active, the preview only flashes shortly or is missing completely.

**To Reproduce**
1. Install Emmet, LSP, LSP-html
2. Open an HTML file
3. Type a complex abbreviations

**Expected behavior**
The preview should be displayed

**Environment (please complete the following information):**
- OS: Arch Linux
- Sublime Text version: 4129
- LSP version: 1.16.1
- Language servers used: LSP-html

**Additional context**
none

**Comment by rwols** [comment]
Did you also open an issue at the emmet package?

**Comment by LDAP** [comment]
I did not. Wasn't really sure if it is a LSP or Emmet Bug (or both).

**Comment by rwols** [comment]
Emmet uses view.show_popup to display the completion. I don’t know what triggers the popup to disappear.

**Comment by rwols** [comment]
Can you enable sublime.log_commands(True) in the console and see if there is any correlation there?

**Comment by LDAP** [comment]
Nothing correlated is logged. 

But I should mention that LSP complains that the file isn't inside window folders. That is the only message logged, besides deletes and character inserts.

**Comment by jwortmann** [comment]
Just because it wasn't pointed out in the previous discussion yet; I believe this happens because of this line
https://github.com/sublimelsp/LSP/blob/36b0bc9a8b772569f06654ab4cae58e6af7f3cf8/plugin/documents.py#L577
which is called after each buffer modification if the language server supports signature help (and has triggerCharacters defined).

**Comment by predragnikolic** [comment]
How can I reproduce this @LDAP ?

For me this looks like its working as expected
[Screencast from 2023-09-24 11-42-15.webm](https://github.com/sublimelsp/LSP/assets/22029477/735aae88-f2eb-487a-82f5-980eb5bc8585)

LSP v1.25.0

**Comment by LDAP** [comment]
Haven't used Emmet for a while. Might be fixed in the meantime? I can't reproduce it either. 

We can close and reopen if the issue occurs in the future.
