### ISSUE TITLE
Selecting / copying type signature in overlay

### ISSUE THREAD

**Issue by dvcrn** [sublimelsp/LSP#1959]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to select text in the overlay when hovering a function: 

<img width="764" alt="Screen Shot 2022-04-07 at 15 39 57" src="https://user-images.githubusercontent.com/688326/162135995-781e4ffe-d23d-4517-bf0e-ca3b7f83b7bd.png">

I sometimes find myself having to copy the signature to use it in different places, but with sublime-lsp I can't (vscode can). 

Is this a limitation of Sublime Text in general or can we do something about it to make it selectable?

**Comment by rchl** [comment]
It's a ST limitation that text can't be selected in the popups - https://github.com/sublimehq/sublime_text/issues/1649

All a plugin could do is expose a copy button that would copy everything but that would not be as convenient and also would be rather tricky to handle with HTML content.

**Comment by dvcrn** [comment]
Okay, thought so! Thanks

**Comment by rwols** [comment]
Same reason why you can't select anything in the release notes window.

**Comment by tukusejssirs** [comment]
I miss this feature as well. I know there are already some issues open for ST (sublimehq/sublime_text#3471, sublimehq/sublime_text#1649), but in both issues, someone suggests to work around this issue by providing a button to copy the text [see [#3471 (comment)](https://github.com/sublimehq/sublime_text/issues/3471#issuecomment-1140443235), [sublimehq/sublime_text#1649 (comment)](https://github.com/sublimehq/sublime_text/issues/1649#issuecomment-293500592)].

Could we add an action to copy the text? Or even better, could we add multiple buttons, each to copy different text (note: I code mostly in TypeScript):
- copy the (usage) code shown in the pop-up;
- copy the docs (JSDoc/TSDoc/whatever);
- copy the type;
- copy the definition;
- copy the error:
  - each error should have a separate copy button.

This could be configurable, as one might want to show all copy buttons, others only subset. It should be configurable globally and per language server.

A copy button could be an icon/symbol, just like we already have for opening a file in a group (tile). This icon could be be place after the action name (or after _open in group_ symbol). As for errors, it could be placed after the error message (or after the error identifier, e.g. `typescript:$erro_code_number`).

**Comment by kylebebak** [comment]
@rchl @rwols 

I've got nothing new to say, just want to advocate for adding a button that copies the text in the popup. If this includes HTML tags and other stuff not visible in the popup I think that's fine, it's a lot better than no copy function at all. Copying this text is an uncommon but not rare use case, so it's not important that the feature be polished, just that it exist

Agree that it would be good to make this configurable, i.e. expose a Sublime LSP setting for enabling / disabling this copy button. FWIW I don't think it's necessary to have more than one copy button, or enable/disable it per language server, one global config flag is enough
