### ISSUE TITLE
uri incorrectly encoded

### ISSUE THREAD

**Issue by Ekopalypse** [sublimelsp/LSP#1966]
According to my understanding and the [ .ts module](https://github.com/Microsoft/vscode-uri)
of MS, an  [URI](https://microsoft.github.io/language-server-protocol/specification#uri) must be encoded accordingly.
For example, a file path like `D:\temp\test.py` must be encoded as `file:///D%3A/temp/test.py`
Language servers that rely on this may have a problem if it is ignored by the plugin.

**Comment by rwols** [comment]
I'm unsure what you think is incorrect about the URI. But I'll assume you're talking about `D:\temp\test.py` being transformed into `file:///D:/temp/test.py` and you expect instead the colon to be hex-escaped into `%3A`.

https://datatracker.ietf.org/doc/html/rfc3986, section 3.3 tells me that `file:///D:/temp/test.py` is a valid encoding for `D:\temp\test.py`. Specifically it's the `path-absolute` variant where `:` is a valid character of `pchar`.

**Comment by Ekopalypse** [comment]
Thank you for the quick reply, and you are right, I am referring to the hexadecimal encoded variant.
I am sorry that I did not make myself clear. 
Yes, that makes sense, but since the default implementation VSCode handles this differently, I was thinking along those lines. If you think it doesn't make sense to change this, and that servers need to be prepared to receive different variants of an encoded file path, feel free to close this issue.
Thank you very much for your time and understanding, I appreciate it.

**Comment by rwols** [comment]
Not a problem! I've encountered this type of question before so I know what to answer. Basically, I'm defending the use of Python's [pathname2url function](https://docs.python.org/3/library/urllib.request.html#urllib.request.pathname2url). It's hard to imagine that function is somehow incorrect. And according to the RFC, it is indeed correct.

In terms of a solution, you could always run a hypothetical `hexDecode` function on path components of an incoming `file` URI and consider that to be the normal form of a path.

**Comment by rwols** [comment]
By the way, when dealing with `file` URIs, there is also the problem of canonicalization of paths (two different paths could point to the same file due to symlinks). So when you're using URIs as keys in a map, beware.

**Comment by Ekopalypse** [comment]
Thank you, I understand and agree. Have a nice weekend.

**Comment by Ekopalypse** [comment]
Thanks also for the tips - and yes, this is exactly where the issue happened :-)
