### ISSUE TITLE
Get back built-in Sublime Text hover popup

### ISSUE THREAD

**Issue by rusproject** [sublimelsp/LSP#1967]
Hello! 

LSP popup doesn't show list of references and definitions, it only shows `definitions` and `references` links which I found unhandy.

I only want to see LSP popup when I press some hotkey, but not on mouse hover. On mouse hover I want to see built-in Sublime Text 4 popup hover, but there is 2 problems:

1) If I turn on Sublime Text popups back by setting `view.settings().set("show_definitions", True)`, it automatically sets to False again after sublime text restart.

2) Solution for disabling LSP popup, which was provided in [#574]( https://github.com/sublimelsp/LSP/issues/574) doesn't works for me at all: I tried to add `"disabled_capabilities": ["hover"],` in my `LSP.sublime-settings` but popups are still here.

**Comment by jwortmann** [comment]
You need to use
```jsonc
{
    "disabled_capabilities": {
        "hoverProvider": true
    },
}
```
in the client settings (i.e. per server) to disable LSP's hover popups. But at the same time, this will prevent to use a user-keybinding for the `lsp_hover` command, because when the command runs, it will also check whether this capability is enabled: https://github.com/sublimelsp/LSP/blob/e14bf5de0cacabea9545cf88f27cea7fa8e4e840/plugin/hover.py#L146
Perhaps there should be another setting to turn on/off popups on mouse hover.

Also related: #1184

**Comment by rusproject** [comment]
It would be great if such feature was released. 

Is here temporarily workaround? Maybe we could use console commands for enabling and disabling "hoverProvider", and bind them to hotkeys?

Is there a way to prevent LSP to automatically set "show_definitions" to False after ST4 restart?

**Comment by rusproject** [comment]
> You need to use
> 
> ```js
> {
>     "disabled_capabilities": {
>         "hoverProvider": true
>     },
> }
> ```
> 

It doesn't work, popups still appears, what am I doing wrong? Screenshot of my LSP.sublime-settings file:

![image](https://user-images.githubusercontent.com/62891105/169260780-3272c8b1-1992-4c58-ba89-a0599c64d2ce.png)

**Comment by rchl** [comment]
> It doesn't work, popups still appears, what am I doing wrong? Screenshot of my LSP.sublime-settings file:

It needs to be set per-server. so in LSP-typescript settings (or whatever server you are using).

> Can you please provide information on the second question: Is there a way to prevent LSP to automatically set "show_definitions" to False after ST4 restart?

Setting stuff on the view is only gonna persist until that file is closed. That's ST behavior, not really LSP.
`show_definitions` is a normal ST setting so you can just set it in ST `Preferences`.

**Comment by rusproject** [comment]
Thank you, now it works. 

I wrote a comment in [#1184](https://github.com/sublimelsp/LSP/issues/1184) with use-cases and my vision on working with native and LSP popups alongside

**Comment by rusproject** [comment]
> `show_definitions` is a normal ST setting so you can just set it in ST `Preferences`.

For some reason it doesn't work for me: if an LSP hover-popup is turned on, after each start of Sublime Text, this setting resets to `false` until I manually set it True through ST console.

**Comment by rchl** [comment]
> For some reason it doesn't work for me: if an LSP hover-popup is turned on, after each start of Sublime Text, this setting resets to `false` until I manually set it `True` through the console.

True, I can see now that LSP modifies that setting before showing the hover popup. It only does it when the server supports `hoverProvider` though so if you disable it for all servers that run on a given file then it should not do that anymore.

**Comment by rusproject** [comment]
> True, I can see now that LSP modifies that setting before showing the hover popup. It only does it when the server supports `hoverProvider` though so if you disable it for all servers that run on a given file then it should not do that anymore.

Yes it helps but occasionally it returns back to False, didn't figured out why yet, but maybe it happens after viewing file with other language server, probably... (although I have installed only one, LSP-intelephense)

By the way, I almost found a solution for my initial question, since I can set keybinding for default ST "show_definition" command, to hop between LSP and ST hovers, I could disable ST `"show_definition"` when needed, then enable LSP `"hoverProvider"`, and vise-versa. It would an acceptable workaround for me, but I don't know what command should I bind to hotkey to disable or enable LSP hoverProvider, can you please help with it?
