### ISSUE TITLE
Unexpected change in autocomplete order

### ISSUE THREAD

**Issue by willrowe** [sublimelsp/LSP#1972]
**Describe the bug**
Since Sublime build 4134, I have noticed that the initial autocomplete suggestions have changed and the closest matching suggestion is no longer displayed at the top. I am not sure if it is specific to lsp-intelephense, but it is where I am seeing the issue most obviously. You can see some more details [on Discord](https://discord.com/channels/280102180189634562/645268178397560865/981600507619602472), but it seems to be that the initial suggestions shown are incorrect and triggering autocomplete again shows as expected.

**To Reproduce**
1. Open Sublime Text in safe mode.
2. Install Package Control.
3. Install LSP package.
4. Install LSP-intelephense package.
5. Open a new buffer.
6. Type the following:
    ```php
    <?php

    $variable = 'value';

    $another = 
    ```
7. When typing `$` at the end of the last line the following is displayed, which is expected:
![Screen Shot 2022-06-02 at 09 11 49](https://user-images.githubusercontent.com/7152423/171636961-570b407e-3f21-462f-8f32-e579d12a6ae9.png)
8. Then when typing a `v` after that, the following is displayed, which is not expected:
![Screen Shot 2022-06-02 at 09 12 18](https://user-images.githubusercontent.com/7152423/171637043-c31ca04a-fd96-4314-a65f-8a73b016a5e1.png)
9. Finally, if autocomplete is triggered manually, the following is displayed, which shows what I expect and what it was doing seemingly before build 4134:
![Screen Shot 2022-06-02 at 09 12 43](https://user-images.githubusercontent.com/7152423/171637125-22a52fa3-05d1-412c-a55d-30dacecba86d.png)

**Expected behavior**
The closest match should be displayed at least towards the top of the suggestions.

**Screenshots**
Included in context above.

**Environment (please complete the following information):**
- OS: macOS 11.6.1
- Sublime Text version: 4134
- LSP version: 1.16.2
- Language servers used: intelephense (1.0.25)

**Comment by rwols** [comment]
Perhaps this has nothing to do with, but I'm seeing this unit test failing on build 4134

test_var_prefix_using_label (test_completion.QueryCompletionsTests) ... FAIL

**Comment by rwols** [comment]
And the CI doesn't detect this regression because it downloads the stable version: https://github.com/SublimeText/UnitTesting/blob/master/scripts/install_sublime_text.sh#L70

by scraping this URL apparently: `curl https://www.sublimetext.com/download_thanks`

**Comment by rchl** [comment]
@willrowe I believe that in both steps 1 and 2 the expected completions are all there. They are just not being sorted and matched properly because the `$` doesn't seem to be taken into account when matching. You can verify that by scrolling the list and looking for expected completions.

**Comment by rchl** [comment]
Created core issue: https://github.com/sublimehq/sublime_text/issues/5437

**Comment by rwols** [comment]
If `$` is not taken into account when matching, then the failing test seems to indeed correctly detect that: https://github.com/sublimelsp/LSP/blob/80d4cbe341a2f7b59601c82ef4bb22f84133aa40/tests/test_completion.py#L130

**Comment by willrowe** [comment]
As mentioned in https://github.com/sublimehq/sublime_text/issues/5437, this appears to be fixed in build 4138.
