### ISSUE TITLE
Add setting to disable function signature/help popup  

### ISSUE THREAD

**Issue by giampaolo** [sublimelsp/LSP#1976]
Hello, and thanks for maintaining this crucial python tool.

I'm looking for a way to disable the function signature popup which automatically appears when I type a function parentheses `(`. I find it particularly distracting because it often displays a long list of type hints, see:

![screen](https://user-images.githubusercontent.com/681260/173904346-fd022680-4e1a-4d30-a41f-4b0313811d57.png)

The only (hackish) solution I've found to disable it was to copy `LSP/plugins/documents.py` into `~/.config/sublime-text-3/Packages/LSP/plugin/documents.py`, and add `return` statement at this line:  
https://github.com/sublimelsp/LSP/blob/e14bf5de0cacabea9545cf88f27cea7fa8e4e840/plugin/documents.py#L463

Would it be reasonable to add a setting which disables this popup explicitly? Or are there other ways to accomplish this goal?

Thanks!

**Comment by giampaolo** [comment]
Thanks a lot, that worked. The confusing part is that `"disabled_capabilities"` option is mentioned in LSP config, but it ends up being applied to pyright config (where it's not mentioned). For future readers using pyright and for extra clarity: the file to modify is `User/LSP-pyright.sublime-settings`.

**Comment by fredcallaway** [comment]
Is it possible to disable the automatic popup while still being able to pull it up when we want it?

**Comment by rchl** [comment]
```js
    "disabled_capabilities": {
        "signatureHelpProvider": {
            "triggerCharacters": true,
            "retriggerCharacters": true
        }
    },
```

**Comment by fredcallaway** [comment]
Thanks for the help @rchl! Unfortunately, adding this to my LSP.sublime-settings doesn't seem to have any effect (fully disabling it does).
