### ISSUE TITLE
Remove all code that seeks to manage installation of tools 

### ISSUE THREAD

**Issue by airtonix** [sublimelsp/LSP#1978]
**Is your feature request related to a problem? Please describe.**

I use [ASDF](https://asdf-vm.com/) to manage all the tools each of my projects might use (they're different for each one).

Unless I start `subl` in the root of a project, then none of the LSP plugins are able to find the binary they need.

**Describe the solution you'd like**
- abandon the philosphy of "If the tool is missing for the user, let's install it for the user"
- replace it with "If the tool is missing for the user, ask them to install it"
- don't assume that resolving the tool will occur from the `LSP` or `LSP-*` package root, instead opt to resolve the binary in this order
  - where `cwd` is the directory of the currently open file, or
  - where `cwd` is the root directory of the currently open project, or
  - where `cwd` is the same place where `subl` was launched.

**Comment by rwols** [comment]
I'd suggest that for each of your asdf projects you also write a .sublime-project where you set up your configuration. And then don't install LSP-* helper packages. See https://lsp.sublimetext.io/guides/client_configuration/#per-project-overrides

**Comment by rchl** [comment]
You can't just ask us to flip everything upside down without even explaining your problem properly and providing specific use cases.

It seems like you are a little confused about things...

The reason that starting `subl` from the root of the project works and starting otherwise doesn't has nothing to do with `cwd` which is not relevant to LSP (to be clear, I'm talking about `cwd` used for starting ST). The reason that makes things work for you is because ST inherits environment variables from the terminal when starting that way. So it says the PATH that ASDF has set up for that directory. None of your suggested changes would help with that problem.

**Comment by rchl** [comment]
Just to reiterate... your specific problem is not gonna be solved by LSP.

What you are asking for is mimicking a logic of `ASDF` where it sets up some environment variables for the current shell when switching to a specific directory. ST has only one "environment" and can't set different variables per-project so that's not really compatible with it.

The only non-trivial solution for something like that that I can think of would be to:
 - create some custom plugin that sources environment variables for project directory on opening a project
 - dynamically create or update a LSP client configuration in the project data with those sourced environment variables.

**Comment by airtonix** [comment]
Needs to be reopened.

LSP needs to be refactored so it doesn't assume that the context to executing the tool is cwd.
Instead it needs to inspect the project root and do it there.

**Comment by airtonix** [comment]
And it looks like you don't understand how ASDF works.

It doesn't set path variables.

It's always on the path.

It has shim executables that are always on the path.

When they run they look in the current directory for `.tool-versions` file. If one isn't in the current directory then it looks in the parent... Etc.

When I launch sublime from terminal the cwd is correct.

When I don't launch from terminal, and switch project the cwd is my home folder which is wrong.

Your LSP has code that decides where to execute a tool...

 It needs to be in the same directory as the sublime-project file.

Not whatever sublime says is the cwd.

**Comment by airtonix** [comment]
Vscode doesn't have this problems btw

**Comment by rchl** [comment]
You are wrong. CWD is not assumed and is mostly irrelevant to the lookup of the server.

If you create a client configuration you typically provide just a binary name and Python resolves its path based on the paths provided in the PATH environment variable (this is Python, not LSP-specific).

If you are using one of the LSP-* helper packages then those by design use bundled server instances (typically) as this results in least amount of friction. You don't have to use those packages.

As far as VSCode, what specific server/extension are you talking about? It also uses bundled binaries for many of the servers so be more specific.

**Comment by rchl** [comment]
I don't know which server are you having issues with.

I'll go ahead and assume `gopls` as an example.
If you'll create a client configuration like:
```js
    "gopls": {
      "command": [
        "gopls"
      ],
      "selector": "source.go",
    },
```
Then LSP will attempt to start it in CWD of the current project. Python will only be able to start it if `gopls` is found in the `PATH` but if it is the the working directory should be of the current project.

**Comment by jwortmann** [comment]
I'm not sure if I understand the problem correctly and whether it is "where to look for the server executable (or interpreter executable which starts the server code)" or if it is rather "how to set the working directory where the process is started".

For the second question and if you use/develop a LSP-* helper package, then you can set the working directory where the tool is started from the `AbstractPlugin.on_pre_start` method:
https://github.com/sublimelsp/LSP/blob/2ac87a73b3a4d95c74d10c39caca4d5820d31e0c/plugin/core/sessions.py#L773-L789

I use this for example for the Julia language server, which uses the cwd to determine the project environment: https://github.com/sublimelsp/LSP-julia/blob/e0f6dcb9a87bfcf986607378c90c5236a775609e/plugin.py#L179-L196
If you would like to set the cwd of the server via a config setting in a .sublime-settings file, then this wouldn't be sufficient in general, because there might be some programming logic required to determine the correct directory (like in the example from the link above).

---

If the problem is "where to look for the server executable", then maybe we can think about to resolve some simple variables like `$file_path` similar to .sublime-build files, if they occur in the "command" setting? This would happen somewhere in https://github.com/sublimelsp/LSP/blob/2ac87a73b3a4d95c74d10c39caca4d5820d31e0c/plugin/core/transports.py#L242-L243

But I don't really see a point in that, because why would you want to use different server versions (instead of the latest available version) for different projects? And then you would need to create separate copies of the server executables into all of your project folders or something like that. In case you have an old project where for whatever reason the latest language server version doesn't work, then you could already achive it via config in a .sublime-project file as described in https://github.com/sublimelsp/LSP/issues/1978#issuecomment-1166318145.

And as mentioned, in VSCode you have even fewer or no config options at all for this, because all the servers come bundled in the extensions.

**Comment by airtonix** [comment]
> But I don't really see a point in that, because why would you want to use different server versions (instead of the latest available version) for different projects? And then you would need to create separate copies of the server executables into all of your project folders or something like that. 

for numerous reasons, the biggest and most well accepted and widely experienced one being: That you do not have the luxury of spending eternity continually upgrading every single one of your projects to the latest version of whatever language engine they use.

You do this by describing a  `.tool-versions` file in the root of every project that looks like: 

```
golang 1.18
just 1.2.0
act 0.2.28
nodejs 17.7.1
```

any execution of commands provided by the above engines within the child directories of the above file are actually executing a shim binary in `~/.asdf/shims/*` (for example there is `~/.asdf/shims/node`, `~/.asdf/shims/npm`, `~/.asdf/shims/pnpm` (because i installed the asdf-pnpm plugin) etc.

So for julia, i'd install https://github.com/rkyleg/asdf-julia and then i'd have whatever binaries a julia engine would normally provide.

if i put in the projects `.tool-versions` file : 
```
julia x.x.x
```

then the julia related shims would divert execution to their real versions in `~/.asdf/installs/julia/x.x.x/bin` .

All of this is automatic.

**Comment by airtonix** [comment]
It's quite perplexing that this requires such laborious explanation.

I would have thought people with such proported experience would have encountered the incredibly obvious requirement for a tool such as ASDF.

**Comment by rchl** [comment]
If I'm condescending then you are arrogant and full of yourself, coming here, demanding that we "Remove all code that seeks to manage installation of tools" and implement your specific solution without really explaining the problem properly.

If you are not willing to provide enough details about the issue and answer our questions then I might as well not want to spend time investigating how asdf works. You are the one asking us to address your issue and I'm not being paid for that.

With that said, you can enable the `lsp_debug` LSP setting and then LSP will tell you in the ST log panel where it's starting the server (`LSP: starting <cmd> in <cwd>` line). It generally sets to `cwd` to project's root so if that doesn't work in some specific cases then EXPLAIN WHERE AND PROVIDE REPRODUCTION.

**Comment by rchl** [comment]
And also read and understand https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers as your issue might be with asdf shim not being on the PATH and that would be ST and not LSP-specific problem.

**Comment by airtonix** [comment]
:) 

```
LSP: starting ['/home/zenobius/.cache/sublime-text-3/Package Storage/LSP-gopls/bin/gopls'] in /home/zenobius/Projects/Mine/Github/golang/bee-game
```

I don't want it to run `/home/zenobius/.cache/sublime-text-3/Package Storage/LSP-gopls/bin/gopls`.

I want it to just run `gopls` which will resolve to the asdf shim and thus the exact version i want my project to be using.

because like i said above: asdf shims are always on PATH: 

```'/home/zenobius/.asdf/shims:/home/zenobius/.asdf/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/root/.android/android-sdk-linux/build-tools/23.0.2:/root/.android/android-sdk-linux/tools/:/root/.android/android-sdk-linux/build-tools/:/root/.android/android-sdk-linux/platform-tools/:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/var/lib/snapd/snap/bin'```

```
$ > ls -al ~/.asdf/shims                                                                                                                                                                                         
total 704
drwxr-xr-x.  2 zenobius zenobius 4096 Jul 30 15:37 .
drwxr-xr-x. 17 zenobius zenobius 4096 Aug 14  2021 ..
-rwxr-xr-x.  1 zenobius zenobius  129 Jun 24 08:54 2to3
-rwxr-xr-x.  1 zenobius zenobius  106 Jun 24 08:54 2to3-3.10
-rwxr-xr-x.  1 zenobius zenobius  104 Sep 24  2021 2to3-3.9
-rwxr-xr-x.  1 zenobius zenobius  149 Jul 14 11:33 act
-rwxr-xr-x.  1 zenobius zenobius  203 Apr 13 16:51 appletviewer
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 20 08:53 asmfmt
-rwxr-xr-x.  1 zenobius zenobius   99 Jun 20 13:15 aws
-rwxr-xr-x.  1 zenobius zenobius  109 Jun 20 13:15 aws_completer
-rwxr-xr-x.  1 zenobius zenobius  100 Jun 25 15:53 bazel
-rwxr-xr-x.  1 zenobius zenobius  127 Jan 20  2022 cargo
-rwxr-xr-x.  1 zenobius zenobius  134 Jan 20  2022 cargo-clippy
-rwxr-xr-x.  1 zenobius zenobius  131 Jan 20  2022 cargo-fmt
-rwxr-xr-x.  1 zenobius zenobius  132 Jan 20  2022 cargo-miri
-rwxr-xr-x.  1 zenobius zenobius  163 Apr 13 16:51 clhsdb
-rwxr-xr-x.  1 zenobius zenobius  135 Jan 20  2022 clippy-driver
-rwxr-xr-x.  1 zenobius zenobius   98 Jul 14 17:37 clq
-rwxr-xr-x.  1 zenobius zenobius  109 Jun 20 16:35 copilot
-rwxr-xr-x.  1 zenobius zenobius  281 Jun 23 17:59 corepack
-rwxr-xr-x.  1 zenobius zenobius  198 Jun 15 19:26 create-next-app
-rwxr-xr-x.  1 zenobius zenobius  201 Jun 15 19:26 create-nextron-app
-rwxr-xr-x.  1 zenobius zenobius  107 Jun 15 19:26 create-npm
-rwxr-xr-x.  1 zenobius zenobius  116 Jun 25 15:42 create-nx-workspace
-rwxr-xr-x.  1 zenobius zenobius  172 Jun 15 19:26 create-webextension
-rwxr-xr-x.  1 zenobius zenobius  111 Jun 24 08:22 create-webpack
-rwxr-xr-x.  1 zenobius zenobius   98 Jun 13 20:59 dlv
-rwxr-xr-x.  1 zenobius zenobius  105 Jul  1 20:10 earthly
-rwxr-xr-x.  1 zenobius zenobius  107 Jun 28 08:39 ebitenmobile
-rwxr-xr-x.  1 zenobius zenobius   98 Jun 13 20:59 ecs
-rwxr-xr-x.  1 zenobius zenobius   97 Apr 13 16:55 erb
-rwxr-xr-x.  1 zenobius zenobius  103 Jun 20 08:53 errcheck
-rwxr-xr-x.  1 zenobius zenobius  165 Apr 13 16:51 extcheck
-rwxr-xr-x.  1 zenobius zenobius  105 Jun 20 08:53 fillstruct
-rwxr-xr-x.  1 zenobius zenobius   97 Jul 19 20:46 fzf
-rwxr-xr-x.  1 zenobius zenobius  102 Jul 19 20:46 fzf-tmux
-rwxr-xr-x.  1 zenobius zenobius   97 Apr 13 16:55 gem
-rwxr-xr-x.  1 zenobius zenobius  136 Jul 21 16:02 gh
-rwxr-xr-x.  1 zenobius zenobius  209 Jun 20 17:36 go
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 29 21:49 gobind
-rwxr-xr-x.  1 zenobius zenobius  100 Jun 20 08:53 godef
-rwxr-xr-x.  1 zenobius zenobius  212 Jun 20 17:36 gofmt
-rwxr-xr-x.  1 zenobius zenobius  104 Jun 20 08:53 goimports
-rwxr-xr-x.  1 zenobius zenobius  144 Jun 20 18:41 golangci-lint
-rwxr-xr-x.  1 zenobius zenobius  103 Jun 29 21:49 gomobile
-rwxr-xr-x.  1 zenobius zenobius  107 Jun 20 08:53 gomodifytags
-rwxr-xr-x.  1 zenobius zenobius  129 Jun 20 17:36 gopls
-rwxr-xr-x.  1 zenobius zenobius  110 Jun 19 19:24 goreleaser
-rwxr-xr-x.  1 zenobius zenobius  103 Jun 20 08:53 gorename
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 20 08:53 gotags
-rwxr-xr-x.  1 zenobius zenobius  100 Jun 16 20:05 gotip
-rwxr-xr-x.  1 zenobius zenobius  102 Feb  6 08:48 gradle
-rwxr-xr-x.  1 zenobius zenobius  106 Feb  6 08:48 gradle.bat
-rwxr-xr-x.  1 zenobius zenobius   99 Jun 20 08:53 guru
-rwxr-xr-x.  1 zenobius zenobius  161 Apr 13 16:51 hsdb
-rwxr-xr-x.  1 zenobius zenobius  129 Jun 21 04:12 husky
-rwxr-xr-x.  1 zenobius zenobius  129 Jun 24 08:54 idle
-rwxr-xr-x.  1 zenobius zenobius  130 Jun 24 08:54 idle3
-rwxr-xr-x.  1 zenobius zenobius  105 Jun 24 08:54 idle3.10
-rwxr-xr-x.  1 zenobius zenobius  103 Sep 24  2021 idle3.9
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 idlj
-rwxr-xr-x.  1 zenobius zenobius  100 Jun 20 08:53 iferr
-rwxr-xr-x.  1 zenobius zenobius   99 Jun 20 08:53 impl
-rwxr-xr-x.  1 zenobius zenobius   97 Apr 13 16:55 irb
-rwxr-xr-x.  1 zenobius zenobius  107 Feb  6 08:55 jaotc
-rwxr-xr-x.  1 zenobius zenobius  194 Apr 13 16:51 jar
-rwxr-xr-x.  1 zenobius zenobius  200 Apr 13 16:51 jarsigner
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 java
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 javac
-rwxr-xr-x.  1 zenobius zenobius  198 Apr 13 16:51 javadoc
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 javah
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 javap
-rwxr-xr-x.  1 zenobius zenobius  169 Apr 13 16:51 java-rmi.cgi
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 jcmd
-rwxr-xr-x.  1 zenobius zenobius  199 Apr 13 16:51 jconsole
-rwxr-xr-x.  1 zenobius zenobius  194 Apr 13 16:51 jdb
-rwxr-xr-x.  1 zenobius zenobius  111 Feb  6 08:55 jdeprscan
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 jdeps
-rwxr-xr-x.  1 zenobius zenobius  114 Feb  6 09:15 jfr
-rwxr-xr-x.  1 zenobius zenobius  161 Apr 13 16:51 jhat
-rwxr-xr-x.  1 zenobius zenobius  107 Feb  6 08:55 jhsdb
-rwxr-xr-x.  1 zenobius zenobius  108 Feb  6 08:55 jimage
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 jinfo
-rwxr-xr-x.  1 zenobius zenobius  194 Apr 13 16:51 jjs
-rwxr-xr-x.  1 zenobius zenobius  107 Feb  6 08:55 jlink
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 jmap
-rwxr-xr-x.  1 zenobius zenobius  106 Feb  6 08:55 jmod
-rwxr-xr-x.  1 zenobius zenobius  194 Apr 13 16:51 jps
-rwxr-xr-x.  1 zenobius zenobius  201 Apr 13 16:51 jrunscript
-rwxr-xr-x.  1 zenobius zenobius  166 Apr 13 16:51 jsadebugd
-rwxr-xr-x.  1 zenobius zenobius  108 Feb  6 08:55 jshell
-rwxr-xr-x.  1 zenobius zenobius  197 Apr 13 16:51 jstack
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 jstat
-rwxr-xr-x.  1 zenobius zenobius  197 Apr 13 16:51 jstatd
-rwxr-xr-x.  1 zenobius zenobius   98 Jul 19 22:43 just
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 20 08:53 keyify
-rwxr-xr-x.  1 zenobius zenobius  198 Apr 13 16:51 keytool
-rwxr-xr-x.  1 zenobius zenobius   99 Jun 24 08:55 lam
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 16 14:32 leon
-rwxr-xr-x.  1 zenobius zenobius  104 Jun 24 08:55 lookatme
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 20 08:53 motion
-rwxr-xr-x.  1 zenobius zenobius  169 Apr 13 16:51 native2ascii
-rwxr-xr-x.  1 zenobius zenobius  453 Jun 23 17:59 node
-rwxr-xr-x.  1 zenobius zenobius  106 Feb 14 18:57 normalizer
-rwxr-xr-x.  1 zenobius zenobius  452 Jun 23 17:59 npm
-rwxr-xr-x.  1 zenobius zenobius  452 Jun 23 17:59 npx
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 15 19:25 nvim
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 orbd
-rwxr-xr-x.  1 zenobius zenobius  198 Apr 13 16:51 pack200
-rwxr-xr-x.  1 zenobius zenobius  101 Jul 30 15:37 packer
-rwxr-xr-x.  1 zenobius zenobius  128 Jun 24 08:54 pip
-rwxr-xr-x.  1 zenobius zenobius  129 Jun 24 08:54 pip3
-rwxr-xr-x.  1 zenobius zenobius  132 Jun 25 15:42 pip3.10
-rwxr-xr-x.  1 zenobius zenobius  102 Sep 24  2021 pip3.9
-rwxr-xr-x.  1 zenobius zenobius  105 Jun 20 08:53 platformer
-rwxr-xr-x.  1 zenobius zenobius  268 Jul 18 13:52 pnpm
-rwxr-xr-x.  1 zenobius zenobius  157 Jul 18 13:52 pnpm.cjs
-rwxr-xr-x.  1 zenobius zenobius  102 Aug  9  2021 pnpm.js
-rwxr-xr-x.  1 zenobius zenobius  268 Jul 18 13:52 pnpx
-rwxr-xr-x.  1 zenobius zenobius  157 Jul 18 13:52 pnpx.cjs
-rwxr-xr-x.  1 zenobius zenobius  102 Aug  9  2021 pnpx.js
-rwxr-xr-x.  1 zenobius zenobius  102 Sep 24  2021 poetry
-rwxr-xr-x.  1 zenobius zenobius  201 Apr 13 16:51 policytool
-rwxr-xr-x.  1 zenobius zenobius  102 Jun 24 08:22 present
-rwxr-xr-x.  1 zenobius zenobius  130 Jun 24 08:54 pydoc
-rwxr-xr-x.  1 zenobius zenobius  131 Jun 24 08:54 pydoc3
-rwxr-xr-x.  1 zenobius zenobius  106 Jun 24 08:54 pydoc3.10
-rwxr-xr-x.  1 zenobius zenobius  104 Sep 24  2021 pydoc3.9
-rwxr-xr-x.  1 zenobius zenobius  106 Jun 24 08:55 pygmentize
-rwxr-xr-x.  1 zenobius zenobius  131 Jun 24 08:54 python
-rwxr-xr-x.  1 zenobius zenobius  132 Jun 24 08:54 python3
-rwxr-xr-x.  1 zenobius zenobius  107 Jun 24 08:54 python3.10
-rwxr-xr-x.  1 zenobius zenobius  114 Jun 24 08:54 python3.10-config
-rwxr-xr-x.  1 zenobius zenobius  114 Jun 24 08:54 python3.10-gdb.py
-rwxr-xr-x.  1 zenobius zenobius  105 Sep 24  2021 python3.9
-rwxr-xr-x.  1 zenobius zenobius  112 Sep 24  2021 python3.9-config
-rwxr-xr-x.  1 zenobius zenobius  112 Sep 24  2021 python3.9-gdb.py
-rwxr-xr-x.  1 zenobius zenobius  139 Jun 24 08:54 python3-config
-rwxr-xr-x.  1 zenobius zenobius  138 Jun 24 08:54 python-config
-rwxr-xr-x.  1 zenobius zenobius   98 Apr 13 16:55 rake
-rwxr-xr-x.  1 zenobius zenobius   98 Apr 13 16:55 rdoc
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 20 17:36 revive
-rwxr-xr-x.  1 zenobius zenobius   96 Apr 13 16:55 ri
-rwxr-xr-x.  1 zenobius zenobius  125 Jan 20  2022 rls
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 rmic
-rwxr-xr-x.  1 zenobius zenobius  195 Apr 13 16:51 rmid
-rwxr-xr-x.  1 zenobius zenobius  202 Apr 13 16:51 rmiregistry
-rwxr-xr-x.  1 zenobius zenobius   98 Jun 21 04:12 rpg
-rwxr-xr-x.  1 zenobius zenobius   98 Apr 13 16:55 ruby
-rwxr-xr-x.  1 zenobius zenobius  127 Jan 20  2022 rustc
-rwxr-xr-x.  1 zenobius zenobius  129 Jan 20  2022 rustdoc
-rwxr-xr-x.  1 zenobius zenobius  129 Jan 20  2022 rustfmt
-rwxr-xr-x.  1 zenobius zenobius  130 Jan 20  2022 rust-gdb
-rwxr-xr-x.  1 zenobius zenobius  131 Jan 20  2022 rust-lldb
-rwxr-xr-x.  1 zenobius zenobius  128 Jan 20  2022 rustup
-rwxr-xr-x.  1 zenobius zenobius  200 Apr 13 16:51 schemagen
-rwxr-xr-x.  1 zenobius zenobius  200 Apr 13 16:51 serialver
-rwxr-xr-x.  1 zenobius zenobius  201 Apr 13 16:51 servertool
-rwxr-xr-x.  1 zenobius zenobius  101 Jun 24 08:29 slides
-rwxr-xr-x.  1 zenobius zenobius  106 Jun 20 08:53 staticcheck
-rwxr-xr-x.  1 zenobius zenobius  200 Apr 13 16:51 tnameserv
-rwxr-xr-x.  1 zenobius zenobius  105 Feb 14 18:57 undervolt
-rwxr-xr-x.  1 zenobius zenobius  200 Apr 13 16:51 unpack200
-rwxr-xr-x.  1 zenobius zenobius  101 Apr 18 09:51 vsce
-rwxr-xr-x.  1 zenobius zenobius  106 Jun 20 19:34 wasmserve
-rwxr-xr-x.  1 zenobius zenobius  105 Jun 24 08:55 witnessme
-rwxr-xr-x.  1 zenobius zenobius  196 Apr 13 16:51 wsgen
-rwxr-xr-x.  1 zenobius zenobius  199 Apr 13 16:51 wsimport
-rwxr-xr-x.  1 zenobius zenobius  194 Apr 13 16:51 xjc
-rwxr-xr-x.  1 zenobius zenobius  214 Jun 24 08:22 yarn
-rwxr-xr-x.  1 zenobius zenobius  160 May 23 19:01 yarn.cmd
-rwxr-xr-x.  1 zenobius zenobius  159 May 23 19:01 yarn.js
-rwxr-xr-x.  1 zenobius zenobius  217 Jun 24 08:22 yarnpkg
-rwxr-xr-x.  1 zenobius zenobius  163 May 23 19:01 yarnpkg.cmd
-rwxr-xr-x.  1 zenobius zenobius   99 Apr 18 09:51 yo
-rwxr-xr-x.  1 zenobius zenobius  108 Apr 18 09:51 yo-complete
```

----

Remember, ASDF is always there for you. avoiding ASDF is not a brave or couragous thing to do. At some point you'll have to work for a living writing software in languages that isn't python.

**Comment by rchl** [comment]
As we said, the packages do that on purpose as there is least amount of friction that way. Your option is to either create custom configuration object or override the `command` in LSP-* settings to point to `gopls` rather than the default `${storage_path}/LSP-gopls/bin/gopls`.

**Comment by TerminalFi** [comment]
@airtonix for LSP gopls. You can just use `"manageGoplsBinary": false,` and then set it however you want.
