### ISSUE TITLE
side_by_side feature sometimes works

### ISSUE THREAD

**Issue by dmilith** [sublimelsp/LSP#1979]
**Describe the bug**
Given that keybindings have a command using the "side_by_side" arguments like this:

```js
{
    "command": "lsp_symbol_declaration",
    "keys": ["super+shift+e"], "context": [
          {"key": "selector", "operator": "equal", "operand": "source"}
      ],
    "args": {"side_by_side": true}
  }
```

is causing LSP features NOT to work in opened split window. It affects all LSP servers, it's a general issue.

**To Reproduce**
    Start ST
    Install any LSP package, make sure it works for your project
    Hit your shortcut action with "side_by_side" set to true
    Now on the split window (usually on the right) all LSP functionality is no longer enabled.

**Expected behavior**
All LSP functionality should work normally when side_by_side is set to true.

**Screenshots**

**Environment (please complete the following information):**
- OS: macOS 12.4
- Sublime Text version: 4134
- LSP version: 1.16.3
- Language servers used: LSP-bash, LSP-shellcheck, LSP-Rust-analyzer, … the same for all I've tried

**Additional context**
none

**Comment by rchl** [comment]
I believe that it only reproduces if the reference is in the same file you are already in. At least I was only able to reproduce in that case.

**Comment by rchl** [comment]
It's this core issue: https://github.com/sublimehq/sublime_text/issues/2411

**Comment by rchl** [comment]
Seems like we can workaround this issue. Created #2174
