### ISSUE TITLE
Configuration option to disable specific directories from LSP treatment

### ISSUE THREAD

**Issue by bigoldbrute** [sublimelsp/LSP#1981]
**Is your feature request related to a problem? Please describe.**
I have directory with typescript code snippets (read: gists), which i sometimes open with sublime. When i interact with such a snippet, i usually get some typecript syntax warnings, coming from LSP. Incorrect syntax in this case is OK of course, because snippets are examples with unmet dependencies, missing constants etc...

**Describe the solution you'd like**
Configuration option to disable specific directories from LSP treatment.

**Comment by rchl** [comment]
You could create a separate project for those snippets and disable specific servers for that project.

**Comment by bigoldbrute** [comment]
Thanks, it worked. For anybody wondering, it is doable via command palette => LSP: Disable language server in project.
