### ISSUE TITLE
Goto definition in the same file should stay in the same tab

### ISSUE THREAD

**Issue by chenglou** [sublimelsp/LSP#1990]
With more than one instance of the same file open, e.g. in 2 columns mode, goto definition always jumps to the first file instance instead of the currently focused file instance.

**To Reproduce**
1. Open 2 columns to view the same file
2. Go to the right one, goto definition on something
3. Focus jumps to the left file instance

**Expected behavior**
Focus stays on the right instance

**Environment (please complete the following information):**
- OS: macOS
- Sublime Text version: 4126
- LSP version: 1.16.3
- Language servers used: LSP-typescript

"Find references" opens a pane whose links always jump to the currently focused file instance, so I thought goto definition doing the same would be consistent.

**Comment by jyounce-aim** [comment]
Hi guys, I recently upgraded to LSP v1.17.0.

My question is, how do I get this functionality back? https://github.com/sublimelsp/LSP/issues/886

I want to be able to go to definition and it open up in an existing open file regardless of what pane the file is in, how it used to be before this package upgrade.

Thank you,

Judd
