### ISSUE TITLE
on hover documentation for( methods,traits .....) missing 

### ISSUE THREAD

**Issue by ayoushbadyal** [sublimelsp/LSP#2014]
![Screenshot at 2022-08-07 12-10-08](https://user-images.githubusercontent.com/85788045/183292321-dbcc1405-a462-42f2-873f-f6d9a8d0e14d.png)

`code_blocks` not visible as per the docs

**Comment by predragnikolic** [comment]
Cannot reproduce.

![2022-08-09-133903_1920x1200_scrot](https://user-images.githubusercontent.com/22029477/183638313-90f4203c-0edd-44ad-b297-d8f5df214165.png)

Here is the payload:
```
:: <<< rust-analyzer 179: {'contents': {'kind': 'markdown', 'value': '\n```rust\nalloc::collections::vec_deque::VecDeque\n```\n\n```rust\npub fn push_front(&mut self, value: T)\n```\n\n---\n\nPrepends an element to the `VecDeque`.\n\n# Examples\n\n```rust\nuse std::collections::VecDeque;\n\nlet mut d = VecDeque::new();\nd.push_front(1);\nd.push_front(2);\nassert_eq!(d.front(), Some(&2));\n```'}, 'range': {'start': {'line': 7, 'character': 12}, 'end': {'line': 7, 'character': 22}}}
```
using LSP-rust-analyzer TAG version "2022-01-10"

Nothing wrong with the payload.

**Comment by predragnikolic** [comment]
related #1171 , #1812

**Comment by predragnikolic** [comment]
Issue was solved on Discord.

Solution:
Specifying the following in [mdpopups.css](https://facelessuser.github.io/sublime-markdown-popups/settings/#mdpopupsuser_css) will fix the issue:
```
html {
  --mdpopups-font-mono: "fira code";  
}
```

**Comment by rchl** [comment]
It's more a workaround than a fix. :)
Ideally you should report it to the ST bug tracker and do more investigation there.
It could be faulty font or something.
