### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#2035]
Following line is incompatible with python 3.8 plugin_host as argument name has changed from `timeout_ms` to `delay`. Using positional arguments is a simple fix on plugin's side.

https://github.com/sublimelsp/LSP/blob/bd4e0149c40cc53fa1f0925fecda38920f7cedc4/boot.py#L150

**Comment by rchl** [comment]
Fixed on `main` with linked commit.
