### ISSUE TITLE
Go To Symbol - Ability to filter the search (e.g: only structs or functions)

### ISSUE THREAD

**Issue by lucypero** [sublimelsp/LSP#2055]
**Describe the solution you'd like**
I would like to be able to filter out by symbol type on the "Go To Symbol" command.

**Additional context**
I most likely do not want struct *fields* listed here but they populate most of the list

**Comment by lucypero** [comment]
I did it. i'll make a PR with a LSP setting later.

**Comment by rchl** [comment]
I don't think we ever got the PR?

But I would anyway discuss this more before (or within the PR) because I'm not sure we want the extra complexity of additional option. Also, where would the option apply? Globally, per server, per request?
