### ISSUE TITLE
documentSymbol doesn't show icon in go to symbol panel.

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#2068]
**Describe the bug**

Symbol icons for some types are not shown. I'm not sure when they broke they did used to work .

<img width="611" alt="Screen Shot 2022-09-24 at 8 02 39 PM" src="https://user-images.githubusercontent.com/10937186/192099473-05ca87f0-7841-42e8-9246-462f4d2a5438.png">

**To Reproduce**

Here are the server logs  from the screenshot above (paths are truncated to file name only):

```
:: --> pascal-language-server textDocument/documentSymbol(280): {'workDoneToken': 'wd280', 'textDocument': {'uri': 'IsoEngine3D.pas'}}
:: <<< pascal-language-server 280: [{'location': {'range': {'start': {'character': 2, 'line': 27}, 'end': {'character': 27, 'line': 27}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'TPlayer', 'containerName': '', 'kind': 5}, {'location': {'range': {'start': {'character': 2, 'line': 30}, 'end': {'character': 80, 'line': 30}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'TMouse', 'containerName': '', 'kind': 23}, {'location': {'range': {'start': {'character': 2, 'line': 42}, 'end': {'character': 101, 'line': 42}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'TRay', 'containerName': '', 'kind': 23}, {'location': {'range': {'start': {'character': 2, 'line': 48}, 'end': {'character': 113, 'line': 48}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'TRay', 'containerName': '', 'kind': 12}, {'location': {'range': {'start': {'character': 0, 'line': 60}, 'end': {'character': 631, 'line': 60}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'IntersectTriangle', 'containerName': '', 'kind': 12}, {'location': {'range': {'start': {'character': 0, 'line': 81}, 'end': {'character': 2107, 'line': 81}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'EventCallback', 'containerName': '', 'kind': 12}, {'location': {'range': {'start': {'character': 0, 'line': 157}, 'end': {'character': 792, 'line': 157}}, 'uri': 'IsoEngine3D.pas'}, 'name': 'DrawDebugConsole', 'containerName': '', 'kind': 12}]
```

**Environment (please complete the following information):**
- OS: macOS 12.6
- Sublime Text version: 4131
- LSP version: 1.18.0

**Additional context**

This issue was reported as the result of talking with @rwols on Discord.

**Comment by rchl** [comment]
Try in safe mode or with default theme/color scheme.

![Screenshot 2022-09-24 at 18 16 33](https://user-images.githubusercontent.com/153197/192108225-6441f998-41c0-40ff-82a3-0835401ed11a.png)

**Comment by genericptr** [comment]
How did you generate that screenshot?

That's default mode! Looks buggy.

<img width="898" alt="Screen Shot 2022-09-25 at 7 38 17 AM" src="https://user-images.githubusercontent.com/10937186/192123470-5837a513-b67d-48f2-ae48-fbf7572d39f3.png">

How do I test in safe mode, doesn't that just remove all the packages and leave you with nothing?

**Comment by jfcherng** [comment]
> How do I test in safe mode, 

https://www.sublimetext.com/docs/safe_mode.html#starting

> doesn't that just remove all the packages and leave you with nothing?

That's the point of safe mode. A clean setup.

**Comment by genericptr** [comment]
OK so I figured out it was my _color scheme_ that was breaking the symbol icons. That's good news but then I have to ask WHY and how does the color scheme file even affect the symbol icon anyways?

**Comment by jfcherng** [comment]
It uses the `--purplish` variable, so if it's an invalid value then it breaks.

**Comment by jfcherng** [comment]
> Here's the color scheme I was using. I don't see anything about --purplish in there though.
> 
> [Xcode.sublime-color-scheme.zip](https://github.com/sublimelsp/LSP/files/9639850/Xcode.sublime-color-scheme.zip)

You can add it like

```diff
   "variables": {
+    "--purplish": "#D8008F",
```

**Comment by genericptr** [comment]
Interesting adding --purplish fixed it, thanks! Is there a list of all the colors I need to make symbol lists work? The red color worked but I wonder what other colors I'm missing now....

Honestly this is a bad design on the part of ST to make every color file add these manually, maybe we need to file a bug with them also?

**Comment by jfcherng** [comment]
> Is there a list of all the colors I need to make symbol lists work?

See https://github.com/sublimelsp/LSP/issues/2068#issuecomment-1257097529

**Comment by genericptr** [comment]
Thanks I guess it was a color scheme bug! Closing now.

**Comment by rchl** [comment]
I've mentioned it about 3 times including both Discord and here so maybe next time pay a bit more attention to suggestions. :)
