### ISSUE TITLE
Prepare plugins for new LSP release

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#2070]
Required
- [X] LSP-metals is covered with https://github.com/scalameta/metals-sublime/pull/102
- [X] LSP-leo -> uses the outdated Range. `Range.from_lsp(lsp_range)` https://github.com/sublimelsp/LSP-leo/pull/2
- [x] LSP-volar -> is covered with https://github.com/sublimelsp/LSP-volar/pull/130
- [X] LSP-OmniSharp -> uses the outdated Range. `Range.from_lsp(arguments[0]["range"])` https://github.com/sublimelsp/LSP-OmniSharp/pull/18

Optionally
- [x] LSP-typescript -> ~~could be updated to not use RangeLSP. I think it is the only plugin that uses RangeLSP~~ (Done), so we could remove RangeLSP in the future. https://github.com/sublimelsp/LSP-typescript/pull/165/files
- [x] LSP-Grammarly -> using new node requirement check: https://github.com/sublimelsp/LSP-Grammarly/pull/15
- [x] Release new version of https://github.com/sublimelsp/lsp_utils

-----

Other things I noted:
- LSP-promql has this import `from LSP.plugin.core.handlers import LanguageHandler`, (this no longer exist in LSP for ST4) this package hasn't been updated in a long time... https://packagecontrol.io/packages/LSP-promql and it is not part of the SublimeLSP organization. We can fix it by submitting a PR there... and asking the https://github.com/prometheus-community to transfer the repo to the SublimeLSP organization.
```json
		{
			"details": "https://github.com/prometheus-community/sublimelsp-promql",
			"name": "LSP-promql",
			"labels": [
				"auto-complete",
				"linting",
				"formatting",
				"code navigation",
				"intellisense"
			],
			"releases": [
				{
					"sublime_text": ">=3092",
					"tags": true
				}
			]
		}
```

- LSP-Serenata has this import `from LSP.plugin.core.handlers import LanguageHandler`, that repo is moved to the SublimeLSP organization. https://packagecontrol.io/packages/LSP-serenata
```json
		{
			"details": "https://github.com/Cloudstek/LSP-serenata",
			"name": "LSP-serenata",
			"labels": [
				"auto-complete",
				"linting",
				"formatting",
				"code navigation",
				"intellisense"
			],
			"releases": [
				{
					"sublime_text": ">=3092",
					"tags": true
				}
			]
		},
```
- LSP-tagml -> has this import from `LSP.plugin import ClientConfig, LanguageHandler, read_client_config`  (this no longer exist in LSP for ST4),

```
		{
			"details": "https://github.com/HuygensING/LSP-tagml",
			"name": "LSP-tagml",
			"labels": [
				"auto-complete",
				"linting",
				"formatting",
				"code navigation",
				"intellisense"
			],
			"releases": [
				{
					"sublime_text": ">=3092",
					"tags": true
				}
			]
		},
```

So I do not think that LSP-tagml,  LSP-Serenata, LSP-promql work at all for ST4.

**Comment by rchl** [comment]
Restricted LSP-serenate to ST3 - https://github.com/sublimelsp/repository/pull/73

**Comment by rchl** [comment]
Released as https://github.com/sublimelsp/LSP/releases/tag/4070-1.19.0
