### ISSUE TITLE
Add screenshots for Code Lenses in documentation

### ISSUE THREAD

**Issue by genericptr** [sublimelsp/LSP#2073]
Code Lenses are missing screenshots in the docs. It would be nice if they included a little animated gif like the other features do.

https://lsp.sublimetext.io/features/#code-lenses

**Comment by predragnikolic** [comment]
A screenshot like this?
![image](https://user-images.githubusercontent.com/22029477/192781028-5bfd0c54-4a24-45bc-829d-1a4aed410f96.png)

**Comment by genericptr** [comment]
Which style is that? There are a few more right? From the docs:

> Code Lenses are "actionable contextual information interspersed" in your source code.
> 
> Actionable: You can click on the link and something happens.
> Contextual: The links are close to the code they are representing.
> Interspersed: The links are located throughout your source code.
>
