### ISSUE TITLE
Output panels are not (reliably) destroyed if LSP is disabled

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#2082]
**Describe the bug**

"Diagnostics" and sometimes "LSP Server Log" output panels are still present after disabling LSP.

**To Reproduce**
1. Add LSP to "ignored_packages" in _Preferences.sublime-settings_ or run "Package Control: Disable Packgage"

**Expected behavior**

No LSP related output panel being left.

**Environment (please complete the following information):**
- OS: Windows 11
- Sublime Text version: 4137
- LSP version: master
- Language servers used: pyright, json, css, html, lemminx, ...

**Comment by rchl** [comment]
We need to get rid of the `windows` global and make sure that nothing assumes that it's always present. Then we'll be able to do proper cleanup on unload and that should also help with properly destroying references to LSP.
