### ISSUE TITLE
diagnostics_additional_delay_auto_complete_ms doesn't work after split view

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#2102]
**To Reproduce**
1. Install LSP-pyright (for example)
2. Set `"diagnostics_additional_delay_auto_complete_ms": 5000` is LSP settings
3. Create and open a Python file
4. Type `im`
5. Confirm that there is an auto-completion popup and that the diagnostic(s) ("im" is not defined) appear after a delay of 5 seconds - so far so good
6. Remove the text and use *File > Split View*
7. Select the left (original) view
8. Type `im`
9. Observe that the diagnostic(s) immediately appears 

**Expected behavior**
Diagnostics appear only after the delay specified in "diagnostics_additional_delay_auto_complete_ms"

**Environment (please complete the following information):**
- OS: Windows 11
- Sublime Text version: 4126
- LSP version: main branch

**Additional context**
Looks like the bug is here:
https://github.com/sublimelsp/LSP/blob/deeb0cbafce3deba4a37af47f9629b52179f8075/plugin/session_buffer.py#L439-L443

By using `SessionBuffer.some_view()`, a random view is checked for visibility of the autocompletion popup. But instead it should use the *active* view, i.e. the view where I'm currently typing.

**Comment by rchl** [comment]
Might make sense to make `some_view()` prefer the active view, if possible.
