### ISSUE TITLE
Wrong underline color in case of multiple diagnostics with different severities

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#2103]
**Describe the bug**
Diagnostics underline color doesn't use the highest severity if there are multiple diagnostics with different severity

**To Reproduce**
1. Install LSP-pyright (for example)
2. Create and open a Python file
3. Type `im`
4. Observe that there are two diagnostics, one "error" and one "warning", but the squiggly underline is orange

**Screenshots**

![severity](https://user-images.githubusercontent.com/6579999/198683905-fe254d2c-5d0f-470c-86fc-21a61a292a2c.png)

**Additional context**
I just wanted to log this issue here that I incidentally noticed, and I don't remember it being discussed before. But unfortunately I think it is impossible to solve (*edit*: possible workaround see below). The reason lies in ST's behavior for the `add_regions` draw order, which is different for icons and for inline decorations (underline). See here:

https://github.com/sublimelsp/LSP/blob/deeb0cbafce3deba4a37af47f9629b52179f8075/plugin/session_view.py#L107-L115

and

https://github.com/sublimelsp/LSP/blob/deeb0cbafce3deba4a37af47f9629b52179f8075/plugin/session_view.py#L130

If we reverse the range, then the underline would have the correct color (highest severity), but the icon would be the one with the lowest severity. So I think it's probably better to have the correct icon and potentially wrong underline color.

---

*Edit*: Perhaps a workaround could be to create two region types for each diagnostic severity, one for the icon and one for the underline, and initialize the icon regions in reversed order. But not sure whether the additional code needed for that is worth it.

**Comment by rchl** [comment]
As far as I remember it's the same with region "annotations". Those need to be added in opposite order to make the most severe appear on top.
