### ISSUE TITLE
The autocomplete is littered with non-LSP entries that pollute it

### ISSUE THREAD

**Issue by lucypero** [sublimelsp/LSP#2116]
**Describe the bug**
The autocomplete is littered with non-LSP entries that pollute it. I use Rust Analyzer.

**To Reproduce**
1. Go to a valid Rust project
2. Try writing a method call

**Expected behavior**
all the LSP suggestions should at least show up first, or exclusively. This slows down development.

**Screenshots**

https://user-images.githubusercontent.com/11927498/201215441-082b0902-67d8-467e-9d00-ef80853db00a.mp4

**Environment (please complete the following information):**
- OS: Windows 11
- Sublime Text version: 4142
- LSP version: 1.20
- Language servers used: rust-analyzer

**Comment by rwols** [comment]
Did you try setting `"inhibit_word_completions"` to `true` in LSP's settings?

Otherwise, it may be other plugins or snippets you installed that provide those completions.

**Comment by lucypero** [comment]
> Otherwise, it may be other plugins or snippets you installed that provide those completions.

I tried disabling all packages except the LSP one and that fixed it. Thank you.
