### ISSUE TITLE
"list index out of range" when no command is defined

### ISSUE THREAD

**Issue by Sainan** [sublimelsp/LSP#2118]
**Describe the bug**
"command" is documented as "can be empty if starting manually, then TCP transport must be configured". However, doing so raises "list index out of range". This is possibly a regression of #1564.

**To Reproduce**
Use the following user configuration:
```JSON
{
    "clients": {
        "pluto-language-server": {
            "enabled": true,
            "selector": "source.lua",
            "tcp_port": 5007,
            "command": []
        }
    }
}
```

**Expected behavior**
It shouldn't've attempted to start the process with the `[]` configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/63328889/202662990-d2183a49-0212-4544-b050-ffd7cfd6994a.png)

**Environment:**
- OS: Windows 10
- Sublime Text version: 4143
- LSP version: 1.20.0
- Language servers used: [pluto-language-server](https://github.com/PlutoLang/pluto-language-server)

**Comment by predragnikolic** [comment]
The "list index out of range" error should be fixed with https://github.com/sublimelsp/LSP/pull/2300

Feel free to reopen, if you stumble upon any issue.
