### ISSUE TITLE
code lens font color customization

### ISSUE THREAD

**Issue by benbenbang** [sublimelsp/LSP#2156]
Hello,

I've checked the documentation about customizing the `code_lens` font color, however I couldn't find the configuration scope for it. 

i've tried this one as well (with both `background` and `foreground`):

```
"rules": [
        {
            "scope": "markup.accent.codelens.lsp",
        }
    ]
```
but it didn't seem to be working.

<img width="1180" alt="CleanShot 2022-12-30 at 11 22 09@2x" src="https://user-images.githubusercontent.com/6682936/210060082-e9e5c1e1-d926-4bc2-87d0-e60f9c21e6b1.png">

currently the code lens (the **_blue part_**) is barely readable for me, did I miss the doc? or it's just not customizable yet?
Thanks for the help

**Comment by rchl** [comment]
What color scheme are you using?

This seems like a generic issue with color scheme that would affect also other areas of ST (where minihtml is shown).

**Comment by jwortmann** [comment]
That scope should have an effect for the small green vertical bar.

Does your color scheme use `"popup_css"` ? You can try to adjust that, for example
```
    "globals": {
        "popup_css": "a{color:#ff0000;}",
    },
```
but this will likely have side effects (should be fixed on latest ST dev build I think).

It will only take effect after annotations are redrawn.

**Comment by benbenbang** [comment]
Thanks for the hint @rchl and @jwortmann !

I am using my custom color scheme. I just try to play with the `popup_css`, it works perfectly now!

<img width="1087" alt="CleanShot 2022-12-30 at 13 06 20@2x" src="https://user-images.githubusercontent.com/6682936/210069454-2c2771d2-d166-4a86-bee1-aee98421e794.png">

now the contrast is way better and the docs are readable. I will keep playing with it :D 

we can close the issue. Thanks again!

---

To people who what to customize the pop up window, you can just update the `popup_css` that @jwortmann mentioned above. It basically takes a string (quoted) of css and you might need to restart to make it work.

If you need any inspiration, this is what I put

```json
    "globals": {
        "popup_css"                     : "\n      html, body {\n        background-color: #282e3b;\n        color: #2A2A37;\n        --mdpopups-font-mono: \"PragmataPro Mono Liga\", \"sf mono\", Consolas, \"Liberation Mono\", Menlo, Courier, monospace;\n        --mdpopups-bg: #1F1F28;\n        --mdpopups-link: #73d0ff;\n      }\n      body {\n        padding: 1px 3px;\n      }\n      a {\n        color: rgba(115,208,255, .7);\n      }\n    ",
        }
```

**Comment by rchl** [comment]
I feel like there should be a cleaner way of fixing that since default color schemes don't define "popu_css" and still manage to make links look good. But I'm not fluent in color schemes so not sure what that would be instead.

**Comment by rchl** [comment]
Looked a bit more into it. Those links use the `--mdpopups-link` color which mdpopup [defaults to `var(--bluish)`](https://github.com/facelessuser/sublime-markdown-popups/blob/08d508303a2170fdd96179cd58c66c9b3d07d903/st3/mdpopups/css/default.css#L4). So I think that means that if your color scheme would define a better `--blue` color then that would also improve how the inferred `--bluish` looks.

**Comment by jwortmann** [comment]
The annotations don't use mdpopups, but the default CSS from ST also uses `var(--bluish)` for the `a` tag color. There was an inconvenience that ST would lose those built-in styles and fall back to likely some plain browser CSS with `color: blue` for the `a` tag, if `"popup_css"` was defined in the color scheme. But it seems to have been fixed recently.

https://www.sublimetext.com/docs/minihtml.html#predefined-variables

> The algorithm to pick the colors uses the HSL color space and uses several heuristics to try and pick colors that are suitable for foreground use.
