### ISSUE TITLE
Missing diagnostics due to "folder_exclude_patterns" with multiple project folders

### ISSUE THREAD

**Issue by philer-jambit** [sublimelsp/LSP#2171]
**Describe the bug**
A recent change has caused error messages to no longer get highlighted in my project. After some fiddling (with help on Discord) I figured out that I had a `"folder_exclude_patterns"` set in my Project settings. This was for a subfolder that was added as a separate project folder:

```json
{
    "folders":
    [
        {
            "path": "my-project",
            "folder_exclude_patterns": ["frontend"],
        },
        {
            "path": "my-project/frontend",
            "name": "my-project/frontend",
        },
    ],
    // ...
}
```
As a result, errors reported by LSP-typescript and LSP-eslint within the `my-project/frontend` directory were being ignored and not rendered in my editor.

Note: I added the redundant frontend project folder a while ago because LSP-eslint needs the .eslintrc file to be found inside a project folder root. I then added the `"folder_exclude_patterns"` so I don't get duplicate entries in the ctrl+p file search.

**Expected behavior**
Errors should be reported for any folder listed in the project folders setting.

**Environment (please complete the following information):**
- OS: Linus Mint 21.1
 - LSP: 1.21.0
 - Sublime Text: 4143
 - eslint, typescript (also pyright and a few others but not in this sub project)

**Comment by jwortmann** [comment]
Oof... yeah that is a bug. The intention is to hide diagnostics (in the diagnostics panel and also the underline in the file if it were opened) for files which are not visible in the sidebar. For example third-party libraries which are added to `"folder_exclude_patterns"`. I did not consider that you can add the same folder to the sidebar multiple times. Therefore
https://github.com/sublimelsp/LSP/blob/01ca49ed2c97bbcab5fe457bd931801d6c69be55/plugin/core/windows.py#L387 is not a sufficient reason to hide a diagnostic. It should rather be something in the sense of "matches a file not visible in the sidebar". Unfortunately there is no ST API to check for that. So for a manual implementation of that, we need to compare all the folder paths included in the project file, to ensure that a folder hidden via `"folder_exclude_patterns"` is not also contained in another of the `"folders"` items.

That is not the only bug in the current implementation, though. I've already found and listed a few more at https://github.com/sublimelsp/LSP/pull/2113#issuecomment-1304836444. And some other project folder settings from https://www.sublimetext.com/docs/projects.html#folders-key, like the `"folder_include_patterns"`, are currently ignored.

**Comment by alecmev** [comment]
Hitting the same problem, I assume the only workaround is to not use `folder_include_patterns` for now?
