### ISSUE TITLE
Choose Formatter for lsp_format_on_save 

### ISSUE THREAD

**Issue by pinecat** [sublimelsp/LSP#2191]
Hello all,

I have been working on some Ruby projects lately, and I have LSP setup with Solargraph and Sorbet.  I would like to be able to use the 'lsp_format_on_save' option, so that my `.rb` files are automatically formatted when I save my project files.  The option works, however, it looks like it defaults to using `rubocop` formatting.  Looking over the default settings, I don't immediately see an option that would allow me to change what formatter is used.  So, would it be possible to add an option that specifies the format (i.e. `standardrb` instead)?

Perhaps something like the following could work?
```json
{
  "clients": {
    "ruby": {
      ...
      "formatter": "standardrb"
    }
  }
}
```

Thank you!

**Comment by rchl** [comment]
I don't quite understand.

Are you running two language servers and it's using formatter from not the one you want? Or it's using correct LSP to format but wrong style?

**Comment by rwols** [comment]
Language servers just expose a “I can format” capability. This package iterates over all attached language severs and runs formatting for all servers that advertise “I can format”. You need to look into the server-specific settings to see what you can tune about the particular formatter.

**Comment by rchl** [comment]
Depending on the answer to my question I was going to suggest that either formatting capability can be disabled for one of the servers or he'd need to look at server-specific settings which it might have.

**Comment by pinecat** [comment]
Hi, thanks for response.  Apologies, you are correct, it appears `solargraph` is what's doing the formatting.  Since the lsp_format_on_save option was outside the clients, I presumed (wrongly), it was using it's own program.  Thanks, will close this out!
