### ISSUE TITLE
Unable to change key bindings for overloads preview

### ISSUE THREAD

**Issue by suprMax** [sublimelsp/LSP#2220]
**Describe the bug**
After last update there is a new overloads preview, unfortunately it blocks up and down buttons which I use while writing code. I was unable to disable this or override the key bindings. Is there a way to disable this feature without disabling the whole LSP?

**To Reproduce**
1. Write code
2. See overloads explanation hijacking keyboard control

**Expected behavior**
It would be great to be able to keep using the keyboard

**Screenshots**
<img width="465" alt="Screenshot 2023-03-16 at 6 23 09 PM" src="https://user-images.githubusercontent.com/789031/225702349-76448f51-c64d-4e37-98dd-8422c7c8938a.png">

**Environment (please complete the following information):**
- OS: macOS 13.2.1
- Sublime Text version: 4143
- LSP version: 1.23.0
- Language servers used: TypeScript running while using plain JavaScript

**Comment by jwortmann** [comment]
The overloads navigation exists in LSP already for a very long time. The key bindings for that use a special context `lsp.signature_help_multiple_choices_available`.
https://github.com/sublimelsp/LSP/blob/4ed8b7a75b091311bff041eb63aea2744c35b23e/Default.sublime-keymap#L222-L234

But due to how key bindings work in ST, to override those bindings should work even without this context. I've just tested and can confirm that it works fine for me. What exactly did you try to override the key bindings?

```json
{
    { "keys": ["up"], "command": "move", "args": {"by": "lines", "forward": false} },
    { "keys": ["down"], "command": "move", "args": {"by": "lines", "forward": true} },
}
```

**Comment by suprMax** [comment]
This is the config I tried to create:

```
[
  { "keys": ["ctrl+alt+s"], "command": "reveal_in_side_bar" },
  {
      "keys": ["shift+up"],
      "command": "lsp_signature_help_navigate",
      "args": {"forward": false},
      "context": [{"key": "lsp.signature_help_multiple_choices_available"}]
  },
  {
      "keys": ["shift+down"],
      "command": "lsp_signature_help_navigate",
      "args": {"forward": true},
      "context": [{"key": "lsp.signature_help_multiple_choices_available"}]
  },
]
```

I've now added your two extra lines, to hopefully unbreak the keyboard navigation, let's see

**Comment by suprMax** [comment]
Yes I can now confirm that adding all 4 values works as it's supposed to. For anyone with the same problem here's how I managed to rebind the help window to shift+arrows:

```

[
  {
      "keys": ["shift+up"],
      "command": "lsp_signature_help_navigate",
      "args": {"forward": false},
      "context": [{"key": "lsp.signature_help_multiple_choices_available"}]
  },
  {
      "keys": ["shift+down"],
      "command": "lsp_signature_help_navigate",
      "args": {"forward": true},
      "context": [{"key": "lsp.signature_help_multiple_choices_available"}]
  },
    { "keys": ["up"], "command": "move", "args": {"by": "lines", "forward": false} },
    { "keys": ["down"], "command": "move", "args": {"by": "lines", "forward": true} },
]
```

**Comment by jwortmann** [comment]
Just as a sidenote, if any other package also overrides the "up" and "down" key bindings with some other context, then the two lines I posted will also deactivate them. So to prevent such surprises, it would be safer to include `"context": [{"key": "lsp.signature_help_multiple_choices_available"}]` in your user override for "up" and "down" too.
