### ISSUE TITLE
Invalid HTML in diagnostics["code"] breaks hover popups.

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sublimelsp/LSP#2223]
**Describe the bug**
If the `code` field of the diagnostic contains invalid html, the hover popup is broken

**To Reproduce**
1. Use haskell-language-server
2. hover over a line with `redundant <$>` hint (for example, `inputForConfig config = (<> config) <$> standardIOConfig >>= inputForConfig`
3. The hover popup is cut in half, and ST's console complaints about parsing errors

**Expected behavior**
Hover is properly formatted

**Environment (please complete the following information):**
- OS: Win10
- Sublime Text version: 4143
- LSP version: current master
- Language servers used: [HLS] with suggested config

**Root cause**
In the `format_diagnostics_for_html` method we append the contents of `diagnostics["code"]` as-is, without escaping (https://github.com/sublimelsp/LSP/blob/main/plugin/core/views.py#L1006).

As far as I understand, the specs of LSP say nothing about that field, it can be an arbitrary text. I suggest
the following diff:
```diff
diff --git a/plugin/core/views.py b/plugin/core/views.py
index cfdce3e..7af8239 100644
--- a/plugin/core/views.py
+++ b/plugin/core/views.py
@@ -1003,7 +1003,7 @@ def format_diagnostic_for_html(
         if code_description:
             code.append(make_link(code_description["href"], diagnostic.get("code")))
         else:
-            code.append(_with_color(diagnostic["code"], "color(var(--foreground) alpha(0.6))"))
+            code.append(_with_color(text2html(diagnostic["code"]), "color(var(--foreground) alpha(0.6))"))
         code.append(_with_color(")", "color(var(--foreground) alpha(0.6))"))
     else:
         code = None
```
I do not have a good idea on how it could impact other LSP servers, comments and suggestions are welcome.

I'll submit a PR sometime later this week.

Cheers!

**Comment by rchl** [comment]
Yes, `text2html` is the correct thing to use here. But there are quite a few more places that need it. Everywhere we get disagnostic `code`, `source` or the `relatedInformation[0]['message]`

**Comment by ShrykeWindgrace** [comment]
@rchl thanks for the confirmation! However, I am not sufficiently familiar with codebase to add that `text2html` in all required places, the PR will take some time=)
