### ISSUE TITLE
Settings for editing inlay hints

### ISSUE THREAD

**Issue by Drakim** [sublimelsp/LSP#2229]
**Is your feature request related to a problem? Please describe.**
I wish to style the inlay hints that LSP provides, however, LSP only allows for very limited styling, basically background color, font type, font color, but nothing else. There are these ugly round borders on the little hint that cannot be removed without editing inlay_hint.py directly to change the enforced CSS.

**Describe the solution you'd like**
The ability to either change all CSS values of the inlay hint though variables, or the ability to outright overwrite the css that's currently there from a settings file.

**Describe alternatives you've considered**
Editing LSP with PackageResourceViewer by hand each time there is an update.

**Additional context**
Here is my cute little CSS improvement for my own enjoyment, no more distracting button-like border :<)
![image](https://user-images.githubusercontent.com/7129377/229368756-fc0716f7-652c-414f-9690-824c936a55f1.png)

**Comment by jwortmann** [comment]
> or the ability to outright overwrite the css that's currently there from a settings file

In theory you can, and there is a guideline for this in the ST [minihtml docs](https://www.sublimetext.com/docs/minihtml.html#best-practices). So you would [override](https://www.sublimetext.com/docs/color_schemes.html#customization) the ["phantom_css"](https://www.sublimetext.com/docs/color_schemes.html#phantom_css) setting in your color scheme, and use the `#lsp-inlay-hint` id in the CSS selector to adjust the styles:
https://github.com/sublimelsp/LSP/blob/ea8d2c1328bb01fa69baf9f306613a825b317377/plugin/inlay_hint.py#L102-L117

The bad news is, that it doesn't work, and there seems little incentive from the ST devs to fix it. This statement is based on the missing reactions in a corresponding [issue report](https://github.com/sublimehq/sublime_text/issues/2935) that I filed in 2019.

So I would say this is mostly an upstream issue. The only thing which I think could be improved, would be to move the hardcoded CSS into a new `phantoms.css` file (there exist already files for `popups.css`, `sheets.css`, `notification.css`). Then you could more easily override this file only, without the risk to break the Python code in a future update if you modify `inlay_hint.py` directly.

**Comment by jwortmann** [comment]
See the description at https://lsp.sublimetext.io/customization/#inlay-hints for a workaround, which should make it a bit easier to adjust the styles. I don't know exactly what PackageResourceViewer does, but if you use Sublime's built-in override mechanics for package files, then you only need to create the override file a single time, and it should keep working even when the package gets updated.

Note that this will only start to work after the next release of the LSP package! (assuming you have installed it with Package Control)
