### ISSUE TITLE
Dubious files in this repository

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP#2230]
There appeared some weird files in this repository, namely
* [`test.cpp`](https://github.com/sublimelsp/LSP/blob/ea8d2c1328bb01fa69baf9f306613a825b317377/test.cpp)
* [`plugin/test.cpp`](https://github.com/sublimelsp/LSP/blob/ea8d2c1328bb01fa69baf9f306613a825b317377/plugin/test.cpp)
* [`plugin/core/test.dart`](https://github.com/sublimelsp/LSP/blob/ea8d2c1328bb01fa69baf9f306613a825b317377/plugin/core/test.dart)

I don't think they have any purpose, and it seems @rchl is to blame 😄 (just kidding)

**Comment by rchl** [comment]
My test files. :)
Removed now, thanks for catching.
