### ISSUE TITLE
Please support ActionScript and MXML for Sublime LSP, and Haxe too

### ISSUE THREAD

**Issue by blackjyn** [sublimelsp/LSP#2248]
No, AS3 and MXML is not dead.  Many indie game developers still code in AS3.
With the compiler now in hand of Harman (part of Samsung) , the development of AIR SDK is thriving and very active.

The problem is , Adobe discontinued support for Flash Builder 4.7. Years come by, as the compiler is being developed actively but the IDE is not, there are many problems in incompatibilities between the new SDK and the OLD FB4.7.

Thus, developing AS3 in FB is useless. Several solution exists : Jetbrains Intellij IDEA support AS3 but only on Ultimate version.
VSCode already support it.

The LSP is there already:
https://github.com/BowlerHatLLC/vscode-as3mxml

I would like to thank if you guys at the ST  team would bring AS3 and MXML support to the platform officially,
This would be valuable alternative for long time ST users just like me (Im using ST since v2 beta btw) and honestly Im not so convenience using VSCode just because it is not as fast and not as sleek as Sublime Text. 

So please ST team bring support for AS3+MXML and for Haxe too.
Haxe is gaining very well and the foundation is getting very solid.

The LSP is there already:
Haxe LSP : https://github.com/vshaxe/haxe-language-server
AS3MXML LSP: https://github.com/BowlerHatLLC/vscode-as3mxml

Thanks!

**Comment by blackjyn** [comment]
The LSP ActionScript itself has already existed and works nicely on VSCode
It is also actively maintained

All I wish for is Sublime Text team brings it to the editor just like you guys bring LSP jdtls to Sublime Text


LSP ActionScript on VScode is amazing, it supports mxml out of the box. 

Would be great if ST4 support it

**Comment by rchl** [comment]
There needs to be someone who maintains the LSP-ActionScript (or whatever) on the ST side.

**Comment by rchl** [comment]
Note that especially the Haxe server looks pretty straightforward to just set using a custom client config. Read https://lsp.sublimetext.io/client_configuration/ on how to add a client configuration and check Haxe's readme (https://github.com/vshaxe/haxe-language-server) on how it should more or less look like (the neovim config is pretty similar to what needs to be done in ST LSP).

**Comment by blackjyn** [comment]
Update: the creator of AS3MXML has provided the way to use the LSP for ST4:
https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/How-to-use-the-ActionScript-and-MXML-language-server-with-Sublime-Text

That is , only for language server. Build, debug , package are done manually on your own
