### ISSUE TITLE
Customizing style of diagnostics with tags no longer works in dev builds

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#2253]
**Describe the bug**

This approach:

https://github.com/sublimelsp/LSP/blob/b49da9e81a8e6096509a24e6b98a4d6897f41c05/plugin/session_view.py#L298-L299

no longer works in current ST dev builds due to this "issue":  https://github.com/sublimehq/sublime_text/issues/5942

I don't remember if there is a reason that we are not adding regions if custom color scheme rule is not defined...
Is it just a minor optimization and it would be fine to always do it? @jwortmann ?

**Comment by jwortmann** [comment]
I would say this is a non-issue, and everything works as expected :)

We even have an explicit warning about this in the [docs](https://lsp.sublimetext.io/customization/#diagnostics):
> The color scheme rule only works if the "background" color is different from the global background of the scheme.

You could simply fix the preceding code block example, to follow this advice, for example similar to the code block example in the "Semantic Highlighting" section. That one should work unless the color scheme's background is `#000001`.

I think the reason to not add it if there's no color scheme rule was only a performance optimization, but I assume if the check for `"background"` doesn't apply, to add the region would have no effect anyway (?). And another disadvantage of adding the region is, that it removes `font_style`, though I haven't checked whether this also applies if there's no relevant color scheme rule for it.

**Comment by rchl** [comment]
Why nobody told me earlier? ;)

> but I assume if the check for `"background"` doesn't apply, to add the region would have no effect anyway (?)

Actually it would create this issue so we can't do that:

![Screenshot 2023-05-13 at 16 15 55](https://github.com/sublimelsp/LSP/assets/153197/1fb252cf-b1fe-43fb-8bfa-2ac9c9bcc3d0)
