### ISSUE TITLE
Error rewriting command lsp_recheck_sessions. Encountered infinite loop

### ISSUE THREAD

**Issue by Shuzhenzhou** [sublimelsp/LSP#2291]
plugins loaded
Error rewriting command lsp_recheck_sessions. Encountered infinite loop
Error rewriting command lsp_recheck_sessions. Encountered infinite loop
Debugger: [startup]
Debugger: [finished]
Package Control: Skipping automatic upgrade, last run at 2023-06-25 14:32:13, next run at 2023-06-25 15:32:13 or after
LSP: LSP-volar crashed (1 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (2 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (3 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (4 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (5 / 5 times in the last 180.0 seconds), exit code 1, exception: None

**Comment by rchl** [comment]
Issue in LSP-volar is enough
