### ISSUE TITLE
Semantic tokens not working with Clojure LSP

### ISSUE THREAD

**Issue by prcastro** [sublimelsp/LSP#2294]
**Describe the bug**
I'm trying to setup LSP  and my editor doesn't recognize `s/defn` macro as a function declaration.

The Clojure LSP should be reporting `s/defn` as function semantic tokens. Looking at the logs, the LSP plugin doesn't seem to be sending any `semanticTokens/full` requests. Also, adding: 

```
{
    "rules": [
        {
            "scope": "meta.semantic-token",
            "background": "#00000101"
        },
    ]
}
```

To the color scheme also does nothing.

**To Reproduce**
Open a clojure project with prismatic schema and clojure-lsp set up. Declare a function using `s/defn`.

**Expected behavior**
I expected `defn` and `s/defn` function definitions to be highlighted the same

**Screenshots**
![Screenshot 2023-07-03 at 11 16 45](https://github.com/sublimelsp/LSP/assets/1280742/c2680a24-7973-4bba-9135-b7bec92c4098)

**Environment (please complete the following information):**
- OS: macOS 13.4.1
- Sublime Text version: 4143
- LSP version: 1.24.0
- Language servers used: clojure-lsp

**Additional context**
I debugged this with the clojure-lsp dev and he was convinced the problem was on the client side (LSP)

**Comment by jwortmann** [comment]
Have you enabled `"semantic_highlighting": true` in the LSP settings? (it's `false` by default)

Can you place the cursor inside `s/defn` and select *Tools > Developer > Show Scope Name* from the menu - there should be a "Semantic Token" section in the popup, if semantic tokens are enabled.

Could you post the exact response to the `initialize (1)` request from the LSP log panel, so we can see the exact capabilities of the clojure-lsp server?

**Comment by predragnikolic** [comment]
Can you pasteg the LSP logs? (Run `LSP: Toggle Log Panel` from the Command Palette)

I am looking to see if the server announces support for semantic tokens.

Also, did you enable this LSP setting?
https://github.com/sublimelsp/LSP/blob/d4ba30d1cfe330c86918e5ab7f30c70a332ee12b/LSP.sublime-settings#L213

**Comment by predragnikolic** [comment]
The docs are missing the part to set `"semantic_highlighting": true`
https://lsp.sublimetext.io/customization/#semantic-highlighting
