### ISSUE TITLE
LSP 1.25.0 is not on packagecontrol.io

### ISSUE THREAD

**Issue by erazor-de** [sublimelsp/LSP#2302]
LSP version 4070-1.25.0 has been released here for a couple of days.
packagecontrol.io still lists 1.24.0.
Is 1.25.0 a non-stable release not meant for packagecontrol or has this been missed?

**Comment by jfcherng** [comment]
pc doesnt update any package at this mement. there is an issue of pc.

**Comment by rchl** [comment]
Created issue in https://github.com/wbond/package_control/issues/1647
