### ISSUE TITLE
Remove obsolete dependencies

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#2334]
While looking through packages and their dependencies I found LSP requesting 2 libraries, which it doesn't seem to use and thus can be removed.

1. `backrefs` is not referenced/imported anywhere in LSP nor one of the other dependencies.
2. `pyyaml` was needed for mdpopups in the past, but is now vendored.

**Comment by rchl** [comment]
[wcmatch](https://github.com/facelessuser/sublime-wcmatch) appears to require `backrefs`.

**Comment by deathaxe** [comment]
Not `bracex`?

**Comment by rchl** [comment]
You are right, both are unused.
