### ISSUE TITLE
CodeLens does not process the whole file after opening it.

### ISSUE THREAD

**Issue by AbraxasDMG** [sublimelsp/LSP#2344]
Hi. Maybe this is by design, actually, but I find it confusing and had to check.

I am using LSP-PowerShellEditorServices. When I open a ps1 file that contains a number of functions and some regular code, the functions are not "analyzed" initially. I need to "click" somewhere in the screen with them visible, in order to have the LSP investigates the number of references and update the default "..." placeholder. 

Is this normal?

Thanks!

**Comment by rwols** [comment]
Yes this is normal because there is no callback in the sublime API for viewport changes.

We could implement a polling solution but I don’t think it’s worth the hassle.

**Comment by AbraxasDMG** [comment]
Thank you for the confirmation.
