### ISSUE TITLE
Refactor/Rename unavailable for function name

### ISSUE THREAD

**Issue by AbraxasDMG** [sublimelsp/LSP#2345]
Hi. Maybe this is by design, but I find it confusing and had to check.

I am using LSP-PowerShellEditorServices. When I try to rename function in powershell script, that option is not available under the menu item Edit > LSP: Refactor > Rename...
Is this something that a specific LSP implementation should take care of (like LSP-PowerShellEditorServices) or is it built into LSP layer itself?

Thanks!

**Comment by LDAP** [comment]
This depends on the LSP server. The server must implement the `renameProvider` capability to enable this functionality.

See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities

**Comment by AbraxasDMG** [comment]
Thank you very much.
