### ISSUE TITLE
Provide a way to save all modified files after applying workspace edits

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#2371]
**Is your feature request related to a problem? Please describe.**

When applying refactorings (like renames) it's often the case that multiple files are modified. It's a chore to then have to find and save all those modified files.

**Describe the solution you'd like**

We could provide a dialog after more than one file was modified asking the user whether all modified files should be saved. Note that some people don't like dialogs (#1922).

Or maybe even show a "tree view" in a sheet, showing all modified files and allowing the user to navigate to them and save all at once.

**Describe alternatives you've considered**

- Saving all edited files one by one.
- Using "save all" command but that fails when there is some unsaved buffer in the window (for example I like to have some to keep notes in them)

**Comment by LDAP** [comment]
What about adding a setting, that lets LSP save all modified files without user interaction?
