### ISSUE TITLE
goto definition cursor position is one char behind

### ISSUE THREAD

**Issue by varunbpatil** [sublimelsp/LSP#2379]
**Describe the bug**
When goto definition opens a new file, the cursor position is always one character behind the actual definition. When the file that the definition is in is already open, then the cursor position is correct.

**Environment (please complete the following information):**
- OS: ubuntu 22.04
- Sublime Text version: 4152
- LSP version: 1.26.0
- Language servers used: gopls

![Recording 2023-12-18 at 22 50 45](https://github.com/sublimelsp/LSP/assets/1353218/e7e888fe-c894-4c75-b0cc-74d7c3e9394b)

**Comment by predragnikolic** [comment]
Hello,

Cannot reproduce with:
```
λ  ~  go version                      
go version go1.19 linux/amd64
```
LSP-gopls v1.14.2
LSP 1.26.0

![output](https://github.com/sublimelsp/LSP/assets/22029477/ccdb7cb9-3cd7-41be-89ab-d88bcb5a8176)

**Comment by predragnikolic** [comment]
Lets debug this.

Can you create a `hello.go` file that looks like this:
```go
package main

import "fmt"

func example() {
    fmt.Println("Hello, world.")
}

func main() {
    example()
    fmt.Println("Hello, world.")
}
``` 

Open the command palette and select LSP: Toggle Log Panel.
Trigger the bug, by triggeing a LSP goto defintion on example.
and copy paste the logs from the LSP log panel here. (make sure that the log includes a `textDocument/definition` log)

**Comment by jwortmann** [comment]
According to the opening post, it only happens if the definition is in another file, and this file is not yet opened.

However, I can't reproduce it (with different servers - haven't tested gopls), and I assume this must be a server issue.
The logs with the response to the `textDocument/definition` request would provide clarity about that. There should be something like
```python
{'uri': '...', 'range': {'start': {'line': 419, 'character': 4}, 'end': ...}}
```
(or with `targetSelectionRange` instead of `range`) and LSP uses the "start" position to place the cursor, where line and column numbers in the response are 0-based.

**Comment by varunbpatil** [comment]
Hi @predragnikolic @jwortmann ,

Here are the LSP logs from a slightly modified example (definition in a different file).

hello.go

```go
package main

func main() {
    example()
}
```

example.go

```go
package main

func example() {}
```

LSP logs when `example.go` is not yet opened.

```
:: [10:29:05.726] <<< gopls (143) (duration: 12ms): [{'command': {'arguments': [{'URI': 'file:///tmp/test/hello.go', 'Range': {'end': {'character': 7, 'line': 3}, 'start': {'character': 7, 'line': 3}}, 'Fix': 'inline_call'}], 'command': 'gopls.apply_fix', 'title': 'Inline call to example'}, 'title': 'Inline call to example', 'kind': 'refactor.inline'}]
:: [10:29:13.373] --> gopls textDocument/definition (144): {'workDoneToken': '$ublime-work-done-progress-144', 'position': {'character': 7, 'line': 3}, 'textDocument': {'uri': 'file:///tmp/test/hello.go'}}
:: [10:29:13.375] <<< gopls (144) (duration: 2ms): [{'uri': 'file:///tmp/test/example.go', 'range': {'end': {'character': 12, 'line': 2}, 'start': {'character': 5, 'line': 2}}}]
:: [10:29:13.402]  -> gopls textDocument/didOpen: {'textDocument': {'uri': 'file:///tmp/test/example.go', 'languageId': 'go', 'text': 'package main\n\nfunc example() {}\n', 'version': 0}}
:: [10:29:13.403] --> gopls textDocument/documentLink (145): {'textDocument': {'uri': 'file:///tmp/test/example.go'}}
:: [10:29:13.413] <<< gopls (145) (duration: 10ms): None
:: [10:29:13.716] --> gopls textDocument/documentHighlight (146): {'position': {'character': 4, 'line': 2}, 'textDocument': {'uri': 'file:///tmp/test/example.go'}}
:: [10:29:13.720] --> gopls textDocument/codeAction (147): {'range': {'end': {'character': 4, 'line': 2}, 'start': {'character': 4, 'line': 2}}, 'context': {'diagnostics': [], 'triggerKind': 2}, 'textDocument': {'uri': 'file:///tmp/test/example.go'}}
:: [10:29:13.721] <<< gopls (146) (duration: 5ms): [{'kind': 1, 'range': {'end': {'character': 4, 'line': 2}, 'start': {'character': 0, 'line': 2}}}]
:: [10:29:13.732] <<< gopls (147) (duration: 11ms): None
:: [10:29:14.419] <-  gopls textDocument/publishDiagnostics: {'uri': 'file:///tmp/test/example.go', 'diagnostics': []}
```


LSP logs when `example.go` is already open.

```
:: [10:31:22.112] <<< gopls (151) (duration: 8ms): [{'command': {'arguments': [{'URI': 'file:///tmp/test/hello.go', 'Range': {'end': {'character': 9, 'line': 3}, 'start': {'character': 9, 'line': 3}}, 'Fix': 'inline_call'}], 'command': 'gopls.apply_fix', 'title': 'Inline call to example'}, 'title': 'Inline call to example', 'kind': 'refactor.inline'}]
:: [10:31:31.651] --> gopls textDocument/definition (152): {'workDoneToken': '$ublime-work-done-progress-152', 'position': {'character': 9, 'line': 3}, 'textDocument': {'uri': 'file:///tmp/test/hello.go'}}
:: [10:31:31.654] <<< gopls (152) (duration: 2ms): [{'uri': 'file:///tmp/test/example.go', 'range': {'end': {'character': 12, 'line': 2}, 'start': {'character': 5, 'line': 2}}}]
:: [10:31:31.682] --> gopls textDocument/codeAction (153): {'range': {'end': {'character': 5, 'line': 2}, 'start': {'character': 5, 'line': 2}}, 'context': {'diagnostics': [], 'triggerKind': 2}, 'textDocument': {'uri': 'file:///tmp/test/example.go'}}
:: [10:31:31.683] <<< gopls (153) (duration: 1ms): None
:: [10:31:31.983] --> gopls textDocument/documentHighlight (154): {'position': {'character': 5, 'line': 2}, 'textDocument': {'uri': 'file:///tmp/test/example.go'}}
:: [10:31:31.987] <<< gopls (154) (duration: 3ms): [{'kind': 1, 'range': {'end': {'character': 12, 'line': 2}, 'start': {'character': 5, 'line': 2}}}]
```

In both cases, gopls is returning character 5 line 2 in `example.go` which is correct, but, there seems to be some problem when the file is not opened yet in which case the cursor stays on (or is moved back to) column 5.

**Comment by varunbpatil** [comment]
Oh, it appears to be a problem with Vintage mode. I disabled vintage mode and now it seems to be working correctly.

Specifically, this setting

```
"vintage_start_in_command_mode": true,
```

causes the mode to change from insert mode to normal mode when a new file is opened and the cursor moves back one char as a result.

**Comment by varunbpatil** [comment]
I switched to using NeoVintageous plugin and everything is good now.
