### ISSUE TITLE
Goto Definition throws

### ISSUE THREAD

**Issue by denballakh** [sublimelsp/LSP#2407]
**Describe the bug**
Using `LSP-pyright`, click `Definition`. Nothing will happen visually.

**To Reproduce**
1. `LSP-pyright`
2. hover over something
3. click `Definition` (or `Type Definition` or `Declaration`)
4. see error in console: 
```py
Traceback (most recent call last):
  File "D:\Programs\Sublime Text 4\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 1681, in <lambda>
  File "D:\Programs\Sublime Text 4\Data\Installed Packages\LSP.sublime-package\plugin/core/open.py", line 96, in open_file
  File "D:\Programs\Sublime Text 4\Data\Installed Packages\LSP.sublime-package\plugin/core/open.py", line 82, in _find_open_file
TypeError: find_open_file() takes 2 positional arguments but 3 were given
```

**Expected behavior**
no error, I go to definition

**Environment (please complete the following information):**
- OS: windows
- Sublime Text version: 4121
- LSP version: 1.28.0
- Language servers used: pyright-1.2.42

**Comment by rchl** [comment]
You need to update your Sublime Text version to the latest stable version.

**Comment by jwortmann** [comment]
I think we could and should still fix it easily here.
```diff
- return window.find_open_file(fname, group)
+ return window.find_open_file(fname, group) if ST_VERSION >= 41XX else window.find_open_file(fname)
```

Just need to find out which ST version added the optional `group` argument for this method. It doesn't seem to be listed in the changelog.

Alternative would be to use the proper version restriction for LSP at https://github.com/sublimelsp/repository/blob/200d5081fdbbff3c2c21f85a4e84f600ec2a7a84/repository.json#L50

**Comment by rchl** [comment]
I suppose we should but at the same I'd prefer a world where people are on latest versions so that they benefit from latest fixes and don't waste time reporting issues that might already be fixed.

But then I suppose in case of paid software (ST) it might be a bit insensitive to require always the latest version given that someone might be using older version due to expired license, for example...

**Comment by denballakh** [comment]
I upgraded to ST4169, it fixed the problem. Thank you.
