### ISSUE TITLE
Two alternative hover definitions provided: one on mouseover, the other upon keyboard shortcut

### ISSUE THREAD

**Issue by mikez** [sublimelsp/LSP#2463]
**Is your feature request related to a problem? Please describe.**
The hover definitions of [pyright](https://github.com/sublimelsp/LSP-pyright) are great in most cases, however completely lack any docstrings for built-in names (unlike its proprietary Pylance). In such cases, the hover definition of [pylsp](https://github.com/sublimelsp/LSP-pylsp) is preferred.

**Describe the solution you'd like**
- A dream solution would be to have pyright's lsp_hover shown by default, unless it has no docstring, and then switch to pyright's output.
- Alternatively, have pyright's lsp_hover show _on mouseover_, whereas pylsp's lsp_hover is shown _on keyboard shortcut_.

**Describe alternatives you've considered**
Only using pyright or only using pylsp for lsp_hover. Since both have complimentary strengths here, this is a less ideal solution.

**Additional context**
–

**Comment by jfcherng** [comment]
In your per use case, the best solution is providing docstrings to pyright like https://github.com/DetachHead/basedpyright/issues/160#issuecomment-2041123766.

But those stubs are required to be generated by using Python installation on the user's machine.

**Comment by mikez** [comment]
@jfcherng Using custom stubs is a wonderful idea, thank you for the pointer! :)

pylsp: no use besides the stdlib docstrings.

**Comment by mikez** [comment]
@jfcherng Update: Using custom stubs seems to work great, **unless** I have "venvPath" and "venv" set in `pyrightconfig.json`.

When "venvPath" and "venv" are set, then it correctly includes all `extraPaths` **except** the stubs directory for some reason. Without `venvPath` and `venv`, it includes all of the `extraPaths` including the stubs directory.

**Comment by jfcherng** [comment]
Mind providing your full `pyrightconfig.json` and LSP-pyright's plugin settings?

**Comment by jfcherng** [comment]
OK. I guess it's a regression in pyright... https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674

**Comment by mikez** [comment]
@jfcherng 👍 I'll close this and move over the discussion to LSP-pyright.
