### ISSUE TITLE
Syntax highlighting in popups, returned by 3rd party language server, not work

### ISSUE THREAD

**Issue by istudyatuni** [sublimelsp/LSP#2472]
and I'm not sure, how to fix it

**Describe the bug**

[Tinymist](https://github.com/Myriad-Dreamin/tinymist) language server returns something like this on hover:

```py
{'contents': '```typc\n...\n```\nsome text'}
```

I tried to add new file_extension `typc` to [syntax definition](https://github.com/hyrious/typst-syntax-highlight/blob/main/Typst.sublime-syntax), but this doesn't help

**To Reproduce**

1. Download server binary from releases and install "Typst" extension
2. Add this to LSP settings:

  ```jsonc
  "tinymist-lsp": {
    "enabled": true,
    "command": [
      "path/to/tinymist"
    ],
    "selector": "text.typst"
  }
  ```

4. Create .typ file with this content:

  ```typ
  #let test() = [test]
  ```

6. Hover over `test()`

**Expected behavior**

Code block with definition is highlighted

**Screenshots**

Second screenshot from vscode

![image](https://github.com/sublimelsp/LSP/assets/43654815/e42a4cf1-3811-4c26-a0cb-1f255f2589dd)
![image](https://github.com/sublimelsp/LSP/assets/43654815/dbc0b0c4-001f-441f-af0f-f0a4861ee29f)

**Logs**

```log
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist::harness] handling textDocument/hover - (3) at Instant { tv_sec: 4646, tv_nsec: 450974903 }
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::analysis::global] def_use_lexical_hierarchy([..]/test.typ): compute
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 18.886µs
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::analysis::global] import(2): compute
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::analysis::global] def_use((2, 0)): compute
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::analysis::linked_def] def_name for function: Ident: "test"
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist_query::analysis::linked_def] okay for function: Some((Func(test), None))
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist::harness] handled  textDocument/hover - (3) in 2.91ms
:: [21:41:41.514] --> tinymist-lsp textDocument/hover (3): {'textDocument': {'uri': '[..]/test.typ'}, 'position': {'line': 0, 'character': 7}}
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist::harness] handling textDocument/codeAction - (4) at Instant { tv_sec: 4646, tv_nsec: 482253701 }
tinymist-lsp: [2024-05-07T18:41:41Z INFO  tinymist::harness] handled  textDocument/codeAction - (4) in 146.34µs
:: [21:41:41.545] --> tinymist-lsp textDocument/codeAction (4): {'textDocument': {'uri': '[..]/test.typ'}, 'range': {'start': {'line': 0, 'character': 7}, 'end': {'line': 0, 'character': 7}}, 'context': {'diagnostics': [], 'triggerKind': 2}}
:: [21:41:41.549] <<< tinymist-lsp (3) (duration: 34ms): {'contents': '```typc\nlet test();\n```', 'range': {'end': {'character': 9, 'line': 0}, 'start': {'character': 5, 'line': 0}}}
:: [21:41:41.674] <<< tinymist-lsp (4) (duration: 128ms): None
```

_Paths are redacted_

**Environment (please complete the following information):**

- OS: Archlinux
- Sublime Text version: 4169
- LSP version: 2.0.1
- Language servers used: ..

**Comment by jfcherng** [comment]
You can either override this file: https://github.com/sublimelsp/LSP/blob/main/language-ids.sublime-settings
or combining other issues you filed, invent a LSP-tinymist plugin.

**Comment by jwortmann** [comment]
> You can either override this file: https://github.com/sublimelsp/LSP/blob/main/language-ids.sublime-settings or combining other issues you filed, invent a LSP-tinymist plugin.

No, this is not used for the syntax highlighting in popus.

You can either add
```jsonc
    "mdpopups.sublime_user_lang_map": {
        "language": [["typst", "typc"], ["Typst/Typst"]]
    }
```
to you *Preferences.sublime-settings* user settings, or better provide a PR upstream at https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/st_mapping.py so that other users can also benefit from Typst syntax highlighting in popups.

See https://facelessuser.github.io/sublime-markdown-popups/settings/#mdpopupssublime_user_lang_map

It is also possible to extend the language map from a LSP-tinymist helper package via https://github.com/sublimelsp/LSP/blob/68c70316595685d2dc40f06e02b8d891f4bdab1a/plugin/core/sessions.py#L967 but imo this is not the best solution.

**Comment by Myriad-Dreamin** [comment]
Note that `typc` is not typst in markup mode but that in code mode.

![image](https://github.com/sublimelsp/LSP/assets/35292584/5ec2df03-5d44-4198-8ed1-1a4d3a187264)

**Comment by predragnikolic** [comment]
@istudyatuni  this comment gives the solution on how to add syntax highlighting in popups for Typst
-> https://github.com/sublimelsp/LSP/issues/2472#issuecomment-2099150902

From the command palette select `Preferences: Settings` and paste:
```jsonc
{
	"mdpopups.sublime_user_lang_map": {
		"typst": [["typst", "typc" ], ["Typst/Typst" ] ]
	}
}
```

Restart ST, and now hover over the variables.

<img width="133" alt="Screenshot 2024-05-20 at 18 20 41" src="https://github.com/sublimelsp/LSP/assets/22029477/2b333c91-222c-456e-a589-a183f8972c3a">

You should see syntax highlighting.

----

LSP uses mdpopus(sublime-markdown-popups) to render the markdown in popups.

A better way would be to submit a PR to mdpopus to add support for Typst. (here is a [PR example](https://github.com/facelessuser/sublime-markdown-popups/pull/71) of how to do that) 
that way someone in the future will not have to configure it manually.

If you have any additional questions feel free to ask.

**Comment by predragnikolic** [comment]
I will close the issue because these [1](https://github.com/sublimelsp/LSP/issues/2472#issuecomment-2120796367), [2](https://github.com/sublimelsp/LSP/issues/2472#issuecomment-2120796367) comments are pointing to the solution.

**Comment by istudyatuni** [comment]
Strangely, but this doesn't work for me. Probably after the LSP update it will work, but I can't check it now

**Comment by istudyatuni** [comment]
@predragnikolic I tested it in clean installation, and it still don't work for me

<details><summary>Preferences</summary>
<p>

```json
{
	"mdpopups.sublime_user_lang_map": {
		"typst": [["typst", "typc"], ["Typst/Typst"]],
	},
	"font_size": 12,
}
```

</p>
</details> 

<details><summary>LSP Preferences</summary>
<p>

```jsonc
// Settings in here override those in "LSP/LSP.sublime-settings"
{
    "clients": {
        "tinymist-lsp": {
            "enabled": true,
            "command": [
                "/usr/bin/tinymist"
            ],
            "selector": "text.typst",
            "auto_complete_selector": "text | markup",
            "initializationOptions": {
                "exportPdf": "never",
            }
        },
    },
}
```

</p>
</details> 

- tinymist v0.11.9
- LSP v2.1.0

Installed packages: LSP, Typst

Also popup differs from you screenshot - there is no `#` at the start:

![image](https://github.com/sublimelsp/LSP/assets/43654815/53361855-178a-409b-9b1b-7f3b4e86044d)

**Comment by jwortmann** [comment]
It doesn't work because the `let test();` expression is implicitly considered to be within a code context, so by itself it is just not highlighted by the Typst syntax highlighter.

What you would need to do is to create a separate syntax definition for `typc` code block contents (could be derived from the regular Typst syntax definition) and the put into your user settings something like
```json
	"mdpopups.sublime_user_lang_map": {
		"typst": [["typst"], ["Typst/Typst"]],
		"typc": [["typc"], ["User/MyTypcSyntax"]],
	},
```
or include the syntax into a LSP-tinymist package (see https://github.com/sublimelsp/LSP-pyright/blob/32ab2159cb79088b52684f068dcd23586ddecdc9/syntaxes/pyright.sublime-syntax and https://github.com/sublimelsp/LSP-pyright/blob/32ab2159cb79088b52684f068dcd23586ddecdc9/plugin.py#L88-L90 for an example in LSP-pyright, which similarly works around Pyright using non-standard syntax for its popups).
