### ISSUE TITLE
Allow `AbstractPlugin` to handle `window/logMessage` notification 

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#2493]
I would like to extract some information from `window/logMessage` notification.

E.g., 

```
:: [05:58:36.942] <-  LSP-pyright window/logMessage: {'type': 3, 'message': 'Pyright language server 1.1.367 starting'}
```

I would like to extract the pyright version `1.1.367` and store it as a class variable of `LspPyrightPlugin`.

## What I've Tried

```py
from lsp_utils import notification_handler
from lsp_utils import NpmClientHandler

class LspPyrightPlugin(NpmClientHandler):
	# ... some other codes

    @notification_handler("window/logMessage")
    def handle_window_log_message(self, params) -> None:
        print(f"{params = }")

```

but nothing gets printed. I guess `window/logMessage` is handled by `LSP` and then stop there. Never being propagated to `LspPyrightPlugin`'s handler.

**Comment by rchl** [comment]
Not quite related to your request but wouldn't it be error prone to rely on non-structured plain text messages like that? And potentially those logs can also be disabled through pyright settings in which case the functionality would be lost?

**Comment by jfcherng** [comment]
> Not quite related to your request but wouldn't it be error prone to rely on non-structured plain text messages like that? And potentially those logs can also be disabled through pyright settings in which case the functionality would be lost?

nothing will be lose. i treart it as a minor improvement.

**Comment by rchl** [comment]
To introduce a new functionality like that, I think there should be a good use case first and I don't think that this use case is particularly good. Processing all messages would add overhead and also it doesn't seem like a very reliable way.
You can already figure out the version of pyright running since you have the corresponding package.json that you could just read once per session.
