### ISSUE TITLE
LSP not installing from Package Control

### ISSUE THREAD

**Issue by gxanshu** [sublimelsp/LSP#2501]
**Describe the bug**

I'm trying to install some packages in a fresh copy of Sublime text but i'm unable to install LSP package. seems like `typing_extensions` is not able to install.

not sure if this issue is related to #2479 or not but i saw this https://github.com/sublimelsp/LSP/issues/2479#issuecomment-2120860031 comment on the ticket, which likely my problem here.

**Screenshots**
[Screencast from 2024-06-29 09-29-06.webm](https://github.com/sublimelsp/LSP/assets/68537640/0541e333-1ed4-4d54-aea6-234050d41346)

**Logs**

```
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'bracex' is not currently installed; installing...
Package Control: The dependency 'bracex' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'typing_extensions' is not currently installed; installing...
Package Control: The dependency 'typing_extensions' is not available
Package Control: The dependency 'typing_extensions' could not be installed or updated
```

**Environment (please complete the following information):**

- OS: ubuntu 24.04
- Sublime Text version: 4169
- LSP version: undefined
- Language servers used: [lsp_typescript]

**Comment by jfcherng** [comment]
some points to check:

1. you are using package control v4
2. you don't have custom channel in package control settings. if you do, you have to add v4 channel, which is in the default settings.

**Comment by gxanshu** [comment]
@jfcherng there is no custom channel in package control settings.
![image](https://github.com/sublimelsp/LSP/assets/68537640/3d2a8776-f0a9-4820-b77c-6892acd9d10d)

**Comment by jfcherng** [comment]
Are you using package control v4? Did you try to starts ST after package control is upgrade to v4?

**Comment by gxanshu** [comment]
@jfcherng Ah, thanks a lot! This happened automatically. When I started Sublime Text, it opened a tab saying that Package Control was updated to V4. Then I tried again to install LSP, and it worked fine.

Could you please explain a bit how this happened and why Package Control automatically updated to V4? It's so strange.

**Comment by jfcherng** [comment]
> It's so strange.

Isn't Package Control updates all plugins (including itself) automatically by default?

**Comment by jfcherng** [comment]
> Could you please explain a bit how this happened

1. ST installs Package Control from `somewhere`.
2. `somewhere` provides Package Control v3. Community members would like `somewhere` to provides v4 but the maintainer (wbond) of `somewhere` no longer uses ST in his daily work (I believe) and thus he no longer dedicates his free time on this.
3. After a ST restart, Package Control updates itself to v4 from GitHub.
4. LSP uses py38 dependencies, which require Package Control v4 channel.

**Comment by gxanshu** [comment]
@jfcherng thanks a lot for the information. Can't the community directly fetch package control 4 from GitHub why it calls `somewhere` ?

**Comment by jfcherng** [comment]
> @jfcherng thanks a lot for the information. Can't the community directly fetch package control 4 from GitHub why it calls `somewhere` ?

I call it `somewhere` just because I don't know the exactly URL. It's hard-coded in ST.

**Comment by dennusd** [comment]
Thank you for this solution, I was breaking my head over this issue, which I couldn't solve. Now it's running fine :)

**Comment by palexdev** [comment]
For anyone that may still struggle with this.
If Package Control does not update after restarting the app, you can force the update manually by using the command palette.
1) Open the command palette
2) Search for Package Control Update Package
3) Update Pakage Control
4) At this point it should show you the changelog and a popup telling you to restart
5) Restart

**Comment by ondohotola** [comment]
Is there a way of manually installing this? 

I have this running with `tinymist` on Intel, but as Package Control requires OpenSSL 1.1 which is not available (on Silicon 15.1) I can't install it.

If someone had a recipe what steps I must do to install LSP with all dependencies (manually) I'd greatly appreciate it.

**Comment by Gabriel-p** [comment]
@palexdev you are a lifesaver, this was driving me insane. Thank you!


@jfcherng mind if I ask where does this rumour come from? If the maintainer is no longer invested in the project this is *very* bad news for those of us using it

> the maintainer (wbond) of `somewhere` no longer uses ST in his daily work (I believe)

**Comment by jfcherng** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/6594915?u=c3fb600d3321cf555a4fd1b9734cc5119942ff29&amp;v=4&amp;size=80">@jfcherng](https://github.com/jfcherng?rgh-link-date=2025-02-10T16%3A35%3A04.000Z) mind if I ask where does this rumour come from? If the maintainer is no longer invested in the project this is _very_ bad news for those of us using it

It looks like that it was my bad memory after a quick search.

![Image](https://github.com/user-attachments/assets/de037504-676e-424f-9a87-bb59cdbe80cd)
