### ISSUE TITLE
 Add support for Nix LSP (Nil)

### ISSUE THREAD

**Issue by MrFoxPro** [sublimelsp/LSP#2551]
It would be nice to have LSP and syntax highlightning (not sure if it's LSP responsibility) for [Nix](https://nix.dev/tutorials/nix-language.html).
Language server: [Nil](https://github.com/oxalica/nil) 
Example integration with Lapce editor: https://github.com/MrFoxPro/lapce-nix

**Comment by jwortmann** [comment]
Have you tried to add a basic config for this server in `LSP.sublime-settings`? From its Readme it appears that the server can be started just by running `nil` (I haven't tested). There is a syntax highlighting package for Nix on Package Control, which would be required: https://packagecontrol.io/packages/Nix

```jsonc
{
    "clients": {
        "nil": {
            "enabled": true,
            "command": ["nil"],
            "selector": "source.nix"
        },
    }
}
```

**Comment by MrFoxPro** [comment]
> Have you tried to add a basic config for this server in `LSP.sublime-settings`? From its Readme it appears that the server can be started just by running `nil` (I haven't tested). There is a syntax highlighting package for Nix on Package Control, which would be required: https://packagecontrol.io/packages/Nix
> 
> ```js
> {
>     "clients": {
>         "nil": {
>             "enabled": true,
>             "command": ["nil"],
>             "selector": "source.nix"
>         },
>     }
> }
> ```

That works with Nix extension, thank you very much! However, seems like it's kinda unmaintained.

**Comment by predragnikolic** [comment]
>  However, seems like it's kinda unmaintained.

What seems unmaintained? The [Nix](https://packagecontrol.io/packages/Nix) syntax highlighting package?
