### ISSUE TITLE
Support dynamic capabilities

### ISSUE THREAD

**Issue by ehuss** [sublimelsp/LSP#372]
Some servers rely on the `client/registerCapability` message to enable features dynamically.  It would be nice if the plugin supported this.

In my particular use case, RLS (rust) needs this to support range formatting.  The initialization indicates it is initially not supported, and it is not turned on until `didChangeConfiguration` is sent with certain settings, after which it sends a `registerCapability` to indicate that range formatting is now enabled.

**Comment by tomv564** [comment]
This is definitely a major mechanism LSP is missing, I'd like to understand it a bit more.

I see the benefit of capability registration for server-initiated behaviour.
But from RLS's perspective, why is range formatting not always available?

**Comment by ehuss** [comment]
I believe they want it to be an explicit opt-in feature where it is disabled by default because it is in an experimental state.

**Comment by AmjadHD** [comment]
[Vscode-json-languageserver](https://github.com/vscode-langservers/vscode-json-languageserver/blob/master) requires dynamic capability registration to support range formatting:
> Formatting support requires the client to support dynamicRegistration for rangeFormatting. If not supported by the client, the server will not offer the format capability.

**Comment by tomv564** [comment]
Ah good, another example:

(working link: https://github.com/vscode-langservers/vscode-json-languageserver/blob/f959652da2a7bb8b80303fcd02702d4d01ee280b/src/jsonServerMain.ts)

In this case the server wants to check client-sent settings before enabling a capability, and that cannot be done while replying to "initialize".

The Metals server uses it with the "documentSelector" parameter for the watched files API, that also makes sense.

Perhaps we can pick some of these capabilities to be not statically enabled.

**Comment by rwols** [comment]
This is in master now.
