### ISSUE TITLE
Feature request: Support incremental mode

### ISSUE THREAD

**Issue by muglug** [sublimelsp/LSP#437]
Here you're passing the whole document in one single change:
https://github.com/tomv564/LSP/blob/f5a4dcfbe117ddf1a07e1c971e8b14ca7e311c00/plugin/core/windows.py#L292-L294

It would be awesome to support incremental changes (if the language server also supports it).

Is grabbing those diffs supported by Sublime's API the way it is in VS Code?

**Comment by predragnikolic** [comment]
This is just a tought.
With `view.run_command('diff_changes')` we can get an output like this:
```diff
--- /home/predrag/Documents/exa/index.html	Mon Oct 22 19:09:45 2018
+++ /home/predrag/Documents/exa/index.html	Mon Oct 22 19:11:54 2018
@@ -25,7 +25,7 @@
 ctx.arc(90, 60, 5, 0, Math.PI * 2)
 ctx.stroke()
 
-
+dsa
 // ctx.lineTo(200, 100)
 // ctx.closePath()
 
```
This will show all unsaved changes. But then we would need to parse it to remove things like the `+` and `-`, `@@`, `+++`... A regex for this might look something like this.
```diff
^--- .*
^+++ .*
^@@ .*? @@ 
^-
^+
```
I am not sure if this approach is better than passing the whole file content?

**Comment by tomv564** [comment]
Yep, this would be nice to have for completeness' sake! 
I didn't see an easy way to accomplish it with the Sublime Text API.
Two strategies I thought of were to track document change events and glue them together (could be complex) or do a full-document diff (simpler, but could be expensive?).

Perhaps other packages have investigated it further? Microsoft's TypeScript plugin, maybe GoSublime?

**Comment by muglug** [comment]
For the time being I'm experimenting with full document diffing in PHP (algorithms are here: https://github.com/vimeo/psalm/blob/2c3e9288f32c4e898caa4e1467b8e5a0af34c505/src/Psalm/Diff/FileDiffer.php) and it's pretty quick.

From what I can tell those packages just send the full source to be linted.

**Comment by maddanio** [comment]
is gluing the changes together so complex? sounds like the most sensible solution...ah, i see, applying the diffs to each other could be hard...hmmm...
cant you just pass them one by one? or are they too small? maybe only glue them if they dont overlap?

**Comment by tomv564** [comment]
I think sending individual edits is the safest way - let the server worry about applying the changes in-order correctly.

Unfortunately, I did not find a Sublime API that tells you 'this region has this text replaced/inserted'. Instead, you can listen to the command history and track cursor movement to "guess" what happened at which location, but it's error prone. 

It might be worthwhile to start with sending partial updates for edits from predictable commands (eg. 'insert'), and send a full update whenever the user edits with an unpredictable command.

**Comment by maddanio** [comment]
We could ask the sublime author to add such hooks, should not be so hatd

**Comment by rwols** [comment]
> We could ask the sublime author to add such hooks, should not be so hatd

Yeah, I think incremental changes are best left to the internals of ST, optionally exposing them via an API.

**Comment by AmjadHD** [comment]
https://github.com/SublimeTextIssues/Core/issues/3017

**Comment by AmjadHD** [comment]
FTR, ST4 comes with new facilities that should make this feasable like `on_text_changed()`, `sublime.TextChange` and `sublime.HistoricPosition`.
(see https://discordapp.com/channels/280102180189634562/280157067396775936/677200038409273363)

**Comment by rwols** [comment]
This will be available for a newer of ST, but not 3211.
