### ISSUE TITLE
no completion on trigger characters

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP#460]
* OS and language server: Windows, lsptsserver
* How did you install the package ? git (latest master)
* Minimal reproduction steps:
1. open a .js file
2. type `console`
3. type `.`
result no autocompletion (list of methods and properties)
* Log
after pressing `.`
```
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP: <--  textDocument/publishDiagnostics
LSP: severity check 1 <= 3
```
*Notes
- `textDocument/completion` is not sent
- `textDocument/completion` is sent when hitting <kbd>ctrl</kbd>+<kbd>        </kbd>
- I set the `.` as a trigger character for `source.js` in my global preferences file:
```json
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": ".",
			"selector": "source.python, source.js"
		}
	],
```
- completion on `.` works fine with python and others.

**Comment by rwols** [comment]
Does this still happen?

**Comment by AmjadHD** [comment]
yes

**Comment by tomv564** [comment]
The settings for auto_complete_triggers are overridden with the server's supported chars when a view is opened (see `register_trigger_chars`). Perhaps you can investigate if this registration is taking place, and what running `sublime.active_window().active_view().settings().get("auto_complete_triggers")` in the console says ?
