### ISSUE TITLE
How about an organization?

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#508]
Hello, 
Lately I been thinking about how we could improve the user experience for other people.

What if we create an organization like this https://github.com/SublimeLinter, in our case SublimeLSP
or something other...

And in that organization we could create repositories for language handlers:
LSP-typescript
LSP-rust
LSP-python
LSP-php
LSP-intelephense

And when one language handler is done, submit a PR to package control.

<hr>

I always wanted to create these language handlers.
The reason I didn't do it is because I don't want the repositories to be directly associated with my github accont. Because maybe some day in the future I will lose interest in sublime or some other reason... I don't want the repos to be unmaintained.  

I don't see that problem if we have an organization. All the repositories are in the SublimeLSP organization. And there will hopefully always be people who will do contributions. 

**NOTE:** I have no experience in github organizations :D I just think this could be a good idea to consider

**Comment by tomv564** [comment]
Yes, I've wanted to do this for a while, great to hear there is interest.

One issue to plan for is moving the repo for this package (people's git remotes and Package Control as well)

**Comment by predragnikolic** [comment]
Here is a useful link. https://help.github.com/articles/transferring-a-repository/#whats-transferred-with-a-repository

> When you transfer a repository, its issues, pull requests, wiki, stars, and watchers are also transferred. If the transferred repository contains webhooks, services, or deploy keys, they will remain associated after the transfer is complete. Git information about commits, including contributions, is preserved. In addition:

> If the transferred repository has any forks, then those forks will remain associated with the repository after the transfer is complete.

But Package Control may be a problem. 
One way around this is just to leave this repo at your account :)

**Comment by randy3k** [comment]
I believe that PC will just follow the redirected repo. Anyway, it’s also easy to submit a PR to package control channel.

**Comment by predragnikolic** [comment]
Made the first step :)
https://github.com/sublimelsp

If someone are interested in getting in, please say in the comments :)

**Comment by tomv564** [comment]
Great job! I'll move some of my LSP-addon packages there when I get some free time!

**Comment by tomv564** [comment]
Just want to update, I haven't forgotten about this but want to catch up on some neglect in this repo before moving it!

**Comment by tomv564** [comment]
LSP is now moved to the @sublimelsp org!
