### ISSUE TITLE
API reference and docs on how to implement a LSP plugin

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP#641]
Related to #628, this project should provide an API reference and docs on how to implement a LSP plugin, some of the questions that I have in mind are:
* How to add custom configurations (settings file), and handle updates, should I implement a `ConfigManager` subclass ?
* what's a `DocumentSyncListener` ?
* ...
as I said in #628, this project should focus on being a framework, and leave out language servers support.

**Comment by tomv564** [comment]
The easy question:
DocumentSyncListener listens to view lifecycle events (load, activate, change, save, close) to notify language servers about changes to document state.

About writing docs for LanguageHandlers:
I think working code can be helpful - Raoul gave a link of some implementations in the earlier issue, and there's also https://github.com/tomv564/LSP-rust/ 

If the functionality your server needs is not in the examples, perhaps you can discuss a specific example here and we can come to needed documentation or API changes?

**Comment by AmjadHD** [comment]
how can I get a reference to the view in which a language server is running ?
My use case is: I want to handle RLS's `"window/progress"` notification so I want to show progress details in the statusbar.

**Comment by predragnikolic** [comment]
Hello @AmjadHD,
You can have a look at what @Kronuz did in his fork https://github.com/Kronuz/Rust-CodeIntel/blob/master/plugin.py

**Comment by tomv564** [comment]
Yeah, that's a good example. To save a bit of time, he uses this spinner class https://github.com/Kronuz/SublimeCodeIntel/blob/master/plugin/core/spinner.py which uses `sublime.status_message` and emoji chars to show a spinner.

Since you're not getting progress for a specific document, you could also `set_status` on `sublime.active_window().active_view()`, but I believe that would disappear when the user switches views?

**Comment by AmjadHD** [comment]
Thanks @predragnikolic

> but I believe that would disappear when the user switches views?

I want the progress to only be visible in the views where the server is running.
The problem with using `sublime.active_window().active_view()` (i guess) is when the user switches to a non supported view (where no server is running) in between the notification and it's handling.

**Comment by ayoub-benali** [comment]
@AmjadHD do you have any WIP branch for this issue ? I also want to provide Metals with compilation status bar.

**Comment by dinvlad** [comment]
@AmjadHD could you share a code example on how to enable a new language server? We've got some interest in enabling our [wdl-lsp](https://pypi.org/project/wdl-lsp) for Sublime users..

**Comment by AmjadHD** [comment]
@ayoub-benali not for now, I haven't reached any usable state yet when I do (if I ever) I'll be pleased to notify you, but I did manage to handle RLS's "window/progress" notification successfully, I simplified the code in https://github.com/Kronuz/SublimeCodeIntel/blob/master/plugin/core/spinner.py for RLS's purpose:
```python
import sublime


class Spinner:
    FRAMES = ('◐', '◓', '◑', '◒')
    enabled = False

    def start(self, prefix: str, postfix: str):
        state = 0

        def _animate():
            nonlocal state

            if self.enabled:
                sublime.status_message("{} {} {}".format(prefix, FRAMES[state], postfix))
                sublime.set_timeout_async(_animate, 100)
                state = (state + 1) % 4

        if not self.enabled:
            self.enabled = True
            _animate()

    def stop(self, message: str):
        self.enabled = False
        sublime.status_message(message)


spinner = Spinner()
```

**Comment by AmjadHD** [comment]
@dinvlad If your language server is compatible with the LSP (protocol) then it should run fine in LSP (plugin), otherwise if you're interested in creating a full plugin then you should start with a `LanguageHandler`, https://github.com/tomv564/LSP-rust/ is a good example on how to implement a `LanguageHandler`.

**Comment by dinvlad** [comment]
Thanks @AmjadHD, could you clarify how to configure LSP (plugin) to point it to our server? We can work on turning that into a stand-alone plugin, but atm it's not even clear how to "enable" it using this (**tomv564/LSP**) plugin.

**Comment by ayoub-benali** [comment]
@AmjadHD thanks, I create a language handler here https://github.com/scalameta/metals-sublime

**Comment by ayoub-benali** [comment]
@dinvlad you can add a client for your server by editing `LSP Settings` (Command Palette Cmd + Shift + P ). Add an entry to the `clients` key. You can find example [here](https://github.com/tomv564/LSP/blob/393262826d51f24220dad40c17395255ca9f6c66/LSP.sublime-settings#L143) 
Basically fill in the `command`, `scopes`, `languageId` and `languageId`. 
After that you can enable the client for a project, in command palette `LSP: enable language server in project`, hit enter and you will find you client.


If you need more help, the gitter channel is probably a better place.

**Comment by AmjadHD** [comment]
I want to create a settings file for LSP-RLS which the user can edit or override some of it's entries in projects settings if desired, in this regard I want to ignore settings coming from LSP
these are the contents of `LSP-RLS.sublime-setting`:
```jsonc
{
    // these are sent directly to the server
    // can be overriden in project settings
    "settings": {
        "all_features": false,
        "all_targets": true,
        "build_bin": null,
        "build_command": null,
        "build_lib": null,
        "build_on_save": false,
        "cfg_test": false,
        "clear_env_rust_log": true,
        "clippy_preference": "opt-in",
        "features": [],
        "full_docs": null,
        "jobs": null,
        "no_default_features": false,
        "racer_completion": true,
        "rustflags": null,
        "rustfmt_path": null,
        "show_hover_context": true,
        "show_warnings": true,
        "sysroot": null,
        "target": null,
        "target_dir": null,
        "unstable_features": false,
        "use_crate_blacklist": true,
        "wait_to_build": 1500
    },
    // these are for the plugin
    "rust-client": {
        "channel": null,
        "disableRustup": false,
        "logToFile": false,
        "nestedMultiRootConfigInOutermost": true,
        "revealOutputChannelOn": "never",
        "rlsPath": null,
        "rustupPath": "rustup",
        "trace": {
            "server": "off"
        },
        "updateOnStartup": false,
        "useWSL": false
    }
}
```
but LSP handles settings and overrides assuming all settings are meant to be in `LSP.sublime-settings`, this is not flexible enough for plugins needs, I believe VSCode leaves handling settings for plugins.
what's the straightforward way to accomplish this ?

**Comment by AmjadHD** [comment]
It should be beneficial to examine VSCode's [language server guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) in order to provide a similar API.

**Comment by rwols** [comment]
There are many examples of LSP-foo helper packages now. See https://github.com/sublimelsp
