### ISSUE TITLE
The Go To on a cloned view is enabled on the first view, instead of the current one

### ISSUE THREAD

**Issue by evandrocoan** [sublimelsp/LSP#718]
Copied from: https://github.com/SublimeTextIssues/Core/issues/1482 (The Go To on a cloned view is enabled on the first view, instead of the current one)

```patch
diff --git a/plugin/definition.py b/plugin/definition.py
index 7e77681..a84899c 100644
--- a/plugin/definition.py
+++ b/plugin/definition.py
@@ -42,12 +42,17 @@ class LspSymbolDefinitionCommand(LspTextCommand):
             # save to jump back history
             get_jump_history_for_view(self.view).push_selection(self.view)
 
+            # https://github.com/SublimeTextIssues/Core/issues/1482
+            group, view_index = window.get_view_index(self.view)
+            window.set_view_index(self.view, group, 0)
+
             location = response if isinstance(response, dict) else response[0]
             file_path = uri_to_filename(location.get("uri"))
             start = Point.from_lsp(location['range']['start'])
             file_location = "{}:{}:{}".format(file_path, start.row + 1, start.col + 1)
             log(2, "opening location %s <%s>", location, file_location)
             window.open_file(file_location, sublime.ENCODED_POSITION)
+            window.set_view_index(self.view, group, view_index)
             # TODO: can add region here.
         else:
             window.run_command("goto_definition")
```

**Comment by tomv564** [comment]
How do people who don't use LSP deal with it?
Also, how often do you work with cloned views deliberately? I usually close accidental clones immediately when I find them.

**Comment by evandrocoan** [comment]
> How do people who don't use LSP deal with it?

They use the same patch I suggested here and there (https://github.com/SublimeTextIssues/Core/issues/1482). On Sublime Text, you need to patch the `Default/symbol.py` file. While on this plugin, you need to patch the `plugin/definition.py` file.

> Also, how often do you work with cloned views deliberately?

Every day, every hour. Sometimes I clone the same view up to 10 clones.

**Comment by rwols** [comment]
I cannot actually reproduce this anymore with the latest st4000-exploration branch. The caret jumps to the def in the same view if I have multiple views open of the same underlying buffer.

**Comment by jwortmann** [comment]
I'd like to reopen this because I can reproduce this issue on the current main branch. So it seems like this was regressed at some point.

I'm working on a fix.

**Comment by rchl** [comment]
What are the exact repro steps?
What is a "cloned" view these days? Is it the "Split view" action or just opening same file in another column?

**Comment by jwortmann** [comment]
It is the "Split view". For the behavior when the same file is opened in different columns, we already have the `force_group` command argument, following ST's default behavior in LSP's predefined menu/command palette items.

**Comment by jwortmann** [comment]
Here is a video to demonstrate the current behavior. It opens the definition in the left view, but I would expect it to open it in the active (right) view. You might need to refocus the view first, in order to attach the view to the server, due to the ST bug with the EventListeners not called after Split View.

[split_view.webm](https://github.com/sublimelsp/LSP/assets/6579999/dd152b0c-245f-413f-8276-4fa67ce38ce1)

**Comment by evandrocoan** [comment]
> What is a "cloned" view these days?

It has several views in the same buffer (text file). Each view shows a different part of the file independently, while editing the buffer contents in one of them affects all view buffers but not their "viewing" position.

Split view does this, but it also splits the editor into two columns.

![image](https://github.com/sublimelsp/LSP/assets/5332158/6505bd29-93dc-4a72-986c-5750a6a0b1f0)

It may also be known as: 
![image](https://github.com/sublimelsp/LSP/assets/5332158/3f322933-d3e6-4a97-a4fd-234edb716031)

**Comment by rchl** [comment]
I was asking because ST doesn't include close options by default anymore (even if functionality might be there).

**Comment by evandrocoan** [comment]
I just downloaded the latest version, and the option is still there:
![image](https://github.com/sublimelsp/LSP/assets/5332158/545885d8-ea58-4605-a921-afd97f1b1c42)

I think it never was exposed on the tab options (as in my screenshot). I know VSCode does not have this option anywhere I could find yet.

**Comment by rchl** [comment]
ST3 has that option in the File menu instead of `Split View`.
