### ISSUE TITLE
Create a step by step tutorial on how to set up a language server for beginners

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#805]
It can be hard to figure exactly what goes where for new users. Create a complete step by step example in the docs to help new users.

**Comment by jwortmann** [comment]
The main page of the documentation seems pretty unorganized and inconsistent overall and there are some more broken links. I think I could create a PR to clean it up:
* extend the "Getting started" section with more information to make it easier for new users
* put the "Server Configuration" and "Per-projects overrides" sections at the top of the page as well
* order the server configurations alphabetically by language and put IntelliJ as a subsection into Java
* use consistent formatting and indentation for the configuration code blocks
* fix typos and improve some descriptions

What do you think? I've seen you made a PR to remove the "syntaxes" keys, so should I wait for it to be merged first?

**Comment by rwols** [comment]
Go for it! You may assume my "remove syntaxes" PR will not be in master for a long time :)
