### ISSUE TITLE
Using the Sourcegraph Javascript-typescript-langserver

### ISSUE THREAD

**Issue by RoundRobin2** [sublimelsp/LSP#823]
Hi,
Just wanted to thank you for the LSP.
I have testing various servers and found that to get the Javascript language server from source graph to recognise javascript files i need to change the settings to.

`
{
	"clients":
	{
		"javascript-typescript-langserver":
		{
			"enabled": true,
			"command": ["javascript-typescript-stdio"],
      "languages": [{
        "scopes": ["source.js", "source.jsx"],
        "syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"],
        "languageId": "javascript"
      }, {
        "scopes": ["source.ts", "source.tsx"],
        "syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"],
        "languageId": "typescript"
      }
      ]
		}
	},
	"diagnostics_gutter_marker": "circle",
	"log_debug": true,
	"log_stderr": true,
	"log_payloads": true,
	"show_view_status": true
}
`

The difference being that the Syntaxes was originally set to "Javascript" which in my case wasn't enough for LSP to pick *.js files.

**Comment by rchl** [comment]
You shouldn't be using `JavaScript (Babel)` syntax as it's old and unmaintained. Default built-in syntax supports all that stuff already.

**Comment by rwols** [comment]
Related: https://github.com/tomv564/LSP/issues/540

**Comment by rchl** [comment]
I think #540 better describes the problem and a possible solution. Closing this in favor of the other.
