### ISSUE TITLE
`scopes` seems to have no effect

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP#834]
## ENV

- LSP: 0.9.3
- Windows 7 x64

## Problem

The `scopes` seems to be ignore. Only `syntaxes` is used. In my memory, both should be satisfied to enable the language server?

## Reproducer

```js
"py-lsp": {
    // pip install -U python-language-server[all]
    "enabled": true,
    "command": ["pyls"],
    "settings": { /* long but shouldn't related to this issue */ },
    "scopes": ["source.python"],
    "syntaxes": [
        "Packages/Python/Python.sublime-syntax",
        //
        // the following "JavaScript" syntax is not related to Python at all
        //
        "Packages/JavaScript/JavaScript.sublime-syntax",
    ],
    "languageId": "python",
},
```

When I open a JavaScript file, the python lsp is enabled. This happens in every language server. `py-lsp` and `JavaScript` are just an example.

**Comment by rwols** [comment]
I would like to remove the syntaxes key in favor of just checking the scopes key. So then this bug would disappear automatically. I have a work-in-progress branch here which should already be working: https://github.com/sublimelsp/LSP/pull/825. But, it will require some major effort to get it working for the tests. I invite you to try out this branch.

**Comment by tomv564** [comment]
LSP has always started servers based on syntax only up to now.
Can you share a real example of what you are trying to accomplish?

**Comment by jfcherng** [comment]
@tomv564 

> LSP has always started servers based on syntax only up to now.

Interesting :thinking: What's the purpose of setting `scopes` then?

> Can you share a real example of what you are trying to accomplish?

Actually I have no goal. Just sharing a finding which I thought counter-intuitive.

**Comment by jfcherng** [comment]
> LSP has always started servers based on syntax only up to now.

Closing because ↑

I am not asking supporting this. I am just aware that I thought this is an issue because of my wrong knowing. I actually prefer the `scopes`-only solution if possible.
