### ISSUE TITLE
LSP options greyed out

### ISSUE THREAD

**Issue by adevart** [sublimelsp/LSP#835]
I have installed typescript-language-server and javascript-typescript-langserver into my node path and they run ok from the Mac command-line.

When I try to enable them using the LSP Enable Language Server Globally, it shows "starting server..." for a few seconds and then the message goes away.

If I change the command property to something random, it does the same. I would have expected it to log an error if I used a command that wasn't found.

I get no debug output in the console log, even when I turn on "log_debug":true.

It's using the settings file because when it enables the server, it changes the enabled values in the corresponding server properties but there's no output and the menu items in the LSP context menu are greyed out.

Is there a way to debug what's going wrong?

* MacOS, latest version of Sublime
* LSP installed from package control

**Comment by rwols** [comment]
In what kind of file are you trying to run with typescript-language-server?

Please run the following two commands in the SublimeText console:

```
view.settings().get("syntax")
```
and
```
view.scope_name(0).split()[0]
```

**Comment by adevart** [comment]
The first is:
'Packages/TypeScript/TypeScript.tmLanguage'
The second is:
'source.ts'

Is there a way that I can check that the server started ok? There's no confirmation in the log panels that says if the server started or failed ok. The name of the server doesn't stay in the status bar so I assumed it wasn't starting ok but it didn't log an error.

**Comment by jfcherng** [comment]
> The name of the server doesn't stay in the status bar so I assumed it wasn't starting ok but it didn't log an error.

Since 0.9.3, LSP no longer log message in sublime's console. 
![image](https://user-images.githubusercontent.com/6594915/71417973-35103200-26a3-11ea-89d0-8e0b543ef1eb.png)
Try this from the command palette.

**Comment by adevart** [comment]
The Language Server panel is empty, I thought that was a bit unusual. I expected something to be logged there.

**Comment by jfcherng** [comment]
Maybe turn all 4 logs on.

```js
    "log_payloads": true,
    "log_debug": true,
    "log_server": true,
    "log_stderr": true,
```

**Comment by adevart** [comment]
Turning on all the logs, I get the following when I start the Typescript server:

LSP: global configs ['golsp=False', 'gopls=False', 'lsp-tsserver=False', 'dart=False', 'haskell-ide-engine=False', 'rls=False', 'metals=False', 'reason=False', 'clangd=False', 'polymer-ide=False', 'phpls=False', 'ocaml=False', 'pyls=False', 'ruby=False', 'bashls=False', 'flow=False', 'jdtls=False', 'ra-lsp=False', 'intelephense-ls=False', 'typescript-language-server=True', 'rlang=False', 'elixir-ls=False', 'javascript-typescript-langserver=False', 'cquery=False', 'vscode-css=False', 'eslint=False']
LSP: window has override for lsp-tsserver {'enabled': True}
LSP: window 21 starting 1 initial views
reloading settings Packages/User/LSP.sublime-settings
LSP: global configs ['golsp=False', 'gopls=False', 'lsp-tsserver=False', 'dart=False', 'haskell-ide-engine=False', 'rls=False', 'metals=False', 'reason=False', 'clangd=False', 'polymer-ide=False', 'phpls=False', 'ocaml=False', 'pyls=False', 'ruby=False', 'bashls=False', 'flow=False', 'jdtls=False', 'ra-lsp=False', 'intelephense-ls=False', 'typescript-language-server=True', 'rlang=False', 'elixir-ls=False', 'javascript-typescript-langserver=False', 'cquery=False', 'vscode-css=False', 'eslint=False']
LSP: window has override for lsp-tsserver {'enabled': True}

The LSP panel stays empty. I tried uninstalling and reinstalling the LSP.

**Comment by rwols** [comment]
Could you share your entire Packages/User/LSP.sublime-settings file?

**Comment by adevart** [comment]
It's pretty much set at the defaults beside the log entries and the client enabled entry is added automatically when I enable the server.

{
	"clients":
	{
		"typescript-language-server":
		{
			"enabled": true
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_server": true,
	"log_stderr": true
}

**Comment by rwols** [comment]
Change it to:

```
{
	"clients":
	{
		"typescript-language-server":
		{
			"enabled": true,
                        "syntaxes": ["Packages/TypeScript/TypeScript.tmLanguage"]
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_server": true,
	"log_stderr": true
}
```
and things should work for you

**Comment by jfcherng** [comment]
there is no `"command"` btw.

**Comment by adevart** [comment]
Thanks, now it's working with the above config and restarting the LSP server. I'm getting logged info in the panel and the menu isn't greyed out.

I was looking for a way to do automatic imports like if I type a class name, it would add the module import. Is that something this package can do?

**Comment by rwols** [comment]
> I was looking for a way to do automatic imports like if I type a class name, it would add the module import. Is that something this package can do?

This plugin can handle "additional text edits" so it now depend on the language server's capabilities, as this plugin is simply a translator between the language server protocol and the ST API from a high-level point of view. You can investigate this by looking at the source of https://github.com/theia-ide/typescript-language-server, or asking a question there.

**Comment by adevart** [comment]
Great, thanks very much for the help.
