### ISSUE TITLE
Fix the CI

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#840]
The CI (travis, coveralls) is broken after the migration to the sublimelsp organization.

- [x] GitHub Actions (currently only macOS)
- [x] Fix flaky tests
- [x] Code coverage reports are too intrusive for the PRs IMO
- [ ] Add windows job to GitHub Actions (would be nice to have)
- [x] Make the Linux job stable
- [x] Disable coverage patch reporting

**Comment by tomv564** [comment]
In the coveralls provider you could disable the patch coverage check, is there any reason you couldn't use coveralls?

**Comment by rwols** [comment]
the coverage is computed via UnitTesting. I couldn't get coveralls to work with it. Agreed that the patch reporting should be disabled :)

**Comment by rwols** [comment]
Let's revisit this once ST4 is out and we can have github actions with UnitTesting again.
