### ISSUE TITLE
Working with files outside the current workspace folder

### ISSUE THREAD

**Issue by Serega124** [sublimelsp/LSP#844]
Sometimes when working within some workspace folder I need to edit config files that are outside the folder (e.g. json files from other packages). And it would be great if json-lsp provided intellisense for that files without closing current project.

**Comment by predragnikolic** [comment]
Hello @Serega124, 
Is your problem the same as #845 ?

**Comment by Serega124** [comment]
@predragnikolic, yes. Your [comment](https://github.com/sublimelsp/LSP/issues/845#issuecomment-569466137) describes my case.

**Comment by rwols** [comment]
should be fixed by #850, please continue the conversation in #845 if any issues arise.
