### ISSUE TITLE
other value for auto_show_diagnostics_panel: when_no_other_panel_visible

### ISSUE THREAD

**Issue by math2001** [sublimelsp/LSP#852]
Currently, the only possible values for `auto_show_diagnostics_panel` are `never`, `always` and `saved`. It'd be nice if there was an other value, maybe `when_no_other_panel_visible` maybe (this name isn't the best, but I don't have a better idea).

The idea is to only show the diagnostic panel *if no other panel is already visible*. This is especially important when using build systems. I build my python code, and then as soon as I save, the build result is hidden by the diagnostics (it's even worse because I have `save_on_focus_lost` set to `true`).

The workflow I would like to have is something like this:

- diagnostic are shown as soon as I open the file
- I write code
- I build my file
- the build result prevents the diagnostics from showing up
- I press escape to hide the build results
- the diagnostic panel is now shown
- if I decide to re-show the build results, then the diagnostic panel isn't forced onto me, it just waits.

The behavior should be exactly the same for any other panel (eg the console).

It should be really easily to implement: just make sure `window.active_panel()` is `None` before showing the diagnostics.

In fact, this `when_no_other_panel_visible` could work with `always` and `saved`, so maybe have the allowed values could be something like:

- `never`
- `saved`
- `saved:when_no_other_panel_visible`
- `always`
- `always:when_no_other_panel_visible`

I'd be happy to contribute that feature if the maintainers think it's a good idea :slightly_smiling_face:

**Comment by tomv564** [comment]
I think LSP may have behaved like this in the past and I feel it's a good default behaviour. Perhaps you want to contribute the needed check?

**Comment by rwols** [comment]
Fixed in #1170 (but only for ST4). The behavior is default and not a setting.
