### ISSUE TITLE
Sourcekit lsp

### ISSUE THREAD

**Issue by Jax0rz** [sublimelsp/LSP#863]
Any plan to  support [SourceKit LSP](https://github.com/apple/sourcekit-lsp)

**Comment by rwols** [comment]
You can always manually add an entry to the `"clients"` dictionary of your Packages/User/LSP.sublime-settings file.

In case of SourceKit-LSP, I believe you're supposed to download a nightly toolchain with the language server binary included: https://github.com/apple/sourcekit-lsp#getting-started

They even have instructions for Sublime Text it seems: https://github.com/apple/sourcekit-lsp/tree/master/Editors#sublime-text
