### ISSUE TITLE
Creaete separate tags for package control for ST4?

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#867]
How about adding a new tag for ST4 on package control? 

That would allow people who use ST4 to test the `st4000-exploration` branch :)

Here is an example I found on how to achieve this:
```

		// If your package is only compatible with specific builds of
		// Sublime Text, this will cause the package to be hidden from
		// users with incompatible versions.
		//
		// The "tags" key can be true for all valid semantic version tags, or
		// can be a prefix string. Only tags in the form
		// {prefix}{semantic_version} will be selected. In the example below,
		// the entry with "sublime_text": "<3000" will match tags like:
		//
		// "st2-1.0.0"
		// "st2-1.1.0"
		//
		// The release with "sublime_text": ">=3000" will match tags like:
		//
		// "st3-1.0.0"
		// "st3-1.1.0"
		{
			"details": "https://github.com/wbond/sublime_alignment",
			"releases": [
				{
					"sublime_text": "<3000",
					"tags": "st2-"
				},
				{
					"sublime_text": ">=3000",
					"tags": "st3-"
				}
			
```

**Comment by rwols** [comment]
I've made the appropriate changes here https://github.com/sublimelsp/package_control_channel/tree/lsp-tag-split

One question I have is what happens when we don't make a new tag in the meantime and this is merged in the upstream package_control_channel repository?

**Comment by rwols** [comment]
Perhaps it's a better strategy to use the minimum-supported ST build number as the major version. e.g.

3092.0.0
3092.0.1
3092.1.0
3092.1.1
4065.0.0
4065.0.1
4065.1.1

This way, we can start using the latest features as they arrive for ST4. We then specify the minimum supported ST build in the package control entry:

```js
{
  "details": "https://github.com/sublimelsp/lsp",
  "releases": [{
      "sublime_text": "3092 - 4065",
      "tags": "3092."
    }, {
      "sublime_text": "4065 - 4111",  // imaginary 4111 build with new features
      "tags": "4065."
    }, {
      "sublime_text": ">=4111",
      "tags": "4111."
    }
  ]
}
```

Users not using those latest builds will be left with older releases.

**Comment by rwols** [comment]
Note: sublime.ListInputHandler first appeared in build 3154. I believe that's the minimum ST build version required for this plugin to work correctly right now.

**Comment by predragnikolic** [comment]
Yes 🙂. But I think there were bugs with sublime.ListInputHandler at the beginning, which may have been fixed in later builds... Maybe, I am not sure

**Comment by predragnikolic** [comment]
Is having two tags like "st3-" and "st4-" sufficient? Or we need to version tags like you suggested? 🙂

**Comment by rwols** [comment]
It's more flexible to use the minimum required ST version as the major version. What other purpose does the major version number have? It has no meaning otherwise.

```
minimum       LSP API     incrementing
required      version     version number
ST version    for LSP-*   for end-users
----------    ---------   -------------
 |               |          |
3154   .         1    .    54
```
We can use the middle number to indicate the API version for plugins depending on LSP.
The last number can be monotonically increasing for distribution purposes. The least significant number can reset to 0 once we increase either the most significant number (the ST build version) or the API version. The API version should never reset and always monotonically increase.
I'll make the changes in package_control_channel soon.

**Comment by rwols** [comment]
This has been achieved :)
