### ISSUE TITLE
Ability to change lint color?

### ISSUE THREAD

**Issue by chavlji** [sublimelsp/LSP#871]
Is there a setting to change linting symbols (gutter icon, underlines) color? I hate the default white one that's too intensive and is burning my eyes...

**Comment by jfcherng** [comment]
>  I hate the default white one that's too intensive and is burning my eyes...

Sound like you should go to find some configuration for the language server itself to see whether some linting/diagnose rules can be disabled.

**Comment by chavlji** [comment]
@jfcherng no. I wanna keep them all, I just don't like the color :)

**Comment by rwols** [comment]
Diagnostics (the squigly linter lines) receive standard scopes:

https://github.com/sublimelsp/LSP/blob/a1a7c14b5d984a31e1ca4bbfebfdbf0ae9a1d122/plugin/diagnostics.py#L23-L28

So, what you have to do is make an override in a .sublime-color-scheme file for the scopes

```
markup.error
markup.warning
markup.info
markup.info.suggestion
```

These markup scopes are experimental scopes. The relevant Request For Change is here: https://github.com/sublimehq/packages/issues/1036. Information about overrding color schemes can be found here: https://www.sublimetext.com/docs/3/color_schemes.html

**Comment by jwortmann** [comment]
The gutter icon colors are affected by the `foreground` color setting in the color scheme for the scopes mentioned above as well.

**Comment by rwols** [comment]
I've added this to the [notes](https://github.com/sublimelsp/LSP/wiki/Notes).
