### ISSUE TITLE
Could you update troubleshooting? ( RVM and ruby server do not work )  

### ISSUE THREAD

**Issue by lolgear** [sublimelsp/LSP#872]
I have encountered strange error ( no output, no error, no diagnostics ).

I install plugin Fix My Mac and still nothing happens.

I have configuration:

```json
{
		"ruby":
		{
			"command":
			[
				"/Users/dmitry/.rvm/gems/ruby-2.6.3/bin/solargraph",
				"socket"
			],
			"enabled": true,
			"languageId": "ruby",
			"scopes":
			[
				"source.ruby",
				"source.ruby.rails"
			],
			"syntaxes":
			[
				"Packages/Ruby/Ruby.sublime-syntax",
				"Packages/Rails/Ruby on Rails.sublime-syntax",
				"Packages/Rails/HTML (Rails).sublime-syntax"
			],
			"tcp_port": 7658
		}
}
```

But!

After reading [this answer](https://stackoverflow.com/a/26370576), I change path to binary:

```
// Was
"/Users/dmitry/.rvm/gems/ruby-2.6.3/bin/solargraph"

// Now
"/Users/dmitry/.rvm/gems/ruby-2.6.3/wrappers/solargraph"
``` 

Everything works fine.

**Comment by rwols** [comment]
I've tested solargraph locally and it seems to work as advertised. I have installed it in /usr/local/bin/solargraph.

I made a new page on the wiki about these kinds of notes: https://github.com/sublimelsp/LSP/wiki/Notes

Anyone can edit that page.
