### ISSUE TITLE
Could you add following command: "Show all occurrences and rename symbol"

### ISSUE THREAD

**Issue by lolgear** [sublimelsp/LSP#873]
Hi!

I would like to see all occurrences of symbol before renaming.
It would be nice to have this command.

Thanks!

**Comment by jfcherng** [comment]
```js
    { "keys": ["???"], "command": "lsp_symbol_references", "context": [{ "key": "setting.lsp_active" }] },
```

**Comment by lolgear** [comment]
@jfcherng 
I believe this plugin exist!

**Comment by lolgear** [comment]
@jfcherng 
But this is what I expect when I use rename command.
I don't want to blindly rename symbol without knowledge about its usage.

**Comment by jfcherng** [comment]
Incremental renaming?

**Comment by lolgear** [comment]
@jfcherng 
Not familiar with this term.
If it is a functionality similar to current Xcode implementation ( you have a view of all occurrences which are updated on-the-fly when you rename symbol ) - yes, this is ideal functionality for renaming.
But with current implementation I am fine: chain of two commands.

This LSP package is API-friendly, not human-friendly. I don't want a command "rename symbol blindly" in Text Editor GUI.
