### ISSUE TITLE
Ready lock timeout with slow Metals 0.8.0

### ISSUE THREAD

**Issue by uncle-betty** [sublimelsp/LSP#874]
On my laptop, it seems to take a while for *Metals* 0.8.0 to start up and report back to the LSP plugin. The 3-second `ACQUIRE_READY_LOCK_TIMEOUT` expires and the LSP plugin tells *Metals* to shut down - right after it has come up.

See the log below, where the `shutdown` message is sent before the response to the `initialize` message is received.

Changing the timeout to 5 seconds fixed the issue on my machine. Maybe make the timeout configurable in the LSP plugin settings and by default be more generous than 3 seconds?

* OS and language server - Ubuntu 18.04 with *Metals* 0.8.0.

* How you installed LSP (Package Control or from git?) - Latest from GitHub.

* Minimal reproduction steps - Open a LSP-enabled Scala project.

* Log:
```
:: --> metals initialize(1): {...}
metals: INFO  logging to file /home/user/foobar/.metals/metals.log
metals: INFO  started: Metals version 0.8.0 in workspace '/home/user/foobar'
metals: INFO  time: initialize in 1.76s
metals: INFO  shutting down Metals
:: --> metals shutdown(2): None
:: <-- metals 1: {...}
:: --> metals initialized: {}
:: --> metals textDocument/didOpen
```

**Comment by uncle-betty** [comment]
Looks like commit https://github.com/sublimelsp/LSP/commit/e4848e9e158c5038b9678c1b3b96a6262aaebbeb introduced the timeout on January 5.

**Comment by rwols** [comment]
Thanks for this report. I have something in the pipeline to remove the need for this lock. In the meantime, would you be willing to experiment with that ACQUIRE_READY_LOCK_TIMEOUT variable in plugin/core/sessions.py to see what works for you?

**Comment by uncle-betty** [comment]
Oh, wow, thank you for the fast response. Yes, 5 seconds works.

For more precision I just measured the exact time between lock acquisition and release. Five runs yielded the following times:

```
3736 ms
3674 ms
3702 ms
3689 ms
3617 ms
```

So for me, on my 2014 Thinkpad X1 with Ubuntu 18.04 (JDK 11.0.6), the *Metals* Scala language server takes ~3.7 seconds to start up.
