### ISSUE TITLE
Clojure Support

### ISSUE THREAD

**Issue by gigavinyl** [sublimelsp/LSP#878]
Howdy! I was wondering if support for [clojure](https://github.com/snoe/clojure-lsp) could be added and if it can be added by the user, how would I go about doing that? Thanks!

**Comment by rwols** [comment]
- Have a Clojure syntax.
- Open a Clojure file.
- Open the Console.
- Run `view.settings().get("syntax")` -> Packages/Clojure/Clojure.sublime-syntax
- Run `view.scope_name(0)` -> source.clojure
- Search the internet if people have decided on an "LSP Language ID" for Clojure. The best place to start is the [LSP spec page](https://microsoft.github.io/language-server-protocol/specification#textDocumentItem). And indeed, we have apparently decided to call it `clojure` (makes sense).
- Install clojure-lsp. Check if it works by running it from your terminal. It should do nothing when running from your terminal.
- Run `Preferences: LSP Settings` from the command palette.
- In the right view, modify the sublime settings file to something like this:

```js
// Settings in here override those in "LSP/LSP.sublime-settings",

{
	"clients":
	{
		"clojure-lsp":
		{
			"command": ["/usr/local/bin/clojure-lsp"],
			"scopes": ["source.clojure"],
			"syntaxes": ["Packages/Clojure/Clojure.sublime-syntax"],
			"languageId": "clojure"
		}
	}
}
```

It looks like clojure-lsp has a bunch of useful commands. This plugin can run those commands with `lsp_execute_command`, but the arguments can only be fixed strings if I remember correctly. We should perhaps let `lsp_execute_commands` translate placeholders like `{uri}` into the current filename URI.

If this all works, consider contributing to the documentation https://lsp.readthedocs.io/en/latest/ https://github.com/sublimelsp/LSP/tree/master/docs

**Comment by rwols** [comment]
Added in 869619b832692ff3bc677281868ff5c7ffd51707.
