### ISSUE TITLE
JSX/TSX auto_complete_triggers with multiple languages array

### ISSUE THREAD

**Issue by roblav96** [sublimelsp/LSP#879]
## Problem

User preferences `auto_complete_triggers` are not respected when using an array of `languages`, for example, `JSX` and `TSX` syntaxes.

#### `User/Preferences.sublime-settings`
```json
"auto_complete_triggers":
[
	{ "selector": "text.html", "characters": "<" },
	{ "selector": "source.jsx", "characters": "<" },
	{ "selector": "source.tsx", "characters": "<" }
],
```

#### `User/LSP.sublime-settings`
```json
"ts-lsp": {
	"enabled": true,
	"command": [
		"typescript-language-server",
		"--stdio"
	],
	"languages": [
		{
			"languageId": "javascriptreact",
			"scopes": ["source.jsx"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage"]
		},
		{
			"languageId": "typescriptreact",
			"scopes": ["source.tsx"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage"]
		},
		{
			"languageId": "typescript",
			"scopes": ["source.ts"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"]
		},
		{
			"languageId": "javascript",
			"scopes": ["source.js"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"]
		},
	]
},
```

## Quirks

What's strange is if I change the order from `[javascriptreact, typescriptreact, ...]` to `[typescriptreact, javascriptreact, ...]` the autocomplete triggers work fine for `typescriptreact` but not `javascriptreact`.

**Comment by rwols** [comment]
Could you open the console and report back what the values are of these settings?

```
>>> view.settings().get("auto_complete_triggers")
>>> view.settings().get("lsp_language")
```

for both `[javascriptreact, typescriptreact, ...]` and `[typescriptreact, javascriptreact, ...]`?

**Comment by roblav96** [comment]
#### `app.jsx`
```json5
>>> view.settings().get("auto_complete_triggers")
[{'selector': 'text.html', 'characters': '<'}, {'selector': 'source.jsx', 'characters': '."\'/@<'}]
>>> view.settings().get("lsp_language")
{'ts-lsp': 'javascriptreact'}
```

#### `app.tsx`
```json5
>>> view.settings().get("auto_complete_triggers")
[{'selector': 'text.html', 'characters': '<'}, {'selector': 'source.jsx', 'characters': '."\'/@<'}]
>>> view.settings().get("lsp_language")
{'ts-lsp': 'javascriptreact'}
```

#### `index.ts`
```json5
>>> view.settings().get("auto_complete_triggers")
[{'selector': 'text.html', 'characters': '<'}, {'selector': 'source.ts', 'characters': '."\'/@<'}]
>>> view.settings().get("lsp_language")
{'ts-lsp': 'typescript'}
```

#### `index.js`
```json5
>>> view.settings().get("auto_complete_triggers")
[{'selector': 'text.html', 'characters': '<'}, {'selector': 'source.jsx', 'characters': '<'}, {'selector': 'source.tsx', 'characters': '<'}]
>>> view.settings().get("lsp_language")
{'ts-lsp': 'typescript'}
```

**Comment by rchl** [comment]
Not sure if related to your problem but why do you have this for `javascript`?:
```
		{
			"languageId": "javascript",
			"scopes": ["source.js"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"]
		},
```
I think you should rather have `"languageId": "javascript"`.

**Comment by predragnikolic** [comment]
Hello. 
can you run `view.settings().get('syntax')` inside a `.js` file, and paste the results here.

I noticed that you put "Packages/TypeScript-TmLanguage/TypeScript.tmLanguage" in the javascript confgiuration:
```
                {
			"languageId": "javascript",
			"scopes": ["source.js"],
			"syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"]
		},
```

If so I am pretty confident that the scope is not `source.js` for that syntax file(`TypeScript.tmLanguage`), but rather "source.ts".

you can also check the scope in a `.js` file by going in the window menu `Tools > Developer > Show Scope` name. :) 
You can also paste the results return from `Show Scope Name`

**Comment by predragnikolic** [comment]
A quick fix is to use 'Packages/JavaScript/JavaScript.sublime-syntax' instead of "Packages/TypeScript-TmLanguage/TypeScript.tmLanguage"

```
  {
			"languageId": "javascript",
			"scopes": ["source.js"],
			"syntaxes": ["Packages/JavaScript/JavaScript.sublime-syntax"]
		},
```

**Comment by rwols** [comment]
I'm sorry @roblav96, I'm indeed seeing some weird results that probably need attention, but it is unclear to me what you're asking. Could you explain what you *expect* to see for `view.settings().get("auto_complete_triggers")` ?
