### ISSUE TITLE
Add Haskell language to the docs

### ISSUE THREAD

**Issue by moodmosaic** [sublimelsp/LSP#885]
As per the the [instructions in `ghcide`](https://github.com/digital-asset/ghcide#using-with-sublime-text) readme, what is the procedure to get this added in [LSP docs](https://lsp.readthedocs.io/en/latest/)?

## Haskell

* Install [LSP](https://packagecontrol.io/packages/LSP)
* Press Ctrl+Shift+P or Cmd+Shift+P in Sublime Text and search for *Preferences: LSP Settings*, then paste these settings
```
{
  "clients":
  {
    "ghcide":
    {
      "enabled"   : true,
      "languageId": "haskell",
      "command"   : ["ghcide", "--lsp"],
      "scopes"    : ["source.haskell"],
      "syntaxes"  : ["Packages/Haskell/Haskell.sublime-syntax"]
    }
  }
}
```

**Comment by rwols** [comment]
Added in d7a10ec06a34e939396d1c63815792c929f327e1.

**Comment by moodmosaic** [comment]
Thank you, @rwols. :100: :+1:
