### ISSUE TITLE
Question: How to go to definition in already open tab?

### ISSUE THREAD

**Issue by RafalSkolasinski** [sublimelsp/LSP#886]
Each time I use `go to definition` functionality it opens a new tab.
It would be nice if it could reuse already open tab and just set the focus in the right place in similar fashion as going through search results do.

**Comment by jfcherng** [comment]
Another thing that I found is the prompt menu sometimes has duplicated items

![image](https://user-images.githubusercontent.com/6594915/75041174-0540a780-54f7-11ea-81af-4cd1427c07cd.png)

**Comment by RafalSkolasinski** [comment]
What I notice is that it is actually reusing the open tab but only if it is open in the same pane.
If the tab with target file is open in different pane `go to definition` will open it again in the same pane.

**Comment by rwols** [comment]
The built-in "Goto Definition" from ST has the same behavior, and we pretty much copy that behavior. There's not much more we can do. See: https://github.com/sublimehq/sublime_text/issues/813

**Comment by rwols** [comment]
I spoke too soon. It's actually fixable by removing a FORCE_GROUP flag!

**Comment by jfcherng** [comment]
I would actually like have the same behavior (or make it configurable) since it's not obvious that which tab in which group is currently getting focused.

**Comment by rwols** [comment]
Well, FORCE_GROUP is an [undocumented flag](https://github.com/sublimehq/sublime_text/issues/2290) anyway, so we shouldn't use it.
