### ISSUE TITLE
ST API: Missing support for textDocument/semanticHighlighting

### ISSUE THREAD

**Issue by junknet** [sublimelsp/LSP#887]
I only see these scopes:{
markup.error
markup.warning
markup.info
markup.info.suggestion
} 
It just for Diagnostics.
How do I get the LSP to analyze my code and return the type name.
for c++ code; such as function , module,struct,keyword.....
Then I can use these to customize my code color !

**Comment by rwols** [comment]
Both clangd and ccls already publish semantic highlighting. However this notification has not been standardized yet. That said, it's basically impossible to accomplish "dynamic" highlighting with the ST API. I'm not saying it will never happen, but you're swimming upstream if you would try to implement it at this time.

**Comment by rwols** [comment]
Looks like it's standardized for 3.16 of the protocol. https://github.com/microsoft/vscode-languageserver-node/blob/release/protocol/3.16.0-next.1/protocol/src/protocol.semanticTokens.proposed.ts

Perhaps we can experiment around with `view.add_regions`.

**Comment by pushqrdx** [comment]
@rwols so it isn't possible to do as a plugin?

**Comment by rwols** [comment]
I'm not saying it's impossible, but likely it's going to be an uphill battle until there's a dedicated API for this in ST.

See: https://github.com/sublimehq/sublime_text/issues/817

**Comment by pushqrdx** [comment]
@rwols yeah the workaround presented seems pretty ineffecient too.

**Comment by predragnikolic** [comment]
This issue can be closed now.

**Comment by rchl** [comment]
If so then I guess we need a more specific issue for tracking upstream support as current solution has many drawbacks.

**Comment by predragnikolic** [comment]
I am subscribed to that issue at https://github.com/sublimehq/sublime_text/issues/817

But yeah, if people start complaining about error underlines not being visible, due to semantic highlighting regions being drown on top of error regions, and vice versa, than yes. An issue for that will probably exist.
