### ISSUE TITLE
Troubleshooting guide link in issue template is wrong

### ISSUE THREAD

**Issue by davidben** [sublimelsp/LSP#889]
The new issue template says:

> Your issue may have been solved already - please search before creating new!
>
> Troubleshooting guide: https://lsp.readthedocs.io/en/latest/#troubleshooting
> Chat: https://discord.gg/RMkk5MR

The troubleshooting link does not work. I assume it was supposed to be https://lsp.readthedocs.io/en/latest/troubleshooting/.

**Comment by rwols** [comment]
Thanks for pointing this out!
