### ISSUE TITLE
LSP plugin eats escape key pushes after dismissing diagnostic window.

### ISSUE THREAD

**Issue by safield** [sublimelsp/LSP#898]
Sublime Text Version: 3.2.2
OS: Windows 10

I am using LSP with clangd on a c++ codebase. When I show the inline diagnostics window, all subsequent esc key presses are eaten.

To reproduce:
-open a c++ source file.
-introduce an error.
-press f8 to run command lsp_next_diagnostic
-press esc to dismiss the diagnostic window.
-all subsequent esc key presses are not recognized in the file.

**Comment by tomv564** [comment]
I didn't add the keybinding for `esc` by default because they seemed buggy - I see now that @predragnikolic helpfully added them.

@rwols  I recommend disabling the esc binding  - I have one fix for it but I suspect there are many cases the context "sticks".

**Comment by rwols** [comment]
@safield a partial fix was committed. I am wondering if it is actually a complete fix. Do you still experience the issue?
