### ISSUE TITLE
Ruby language server with rbenv

### ISSUE THREAD

**Issue by tvallois** [sublimelsp/LSP#923]
Hello,

LSP is not able to recognize when binaries such as Solargraph or Sorbet are installed with rbenv.
As a workaround, you need to put the complete path to solargraph e.g `/home/tvallois/.rbenv/shims/solargraph`
Error: 
```
Could not start solargraph
[Errno 2] No such file or directory: 'solargraph'
Server will be disabled for this window 
```

* OS and language server
Ubuntu 19.10 / Solargraph
* How you installed LSP (Package Control or from git?)
Package Control
* Minimal reproduction steps
- Install rbenv
- Create a rails project and add Solargraph to the Gemfile.
- Launch LSP with default config. 
* Log
```
Server will be disabled for this window
Traceback (most recent call last):
  File "/home/tvallois/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 478, in _start_client
    lambda msg: self._handle_stderr_log(config.name, msg))  # on_stderr_log
  File "/home/tvallois/.config/sublime-text-3/Packages/LSP/plugin/core/clients.py", line 47, in start_window_config
    on_stderr_log=on_stderr_log)
  File "/home/tvallois/.config/sublime-text-3/Packages/LSP/plugin/core/sessions.py", line 348, in create_session
    process = start_server(server_args, working_dir, env, on_stderr_log)
  File "/home/tvallois/.config/sublime-text-3/Packages/LSP/plugin/core/process.py", line 53, in start_server
    startupinfo=si)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'solargraph'
```

**Comment by rwols** [comment]
I've read that python users solve this by installing a `pyls` version in their virtualenv and pointing to that `pyls` in their .sublime-project. So, your .sublime-project could look something like this, but I haven't tested this:

```js
{
  "settings": {
    "LSP": {
      "sorbet": {
        "enabled": true, // if you want to enable Sorbet for current project only
        "command": ["/path/to/rbenv/srb", "options"]
        "env": {
            // if you need to set a few env variables, put them here
        }
      }
    }
  }
}
```

**Comment by tvallois** [comment]
Yup, this is how i've been able to make it work however it's quite confusing to have to write the full path. Idk if an easy fix for this is possible, i'll have a look asap.

**Comment by rchl** [comment]
Wouldn't it work if `rbenv` would be in the PATH?
LSP "sees" the PATH as SublimeText "sees" it. If you make SublimeText have `rbenv` in the PATH then I think it should work. ST queries shell init script so if you make sure that script modifies PATH appropriately (as [explained in rbenv docs](https://github.com/rbenv/rbenv#basic-github-checkout)) then it might just work.

**Comment by tvallois** [comment]
No i've already added rbenv path to my `~/.bashrc` but it's still not working.

**Comment by rchl** [comment]
try `.bashprofile` instead. I believe that's what ST is sourcing when you are using bash.
And you need to at least log-out and log back for changes to apply.

**Comment by rwols** [comment]
You can check what your $PATH is in SublimeText by opening the Console and running the following:

```
>>> import os; os.environ['PATH']
'/home/raoul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by rchl** [comment]
Extending the path in `.profile` (or `.bash_profile`, not sure now) should work so I'm gonna close this.

**Comment by tsujp** [comment]
I am having this issue also with Sorbet. It's in my PATH both in a shell and via Sublime's console checking, `which srb` both point to the same both in the shell and through Sublime's console. Theres nothing in the logs with full logging enabled. I can run it fine in a shell using the exact same arguments at the exact same path.

The only diagnostic I have is `sorbet exited with status code 1.`. `.profile` is symlinked to `.bash_profile`.

**Comment by rchl** [comment]
Either create a separate issue or discuss it in Discord #lsp.
(There should be some error in the ST console at least.)

**Comment by tsujp** [comment]
Ack. Did message on Discord before but thought it was topical to this issue too, also I dun goofed and forgot to check the LSP log panel _not just_ the Sublime Text console logs. Anyway, discussion in #LSP will report findings back in a new issue.

**Comment by feliperaul** [comment]
I have a pretty vanilla env here (MacOs 10.15.16) and I'm facing the same issue.

This is what Sublime sees as my PATH:

```
>>> import os; os.environ['PATH']
'/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'
```

I use zsh and rbenv, everything else works just fine automatically, but that PATH is obviously wrong.

**Comment by rchl** [comment]
@feliperaul there should be enough information here for you to try out things.
