### ISSUE TITLE
[AC] AC should hide once the whole word is typed and that word is the only suggested

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP#934]
Noticed a bug with latest changes:

When, in Python, I'm typing `False` and getting an (only) suggestion with it, the suggestion popup doesn't disappear once I've typed whole word. It did before those changes.

![Screenshot 2020-03-28 at 21 49 09](https://user-images.githubusercontent.com/153197/77833520-42bfd280-713e-11ea-83b4-7ee1da449ae8.png)

_Originally posted by @rchl in https://github.com/sublimelsp/LSP/pull/866#issuecomment-605518024_

**Comment by rwols** [comment]
This looks like the complete opposite of #935 :)

**Comment by rchl** [comment]
Not really IMO as here you expect the popup to disappear because you've typed full and exact suggestion.

The other issue is about popup being hidden when match is only partial.

**Comment by predragnikolic** [comment]
> Not really IMO as here you expect the popup to disappear because you've typed full and exact suggestion.

I would only add "...  disappear because you've typed full and exact suggestion and there are no other completion items available."

**Comment by predragnikolic** [comment]
I think that sublime should handle this case. 
I see nothing I could do about it in LSP.

**Comment by rwols** [comment]
I believe ST cannot hide the AC widget, because it’s a command completion. And selecting a command completion has the potential to replace “False” with “True”.

**Comment by rwols** [comment]
We could optimize for cases when:

- the server only sends insertText,
- the server has no completionResolve capability.

If these two conditions are true, then instead of a command completion we can use a snippet completion.

**Comment by rwols** [comment]
As it turns out we can always use a snippet_completion for pyls.

**Comment by rwols** [comment]
#992 also fixed this.

See the gif:

![Peek 2020-04-28 18-36](https://user-images.githubusercontent.com/2431823/80530074-c74d7d00-8998-11ea-877b-3a7331a48cde.gif)

Because snippet completions are sufficient for pyls.
