### ISSUE TITLE
Trying to get this working with clojure-lsp

### ISSUE THREAD

**Issue by slifin** [sublimelsp/LSP#936]
This is a crosspost from https://github.com/snoe/clojure-lsp/issues/121 because I can't figure out where the problem originates

**Comment by rwols** [comment]
https://lsp.readthedocs.io/en/latest/#clojure

Try changing your `command` to something like `["java", "-jar", "/usr/local/bin/clojure-lsp"]`. I don't know why clojure-lsp is actually a jar, it should be an executable.

**Comment by slifin** [comment]
That works thank you
