### ISSUE TITLE
TextEdit insertion not entirely correct

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#947]
Examples where this fails for clangd:

![Peek 2020-04-05 09-03](https://user-images.githubusercontent.com/2431823/78468922-5fe73900-771c-11ea-830d-22dec48cc6d5.gif)
![Peek 2020-04-05 09-02](https://user-images.githubusercontent.com/2431823/78468924-607fcf80-771c-11ea-8e78-65ea84cb46ba.gif)

The first one should insert `return $0;`, and then insert `Size()`, making the line look like `return Size();`.

The second one should insert `reinterpret_cast<${1:type}>(${2:expression})`.

**Comment by predragnikolic** [comment]
Can you make a repro repo?
I will try to setup clangd now.

**Comment by rwols** [comment]
I already have a fix in the works :)

**Comment by rwols** [comment]
Fixed by #949
