### ISSUE TITLE
Having rootPath configuration

### ISSUE THREAD

**Issue by quangbuule** [sublimelsp/LSP#953]
Hi, I just closed a PR https://github.com/sublimelsp/LSP/pull/952

I found that we need a configuration for rootPath that will send to language server instead of using the first_folder path (this is also flaky, the workspace folders are sorted in this plugins so the first folder is not always the one you see on top of the sidebar).

https://github.com/sublimelsp/LSP/blob/master/plugin/core/sessions.py#L14

My use-case:
I am using Flow, my sublime workspace contains only a sub-folder of a big project, there is no `.flowconfig` in that directory, but there is one in root big project.

Output from the console:
```
flow: Could not open_in_bin: '/Users/home/the-root-project/src/packages/my-working-dir/.flowconfig' ((Sys_error "/Users/home/the-root-project/src/packages/my-working-dir/.flowconfig: No such file or directory"))
```

cc @jfcherng

**Comment by jfcherng** [comment]
I am not sure but [LanguageHandler](https://github.com/sublimelsp/LSP/blob/9a16fba826119a139e17961604176da65e08c382/plugin/core/handlers.py#L6) seems not able to deal with `initializeParams['rootPath']`. 

I found that another LSP client implementation has a `rootPatterns` configuration for various possible LSP server.  https://github.com/neoclide/coc.nvim/wiki/Language-servers#flow

In its definition, 
> `rootPatterns` is used to resolve the root path which should contain one of the patterns as a child directory or file, it will use "coc.preferences.rootPatterns" (default to [".git", ".hg", ".projections.json"]) when not specified,

They also use `rootPatterns` to auto find the project root (i.e., our `initializeParams['rootPath']`?) for clangd (https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c)

**Comment by quangbuule** [comment]
@jfcherng that's interesting approach. By that way, it doesn't need to have the `.sublime-project` to declare the rootPath, we can literally open any sub-folder of the project.

Again, this may travel up to `/` if the `.flowconfig` is not found, but we can yield an error to the user like ".flowconfig cannot be found".

**Comment by rwols** [comment]
This should be handled by a LanguageHandler. Its API should be reworked because it isn't flexible enough in a lot of cases. See: https://github.com/sublimelsp/LSP/issues/927

**Comment by rwols** [comment]
If you're using the ST4 alpha, you may try https://github.com/sublimelsp/LSP-flow

**Comment by rwols** [comment]
This is fully fixed by the LSP-flow helper package. Do not install flow globally but use the binary in node_modules/.bin/ (which is exactly what LSP-flow does automatically for you).
