### ISSUE TITLE
clangd: duplicate bracket on completion

### ISSUE THREAD

**Issue by lulor** [sublimelsp/LSP#956]
When clangd offers a completion option, it will include (closing?) brackets as well.
The problem is that if the closing bracket is already in place, the auto-completion will cause a duplicate character.
Is there a way to  tweak/disable this behaviour?

Here are some screenshots:

<img width="341" alt="Screenshot 2020-04-08 at 23 35 47" src="https://user-images.githubusercontent.com/61948614/78836323-25b6b980-79f2-11ea-8a46-ed3351aa4e52.png">
<img width="405" alt="Screenshot 2020-04-08 at 23 35 59" src="https://user-images.githubusercontent.com/61948614/78836292-1d5e7e80-79f2-11ea-9274-ecf1c791f8b6.png">
<img width="218" alt="Screenshot 2020-04-08 at 23 35 35" src="https://user-images.githubusercontent.com/61948614/78836350-323b1200-79f2-11ea-9bbf-e795ffa94085.png">

**Comment by rwols** [comment]
SublimeText cannot actually handle the text edits from an LSP-conforming language server. It is impossible to account for all possible text edits with the ST3 API. We have various workarounds accumulated over the years. This is yet another case where we could add another workaround.

ST4 is currently in alpha, and might get a dev release this year. It has an API which *does* allow properly handling "LSP text edits". Package developers can already play around with an alpha version of ST4, along with its new (undocumented) API.

If you absolutely need this fixed, look at plugin/core/completion.py for the workarounds, and add another workaround.

But you can also wait for ST4 to be released and your issue will be auto-fixed.

**Comment by lulor** [comment]
I got it, thanks!
