### ISSUE TITLE
LSP package is no longer installable from Package Control

### ISSUE THREAD

**Issue by imjoehaines** [sublimelsp/LSP#960]
I'm in the process of setting up a new laptop and after cloning my Sublime packages repo found that Package Control isn't able to install the LSP package

I'm assuming this is because of something to do with the [tag split](https://github.com/wbond/package_control_channel/pull/7834) based on the error message on [the LSP package page](https://packagecontrol.io/packages/LSP):

<img width="623" alt="LSP package error on Package Control" src="https://user-images.githubusercontent.com/282732/79000671-f5336480-7b44-11ea-89c6-d420d537396d.png">

"LSP" doesn't bring up a package to install from inside Sublime (build 3211) and manually adding it to "installed_packages" in Package Control's settings errors too:

<img width="408" alt="LSP package error in Sublime" src="https://user-images.githubusercontent.com/282732/79000930-768af700-7b45-11ea-9faf-f5decdd7f256.png">

As an aside; thanks for all the work on Sublime LSP — it's the reason I can use Sublime as my main editor again 🙂

**Comment by rwols** [comment]
I'm not sure what's wrong. Perhaps the crawler needs a bit of time? cc @Fichtefoll

**Comment by imjoehaines** [comment]
It's working now, probably was just the crawler needing to update then :)

**Comment by rwols** [comment]
No PC requires both tag prefixes to exist apparently, so I added a tag for ST4 alpha users that download this package through package control, of which there are none... :)

**Comment by imjoehaines** [comment]
Ah awesome, thank you!
