### ISSUE TITLE
Add Dockerfile support

### ISSUE THREAD

**Issue by rcjsuen** [sublimelsp/LSP#980]
I don't see Dockerfiles mentioned in the list of supported languages in the [`README.md`](https://github.com/sublimelsp/LSP/blob/2773758de44ad051f0ace93667cfdf33b3c4ad69/README.md) file. Can this be added?

My [language server](https://github.com/rcjsuen/dockerfile-language-server-nodejs) is written in TypeScript and is already used by some existing LSP clients.

**Comment by ayoub-benali** [comment]
Yes it can. Please feel free to make PR editing that readme file.

**Comment by rcjsuen** [comment]
@ayoub-benali So the only thing that is necessary is to update the `README.md` file? No changes need to be made to the [readthedocs.io](https://lsp.readthedocs.io/en/latest/#css) page?

**Comment by ayoub-benali** [comment]
You have to add an entry in `docs/index.md` as well

**Comment by rchl** [comment]
Additionally, we could create a `LSP-dockerfile` server in LSP organization (https://github.com/sublimelsp/LSP), similarly to the other node-based ones that we have. That simplifies the process as then the user doesn't have to edit a configuration file and dependency is maintained by the package.

**Comment by jwortmann** [comment]
I just tried out this language server, it works fine for me with the following configurations:
```js
"docker-langserver": {
  "command": ["docker-langserver", "--stdio"],
  "enabled": true,
  "languageId": "dockerfile",
  "scopes": ["source.dockerfile"],
  "settings": {
    "docker": {
      "languageserver": {
        "diagnostics": {
          // string values must be equal to "ignore", "warning", or "error"
          "deprecatedMaintainer": "warning",
          "directiveCasing": "warning",
          "emptyContinuationLine": "warning",
          "instructionCasing": "warning",
          "instructionCmdMultiple": "warning",
          "instructionEntrypointMultiple": "warning",
          "instructionHealthcheckMultiple": "warning",
          "instructionJSONInSingleQuotes": "warning"
        }
      }
    }
  },
  "syntaxes": ["Packages/Dockerfile Syntax Highlighting/Syntaxes/Dockerfile.sublime-syntax"]
}
```

I can see some error logs
```
(node:13132) UnhandledPromiseRejectionWarning: Error: client/registerCapability
at handleResponse (C:\Users\XXX\AppData\Roaming\npm\node_modules\dockerfile-language-server-nodejs\node_modules\vscode-jsonrpc\lib\main.js:449:48)
at processMessageQueue (C:\Users\XXX\AppData\Roaming\npm\node_modules\dockerfile-language-server-nodejs\node_modules\vscode-jsonrpc\lib\main.js:276:17)
at Immediate.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\dockerfile-language-server-nodejs\node_modules\vscode-jsonrpc\lib\main.js:260:13)
at processImmediate (internal/timers.js:439:21)
(node:13132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
after a dynamic `client/registerCapability` request `{'registrations': [{'id': 'c7b8a882-57f4-476d-8e5a-a62db43a233a', 'method': 'workspace/didChangeConfiguration', 'registerOptions': {}}]}`, which the LSP client rejects with `{'code': -32601, 'message': 'client/registerCapability'}`, but that seems to have no impact on the server's functionality.

I can make a PR to update the LSP docs with the configs above tomorrow.

**Comment by rchl** [comment]
> Additionally, we could create a `LSP-dockerfile` server in LSP organization (https://github.com/sublimelsp/), similarly to the other node-based ones that we have.

@rcjsuen would you be open to maintaining it in there if we give you necessary permissions? Or otherwise, are you fine with use creating a package like that and maintaining it?

**Comment by rchl** [comment]
> I can see some error logs

Yes, SLSP is missing support for `client/registerCapability` right now. As long as server doesn't react badly to the error that is returned in that case, it should be "fine". It will still receive `workspace/didChangeConfiguration`.

**Comment by rcjsuen** [comment]
> > Additionally, we could create a `LSP-dockerfile` server in LSP organization (https://github.com/sublimelsp/), similarly to the other node-based ones that we have.
> 
> @rcjsuen would you be open to maintaining it in there if we give you necessary permissions? Or otherwise, are you fine with use creating a package like that and maintaining it?

@rchl I am fine with you all creating a repository and maintaining the package. I will watch the created repository and keep an eye out for questions and bugs. Does that sound okay?

**Comment by rcjsuen** [comment]
Thank you @jwortmann!

**Comment by rchl** [comment]
Also `LSP-dockerfile` package was created at https://github.com/sublimelsp/LSP-dockerfile :)

**Comment by rcjsuen** [comment]
@rchl Yup, already watching that repository after rcjsuen/dockerfile-language-server-nodejs#240 got opened. :)
