### ISSUE TITLE
Support for MarkupContent in hover

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#991]
[MarkupContent](https://microsoft.github.io/language-server-protocol/specification#markupContent) is an object with required `kind` and `value` properties where `kind` can be either `plaintext` or `markdown`.

It's allowed in:
 - `textDocument/completion` response `CompletionItem.documentation` ([link](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion))
 - `textDocument/hover` response `Hover.contents` ([link](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover))
 - `textDocument/signatureHelp` response: `SignatureHelp.signatures[].documentation?` ([link](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp))

We are currently not supporting it in hover popups for sure and probably in other places too. And while we read the actual `value` from the contents, we don't make a proper choice regarding escaping, rendering as markdown due to not taking `kind` into account.

**Comment by genericptr** [comment]
Here is an example hover response which shows the bug:

`{'contents': {'value': 'type TVec2i = specialize TGVec2<Integer>', 'kind': 'plaintext'}, 'range': {'end': {'character': 3, 'line': 339}, 'start': {'character': 3, 'line': 339}}}`

and a picture of how it is displayed:

![Screen Shot 2020-04-28 at 4 46 22 PM](https://user-images.githubusercontent.com/10937186/80486501-784a1c80-8985-11ea-83ed-5f530a150fa6.png)

**Comment by rchl** [comment]
@rwols @predragnikolic do you know if this is now fully implemented in all contexts where `MarkupContent` is allowed?

**Comment by predragnikolic** [comment]
We now have the `minihtml` function which accepts a string or a MarkupKind.

We can now use that function when parsing the content in hover or signature help popups.

**Comment by rwols** [comment]
Fixed by #1046.
